### ISSUE TITLE
When sending a message: "property conversion error: Type not supported: DateTime"

### ISSUE THREAD

**Issue by DavidR91** [paolosalvatori/ServiceBusExplorer#10]
If I specify a date/time when sending a message, I receive a conversion error

I've tried a lot of different date formats (since it's unclear which one is preferred) - none of them seem to work

e.g.
* `2014-11-06T17:18:03.267Z`
* `Sun, 06 Nov 1994 08:49:37 GMT`
* `2008-10-31T15:07:38.6875000-05:00 `
* `2002-05-30T09:00:00`
* `29/05/2015`

etc.

What date format am I supposed to be entering into this field? [And will it be possible to add a picker in the future?]

**Comment by paolosalvatori** [comment]
Hi David
which are you referring to? Schedule? TimeToLive? In both cases you should just specify seconds as an integer value. In particular, for the Schedule field, the tool adds the specified amount of seconds to DateTime.Now to calculate the schedule time. Hope this helps.
Ciao
Paolo

**Comment by jglinsek** [comment]
Not sure if it's related (based on original question), but I created a pull request to allow sending a DateTime as a custom property when resubmitting a message from the Dead Letter queue. Before this change, I was getting the same warning when re-submitting messages from the Dead Letter queue and then that property would be ignored when sending the message.

https://github.com/paolosalvatori/ServiceBusExplorer/pull/12

**Comment by paolosalvatori** [comment]
Hi James
I'll look into this tomorrow or Friday. Thanks for the new feature.
Ciao
Paolo

Inviata dal mio Windows Phone
________________________________
Da: James Glinsek<mailto:notifications@github.com>
Inviato: ‎22/‎07/‎2015 17:13
A: paolosalvatori/ServiceBusExplorer<mailto:ServiceBusExplorer@noreply.github.com>
Cc: Paolo Salvatori<mailto:leprino@hotmail.com>
Oggetto: Re: [ServiceBusExplorer] When sending a message: "property conversion error: Type not supported: DateTime" (#10)

Not sure if it's related (based on original question), but I created a pull request to allow sending a DateTime as a custom property when resubmitting a message from the Dead Letter queue. Before this change, I was getting the same warning when re-submitting messages from the Dead Letter queue and then that property would be ignored when sending the message.

https://github.com/paolosalvatori/ServiceBusExplorer/pull/12

---
