### ISSUE TITLE
Transfer DLQ implementation

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#100]
Needs to be implemented for
- [x] Queues
- [x] Subscriptions

**Comment by SeanFeldman** [comment]
Ran into a snag with subscriptions. Ironically, `SubscriptionClient` doesn't expose `FormatTransferDeadLetterPath()` like `QueueClient` does 🙂

**Comment by SeanFeldman** [comment]
Ah, Need to use [`TopicClient`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.topicclient.formattransferdeadletterpath) to get the path to the transfer DLQ. Then a normal QueueClient can be used. Will send a PR later.

**Comment by SeanFeldman** [comment]
hmmm
```c#
SubscriptionDescription.MessageCountDetails.TransferDeadLetterMessageCount
TopicDescription.MessageCountDetails.TransferDeadLetterMessageCount
```

**Comment by TPoise** [comment]
This would be a lovely feature.  If you need help, just let us know.

**Comment by SeanFeldman** [comment]
A subscription can be used as `Send-Via` path. Meaning an incoming message can be received from subscription and outgoing messages will go _via_ subscription (queue). Therefore it makes sense for subscription to have TDLQ sub-queue. Topics, well, while you can't receive from a topic, internally (on the broker) it _is_ a queue. If so, and internally ASB receives from a 'topic-queue' to send to 'subscription-queues', then a TDLQ on a topic is also an option. Feels like internals of ASB are leaking out 🙂

**Comment by TPoise** [comment]
I'm trying to find a way to re-queue all DLQ messages for a topic.  Right now, there will be an error throw if you try to submit too many at once:

> Exception: A request from the client instance has exceeded the maximum message size, and the underlying channel will be recreated.

**Comment by SeanFeldman** [comment]
@TPoise this issue is not about DLQ but Transfer DLQ. Just clarifying.

**Comment by bh3605** [comment]
Coming in out of left field here.

What is the Transfer Dead Letter queue, and how does it differ from the Dead Letter queue?

I haven't found any documentation explaining what this transfer dead letter queue is, and I've been using ASB for a year now and today was the first time I ever heard about this. It was also the first time I've come across this AMAZING tool today as well. Good job guys!

**Comment by SeanFeldman** [comment]
@bh3605 this might help you https://weblogs.asp.net/sfeldman/the-secret-brotherhood-of-message-counts and https://weblogs.asp.net/sfeldman/azure-service-bus-message-wanted-dead-or-alive

**Comment by bh3605** [comment]
Good stuff! Thank you

**Comment by paolosalvatori** [comment]
Thanks @SeanFeldman I will close this issue for now
