### ISSUE TITLE
Sending "saved" messages back to a queue?

### ISSUE THREAD

**Issue by Oculys-DanL** [paolosalvatori/ServiceBusExplorer#109]
I can see that for any queue that I can peek the messages and then save one or more of them to disk in a JSON document. This document contains all of the message content and metadata.

For testing, is it possible to load this JSON document and send those messages back to the queue? When I choose "Send Messages" on the queue, the file saved above seems to only be interpreted as a text message, not as a list of the original messages with header information.

I am not sure if I am maybe missing something in the UI, or if this might not be implemented the way I am thinking.  If the latter, I might be willing to fork the code and try to contribute.

**Comment by SeanFeldman** [comment]
@paolosalvatori 👍 / 👎 for this as a feature request?

**Comment by paolosalvatori** [comment]
Hi @Oculys-DanL, are you saying that your JSON file contains an array of messages and that when you select the file from the UI, you would like the tool to understand that the file in in JSON format, it contains an array and each item in the array should be interpreted as a distinct message to send to the target queue?

**Comment by Oculys-DanL** [comment]
Yes.  Saving multiple messages at once puts them all into one file.  It would be helpful if there was a way to reverse the process.  

Alternatively, maybe when saving more than one message at the same time, there is an option to save as  individual JSON files?

**Comment by paolosalvatori** [comment]
This is a good feedback, I'll work on this when I'll have some bandwidth thanks @Oculys-DanL

**Comment by lansal15** [comment]
Was this ever addressed? We were able to save off messages but cannot load them into the Send Messages dialog. The message indicates that the file is not a valid template file.

**Comment by paolosalvatori** [comment]
Hi @lansal15 I didn't have bandwith to implement this feature, sorry about that

**Comment by lansal15** [comment]
@paolosalvatori, any update here? Is this feature now available?

**Comment by paolosalvatori** [comment]
I should invest time to implement this feature. Maybe in December, I may have some time at disposal.

**Comment by lansal15** [comment]
Any luck?
