### ISSUE TITLE
Message text always appears encoded

### ISSUE THREAD

**Issue by BrianVallelunga** [paolosalvatori/ServiceBusExplorer#11]
I always see the message text encoded such as: 40 18 52 65 63 6F 72 64 41 63

My messages are created using var message = new BrokeredMessage(myObject). I think this uses the binary XmlDictionaryWriter. Is there something I can do to see a text version of the XML content?

**Comment by paolosalvatori** [comment]
Hi Brian
The reason why the message text is visualized that way is that the message itself is probably in binary format. The tool tries to read the message in text format, and if it's not possible, it visualize it in binary format.
Ciao
Paolo

**Comment by tekmaven** [comment]
@paolosalvatori I am having a similar issue.  I did not have the issue in older versions (I think 2.2).  I believe the messages are UTF-8 encoded (possibly with BOM).  If I change the Body Type to "String" nothing happens.

**Comment by SeanFeldman** [comment]
@tekmaven Are those by any chance messages from NServiceBus? 
NServiceBus messages are XML or JSON but they are sent as bytes of an original UTF-8 string (with BOM). I have opened [this PR](https://github.com/paolosalvatori/ServiceBusExplorer/pull/17) to address this. Wondering if your issue is related.

**Comment by tekmaven** [comment]
@SeanFeldman  They are NSB messages.  We use the JSON serializer.

We will test your fork out and use it.  We have had to rely on a hacked source to view message contents, and use powershell scripts to move messages currently.

I hope @paolosalvatori can review the PR (#17) and merge it.

**Comment by paolosalvatori** [comment]
Yep. I merged your change already, thanks. :)

**Comment by SeanFeldman** [comment]
@paolosalvatori should this issue be close since https://github.com/paolosalvatori/ServiceBusExplorer/pull/17 is merged and `byte[]` is supported now?

**Comment by paolosalvatori** [comment]
Closed. Thanks!
