### ISSUE TITLE
Add version to ServiceBusExplorer.zip

### ISSUE THREAD

**Issue by tomkerkhove** [paolosalvatori/ServiceBusExplorer#114]
When downloading a new release of Service Bus Explorer it always has the name `ServiceBusExplorer.zip`.
It would be nice to have the version name in the filename.

Important to say that this is not important but rather an improvement request.

**Comment by paolosalvatori** [comment]
Excellent feedback @tomkerkhove :) @SeanFeldman, do you think it's possible to implement this feature?

**Comment by SeanFeldman** [comment]
Are holding on to those zips @tomkerkhove because you don't trust the latest and greatest? 🙂 
Reasonable ask, 👍

**Comment by tomkerkhove** [comment]
That's fast - Thanks @paolosalvatori & @SeanFeldman!

**Comment by bojordan** [comment]
Bo Jordan liked your email
Spark by Readdle
