### ISSUE TITLE
Convert solution to use the new CSPROJ format

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#116]
The new csproj format is cleaner, smaller, better package and reference management, multi-targeting, etc.

Some reading material:
- [Old csproj to new csproj: Visual Studio 2017 upgrade guide](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) bit dated, but still good.
- [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)

**Comment by SeanFeldman** [comment]
Not possible with windows forms projects

**Comment by SeanFeldman** [comment]
Perhaps it's possible now?

**Comment by paolosalvatori** [comment]
@SeanFeldman can anyone make a prototype and then a PR?

**Comment by ErikMogensen** [comment]
It looks like it is still not possible, the article https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md says support for WinForms projects will come in 16.0, which is VS 2019.

**Comment by paolosalvatori** [comment]
Let's wait a few months then :)

**Comment by SeanFeldman** [comment]
An issue that would cover this request: https://github.com/paolosalvatori/ServiceBusExplorer/issues/527

**Comment by ErikMogensen** [comment]
Fixing this will ease the migration to .NET 5 and a GitHub Actions based build.
