### ISSUE TITLE
Cannot connect with connection string

### ISSUE THREAD

**Issue by filipebezerra** [paolosalvatori/ServiceBusExplorer#121]
I'm trying to connect to my Notification Hub using the version 4.0.91 and some other earlier versions but everything that I got is:

```
<14:27:40> The application is now connected to the sb://ns-push-monkeyhub-app.servicebus.windows.net/ service bus namespace.
<14:27:40> MessagingFactory successfully created
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 1 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 2 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 3 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 4 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 5 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 6 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 7 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 8 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 9 of 10.
<14:34:36> Exception: Um ou mais erros.. Method <GetRelays>b__211_0: retry 10 of 10.
<14:34:36> Exception: Um ou mais erros.
<14:34:36> InnerException: O servidor remoto retornou um erro: (500) Erro Interno do Servidor. TrackingId:b1bec10e-ef0c-4286-b98e-e3d5a5ff4515, SystemTracker:NoSystemTracker, Timestamp:18/06/2017 17:34:36
```

I'm setting up with DefaultFullSharedAccessSignature connection string.

Maybe isn't important but my account is a DreamSpark Subscription so it's a free subscription and it's located at Brazil South.

**Comment by SeanFeldman** [comment]
@paolosalvatori do you know if DreamSpart subscriptions require anything special?

**Comment by paolosalvatori** [comment]
Mmm... @filipebezerra @SeanFeldman, I don't know DreamSpart subscriptions, hence I can't answer your question :(

**Comment by filipebezerra** [comment]
Thanks @paolosalvatori. Can you indicate someone related to Microsoft to help with this? How can I submit an issue to the team related with Dreamspark subscriptions?

**Comment by SeanFeldman** [comment]
@filipebezerra can you raise an issue on the [Azure portal](http://www.azureman.com/infrastructure/manage-your-azure-support-tickets-in-the-new-azure-portal/)?

**Comment by filipebezerra** [comment]
Yep, I will. Thanks

**Comment by tomkerkhove** [comment]
What was the outcome of this @filipebezerra? Can this be closed?

**Comment by filipebezerra** [comment]
yes, it wasn't solved but can be closed

**Comment by tomkerkhove** [comment]
Sorry to hear that - If we can help you in any other way, feel free to re-open it or create a new issue
