### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by KSib** [paolosalvatori/ServiceBusExplorer#126]
I noticed that the documentation says the following: 

> Important Note
> The zip file contains:

but I don't see a zip file. I've downloaded the version I have from... I don't even know where anymore. Shouldn't the link to the download just be right at the start of the documentation?

Thanks.

**Comment by paolosalvatori** [comment]
Hi @Ksib, I initially published the code on MSDN Code Gallery at https://code.msdn.microsoft.com/windowsapps/Service-Bus-Explorer-f2abca5a. Here the code is available by downloading a zip file. However, I'm no more updating the code at that link, and sooner or later I'll clearly drop the project on MSDN Code Gallery.

**Comment by SeanFeldman** [comment]
For anyone who's looking at this issue - all versions for download are under GitHub [here](https://github.com/paolosalvatori/ServiceBusExplorer/releases). The old version, (2.1.0) is available as a [zip](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/2.1.0) or as [support branch](https://github.com/paolosalvatori/ServiceBusExplorer/tree/support-2.1).
