### ISSUE TITLE
Update README.MD with meta information about the repo

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#127]
Document things such as
- VS and C# version requirement
  - Fortify
  - Support branches policy
- Versioning and releases
  - Include future plans
- _Consider_ moving documentation into appropriate (linked) location similar to how other projects are doing it ([GitVersion](https://gitversion.readthedocs.io/en/latest/), [BenchmarkDotNet](http://benchmarkdotnet.org/Guides/GettingStarted.htm), [AutoMapper](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started), etc)

**Comment by paolosalvatori** [comment]
Thanks :)
