### ISSUE TITLE
SAS Token error: Manage claim is required for this operation - Notification Hubs

### ISSUE THREAD

**Issue by gorillapower** [paolosalvatori/ServiceBusExplorer#128]
Im getting `<Error><Code>401</Code><Detail>Manage claim is required for this operation..TrackingId:1745cb27-0fda-4c6c-8f7b-ee2d6868ac96_G6,TimeStamp:6/27/2017 11:32:19 AM</Detail></Error>` whenever i try and connect to a notification hub using a SAS key. Ive tried regenerating the key, tried a SAS Key from a different Notification Hub, tried creating a separate key, tried a key from a different Azure subscription, tried running the explorer from a different PC. Same result.... am i missing something obvious?

![image](https://user-images.githubusercontent.com/8879065/27585684-880766ba-5b3d-11e7-8ec9-0ee2d191deb6.png)

**Comment by SeanFeldman** [comment]
I wasn't able to connect with a connection string for Basic tier.
Multiple `Microsoft.ServiceBus.Messaging.MessagingException` exceptions, but that's it.
@paolosalvatori any ideas?

**Comment by gorillapower** [comment]
It seems to work on an old version of Service Bus Explorer 3.4.2. But in that version the hubs dont load at first I have to manually refresh entities on the notification hubs entity to get them to show...but it does work. Not sure why the latest version throws the 401?

**Comment by paolosalvatori** [comment]
Hi @gorillapower, could you please send me the connection string offline? You can find my email address in the about form, This way I can debug the code and find the culprit. Thanks!

**Comment by gorillapower** [comment]
@paolosalvatori  thank you! I have sent a mail.

**Comment by paolosalvatori** [comment]
Ok, I solved the issue, but I need more time to make other changes to the code. :) So expect a new release soon that will fix the issue. :)

**Comment by SeanFeldman** [comment]
In a branch, right @paolosalvatori? 😃

**Comment by gorillapower** [comment]
@paolosalvatori <https://github.com/paolosalvatori> Thanks!!!

**Comment by paolosalvatori** [comment]
Yes @SeanFeldman :) I never thought that someone else could make the rules on my project :) Ah ah ah... but yes, it's a good practice :)

**Comment by SeanFeldman** [comment]
Not rules. Recommendations 😉

**Comment by paolosalvatori** [comment]
@SeanFeldman I'm joking... it's all fun :)

**Comment by SeanFeldman** [comment]
:+1:

**Comment by paolosalvatori** [comment]
@gorillapower try to get the latest version. Also, I suggest you to select only Notification Hubs from the dropdownlist when connecting to a Notification Hub namespace. In fact, the tool cannot determine the type of namespace and it tries to retrieve all the entities (queue, topics, relays, event hubs, notification hubs) when connecting to a namespace. In order to understand the namespace type, the tool should use an AAD user to retrieve this information from the namespace resource. But this would require creating an Application on a tenant of the user AAD, and... too complicated :)

**Comment by ErikMogensen** [comment]
In case anyone ends up here when searching for this error, the solution for me was to use the connection string from the **Notification Hub Namespace** and not the Notification Hub when copying it from the Azure Portal.

**Comment by cirino-gomez** [comment]
As @ErikMogensen said, it works with the RootManageSharedAccessKey :-) Thanks for this amazing tool 🥇

**Comment by paolosalvatori** [comment]
Thanks for the positive feedback @cirino-gomez :)
