### ISSUE TITLE
Need to complete the message repair and re-transmit pattern

### ISSUE THREAD

**Issue by paolosalvatori** [paolosalvatori/ServiceBusExplorer#135]
Need to complete the message repair and re-transmit pattern:
 - Defer the original message
 - Receive the deferred message by sequence number to consume it

Repair and resubmit is already in place. What's missing is the safe original message removal leveraging steps above.

**Comment by SeanFeldman** [comment]
Similar concept implemented by SB360 with ["Deferred Dead Letter" feature](https://www.servicebus360.com/blogs/resubmit-delete-messages-azure-service-bus-messaging/).
