### ISSUE TITLE
Can't purge sessioned entities

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#136]
Exception thrown:
`It is not possible for an entity that requires sessions to create a non-sessionful message receiver.`

**Comment by lenardg** [comment]
Isn't this the same as #96 ?

**Comment by SeanFeldman** [comment]
#96 is a subset of this one.

**Comment by paolosalvatori** [comment]
This looks like a bug

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/8f9d3d0cbf694d60be8df387686e6c3619d8d1cc

**Comment by SeanFeldman** [comment]
@paolosalvatori indeed. And #159 has addressed it ([see comment](https://github.com/paolosalvatori/ServiceBusExplorer/issues/136#issuecomment-339501687)). 🙂
