### ISSUE TITLE
Not supported api-version

### ISSUE THREAD

**Issue by stjepan** [paolosalvatori/ServiceBusExplorer#138]
Hi,

I'm trying to connect with latest version (4.0.99 at the time of writing) of Service Bus Explorer to locally installed Service Bus 1.1 (running on Windows 10) and I'm getting  following message: "The api-version in the query string is not supported. Either remove it from the Uri or use one of '2012-03,2012-08,2013-04,2013-07'".

I see a lots of people ask about this one, but can't get a better answer then using an older version of Service Bus Explorer, like 2.1 which used an older api-version, like 2013-07.

Do you have a plans of fixing the api-version issue?

Thanks in advance!

/S.

**Comment by paolosalvatori** [comment]
Hi @stjepan Service Bus Explorer tool stopped supporting Service Bus for Windows Server 1.1 from version 2.2. The only version of the tool that supports SB 1.1 is available at: https://github.com/paolosalvatori/ServiceBusExplorer/tree/support-2.1

**Comment by stjepan** [comment]
Then I know!
Thank for the quick answer!

**Comment by SeanFeldman** [comment]
FWIW: #119
