### ISSUE TITLE
Access individual entities w/o permission to the entire namespace

### ISSUE THREAD

**Issue by nkeeslin** [paolosalvatori/ServiceBusExplorer#139]
I have a connection string that provides access to a Topic, but not to the Namespace.  I need to be able to connect to that Topic and create/update Subscriptions, but when I try to use the connection string it fails with message: 

"Exception: The remote server returned an error: (401) Unauthorized. claim is empty..".

The purpose for this is to allow our external teams to have manage rights over a single Topic while not letting them Manage the whole namespace.  Is there any way around this?

**Comment by paolosalvatori** [comment]
Hi @nkeeslin the tool currently does not support entity-level connection string and the ability to connect to a single topic or queue, sorry about that. If you like, you can extend the tool with a PR. At the moment, I'm quite busy with some work, and I can't do it personally.
