### ISSUE TITLE
Messages are not always send to topic

### ISSUE THREAD

**Issue by MikeWilliams-UK** [paolosalvatori/ServiceBusExplorer#144]
We have been having issues where a repaired message is not always sent to a topic

I think it might be down to the cloned (repaired) message having the same messageid as one already present.

I have experimented with the code and inserting the following code

`clone.MessageId = Guid.NewGuid().ToString("N");`

into the file ..\Helpers\BrokeredMessageExtensions.cs during the Clone operations

**Comment by SeanFeldman** [comment]
Do you have message de-duplication turned on?

**Comment by MikeWilliams-UK** [comment]
Where is that setting?

**Comment by SeanFeldman** [comment]
On the topic itself. If it's on, messages will be de-duplicated on message ID. That's ASB feature, not SBExplorer. Which explains why re-submitting with a different message ID worked for you.

**Comment by MikeWilliams-UK** [comment]
Thanks, we do not have ownership or the topic so can't change its settings.  So a coded solution in SBE works best for us.

**Comment by SeanFeldman** [comment]
This cannot be mandatory as it would break those that already rely on the fact that message ID is re-used.
Suggest to close this one and open a feature request issue to enable message ID override when sending to entities that perform message de-duplication (like in this case).

**Comment by MikeWilliams-UK** [comment]
I 100% agree that it can't be mandatory. I will submit as a feature request to make it an option in the resubmit form

**Comment by paolosalvatori** [comment]
Back from vacation, I agree with @SeanFeldman, let's create a separate open issue for the missing feature.
