### ISSUE TITLE
Chocolatery deployment fails when a PR is merged into master

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#154]
[`Release-4.0.104`](https://github.com/paolosalvatori/ServiceBusExplorer/pull/153) was merged into `master`, but [deployment to choco has failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/build/4.0.104-ci.8.build.310).

I have manually pushed the package and had timeout issues while doing so.

If choco server might have issues, we should script retries in the deployment script to try a few times and log a more meaningful message.

> Chocolatey v0.10.7
Attempting to push ServiceBusExplorer.4.0.104.nupkg to https://push.chocolatey.org/
There was an internal server error, which might mean the package already exists on a Simple OData Server.
Command exited with code 1

Also, the message logged makes me wonder if we've tried to push more than once?

/cc @tomkerkhove

**Comment by tomkerkhove** [comment]
This might be interesting - https://github.com/appveyor/ci/issues/418

We could do `appveyor-retry choco push ServiceBusExplorer.%GitVersion_MajorMinorPatch%.nupkg -k="'%choco_token%'"`

**Comment by SeanFeldman** [comment]
Well, glad to see we're not the only ones who ran into it.
`appveyor-retry` for choco it is then...

**Comment by SeanFeldman** [comment]
While chocolatey is failing (for now), has anyone noticed that our latest submitted package was approved w/o any hassle? Huge kudos to all!

![image](https://user-images.githubusercontent.com/1309622/31108526-19044c30-a7b7-11e7-8f09-018d4a83ec56.png)

Yes, I'm celebrating a small success 🙂

**Comment by paolosalvatori** [comment]
Yep, I received the email a few days ago :) Congrats guys :)

**Comment by tomkerkhove** [comment]
@SeanFeldman I'll have a look at it this week/next week!

Good to hear!

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/bc3d7da738d1aa619bb45fd7a54f1504292e5a88

We'll see it in action in version [4.0.105](https://github.com/paolosalvatori/ServiceBusExplorer/milestone/9)
