### ISSUE TITLE
Provide documentation on how to contribute

### ISSUE THREAD

**Issue by tomkerkhove** [paolosalvatori/ServiceBusExplorer#157]
Provide documentation on how to contribute to ServiceBusExplorer.

Should include information like:

- [x] What issues people can pick up
- [x] Branching

**Comment by SeanFeldman** [comment]
Quick notes to help with the outline.

> What issues people can pick up

We've got [`help wanted`](https://github.com/paolosalvatori/ServiceBusExplorer/labels/help%20wanted) label

> Branching
- `master` is used to release
- `develop` is the default branch
  - PRs automatically go against the default branch
- fixed issues/PRs should be assigned the next release milestone upon completion

**Comment by tomkerkhove** [comment]
@SeanFeldman This can be closed I think?

**Comment by SeanFeldman** [comment]
:+1:
