### ISSUE TITLE
Cogin QueueExplorer

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#165]
A [new offer](http://cogin.com/QueueExplorer/prerelease/) is on the market. Currently in preview.
Question I have what's the future of this project? Besides being an OSS, what else would distinguish it from everything else [out there](https://github.com/paolosalvatori/ServiceBusExplorer#alternative-service-bus-management-tools) (listed and unlisted)?

**Comment by paolosalvatori** [comment]
Hi Sean, I started this project years ago. Currently, as you know, I'm developing this project on a best effort basis. Let's talk offline about this.

**Comment by tomkerkhove** [comment]
For what it's worth - It's a pretty popular tool that a lot of people use imo so would be good to keep maintaining it. But ofcourse, this is @paolosalvatori his baby so it's up to him.

**Comment by paolosalvatori** [comment]
@tomkerkhove @SeanFeldman of course we'll mantain it :) Let's make a plan of what we want to implement. Feel free to sugest new features.

**Comment by SeanFeldman** [comment]
You've misread my original comment. The question is not about maintaining it or not. The question is what distinguishes the tool from everything else out there. If it's just "free", then it's one strategy to maintain the code. If it's "provide certain core functionality" and "remain free", then it's a different route.

Having a chat about it is a good step. 👍

**Comment by SeanFeldman** [comment]
Closing. We haven't discussed this, but can be re-opened if needed.
