### ISSUE TITLE
ContentType lost when resubmitting message with body type ByteArray

### ISSUE THREAD

**Issue by snaits** [paolosalvatori/ServiceBusExplorer#166]
This may be due to an error on my part, but there's little help to be found on the wiki pages or the internet in general, so I thought I'd start an issue to shed some light on how it's intended.

We send messages that are serialized to JSON. This is indicated by the ContentType property as well; it says application/json.

When I receive messages from a dlq on a subscription, and try resending it, the message has lost it's ContentType value - it is empty. But this only happens when I resend it with a body type of ByteArray. Stream, String and WCF body types behave as expected.

**Comment by tomkerkhove** [comment]
Thank you for reporting & fixing it!

**Comment by paolosalvatori** [comment]
Thanks everyone, I was OOF last week
