### ISSUE TITLE
messages lost when using SignalR Scaleout with Azure Service Bus Premium

### ISSUE THREAD

**Issue by racchen** [paolosalvatori/ServiceBusExplorer#169]
Hi , 

I followed the link below to realize SignalR scaleout with Azure Service Bus. 
https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-windows-azure-service-bus

When using Azure Service Bus Standard Tier, i can receive the message successfully but with network latency around 10 seconds. However, when changing to Premier Tier, i encountered the problem of message lost. I have confirmed the Azure Service Bus has correct number of input and output messages. So i think the problem here might be VS code was failed to receive message from Service Bus. 

I used Azure Service Bus SDK in VS code. I think the issue might related to it. Will it be better by using Azure RestAPI instead? Or using Azure Service Bus endpoint? 

I am kinda wonder how Service Bus Explorer does to receive messages correctly. 

Thanks,

**Comment by racchen** [comment]
Hi @paolosalvatori , 
Yes, now i am using updated driver version.

Install-Package Microsoft.AspNet.SignalR.ServiceBus3 -Version 2.2.2
Install-Package WindowsAzure.ServiceBus -Version 4.1.6

I heard there might be some problems when using Azure Service Bus SDK in VS code. Do you think the performance might be better if we change to Azure RestAPI instead or Azure Service Bus endpoint?

**Comment by paolosalvatori** [comment]
That is certainly an valid option. I'll let @clemensv from the product group to comment on this.

**Comment by racchen** [comment]
Okay, thanks! i am looking forward to have good news soon :)

**Comment by SeanFeldman** [comment]
@racchen I'm going to close the issue as it's not SBE specific, but please keep the conversation here if needed. Thanks.

**Comment by racchen** [comment]
yes, please close it :)

**Comment by dil-bpecor** [comment]
Any Results?
