### ISSUE TITLE
Repair and resubmit all messages from DLQ

### ISSUE THREAD

**Issue by antongeorgiev** [paolosalvatori/ServiceBusExplorer#173]
It is not possible to repair and resubmit large amount of messages from the dead-letter queue because currently messages can only be resubmitted in a batch mode and a batch size is limited to 256 KB.

A user should be able to either select the queue or manually select multiple or all messages in a queue and choosing to "Repair and resubmit in batch mode" should have all selected messages processed.

Possible solution might be to leverage the functionality in the "Send messages" dialog by using the DLQ as an input source and providing an option to select the destination queue but defaulting to the entity the DLQ is part of. 

The following posts might be helpful:

- https://weblogs.asp.net/sfeldman/asb-batching-brokered-messages
- https://mikhail.io/2017/07/sending-large-batches-to-azure-service-bus/

**Comment by antongeorgiev** [comment]
The following posts might be helpful:

- https://weblogs.asp.net/sfeldman/asb-batching-brokered-messages
- https://mikhail.io/2017/07/sending-large-batches-to-azure-service-bus/

**Comment by SeanFeldman** [comment]
@antongeorgiev it's not possible to repair and resubmit more than a single message. SBE was designed to handle only one message at a time and it is not related to a batch size. The current UI would need to be modified and better not reuse-abuse existing functionality as it becomes more and more difficult to maintain this code based.

I don agree that having an ability to fix multiple messages from DLQ and resubmit would be nice to have. Would you like help and send a PR?

**Comment by paolosalvatori** [comment]
Hi @antongeorgiev one of the articles you sent me refer my Service Bus Extensions library that you find on this GitHub account ;) The reason why the tool is designed this way it's because:
 - if you want to resubmit multiple messages, you can select them and send them as is, with no changes
 - if you want to repair and resubmit messages, there's no wayout, you have to do this operation one message at the time.
Hope this helps. You have another idea in mind, please let us know.

**Comment by ErikMogensen** [comment]
@antongeorgiev, in the latest version of the Service Bus Explorer (SBE) in the Develop branch, there is new functionality for submitting multiple messages from the DLQ. There is a new checkbox with the text "Remove messages from the DLQ". If you check it, SBE will send the messages one at a time to avoid duplicates.

Is that what you are looking for? 

Anyway, I think that the "Resubmit selected messages in batch mode" should be changed to just send as many messages that fits in a batch and then create more batch messages to be able to send all of the selected messages. Paolos Service Bus Extensions Library seems great for this task.

**Comment by prakratipradhan** [comment]
> Hi @antongeorgiev one of the articles you sent me refer my Service Bus Extensions library that you find on this GitHub account ;) The reason why the tool is designed this way it's because:
> 
> * if you want to resubmit multiple messages, you can select them and send them as is, with no changes
> * if you want to repair and resubmit messages, there's no wayout, you have to do this operation one message at the time.
> 
> Hope this helps. You have another idea in mind, please let us know.
