### ISSUE TITLE
Mouse pointer in dialog window when asking for confirmation to purge is in wait state

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#176]
When selecting Purge or Purge DLQ from the main window the mouse pointer turns into the wait state when the dialog window asking for confirmation to proceed. It should not turn into the wait state until OK has been clicked. 

This behavior does not occur when selecting Purge* from the Popup menu. 

I believe there is a simple fix for this. I'll create a PR.

**Comment by paolosalvatori** [comment]
Thanks @ErikMogensen.. again! :)
