### ISSUE TITLE
TimeoutExceptions cause Null reference exceptions

### ISSUE THREAD

**Issue by jgoyvaerts** [paolosalvatori/ServiceBusExplorer#177]
When a timeout exception occurs when you refresh Queues or other top nodes, a null reference exception occurs as a result of incorrect nodes list removal (`relayServiceListNode` is attempted to be removed for [queues](https://github.com/jgoyvaerts/ServiceBusExplorer/commit/3e98cf2faf9dcfd285b4a43f1aae71de13bd6b05#diff-c6c670cf209d398a1828a3de03a47565L4815), [topics](https://github.com/jgoyvaerts/ServiceBusExplorer/commit/3e98cf2faf9dcfd285b4a43f1aae71de13bd6b05#diff-c6c670cf209d398a1828a3de03a47565L4940), event hubs and notification hubs)

**Comment by SeanFeldman** [comment]
Thank you @jgoyvaerts for catching this and sending a PR.
I took the liberty to update issue with details why the `NullReference` why taking place.

**Comment by paolosalvatori** [comment]
Thanks @jgoyvaerts

**Comment by PratikMSFT** [comment]
Customers has issue connecting through latest SB explorer version with 1000 entities in queues getting timeout, any options to tackle this problem please

**Comment by ErikMogensen** [comment]
@PratikMSFT , increase the Receive timeout setting and perhaps the Server timeout setting too in the View -> Options dialog. 

In the next release the default settings for these are greatly increased.
