### ISSUE TITLE
Repair and Resubmit Messages without Copy

### ISSUE THREAD

**Issue by YetiNerd** [paolosalvatori/ServiceBusExplorer#179]
Hi There,

it would be great if there would be the opportunity to repair and submit Messages without creating a copy. 
If your Logic App is using Lock&Peek and cannot process the Message due downtime of destination system there would be great to resubmit this message (from DLQ).

Thank you! 

Best
Waldemar

**Comment by SeanFeldman** [comment]
@YetiNerd it's an ASB requirement, not ServiceBus Explorer. ASB doesn't allow to update an existing message and requires a new message to be submitted.

**Comment by YetiNerd** [comment]
@SeanFeldman Understand. 
Can you maybe suggest a best practice how to resend messages when destination is unavailible and you want to resend the message when the destination is online/availible again? As in: how to resend (new) and delete (old) message in DLQ?

**Comment by SeanFeldman** [comment]
It depends. If it's a one off, you could use SBExplorer to achieve this.
If we're talking about a significant number of messages, then it depends on whatever the scenario is.
