### ISSUE TITLE
Purge DLQ is broken

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#183]
SBE version: 4.0.106
Queue: not partitioned, standard tier, no sessions, 1GB size

Looks like there was a regression in #180.
As of now, Purge DLQ doesn't do anything.

Validation: have a single dlq-ed message, push Purge DLQ. Status says:
><22:28:57> [0] messages have been purged from the deadletter queue of the [test] queue in [896] milliseconds.

and dead-lettered message stays as is.
![image](https://user-images.githubusercontent.com/1309622/35763389-9528264e-0868-11e8-94b8-9c37ff7b35a4.png)

**Comment by ErikMogensen** [comment]
Hi Sean,

I wrote the MessagePurger class. Great that you found the bug with one-message queues and fixed it. I tested the class with different combinations of partioned/non-partioned/sessioned/non-sessioned/standard/premium queues and subscriptions with up to a million messages but never tested with just one message.

**Comment by SeanFeldman** [comment]
@ErikMogensen no worries. It's an edge case I happened to run into.

**Comment by paolosalvatori** [comment]
Thanks guys!
