### ISSUE TITLE
Change C# language version

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#186]
Currently the Language version is set to "C# latest major version (default)". I suggest this is changed to "C# latest minor version (latest)". That way we could take advantage of the new features in C# 7.1, 7.2 and later versions.

Do you agree?

**Comment by SeanFeldman** [comment]
Sounds good. Any specific features you're thinking of?

**Comment by ErikMogensen** [comment]
I was thinking of [Reference semantics with value types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#reference-semantics-with-value-types) and [Non-trailing named arguments](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#non-trailing-named-arguments). 

It would also be nice with the C# 7.0 support for tuples but as I understand it that requires an upgrade to .NET 4.7 or having to include one more dll when distributing SBE which may be not worth it.

**Comment by SeanFeldman** [comment]
Tuples require an external [package](https://www.nuget.org/packages/System.ValueTuple/)

**Comment by ErikMogensen** [comment]
It was only changed for Debug builds, not for Release builds.

**Comment by paolosalvatori** [comment]
Let me check to understand the implications in terms of version of the .NET framework and Visual Studio.

**Comment by ErikMogensen** [comment]
@paolosalvatori, I tried different combinations of the C# version setting and the Target framework setting and some combinations do not compile. It looks like the target version of the .NET Framework is solely determined by the Target framework setting (on the Application tab in project settings).

**Comment by paolosalvatori** [comment]
@ErikMogensen which version should I set? :)

**Comment by paolosalvatori** [comment]
Ok I approved the PR, I need @SeanFeldman to approve it as well :)

**Comment by SeanFeldman** [comment]
`LangVersion` version has no impact on the compiled assembly. It's a syntactic sugar.

> Regardless of which -langversion setting you use, you will use the current version of the common language runtime to create your .exe or .dll. 

For that reason I'm 👎 to merge that change.

**Comment by ErikMogensen** [comment]
I'll try to convince you.

By setting the C# language to a fixed version you know which features you may use and not use when developing. 

If you set it to the latest version the resulting version would be determined by which compiler version you are using which in turn is usually determined by the VS version. This may create problems when a new C# version is released since AppVeyor and people developing for SBE may upgrade at different times. Some may even use a preview of the next C# version. There are indications that C# 8.0 may end up not being backwards compatible so this may be a big issue when it is released.

Better to get a build error that your compiler is unable to handle a C# version than get strange compiler errors.

**Comment by SeanFeldman** [comment]
Not convinced 😉

When C# 8.0 will be out, AppVeyor will have an image. Frankly, it feels
like solving a problem we don't really have.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/cc13644b64ff677d15c493f81b3e22f25b995718
