### ISSUE TITLE
Commits to master should not be allowed

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#187]
We're using a flow for a while where changes are staged on `develop` and released in a control version by having a PR from `develop` to `master`. Once PR to `master` is merged, a release is created with appropreate version increase (build version) and it's possible to know what bugs where fixed/improvements made on the [releases page](https://github.com/paolosalvatori/ServiceBusExplorer/releases).

With commits streight to `master` that flow is ultimately is broken. For example, there's a [release 4.0.107](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.0.107) that doesn't have any information what the release is all about. It's entirely based on a [single commit](https://github.com/paolosalvatori/ServiceBusExplorer/commit/c84dc37623f9c8134f1d9554f52ec1442b20afee) that appears to be cosmetic at most (no descriptive commit message either).

@paolosalvatori you're the only one who can commit directly to `master` ATM. To avoid this, the default branch has to be set to `develop` and not `master`.

**Comment by SeanFeldman** [comment]
Also, if we follow the flow, `master` should never contain commits that cannot be found on `develop`.

**Comment by tomkerkhove** [comment]
Agreed :+1:

**Comment by paolosalvatori** [comment]
Sorry guys, I was in a hurry and didn't realize I published to the master.
