### ISSUE TITLE
Auto-refresh queue 

### ISSUE THREAD

**Issue by Asura5** [paolosalvatori/ServiceBusExplorer#188]
I'm often working with a single queue or queues that do not have subscriptions or event hubs (yet or ever) - I know that F5 will trigger a refresh of an queue however for those monitoring mesasge/DLQ numbers (note I am not suggesting wider use as queue monitoring application!) would auto-refresh be an option?

**Comment by SeanFeldman** [comment]
@Asura5 could you walk through how this would work? I imagine it would be some toggling to have a queue refreshed. But how often? Is it something that should be configured? Etc. You see where I'm leaning with this. Thanks.

**Comment by paolosalvatori** [comment]
This is not the first time that I receive this request. We should introduce two options in the application configuration and options dialog:
 - Enable autorefesh
 - Refresh interval in seconds
At each refresh, we should basically refresh the entire TreeView making sure to avoid flickering.

**Comment by Asura5** [comment]
That's pretty much what I had in mind. The refresh rates are global to all queues, so:

- Add Queue refresh time (seconds) option to OptionForm.
- 0 in this box disables auto-refresh, and is the default
- Non-zero input will enable auto-refresh with the given number of seconds:
-     GetEntities called asynchronously (I am not sure of exact implementation details - awaitable Task?)

**Comment by tomkerkhove** [comment]
If it's in the UI I think we should provide a slider with reasonable values to avoid hammering SB because somebody wants to refresh every second, but that's my personal opinion.

**Comment by paolosalvatori** [comment]
@tomkerkhove  I couldn't agree more

**Comment by SeanFeldman** [comment]
Refreshing entities to get message counts is a bad idea.
First, we're on the old client and the new client has removed that functionality for a good reason.
Second, message count is **not** as accurate as you'd think. So pinging it every second for **all** entities will be just counterproductive.

Is F5 that hard? SBE is for _managing_ entities and messages, not monitoring. If you need monitoring, I'd argue that's a different tool. My 2c 🙂

**Comment by Asura5** [comment]
As suggested in the initial post I was in not suggesting use for monitoring - not nearly in the order of every second - more along the lines of every x minutes. However - thanks for the very clear feedback. I'll implement locally and close the issue.
