### ISSUE TITLE
Protect master branch from direct commits

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#190]
@paolosalvatori could you please configure to protect `master` branch to avoid accidental direct commits and only allow PRs? This is how it works for others targetting `develop` and `master` branches.

Once a branch is protected, issues like #187  will not take happen.

**Comment by paolosalvatori** [comment]
Let's take this offline next week. Ping me on Tuesday and let's make this together.

**Comment by SeanFeldman** [comment]
> Ping me on Tuesday and let's make this together.

This is where I wish Swatch Beat (aka [Internet Time](https://www.swatch.com/en_ca/internet-time/)) would become a standard...
Tuesday what time and time zone? 😛

**Comment by paolosalvatori** [comment]
Just ping me in the morning and we'll figure it out :)

**Comment by SeanFeldman** [comment]
Checked again and noticed that `master` and `develop` are protected from deletions.
![image](https://user-images.githubusercontent.com/1309622/36439785-223dbca4-162b-11e8-97dc-55751a375aab.png)

Great. The only remaining item then is to ensure no direct commits are allowed to `master`.

Probably 2 other branches should be protected so they cannot be accidentally deleted.

![image](https://user-images.githubusercontent.com/1309622/36439718-f6d1e31a-162a-11e8-8a1b-85bf9527005a.png)

**Comment by tomkerkhove** [comment]
@paolosalvatori Would it be possible to secure `master` please?

**Comment by paolosalvatori** [comment]
Hi @tomkerkhove / @SeanFeldman  the master branch already requires pull requests to be reviewed and approved by an administrator... but this rule applies to everyone but administrators, in other words, it does apply to me ;) So I suppose you want me to enable the following option:

Include administrators  
Enforce all configured restrictions for administrators. 

Can you confirm, please? :)
Thanks!

**Comment by SeanFeldman** [comment]
Ability to review and approve should be done by [CODEOWNERS](https://help.github.com/articles/about-codeowners/) that should be listed and the option _Require review from Code Owners_ is enabled. That way, no matter if the person an admin or not, they would be able to review and merge. Assuming there's at least a 2nd review in place. Which is achieved by enabling _Require pull request reviews before merging_.

**Comment by paolosalvatori** [comment]
@SeanFeldman @tomkerkhove @ErikMogensen I created a CODEOWNERS file under the docs/ folder in the develop branch.

**Comment by SeanFeldman** [comment]
Is there anything left to do on this or are we good to close it?

**Comment by tomkerkhove** [comment]
Think we are good for now at least, can still re-open.

**Comment by SeanFeldman** [comment]
> Think we are good for now at least, can still re-open.

Then why wasn't that your closing comment? 😝
