### ISSUE TITLE
How do we use SBE to move messages between queues?

### ISSUE THREAD

**Issue by todthomson** [paolosalvatori/ServiceBusExplorer#193]
Hi SBE Team,

I'm currently using Mass Transit 3 https://github.com/MassTransit/MassTransit with the Azure Service Bus transport.

In Mass Transit when messages fail to be processed (configurable X times) then they get moved to an `QueueName_error` queue rather than the DLQ.

I can't work out how to use SBE to move those messages back to the original queue for re-processing... Is it just me, or is this not a feature of SBE?

If it's not a feature, what would be involved in adding it? Would this be something that you would be interested in doing?

Cheers,

Tod.

**Comment by tomkerkhove** [comment]
Do you want to automatically send them to a different queue or do it on-demand?

**Comment by SeanFeldman** [comment]
Related to #173.
If you want to move messages automatically, auto-forwarding could help. Otherwise, it's a feature that would be required to be implemented. It would be clone/send/delete type of deal.

**Comment by todthomson** [comment]
> Do you want to automatically send them to a different queue or do it on-demand?

**Comment by todthomson** [comment]
> It's a feature that would be required to be implemented. It would be clone/send/delete type of deal.

Roger that. How do I turn this into a "feature request"? Do you think it would be reasonable for someone unfamiliar with the project (e.g. me) to tackle it?

**Comment by SeanFeldman** [comment]
@todthomson you can definitely send a PR if you have some time on hands.

**Comment by ErikMogensen** [comment]
I implemented moving of messages from deadletter subqueues (DLQ) in #192. I explained the reason for only implementing it on DLQs in the PR. In short it requires incrementing the Delivery Count for every message that is before the message(s) you want to move (clone/send/delete) and that in turn might lead to messages stored on normal queues, like your Queuename_error queue, being moved to their DLQ. 

My idea was that this feature should be tested for a while only on DLQ where the it does not matter that the Delivery Count is increased and then implemented on normal queues with a warning that the Delivery Count is incremented when using this feature.

**Comment by todthomson** [comment]
I'm closing this (and presuming that it has been fixed by #192). If for some reason this is not the case and someone cares to re-open this then that's fine, but I have moved on from Azure Service Bus so this is no longer relevant to me.

**Comment by subhendu-de** [comment]
Please refer to the article here

http://dotnetartisan.in/move-messages-service-bus-queue/
