### ISSUE TITLE
InnerException: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by Cheranarasu** [paolosalvatori/ServiceBusExplorer#194]
I gave connection string placed in namespace of my notification hub.

Exception: The remote server returned an error: (401) Unauthorized..TrackingId:7069cd50-9cbf-4bb7-a04f-6270054d75a8,TimeStamp:3/16/2018 4:11:06 AM
<09:41:06> InnerException: The remote server returned an error: (401) Unauthorized.

Previously it working properly. Now only got issue like below. It seems authentication failure and how to give proper credential to this?.

Help me to resolve it.

I have an query, do we able to send push notification to all registered device in production using this tool?.

Regards,
Cheran

**Comment by paolosalvatori** [comment]
Hi @Cheranarasu the tool requires a namespace-level connection string with manage claim, any entity-level connection string or namespace-level connection string without the manage claim will return an unauthorized error.

**Comment by Cheranarasu** [comment]
Hi @paolosalvatori ,

Thanks for your update. How to provide manage claim to my notification hub?

Can we able to send push notification to all registered device in production using this tool?

Regards,
Cheran

**Comment by paolosalvatori** [comment]
Hi @Cheranarasu the answer is yes. Please scroll the log at https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/docs/documentation.md for more information. It's quite sometime that I don't test the notification hub support in Service Bus Explorer, so I can't guarantee that it's working as expected. Hope this helps.

**Comment by tomkerkhove** [comment]
@Cheranarasu Can we close this issue?

**Comment by tomkerkhove** [comment]
Closing since @Cheranarasu did not respond for a while, will re-open when need be
