### ISSUE TITLE
Failed to resend a deadletter message with the size of 256291

### ISSUE THREAD

**Issue by oak-tree** [paolosalvatori/ServiceBusExplorer#195]
## Logs 
This what I got from the logs:

> <12:00:42> Exception: A request from the client instance has exceeded the maximum message size, and the underlying channel will be recreated. Validate the content size before retrying. TrackingId: Timestamp:3/16/2018 10:00:42 AM
> <12:00:42> InnerException: A request from the client instance has exceeded the maximum message size, and the underlying channel will be recreated. Validate the content size before retrying. TrackingId:, Timestamp:3/16/2018 10:00:42 AM

## Problem
But clearly this message had been sent before as I received it from the bus using `ServiceBusExplorer` after it became `deadletter`. 

## Ideas - Possible cause?
1. The message body is a `json`. Maybe `ServiceBusExplorer` tries to send the `json` in prettify mode and then add "\n\r" in every line ?

P.S
The reason it became `deadletter` has no relation to the above exception.

**Comment by paolosalvatori** [comment]
Hi @oak-tree, if you are trying to use SBE to send a message to a queue / topic / event hub, the tool does not attempt to recognize the format of the payload or manipulate the message body.

**Comment by SeanFeldman** [comment]
The message you're trying to send is 250KB. Depending on the headers and serialization it could easy exceed max size of 256KB.

1. Are you adding any custom properties to your message when sending from SBE? If you do could you provide their details (count, size).
1. If you send exactly that JSON using C# client, do you get this error?

**Comment by ErikMogensen** [comment]
@oak-tree , do you have anymore information on this issue? If not I suggest it is closed since it has passed more than three months without a reply.

**Comment by oak-tree** [comment]
Extra think I notice that if I try to cut the text, remove the `\n\r` and paste it again the `service bus explorer` cuts the message. I guess there is some kind of limit of the `textbox` . But this limit apears only if I try to enter the message my self or paste text. This limit does not appear if I just open a message from the bus

**Comment by ErikMogensen** [comment]
@oak-tree , I noticed that both if the properties that are set by the Service Bus service when a message is deadlettered are kept when a message is resubmitted. That could be the explanation for the increased size. 

I just created #344 for removing the deadletter properties.

**Comment by ErikMogensen** [comment]
@oak-tree , do you have any update on this issue?

**Comment by paolosalvatori** [comment]
@oak-tree I'm closing the issue, feel free to reopen it. By the way, if you feel that the textbox may have some limits in terms of supported length, you can always create your JSON file with your favorite editor and than send the file by selecting the Files tab instead of the Message tab.
