### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#2]
Would it be possible to have releases to contain MSIs?

**Comment by regisbsb** [comment]
Or even better you could add a appveyor.yml and get FREE! builds on appveyor.
@paolosalvatori if you are interested I could setup for you in a fork of mine and pull request.

**Comment by rytmis** [comment]
Not sure if you're aware, but your chocolatey package at https://chocolatey.org/packages/ServiceBusExplorer/ is not in a valid state. It can't be installed and it's still under moderation.

**Comment by paolosalvatori** [comment]
Hi Lauri
I’m pretty busy in this period. Guys, could you please help me to fix the problem to properly publish the new version to Chocolatey? Thanks!
Ciao
Paolo

**Comment by SeanFeldman** [comment]
@regisbsb I'd like to resurrect this thread and look into it. A PR would be great :)
Let's sync.

**Comment by SeanFeldman** [comment]
@regisbsb already started that here 087877502831d6383ef5f3ce5d2d956865aa2085

**Comment by SeanFeldman** [comment]
Quick update:
1. Connected the project to AppVeyor
1. Created a [sample project](https://github.com/SeanFeldman/Spike) to demonstrate how we could [package and release builds](https://github.com/SeanFeldman/Spike/releases) of master using GH. Right now it's just zipping the files.

@paolosalvatori is this something worth proceeding? I haven't spent time thinking about versioning. We could lock it in the source code to let's say `3.4.patch` and `patch` would be auto-increased whenever master is updated.

**Comment by paolosalvatori** [comment]
@SeanFeldman I updated the version of the tool right today to 3.4.2. I usually bind the tool version to the SB .NET API. We may eventually use the fourth digit for the tool version. Thoughts?

**Comment by SeanFeldman** [comment]
So according to [SemVer 2 schema](http://semver.org/) it would be `3.4.2+buildNumber`, which would be ok I presume.

Is this something we'd proceed with? I'd setup the repo to follow the sample project and we'd be able to have our build right away deployed via GH.

**Comment by paolosalvatori** [comment]
Yes, let's go with this schema.

**Comment by vonlar** [comment]
Just one comment, rather than utilizing the installer project, you might consider WiX.  It's a pain to implement though because you have to know their markup, but I'm pretty positive it's OSS and I know it's available via NuGet.  http://wixtoolset.org/

**Comment by SeanFeldman** [comment]
The current installer project is somewhat broken imo. On my machines I can't even get it loaded.

The plan for releases is following:

1. Have releases under GitHub https://github.com/paolosalvatori/ServiceBusExplorer/releases as a part of automated build (using AppVeyor).
2. Releases will include zipped files and APPX (#49)

**Comment by SeanFeldman** [comment]
Update: we have auto-deployment as part of the `master` build and currently a portable version (zip) is available under [GH Releases section](https://github.com/paolosalvatori/ServiceBusExplorer/releases). APPX to come soon.

I'm closing this issue. Please raise separate (specific) issues for items that have not been addressed.
