### ISSUE TITLE
SBE doesn't show Topics and Queues whilst Azure portal shows them

### ISSUE THREAD

**Issue by margani** [paolosalvatori/ServiceBusExplorer#205]
# Problem

Suddenly, I couldn't retrive the list of topics and queues from Azure using SBE. 
SBE logs show:
<15:15:17> The application is now connected to the sb://_MyNamespace_.servicebus.windows.net/ service bus namespace.
<15:15:17> MessagingFactory successfully created

but the right hand side tree is empty, although I can see the queues and topics in Azure web portal.

**Comment by margani** [comment]
Now, It does show the queues and topics. Any clue why it may happen?

**Comment by SeanFeldman** [comment]
@margani you're saying 

> Suddenly, I couldn't retrive the list of topics and queues from Azure using SBE.

and then 

> but the right hand side tree is empty, although I can see the queues and topics in Azure web portal.

If you couldn't retrieve the list of entities (on the left), the details view (on the right) is expected to be empty. Perhaps you could share a snapshot?

**Comment by margani** [comment]
@seanfeldman
Yes it was empty and empty screen with empty tree (with just the root node) didn't  make sense.

**Comment by SeanFeldman** [comment]
What region the namespace is at? I know West EU had issues yesterday/early today.

**Comment by ErikMogensen** [comment]
The Server Timeout setting in the Options dialog determine how long SBE will wait for a response from the ServiceBus namespace. If the namespace had performance issues and the Server Timeout setting was set to just a few seconds it would explain why you didn't see the queues and topics in SBE but in the Azure Portal which seems to have a longer timeout.

If you run into this issue again, increase the Server Timeout setting to 30 seconds and see if that works. If not, increase it even more.

**Comment by margani** [comment]
Thanks a lot. If it happened again I will increase the timeout.

**Comment by tomkerkhove** [comment]
The question is - Did it show that it was not able to get all entities or did it silently continue without displaying anything @margani?

**Comment by margani** [comment]
@tomkerkhove It silently continued. The only log I could see was "MessagingFactory successfully created". I thought all the queues and topics are deleted till saw the azure portal.

**Comment by tomkerkhove** [comment]
That's odd.

@SeanFeldman What do you think - Shall we create an issue for this?

**Comment by margani** [comment]
Hi @paolosalvatori currently I don't have that issue anymore, but will do once I have it again.

**Comment by SeanFeldman** [comment]
@tomkerkhove we already have an issue - this one 🙂 It has all the context.

@paolosalvatori @ErikMogensen is there a way to mimic this behaviour? I'd like to see what the UX is like.
