### ISSUE TITLE
Remove support for Service Bus metrics

### ISSUE THREAD

**Issue by tomkerkhove** [paolosalvatori/ServiceBusExplorer#212]
Since Microsoft has removed support for getting metrics via REST API and is turning this off soon we are removing support for viewing metrics, read more about it [here](https://blogs.msdn.microsoft.com/servicebus/2018/05/11/azure-service-bus-deprecating-entity-metrics-rest-api/).

We are removing the following content:
![image](https://user-images.githubusercontent.com/4345663/39821929-f8a54962-536e-11e8-9f1b-3c06223ad033.png)

**Scope**: All entity types.

_If you are interested in this capability we suggest to use [Azure Monitor](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-metrics-azure-monitor) or the ARM SDK._

**Comment by paolosalvatori** [comment]
Yep, let's remove this part. @tomkerkhove are going to work on this?

**Comment by tomkerkhove** [comment]
Jup, should have time this week

**Comment by Mossharbor** [comment]
Hmm, you are about to have a mutiny on your hands if you force people to move to ARM resource manager and cut support for existing functionality  (that does not have a comparable replacement).  ARM it is just not performant enough.  You are forcing people to move to something other than service bus, and pretty much that means something other than azure.

See thread here,
https://github.com/Azure/azure-service-bus-dotnet/issues/65

**Comment by SeanFeldman** [comment]
@Mossharbor issue https://github.com/Azure/azure-service-bus-dotnet/issues/65 is about namespace management, which the ASB team has agreed to address, and not metrics.

For metrics, *all* Azure services are moving to use the Monitor service, which cannot work with a connection string.

**Comment by Mossharbor** [comment]
@SeanFeldman that is fine, but it seems to me like there is overlap between metrics and namespace management in getting approximate counts of a queue using a connection string, that is falling through the cracks.

This phrase:
_"is turning this off soon we are removing support for viewing metrics_."_...."should have time this week"_

Seems to indicate that getting queue lengths will be a problem very soon as existing functionality to get queue counts with a connection string will not longer be available.

**Comment by SeanFeldman** [comment]
The only overlap is that both, entity management operations and message counts are gone from the new client.

MSFT has comitted to a very specific subset of functionalities in the package they'll created and release soon to replace NamespaceManager. [That list](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419) never included message counts. Message counts will be coming from Monitor service only, which will require AAD authenitcation.

**Comment by tomkerkhove** [comment]
The bottom line is - We need to do this because what we rely on will not be there anymore, it's not that we want to do it but it's because we have to do it...

**Comment by paolosalvatori** [comment]
Hi @Mossharbor we are not going to remove the abiliy to see the length of a queue or things like that from the tool. We are just going to remove support for retrieving and displaying statistic data about incoming messages, outgoing messages, failures, etc. obtained invoking the Service Bus Metrics REST API that is going to be dismissed by the product group. All diagnostics logs and metrics for all Azure Services are now available through Azure Monitor. You can easily configure an Azure Services from the portal or via a PowerShell script to send diagnostic logs and metrics to an Event Hub, storage account or Log Analytics. If you want to send this data to Application Insights, you can create an Azure Function to retrieve metrics from an Event Hub and use a TelemetryClient object to write this data to Application Insights. I recently used this technique with more than a customer and it works like a charm. The ability to create Kusto queries in Application Insights and Log Analytics is very powerful, and you can render time charts. When I created the Service Bus Explorer, this functionality was not available, but now Azure provides a wide range of solutions to retrieve, analyze and render metrics of Azure services. Hope this helps.

**Comment by Mossharbor** [comment]
@SeanFeldman Thanks for sending that list.  I am not sure why you say:

> That list never included message counts

It seems like it is the second item on the list:

> GetRuntimeInformation (Gets all **counts** and last state, Approximate count, accurate within 10s)

Anyway if that list is correct then I don't have an issue as long as there isn't a gap between turning the older REST API's off and the release of the newer library you referenced.

**Comment by tomkerkhove** [comment]
Updated the issue with what we are removing.

**Comment by Mossharbor** [comment]
@paolosalvatori thanks for the clarification and the suggested workaround.

**Comment by tomkerkhove** [comment]
Updated issue with link to official blog post - https://blogs.msdn.microsoft.com/servicebus/2018/05/11/azure-service-bus-deprecating-entity-metrics-rest-api/

**Comment by SeanFeldman** [comment]
@tomkerkhove open a PR and mark as `[WIP]`.

@paolosalvatori we should enable [WIP plugin](https://github.com/apps/wip) on this repo to block merging of anythign that is marked as `wip`/`spike`.

**Comment by tomkerkhove** [comment]
Re-opening given the PR was still a WIP and needs more testing + final fixing.

**Comment by paolosalvatori** [comment]
Hi @tomkerkhove I downloaded the latest version of the code. It looks like you didn't complete the work, right? You removed metrics for queues and topics but not for event hubs or notifications hubs. Are you planning to work on this or should I plan some time to do it? In addition, buttons are not properly aligned when selecting an existing queue or topic.

**Comment by paolosalvatori** [comment]
@tomkerkhove no worries, just checking! :)

**Comment by SeanFeldman** [comment]
2 vConferences and 1 IRL conference talks coming up in June, sorry I'm out... (will do [4.0.110](https://github.com/paolosalvatori/ServiceBusExplorer/projects/1#card-9307507) release if no one gets to it before).

**Comment by ErikMogensen** [comment]
I am unable to connect to a Notification Hubs namespace. I have tried Free and Basic. Does it work for other people? SBE reports the following error:

<11:10:12> Failed to retrieve Notification Hub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. Manage claim is required for this operation..TrackingId:xxxxxx,TimeStamp:6/2/2018 9:10:11 AM ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

I copied the connection string from the Access Policies -> DefaultFullSharedAccesSignature textbox.

**Comment by tomkerkhove** [comment]
This is related to the other issue, not the metrics one
________________________________

**Comment by ErikMogensen** [comment]
@tomkerkhove, yes, this does not with a version of SBE from March either, but it is stopping me from fixing this issue. 

Is the impossibility to connect to Notification Hubs a known issue?

**Comment by ErikMogensen** [comment]
Metrics for all services excepts Notfication hubs were removed in the PR #225. The initial commit and the description for that PR is actually for a different issue. 

What is left is:

- Remove metrics from Notification Hubs
- Test Relay with IsDynamic = true
- Remove some helper classes for Metrics
- Perhaps remove Subscription ID and Certificate thumbprint from the Options dialog
- The rebasing of the commits Sean wrote about
