### ISSUE TITLE
Support for all four of queues suspension states

### ISSUE THREAD

**Issue by kawazoe** [paolosalvatori/ServiceBusExplorer#222]
While the Azure Portal only supports the Active and Disabled state on queues, the NamespaceManager actually supports two additional states: SendDisabled and ReceiveDisabled. These two states can be incredibly useful and do not appear to be supported by the current version of ServiceBusExplorer.

I propose to tweak the current "Enable/Disable" contextual menu options, as well a all of their various counterparts to replace them with a "State" menu with all four options as a sub-menu. This isn't the best UX proposition ever, as it makes it harder/less-obvious to disable or enable a queue.

I could probably find sometime to write a PR for this in the coming week if this seems like a good implementation to you.

**Comment by SeanFeldman** [comment]
Technically, there are [more states](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus?view=azure-dotnet). Perhaps UI wise we could reflect a state w/o tweaking the context menu. Are SendDisabled and ReceiveDisabled settable?

**Comment by kawazoe** [comment]
According to the docs, it’s seems like it, but only for queues; not for topics or subscriptions.

What do you have in mind?

**Comment by SeanFeldman** [comment]
Thinking there should be a status bar, so when navigating from entity to entity, the status would be reflected there.

> According to the docs

Could you link to the docs so that others can follow the same path as you? Thanks.

**Comment by SeanFeldman** [comment]
Found it: https://docs.microsoft.com/en-us/azure/service-bus-messaging/entity-suspend
EntityStatus: https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus

**Comment by kawazoe** [comment]
You were faster than me on this one! Yes, those are the pages I was referring too.

> the status would be reflected there.

But what about changing it to those extended disabled states? That's the main goal of my proposition.

**Comment by SeanFeldman** [comment]
I have never had a need in `SendDisabled` or `ReceiveDisabled` queue statuses.
Could you elaborate on the scenarios you'd use those?

**Comment by kawazoe** [comment]
I currently have a long running process built on an Azure Functions App. Basically, this function runs a paged query on a large database, then process the data, then move on to the next page. This function is triggered by a message in a service bus queue telling it to process the first page. Once the function finishes a page, it will post a message in the same queue triggering the next page, and so on and so on. This pattern mimics a recursive call but via a queue.

It enables two interesting scenarios. First, Azure Functions have a run-time limit of a few minutes. This process can take hours on large data-sets but since the function only run for the duration of a single page, an instance of the function never runs for more than a few seconds at a time. The second advantage of this pattern, and this is where those states becomes useful, is that you can pause it at any time by setting the queue to the ReceiveDisabled state. That way, the function can still request the next page for processing, but processing will never start since the queue will never send the message to listeners.

Alternatively, the SendDisabled state can be used to safely shut-down a queue. For instance, if you need to rename a queue or enable partitioning. In that case, you have to empty the queue before deleting it. This is very easy when you can just set the queue to SendDisabled. That way, you cannot send new messages to the queue which lets you safely process the remaining messages before switching to the new queue/topic.

I'm sure there are other reasons where those states might be useful, but those are just the two first ones that came to my mind.

**Comment by SeanFeldman** [comment]
Wouldn't changing a state of a queue cause a runtime exception? I guess for Azure Functions you don't really care as your code is not going to be affected, but you'll still be charged something for the trigger that will continuously kick off trying to dequeue a message.

I'll let other maintainers chime in. Personally, I could see something like this:
![image](https://user-images.githubusercontent.com/1309622/40630882-e3cac1f0-6293-11e8-918f-95eff0cc0789.png) lightening up when it's a Queue and disappearnig when it's anything else.

**Comment by paolosalvatori** [comment]
@SeanFeldman @kawazoe I agree to add the possibility to provide the ability to set the state of a queue to ReceiveDisabled or SendDisabled, but I don't like the dropdown list at the bottom of the main form. It's inconsistent with the look and feel of the tool and placing a control that applies only to queues to the bottom of the main form is conceptually wrong. Let's rather extend the context menu with two additional items, or let's open up a dialog where you can select a state from a dropdownlist. Let me know if you agree with this plan.

**Comment by SeanFeldman** [comment]
No strong feelings about it. Saying that, can you add a mock? You mind find
things not as you think of them when see those 🙂

**Comment by paolosalvatori** [comment]
@SeanFeldman do I really need to add a mock of a couple of additional context menu items below the existing one? :)

**Comment by SeanFeldman** [comment]
Free to do anything, right? 😉

**Comment by ahofman** [comment]
I have an interest in this - happy to raise a PR if I can find the time :) 

Just to make sure I understand @paolosalvatori correctly, is something like this OK? 
![image](https://user-images.githubusercontent.com/1689712/51507735-61de1880-1e46-11e9-9b66-0bd1b79afb39.png)

Also, do we want to do something about this button, or leave as is (i.e., only able to Enable and Disable):
![image](https://user-images.githubusercontent.com/1689712/51507766-81754100-1e46-11e9-8a51-bd1b6562b89a.png)

**Comment by paolosalvatori** [comment]
@ahofman the items in submenu are perfect. We should probably change the label of the Enable \ Disable button to Status and its semantics: clicking the button should open a dialog where you can select one of the possible states from a drop-down list
