### ISSUE TITLE
Scrollbars are missing

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#224]
The three scrollbars are missing from the main window. This has happened in one of the later commits.

**Comment by ErikMogensen** [comment]
It seems that some of the changes to MainForm.Designer.cs that were part of the commit 178351124af10ad3f973c0d3f0c3e04d23c79f08 in PR #216 caused this. @tomkerkhove, do you see a problem if I undo some of the changes to the window sizes and paddings in MainForm.Designer.cs?

**Comment by tomkerkhove** [comment]
Nope
________________________________

**Comment by ErikMogensen** [comment]
I tested this on three different setups. The scrollbars were missing when running on two laptops, but when connected to a high DPI display the scroll bars showed up.
