### ISSUE TITLE
Remove message from DLQ error Exception

### ISSUE THREAD

**Issue by middlewaysas** [paolosalvatori/ServiceBusExplorer#227]
Hi,
When trying to repair/resubmit a message from the DLQ with the option "Remove message from DLQ", the message is resubmitted but it is not removed from the DLQ. In the console log, I have this error : __Exception: Rows cannot be programmatically removed unless the DataGridView is data-bound to an IBindingList that supports change notification and allows deletion.__

Thanks.

**Comment by ErikMogensen** [comment]
Lately there has been done changes to that part. Where did you get the executable from? I also want to know if this is repeatable or it just on this queue? If you restart ServiceBus Explorer does the error show again?

**Comment by middlewaysas** [comment]
Hi,
It is repeatable and we have the same issue for all queues, even after a restart.
We got the executable from here.

**Comment by ErikMogensen** [comment]
I tested this on the executable I just downloaded from https://github.com/paolosalvatori/ServiceBusExplorer/releases/download/4.0.109/ServiceBusExplorer-4.0.109.zip and I am unable to reproduce this issue. Please download the executable using the above link again and let me know the outcome.

**Comment by middlewaysas** [comment]
Hi,
We are using the same version / executable.
We are using ServiceBus Premium, maybe this is the root cause?

**Comment by ErikMogensen** [comment]
I don't think so but I'll test that. Please test with a Standard namespace on your end. 

It looks like SBE does not understand that it is an DLQ you are working with and instead believes that it is the normal queue.

**Comment by ErikMogensen** [comment]
I have tested on Premium and there were no issues. Please let me know how it worked on a Standard namespace for you.

If that also failed, please list the steps you are doing to reproduce the issue. Also specify the properties of the queue or topic/subscription you are using.

**Comment by middlewaysas** [comment]
The issue is not there when there is only one message in the queue.
To reproduce the issue it is very simple: I open the Dead Lettered messages, then I select a message and click on resubmit and check the "Delete the message in DLQ". Then the message is well resubmitted but a quick seconds after I have the error in the console (but the message is deleted from the DQL, it sounds like it is only a display issue).

**Comment by ErikMogensen** [comment]
I was able to repro this on a partioned queue on Standard. Edition, but I have some questions:

1. The Service Bus service was changed some months ago to not report queues as partitioned on Premium anymore. Are you sure this is a Premium namespace? 
2. Is this for a queue or a subscription?
3. When looking at the Description tab for the queue, is the checkbox for 'Enable partition' checked?

**Comment by SeanFeldman** [comment]
ReceiveBatch is there, but it is not promised to give the batch. It will always stream messages, whatever it can provide.

**Comment by ErikMogensen** [comment]
Thanks Sean. Do you see a problem using ReceiveBatch with partitioned queues when calling it until it returns zero messages? If not way performance could be enhanced and there would be a possibility to lessen the code to maintain.

**Comment by SeanFeldman** [comment]
It is a recommended way. The server streams messages, so that's probably how we should tackle it.

**Comment by paolosalvatori** [comment]
Let's keep the code as is for background compatibility. We'll change it in the future if and when in the future the behavior will change for all existing namespaces.

**Comment by middlewaysas** [comment]
@ErikMogensen: you are right, it was not on Premium but on Standard.
This was for a queue and Enable Partitionning for this queue is set to true.
