### ISSUE TITLE
Cannot define CorrelationFilter

### ISSUE THREAD

**Issue by brkzkn** [paolosalvatori/ServiceBusExplorer#234]
I cannot define correlationFilter like; https://imgur.com/a/qz2aI

The reason of problem is that ruleWrapper.RuleDescription is alwalys null. 

ShowRule function which is written in MainForm.cs line 5146, called with NULL RuleDescription value.

As a result, HandleRuleControl.InitializeData function cannot detect correlationFilter.

**Comment by ErikMogensen** [comment]
Hi, 

Which version of ServiceBus Explorer are you using? There was a version released last week. Do notice that there is a bug in that it may just return the latest version number released instead of the actual version number.

**Comment by brkzkn** [comment]
Hi Erik,

I'm working with version 4.0.110

**Comment by SeanFeldman** [comment]
If memory doesn't fail me, the tool was never designed to support
Correlation filters. I added an option to output it so that at least it can
be inspected.

**Comment by briandunnington** [comment]
Support added in #244

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/1ed7a509232f0867c97b511e2ce08dd67c64a4d2
