### ISSUE TITLE
401 Unauthorized when attempting to Get Registrations

### ISSUE THREAD

**Issue by darrellbooker** [paolosalvatori/ServiceBusExplorer#240]
I'm getting the following error when attempting a "Get Registrations" on my notification hub. 

<12:22:02> Exception: The remote server returned an error: (401) Unauthorized..TrackingId:c454cb35-346e-4179-8034-c0807ca2226f,TimeStamp:7/20/2018 7:22:02 PM
<12:22:02> InnerException: The remote server returned an error: (401) Unauthorized.

 I'm connecting using a policy connection string that has full permissions.  I seem to be able to navigate all other areas except the Registrations

**Comment by thesourav123** [comment]
@darrellbooker  I am getting the same error while passing the connection string
<09:27:34> InnerException: The remote server returned an error: (401) Unauthorized. claim is empty. TrackingId:bd87fb6c-ff78-4dc5-a32c-92f2210e0d4c_G23, SystemTracker:xxxxxxxx.servicebus.windows.net:$Resources/Relays, Timestamp:8/21/2018 1:27:34 PM

Did you find a solution

**Comment by paolosalvatori** [comment]
Hi @thesourav123 I didn't invest time in recent years to check, update and modernize support for notification hubs. I'll do my best to investigate the problem. Does this issue happen with any connection string to any notification hub namespace?

**Comment by thesourav123** [comment]
@paolosalvatori , i am checking it with the Queues. I have opened up a new issue in the tracker.
 #https://github.com/paolosalvatori/ServiceBusExplorer/issues/246

**Comment by paolosalvatori** [comment]
Eventually, if you trust me, please share the connection string with me offline. You can change regenerate keys later on.

**Comment by JACoetzee** [comment]
Hi @paolosalvatori I am getting the same error with the latest app. Any resolution on this?
~Thanks

**Comment by ErikMogensen** [comment]
Closing this since the related #246 is closed. Also this issue is more than a year old since last update.

**Comment by jpalo** [comment]
Too bad there isn't a way to get NH registrations with this tool as the issue persists also in latest version 5.0.4.
```
<13:40:22> Exception: The remote server returned an error: (401) Unauthorized..TrackingId:96a0e653-2912-4b92-b730-d4b9433c611c,TimeStamp:5.1.2022 11.40.22
<13:40:22> InnerException: The remote server returned an error: (401) Unauthorized.
```

**Comment by ruimlourenco** [comment]
Also unable to retrieve registrations:
<23:47:36> Exception: The remote server returned an error: (401) Unauthorized..TrackingId:15d6ab41-68c5-4978-857c-53a3b7a98aee,TimeStamp:2022-05-03 3:47:36 AM
<23:47:36> InnerException: The remote server returned an error: (401) Unauthorized.

I followed comment #194 and made sure I was using a token for the Namespace with 'Manage' permission.

Does anyone know what else needs to happen for this to work?
