### ISSUE TITLE
MessageBodyType as default in the options 

### ISSUE THREAD

**Issue by NoNod** [paolosalvatori/ServiceBusExplorer#242]
Hi!

We use the ServiceBusExplorer and I have loaded the latest version.
Here I have adapted that as a MessageBodyTyp "String" is enabled by default.
Because we only use „String“.
Is it possible to include a default MessageBodyType in the options for your next changes?

**Comment by SeanFeldman** [comment]
@NoNod not sure I follow you. Could you please elaborate in a bit more details? Thank you.

**Comment by NoNod** [comment]
Hi!

 

Stream is selected by default. ( cboBodyType.SelectedIndex = 0; )
I want, that String is selected by default. ( cboBodyType.SelectedIndex = 1; )



My idea:
Define the default value in the options.

( cboBodyType.SelectedIndex = ServiceBusHelper.MessageBodyTypeSelectedIndex; )

 

Here in private void GetServiceBusNamespaceSettingsFromConfiguration()



Set the value from config:



            parameter = ConfigurationManager.AppSettings[ConfigurationParameters.MessageBodyTypeSelectedIndex];

            if (!string.IsNullOrWhiteSpace(parameter))

            {

                int messageBodyTypeSelectedIndex;

                if (int.TryParse(parameter, out messageBodyTypeSelectedIndex))

                {

                    ServiceBusHelper.MessageBodyTypeSelectedIndex = messageBodyTypeSelectedIndex;

                }

            }



The ConfigurationParameters.MessageBodyTypeSelectedIndex bring in the Options-Dialog.

Have a funny day!

Grettings
Ralf

 

 

Von: Sean Feldman <notifications@github.com> 
Gesendet: Dienstag, 31. Juli 2018 04:33
An: paolosalvatori/ServiceBusExplorer <ServiceBusExplorer@noreply.github.com>
Cc: Ralf Gedrat <cooperatio@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [paolosalvatori/ServiceBusExplorer] MessageBodyType as default in the options (#242)

 

@NoNod <https://github.com/NoNod>  not sure I follow you. Could you please elaborate in a bit more details? Thank you.

**Comment by SeanFeldman** [comment]
Ok, now I see what you're after. Perhaps the issue should be titled something among the lines of "Allow default MessageBodyType to be user configured" rather than "MessageBodyType as default in the options"? 🙂

I see no problem with this. Feel free to send a PR if you'd like to speed it up.

**Comment by briandunnington** [comment]
Looks like this was added/fixed in #243

**Comment by ErikMogensen** [comment]
Closed since it was fixed in #243 as mentioned.
