### ISSUE TITLE
DataContract Serialized Stream-Bodied Messages Sent in Repair and Submit Are Corrupted

### ISSUE THREAD

**Issue by c-lombardi** [paolosalvatori/ServiceBusExplorer#245]
When re-queuing Dead-Letter-Queued messages with a Stream body that have a custom content type that was serialized by a Data-Contract-Serializer, the stream sent in the new message can no longer be read by the application that originally Data-Contract-Serialized the message.

Attempting to re-queue the same messages with ByteArray and String content types are also unsuccessfully able to be de-serialized by the application.

It appears that the message body is corrupted when the body was a custom content type and serialized with the DataContractSerializer.

**Comment by c-lombardi** [comment]
I think that you might just need to instantiate the new BrokeredMessage with the body of the old message as a stream: deadLetteredMessage.GetBody<Stream>()

**Comment by paolosalvatori** [comment]
Hi @c-lombardi the Clone overloaded method in the BrokeredMessageExtensions class should do exactly what you are looking for. This is the first time that I receive this feedback. Could you please debug the application and see if the proper method overload is used when choosing Stream as format for the message to resubmit?

```csharp
public static BrokeredMessage Clone(this BrokeredMessage message, Stream stream)
        {
            if (stream == null)
            {
                return null;
            }
            if (stream.CanSeek)
            {
                stream.Seek(0, SeekOrigin.Begin);
            }
            var clone = message.Clone();
            BodyStreamPropertyInfo.SetValue(clone, stream);
            return clone;
        }
```

**Comment by c-lombardi** [comment]
I see what you are saying now and that seems to have resolved the problem for me in my local build!

**Comment by SeanFeldman** [comment]
> seems to have resolved the problem for me in my local build!

Just making sure you're always using the latest release that can be obtained [here](https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest).
