### ISSUE TITLE
Azure Service Bus Queue Connection Not Working

### ISSUE THREAD

**Issue by thesourav123** [paolosalvatori/ServiceBusExplorer#246]
Hi @paolosalvatori ,
 I am trying to connect to my Azure Service Bus Queue and view the messages i send.
 So, i clicked on Connect Button, Enter SASConnection String Menu(Attached the picture), filled all the details and i see my connection details on the top left, but i don't see my queue. 
The following messages are appearing on the log
```
<11:06:28> The application is now connected to the sb://namespace.servicebus.windows.net/ service bus namespace.
<11:06:28> MessagingFactory successfully created
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 1 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 2 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 3 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 4 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 5 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 6 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 7 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 8 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 9 of 10.
<11:06:33> Exception: One or more errors occurred.. Method <GetRelays>b__34: retry 10 of 10.
<11:06:33> Exception: One or more errors occurred.
<11:06:33> InnerException: The remote server returned an error: (401) Unauthorized. claim is empty. TrackingId:85583882-e2ee-42c5-af32-a5c83d1d1502_G16, SystemTracker:NAMESPACE.windows.net:$Resources/Relays, Timestamp:8/22/2018 3:06:33 PM
```

![image](https://user-images.githubusercontent.com/16967244/44478952-29bf7900-a60d-11e8-8d0c-8bdc65e9bdf3.png)

**Comment by SeanFeldman** [comment]
Could you try connecting from a different location? Looks like connectivity
issue. Alternatively, try HTTPS rather than TCP.

**Comment by paolosalvatori** [comment]
I also see that the method failing is GetRelays… which version of the tool are you using? Does the namespace contain only queues and topics?

**Comment by thesourav123** [comment]
@paolosalvatori You are correct. I only have 1 queue in my Azure Service Bus Namespace which i am trying to connect to. I don't know why it is calling Relays

**Comment by paolosalvatori** [comment]
That should not be a problem, can you please try to use the latest version of the tool? Thanks!

**Comment by thesourav123** [comment]
Its working with the latest version. thanks.
