### ISSUE TITLE
"Unable to read the message body." intermittently

### ISSUE THREAD

**Issue by davidwmartines** [paolosalvatori/ServiceBusExplorer#248]
version 4.0.110

I am using the Event Hub Listener to view events in an Event Hub.  When the events are initially consumed, I can usually click the row in the Events List grid, and the event text and custom properties are shown correctly.  However, clicking off this row and back, it gives the message "Unable to read the message body", plus the custom properties are missing.   Also, this message is sometimes shown even the first time the event is viewed.   I can restart the listener, and the events show correctly again, but this error comes back frequently.  Could it be because I am using JSON as the event body (not XML)?

**Comment by japicket** [comment]
I am seeing this issue as well. Is there a fix or work-around for it?

**Comment by paolosalvatori** [comment]
This is strange. The original code used to create a clone of the EventData because this way I could read the message any time a user selects it. If you directly read the message from the EventData object, you can't read it a second time. I should debug and check. @ErikMogensen?

**Comment by ErikMogensen** [comment]
@davidwmartines , is this issue still occuring?

**Comment by ErikMogensen** [comment]
It may be due to timeouts. There is one timeout that by default is set to 1 second. @japicket and @davidwmartines please increase the Service Bus Explorer timeout settings and report back here whether that solves the this issue or not
