### ISSUE TITLE
Support DateTime as filter

### ISSUE THREAD

**Issue by lonevvolf** [paolosalvatori/ServiceBusExplorer#249]
It would be extremely useful to support DateTime objects in the filters expression when viewing messages.  We would like to view, for instance, message with EnqueuedTimeUtc between dates A and B.

**Comment by SeanFeldman** [comment]
@lonevvolf sounds like a good idea. Would you want to take a stab at it?

**Comment by lonevvolf** [comment]
I will see if we can allocate some time to it in our project.
