### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by bgoerdt** [paolosalvatori/ServiceBusExplorer#25]
Is it possible to configure a proxy to connect through? I cannot use this software without this option.

**Comment by paolosalvatori** [comment]
Customers have always configured the proxy outside of the tool. I'm not aware of any mechanism to define a proxy in SB. What do you mean exactly?

**Comment by ErikMogensen** [comment]
bgoerdt, you may configure a proxy in the Service Bus Explorer config file using the standard .NET way described at https://msdn.microsoft.com/en-us/library/dkwyc043(v=vs.110).aspx

You probably need to set ServiceBusEnvironment.SystemConnectivity.Mode = ConnectivityMode.AutoDetect; too.

**Comment by paolosalvatori** [comment]
Thanks Erik!

**Comment by SeanFeldman** [comment]
@paolosalvatori can this be closed?

**Comment by paolosalvatori** [comment]
Yep :)

**Comment by roastedmonk** [comment]
can you show where to put ? its not working

**Comment by ErikMogensen** [comment]
@roastedmonk ,

When using SBE to connect to SB through a proxy the following four requirements must be met:

- The SBE config file must be properly configured for the proxy used. This is described at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration. SBE needs to be restarted after a config file change. If you do this change within Visual Studio on the app.config file, verify that the servicebusexplorer.exe.config in the output folder contains this change.

- Connectivity Mode must be AutoDetect, Http or Https. This is set when connecting to a namespace. Test all three modes.
 
- SBE must be using a version of the SB Client that does not have the Http/Https bug. So either use a really old version of SBE or the latest.
 
- The proxy must allow traffic to SB and properly handle it.

Let us know if it works for you. 

I'll create an issue for setting the proxy within ServiceBusExplorer.

**Comment by ErikMogensen** [comment]
Regarding how to change the application configuration file you may do it like below. Change http://proxy.organization:1234 to the url to your proxy.

```
</startup>
  <system.net>
    <defaultProxy useDefaultCredentials="true">
      <proxy proxyaddress="http://proxy.organization:1234" bypassonlocal="True"/>
    </defaultProxy>
  </system.net>
```

  <system.serviceModel>
