### ISSUE TITLE
Ability to save connection details/multiple connection profiles

### ISSUE THREAD

**Issue by MattTrinder1** [paolosalvatori/ServiceBusExplorer#250]
Exactly as the title - save connection details to prevent having to re-enter them each time.  In addition, the ability to save multiple sets of connection details to allow connections for different customers/environments etc.

**Comment by SeanFeldman** [comment]
@MattTrinder1 this is already possible.

![image](https://user-images.githubusercontent.com/1309622/45161638-8d1ede80-b1a9-11e8-938b-96a22249db32.png)
![image](https://user-images.githubusercontent.com/1309622/45161666-9f991800-b1a9-11e8-8b21-902ad77e83ba.png)

Please ensure you use the latest version (https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest).

**Comment by apjanke** [comment]
How do you actually Save the connection? I'm using a recent version, 4.1.113, and I can't figure out how to save my connections. I don't see any Save button or menu option.

**Comment by ErikMogensen** [comment]
Select "Enter connection string" from the drop down. Then you can enter it. Finally press Save. 
![image](https://user-images.githubusercontent.com/9644248/54335865-942c1b00-462a-11e9-935b-82e3c21051c3.png)

You may also edit the configuration files directly.

**Comment by apjanke** [comment]
Ah, there it is. I was using "Select a service bus namespace..." or the other connection creation options, and the "Save" button doesn't appear for them. When I switch it to "Enter connection string...", the Save button appears.

Thanks!
