### ISSUE TITLE
The entry '*' has already been added. ServiceBusExplorer.exe.config

### ISSUE THREAD

**Issue by jeremy001181** [paolosalvatori/ServiceBusExplorer#254]
For some reason I wasn't able to access to any Azure service bus via connection string, and it was complaining 

![image](https://user-images.githubusercontent.com/2342277/45619162-313d3b00-ba70-11e8-9f5b-106c50e2065d.png)

Then I figured out that it is my host app config has already have this entry added due to whatever reason, so what I have done to work around it is to add `clear` before the `add` like below

![image](https://user-images.githubusercontent.com/2342277/45619262-8a0cd380-ba70-11e8-9b25-ee4e5194eaca.png)

I think it would be good to have it in app.config by default to avoid any conflict, I can create a pull request if you think it is okay?
[commit](https://github.com/jeremy001181/ServiceBusExplorer/commit/c1d959c7a49a49f98f46b128d8b6ccac0b93d0d5)

**Comment by SeanFeldman** [comment]
I'd rather see this achieved via code and not configuration.
[`ServicePointManager.DefaultConnectionLimit`](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit) can be used to have more than 2 HTTP connections.

**Comment by jeremy001181** [comment]
Good idea, since it has less configure to manage, here is the [change](https://github.com/jeremy001181/ServiceBusExplorer/commit/d777d86b6e4dc49e1bdb59aac5809b4c2b0933b0)
