### ISSUE TITLE
Update the repositories reference

### ISSUE THREAD

**Issue by candidodmv** [paolosalvatori/ServiceBusExplorer#26]
I found this tool on this link http://blogs.msdn.com/b/paolos/archive/2015/03/02/service-bus-explorer-2-6-now-available.aspx, but only this current link reference is working. Where I can to find the executable/installer ? Thanks.

**Comment by SeanFeldman** [comment]
There's no such ATM. You'll have to D/L the project, compile and grab the artifacts.
Should we look into something like https://github.com/Squirrel/Squirrel.Windows for a quick setup?

**Comment by SeanFeldman** [comment]
PS: squirrel will still require to open the project, but can generate an install in a fast way
/cc @paolosalvatori

**Comment by paolosalvatori** [comment]
Hi guys
I know I should use some tools to create an exe whenever a new version of the tool is available, but I'm really busy and I can't spend time on this. Sorry about that. :(
Ciao
Paolo

**Comment by LiamFeldman** [comment]
@paolosalvatori I can add squirrel to the solution. While it's not the most convenient way to generate an installer, it is a way to get it with the solution and doesn't require CI/build server. Would that work?

**Comment by paolosalvatori** [comment]
Hi Liam
yes please, it looks like a lightweight solution to generate an installer. Please, go ahead and keep me informed! Thanks!
Ciao
Paolo

**Comment by SeanFeldman** [comment]
@LiamFeldman was me on my sons account :blush: 
I'll look into that.

**Comment by paolosalvatori** [comment]
Ah ah ah Thanks!

**Comment by SeanFeldman** [comment]
@paolosalvatori shouldn't this stay opened until done? :) or you'll be opening a new issue?
