### ISSUE TITLE
Remove support for ACS

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#262]
Since ACS will stop working the 7th of November, we might as well remove it from SBE now. That way users get an early warning if they try to use SBE with ACS. As long as you have access to the Azure Portal it is easy to switch to SAS.

**Comment by paolosalvatori** [comment]
Let's do it after the 7th of November. I don't want users to start blaming SBE to be the culprit of the ACS disposal :)

**Comment by ErikMogensen** [comment]
I saw that there was an option to extend the use of ACS. I don't remember for how long, but that means we should keep the support for it for a while longer.

**Comment by SeanFeldman** [comment]
Are you sure? It has a few days left 🙂

https://blogs.msdn.microsoft.com/servicebus/2017/06/01/upcoming-changes-to-acs-enabled-namespaces/

**Comment by ErikMogensen** [comment]
Yes, you may request to extend the use of ACS to the 4th of February next year.

**Comment by SeanFeldman** [comment]
3 months extension (as of today). 🔥

**Comment by ErikMogensen** [comment]
When removing ACS support it is good to keep in mind that we want to add support for RBAC authentication, https://github.com/paolosalvatori/ServiceBusExplorer/projects/1#card-9365420.

**Comment by ErikMogensen** [comment]
Looking at https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/src/Common/Helpers/ServiceBusNamespace.cs, besides SharedSecretIssuer/SharedSecretValue there is support for IssuerName/IssuerSecret. I don't know what IssuerName/IssuerSecret but I assume it is not supported anymore since there is only support for SharedAccessKeyName/SharedAccessKey in the Track1 and Track2 SDKs (the connection string parsing code is located in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusConnectionStringBuilder.cs and https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/ConnectionStringParser.cs respectively).

I'll therefore remove support for IssuerName/IssuerSecret unless someone objects. 

I'll leave the Windows authentication code for now since that is another issue, #119.

**Comment by ErikMogensen** [comment]
The other Azure Messaging clients also only seem to support SharedAccessKeyName/SharedAccessKey. Below I listed the respective SDKs and the file comprising the connection string parsing. I may have missed something, please correct me in that case.

- Relay Track1 SDK (does not seem to have a Track 2 SDK) https://github.com/Azure/azure-relay-dotnet/blob/dev/src/Microsoft.Azure.Relay/RelayConnectionStringBuilder.cs 

- Event hubs Track 1 SDK, https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/src/Primitives/EventHubsConnectionStringBuilder.cs
- Event hubs Track 2 SDK, https://github.com/Azure/azure-sdk-for-net/blob/97b9ebe1ca1c79c2703260996501b045569f63e5/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ConnectionStringParser.cs
- Notification hubs - seems to only have one SDK for .NET Standard. The file doing the parsing is https://github.com/Azure/azure-notificationhubs-dotnet/blob/master/src/Microsoft.Azure.NotificationHubs/NotificationHubConnectionStringBuilder.cs
