### ISSUE TITLE
Able to run VS Code Analysis without any warnings

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#263]
I think that you should be able to run the VS Code Analysis with default rules on the solution without any warnings. To handle that we probably have to suppress some warnings. In that case, should we create a separate file or put the suppressions in the code? I think it is best to put it in the code.

**Comment by SeanFeldman** [comment]
If it's in the code, we can inspect it. If it's hidden, we'll forget about. Rather see it in code.

**Comment by paolosalvatori** [comment]
I'd prefer to suppress warnings in the code, rather than in a separate file.
