### ISSUE TITLE
Incorrect casing in choco's sample install & upgrade lines

### ISSUE THREAD

**Issue by rabrahamOpti** [paolosalvatori/ServiceBusExplorer#264]
[The ServiceBusExplorer page on chocolatey's site](https://chocolatey.org/packages/ServiceBusExplorer/) has incorrect casing on its example install and upgrade lines. See here:

![image](https://user-images.githubusercontent.com/28309959/46476107-58f10a80-c7b5-11e8-9781-078d28b70fe2.png)

**Comment by tomkerkhove** [comment]
Before we log an issue, can you verify that this is not a setting in the portal @paolosalvatori/@SeanFeldman?

**Comment by Nate-Wilkins** [comment]
Worked on this a while ago but `servicebusexplorer` is in the `.nuspec` file. Guessing chocolatey might not be respecting these ids? I did find these when searching for whether this was case sensitive or not. (pretty sure it's not)

States that when installing a specific version of a package the id becomes case sensitive. https://github.com/chocolatey/choco/issues/1240

And it looks like this used to be a bug a few years ago where a few packages where case sensitive: https://chocolatey.org/docs/release-notes#march-3-2015-1

**Comment by CollinChaffin** [comment]
FYI this is a bigger issue than it is being treated as EVERY single locally-hosted package I have now fails with Choco beta 0.10.12 claiming the package is not found (erroneously) due to improperly matching case when version is not specified.

**Comment by CollinChaffin** [comment]
I have opened issue #1656 over at Chocolatey because I am seeing catastrophic failures across the board for both installs as well as upgrades due to this sudden case sensitivity of package IDs/filesnames/paths:

https://github.com/chocolatey/choco/issues/1656

**Comment by ferventcoder** [comment]
@CollinChaffin "beta" signifies not stable - so not catastrophic. Just go back to the 0.10.11 stable release while we investigate the issue.

**Comment by ferventcoder** [comment]
As for the rest of this issue - we agree that case sensitivity should definitely not be an issue - we'll investigate fixing that with the next release (there may already be an issue logged on it).

**Comment by ErikMogensen** [comment]
@rabrahamOpti , is this working properly now?

**Comment by rabrahamOpti** [comment]
I already have the package installed, but it looks like case sensitivity is no longer an issue:

```
$ choco install servicebusexplorer
Chocolatey v0.10.8
Installing the following packages:
servicebusexplorer
By installing you accept licenses for the packages.
servicebusexplorer v4.0.110 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - servicebusexplorer - servicebusexplorer v4.0.110 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```

**Comment by tomkerkhove** [comment]
Let's close it then, thanks for letting us know!

**Comment by ErikMogensen** [comment]
Thanks for verifying, @rabrahamOpti !
