### ISSUE TITLE
Paired Namespaces - Refresh Queues

### ISSUE THREAD

**Issue by togglebrain** [paolosalvatori/ServiceBusExplorer#266]
Add **Refresh All** option for all queues created in the secondary namespace under x-servicebus-transfer

**Comment by SeanFeldman** [comment]
@togglebrain Paired Namespaces is a deprecated feature. As such, I'd suggest not add this functionality to the tool.

**Comment by togglebrain** [comment]
@SeanFeldman Thanks, just checked this is not available in the library for .net standard. Wish there was an announcement under https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-paired-namespaces too.
