### ISSUE TITLE
Change behavior and text for some of the OptionsForm buttons

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#270]
To persist the changes you make in the Options dialog you have to click the Save button. That is not like how it works in other programs and it is probably confusing since settings won't be kept between sessions if you don't click Save.

The OK button should save the settings to disk and then do the same things as before.

Instead the Save button should moved up to the right corner to be besides the new Open button. That way you can see your changes in the file(s) if you click Save and then Open.

**Comment by paolosalvatori** [comment]
Hi @ErikMogensen I'm good with that, this should be an easy one, let's do it at the next round of changes :)

**Comment by ErikMogensen** [comment]
Looking further into this - I suggest:

- Renaming the Save button to Apply 
- Contrary to what I wrote previously, let the Apply stay at the bottom of the dialog
- Switch places between the Apply and the Default buttons
