### ISSUE TITLE
Cannot create Subscription rule when DPI > 100%

### ISSUE THREAD

**Issue by baltuonis** [paolosalvatori/ServiceBusExplorer#271]
This was not fixed. Windows 7 DPI scaling 125% or 135% does not show action buttons. But shows on 100%

![image](https://user-images.githubusercontent.com/188666/47567289-83da0480-d904-11e8-9e77-d81b9122b217.png)

**Comment by paolosalvatori** [comment]
Hi @baltuonis I don't have the possibility to install and test SBE on Window 7, sorry about that :(

**Comment by kyle46** [comment]
I was able to reproduce this on Windows 7 at 125% and 135%. On Windows 7 125% is the default where as Windows 10 100% is the default.

I'll provide screenshots on Monday. I don't have access to my Windows 7 machine until I get to work.

**Comment by ErikMogensen** [comment]
Closing this as it has been verified on Windows 10.
