### ISSUE TITLE
Retention period + partitions in SBE and portal don't match

### ISSUE THREAD

**Issue by arerlend** [paolosalvatori/ServiceBusExplorer#275]
Portal shows 1 day retention, SBE shows 16.  EH REST API correctly responds with message retention period of 1 day.

Entity retrieval is hanging, I'll post a picture in a moment.

SBE version 4.0.110
Windows 10

**Comment by arerlend** [comment]
![incorrect_retention](https://user-images.githubusercontent.com/30675661/47870731-7b337380-ddc7-11e8-89fb-4c6f8d73689f.PNG)

**Comment by arerlend** [comment]
Just tested minimum partition count (2) and that displays incorrectly as well.

![image](https://user-images.githubusercontent.com/30675661/47870960-fb59d900-ddc7-11e8-8b6f-f8cae7746ad9.png)

versus

![image](https://user-images.githubusercontent.com/30675661/47870977-06ad0480-ddc8-11e8-86ac-12c551c95233.png)

**Comment by SeanFeldman** [comment]
Thank you @arerlend for reporting this.
What ASB tier your namespace is using?

Regarding

> Entity retrieval is hanging, I'll post a picture in a moment.

Could you please open a separate issue? Thanks.

**Comment by arerlend** [comment]
I was using some pre-release bits so I spun up new namespaces w/ prod bits just to make sure there wasn't an effect.

Standard tier, Kafka-enabled namespace - entity w/ 1 day retention, 1 partition:
![image](https://user-images.githubusercontent.com/30675661/47873159-b0db5b00-ddcd-11e8-9378-473ff987ed9c.png)
and
![image](https://user-images.githubusercontent.com/30675661/47873186-bdf84a00-ddcd-11e8-994d-a7cbaef625c5.png)
(entities with single partitions are new)

Standard tier, non-Kafka-enabled namespace - entity w/ 1 day retention, 2 partitions:
![image](https://user-images.githubusercontent.com/30675661/47873339-33641a80-ddce-11e8-8d58-6d6294ebea4f.png)
and
![image](https://user-images.githubusercontent.com/30675661/47873380-4d9df880-ddce-11e8-81b0-edc5ff4acb4e.png)

I'll wait a bit to open the issue for entity retrieval since it may be something else.

**Comment by paolosalvatori** [comment]
@arerlend don't you have the ability to debug the problem in VS and eventually submit a PR? Thanks! I don't see this issue under my EH namespaces. If you can't work at a PR, could you please send me the connection string? You can find my email account in the About dialog. Thanks

**Comment by arerlend** [comment]
Sorry I fell behind on this.  I don't have much time to spare so I'll generate a namespace and send you over a connection string by EOD @paolosalvatori

**Comment by ErikMogensen** [comment]
Closing this since it is more than a year since last update. If this is still an issue, please reopen it.
