### ISSUE TITLE
Unable to install SBE with Chocolatey

### ISSUE THREAD

**Issue by jrmcdona** [paolosalvatori/ServiceBusExplorer#276]
```
C:\WINDOWS\system32>chocolatey install ServiceBusExplorer
Chocolatey v0.10.8
Installing the following packages:
ServiceBusExplorer
By installing you accept licenses for the packages.
[NuGet] An error occurred while loading packages from 'http://wanuget/bootstrap/nuget': The remote name could not be resolved: 'wanuget'
ServiceBusExplorer not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "http://wanuget/bootstrap/nuget"
```

**Comment by tomkerkhove** [comment]
I think this is more of a Chocolatey issue rather than a SBE explorer issue.
Feel free to create an issue with them.

**Comment by jrmcdona** [comment]
Is nobody else facing this issue?

**Comment by jrmcdona** [comment]
@tomkerkhove Chocolately says this is not a problem with them.  See the below for reference.

https://github.com/chocolatey/choco/issues/1672#issuecomment-435704961

**Comment by tomkerkhove** [comment]
I tried this and this works fine on my machine: 
![image](https://user-images.githubusercontent.com/4345663/47985713-d2448b80-e0da-11e8-9577-697d873dc567.png)

Does the machine have a good connection?

**Comment by jrmcdona** [comment]
@tomkerkhove hmm odd.  I do have a good connection.  Nothing else seems to be having trouble.  

I wonder what on my machine is blocking access to http://wanuget/bootstrap/nuget or referecing it causing this failure

**Comment by arerlend** [comment]
How about the public choco repo?  Your choco is probably looking for SBE in a private repository.

`choco install ServiceBusExplorer -s https://chocolatey.org/api/v2/` or something similar.

**Comment by bcurran3** [comment]
@jrmcdona 

Source(s): "http://wanuget/bootstrap/nuget" is your problem. You are using a localized package built for (assuming) your local environment. "wanuget" is not a fully qualified domain name. The package you are using is not going to work to download files from the Internet. I'm assuming "wanuget" is the NETBIOS name of a local server. Make sure you have access to that server and check with your server administrators if not.

https://chocolatey.org/packages/ServiceBusExplorer is the Chocolatey community repository version. It has all the files embedded. If your immediate goal is to just install the package, you can download the package from the above page and install or do
choco install ServiceBusExplorer -s https://chocolatey.org/api/v2/

If the goal is to fix the package, you're going to have to take it up with your local IT department that made the package and administrators of the "wanuget" server.

**Comment by jrmcdona** [comment]
Thanks I went ahead and got SBE from here https://code.msdn.microsoft.com/windowsapps/Service-Bus-Explorer-f2abca5a for now
