### ISSUE TITLE
Unable to save connection string

### ISSUE THREAD

**Issue by bencalegari** [paolosalvatori/ServiceBusExplorer#280]
Attempting to save my connection string in ServiceBusExplorer 4.0.110 returns this error, visible in the logs below:

```
<12:12:24> Exception: An error occurred loading a configuration file: Access to the path 'C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\rzr3xdv1.tmp' is denied. (C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe.Config)
<12:12:24> InnerException: Access to the path 'C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\rzr3xdv1.tmp' is denied.
```
Permissions on the tools directory (using gitbash):
```
drwxr-xr-x 1 <username> 1049089       0 Nov 19 15:58 tools/
```

![screenshot 2018-11-20 10 17 14](https://user-images.githubusercontent.com/4923102/48794121-da412580-ecad-11e8-9e7d-2287724dabc7.png)

**Comment by ErikMogensen** [comment]
Please try one or more of the following solutions/workarounds and let us know what worked:

1. Start ServiceBusExplorer in elevated mode by selecting "Runs as administrator".
2. Give your user (it is not enough with the Administrators group) the Full Control permission on the Tools directory. 
3. A recent feature has been added to ServiceBusExplorer that allows you to save connection strings in a separate file in your user folder. It has not been released yet so to use this you need to download the source from https://github.com/paolosalvatori/ServiceBusExplorer and build it yourself.

**Comment by bencalegari** [comment]
Running as administrator did the trick! Thanks.

**Comment by thomaslevesque** [comment]
@ErikMogensen running as admin or giving permission on the directory will work, but it's not the right way to handle this. Application data should be saved in the AppData folder, not in the installation folder.

**Comment by paolosalvatori** [comment]
@thomaslevesque / @ErikMogensen can we add the option to save data in the C:\%APPDATA% folder instead of the installation folder?

**Comment by thomaslevesque** [comment]
> @thomaslevesque / @ErikMogensen can we add the option to save data in the C:%APPDATA% folder instead of the installation folder?

Honestly, I think it shouldn't even be an option, it should be the default.
Saving the connection should at least work when you use the recommended installation method (Chocolatey), and currently it's not the case.

**Comment by paolosalvatori** [comment]
@thomaslevesque, you are right, but take into account when the tool was born years ago it was just a sample, then it evolved into a community supported tool. Why don't you create a PR and contribute to make the tool better?

**Comment by thomaslevesque** [comment]
@paolosalvatori I'm well aware of this, and I'm not demanding anything of course ;)
I might send a PR if I find the time.

**Comment by paolosalvatori** [comment]
Thanks @thomaslevesque ;)

**Comment by ErikMogensen** [comment]
@thomaslevesque  and @paolosalvatori , previously in this thread I wrote:

> A recent feature has been added to ServiceBusExplorer that allows you to save connection strings in a separate file in your user folder. It has not been released yet so to use this you need to download the source from https://github.com/paolosalvatori/ServiceBusExplorer and build it yourself.

This feature is part of the latest release. It is however not the default since it was deemed that maintaining backwards compatibility was more important. You enable this using the Options dialog and you can decide if it should use the classic way of only using the application, only store and read connection string from the User file or both. The last option will store the connection strings in the User file but read connection strings from both files. :

![image](https://user-images.githubusercontent.com/9644248/53754597-b39da800-3eb4-11e9-8ad7-8e3a2230a590.png)

 Try it out!

**Comment by thomaslevesque** [comment]
Hey @ErikMogensen, thanks for the tip, I'll give it a try!

> It is however not the default since it was deemed that maintaining backwards compatibility was more important.

The last option ("Both") could be made the default without breaking compatibility. Users who have their settings in the application folder will still be able to use them, and if they change them, they will be written to the user file. Looks like the best of both worlds to me!

**Comment by ErikMogensen** [comment]
Depends upon how you define backwards compability. It might create confusion when not all of the connection strings are put in the application configuration file as usual. 

Also, It required a lot of changes, far more than I expected, to implement the functionality to save the connection strings in another file, so it is quite likely that there are bugs or other problems related to this. Perhaps when this functionality feels stable and most users are aware of the other configuration file we will make option Both the default.

**Comment by apjanke** [comment]
Gonna chime in here that I think “Both” should be the default, too, and hopefully you can get to a point where that's feasible.

I see two scenarios where this is important:

If SBE gets installed by IT as a managed package or as a program on a shared drive, the installation folder may well be read-only to users. So saving to the Application Configuration File won't work.

Maybe more importantly, in a multi-user scenario, saving to the Application config file could be a security issue: the Shared Secret values in the connection strings look like they're stored in plain text. So anyone who can see the shared app config file can get the password and connect to the queue (as an admin, I think).

**Comment by mlsomers** [comment]
I was on my way to report a duplicate when I found this thread...
It's not working "out of the box" as it is.
For backward compatibility you should be able to differentiate a clean install from an upgrade... When upgrading I guess you don't overwrite the configuration any way unless you run some conversion on them. Why not keep it backward compatible for upgrades and working out of the box for new users?

**Comment by paolosalvatori** [comment]
Sorry for coming late to the discussion, I think both should be default. All connection strings and settings should be read from both the application and user configuration file, but when selecting this option, any new option or connection string should ends up in the user configuration file as the main source of truth.
