### ISSUE TITLE
Subscription Listener

### ISSUE THREAD

**Issue by joclefrancois** [paolosalvatori/ServiceBusExplorer#282]
Hi,

Using the Service Bus Explorer, I create a "Subscription Listener" on the same subscription on my application. No matter what parameters I set before to start the listener, e.g. "ReceiveDelete" or "PeerLock", "Auto Complete" on or off, it seems that messages are lost forever, my application will never receive messages that were caught by the listener while it's running. 

Maybe it is by design, maybe it is a bug. Thank you to share more information about this feature.

**Comment by SeanFeldman** [comment]
Looking at the code, `ReceiveAndDelete` will always delete, which is expected.
`PeekLock` will auto-complete or delete manually. Meaning it will **always** delete.
The tool simply doesn't allow to purely "peek" messages with a listener w/o not deleting messages.

/cc @paolosalvatori

**Comment by paolosalvatori** [comment]
Hi @joclefrancois if you just want to see what is in the subscription without deleting messages, you can simply proceed as follows:

- Select the subscription in the the tree view
- Click the Messages button
- Select Peek receive node in the dialog box
- Click OK button

We may extend the subscription listener with the ability to just peek messages from a subscription without deleting them, but if your goal is just checking if the subscription contains messages, please follow the above approach. Please, let me know if this answers your question.

**Comment by joclefrancois** [comment]
Yes, it answers my question, thank you.
