### ISSUE TITLE
Error Connecting using Connection String

### ISSUE THREAD

**Issue by RealDotNetDave** [paolosalvatori/ServiceBusExplorer#289]
I've been trying to connect using a connection string like this:

DefaultEndpointsProtocol=https;AccountName=testsb;AccountKey=zJb0Z1e9FwMnmuEkNqo19WgXCBldSBm/cKY3d04x9tihMFPhu/2Sv3Dwdg==;BlobEndpoint=https://testsb.blob.core.windows.net/;TableEndpoint=https://testsb.table.core.windows.net/;QueueEndpoint=https://testsb.queue.core.windows.net/;FileEndpoint=https://testsb.file.core.windows.net/;TransportType=NetMessaging

But I keep getting these errors:
<16:26:01> Both the uri and namespace for the service bus entry Manual is null or empty.
<16:26:01> Exception: The connection string argument cannot be null.. Method <Connect>b__2d: retry 1 of 10.

**Comment by SeanFeldman** [comment]
The connection string you're using is a Storage connection string, not
Service Bus 🙂

Sean Feldman

**Comment by RealDotNetDave** [comment]
Where do I get the storage connection string? I tried using the one that starts with "Endpoint=" but could not get that working either.

**Comment by RealDotNetDave** [comment]
Oh, I got it working. Thanks.

**Comment by SeanFeldman** [comment]
🙂
