### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#29]
Version SBE using [GitVersion](https://github.com/GitTools/GitVersion) (auto-incremented upon commit to master)

**Comment by paolosalvatori** [comment]
Sounds great, let's talk about it during a call.
Ciao 
Paolo

**Comment by SeanFeldman** [comment]
I've suggested to use GitVersion with auto-increment upon commits to master.
@paolosalvatori prefers to have SBE version match the ASB client version.
While I can see the value in ability to link between ASB client version with SBE, I find this versioning model very restrictive and inaccurate. For example: assuming there were bug fixes and several releases for SBE, it's still against the same ASB client version, but now users cannot know what version of SBE has the bug fixed or not. 

The association could be addressed by having GH release notes that are generated off the issues closed. Would rather see SBE version that can show what issues where closed and not what ASB client is used behind the scenes. 

Let's discuss this.

**Comment by paolosalvatori** [comment]
Hi @SeanFeldman I agree with you about your comment on linking SBE version with ASB version about bugs, but for historical reasons, I prefer to keep this approach. Now, since ASB usually uses the first 2 numbers of the major and minor version (x.y) we could use the patch number (z) to actually specify the tool versions.

**Comment by SeanFeldman** [comment]
This is already happening 😉 as of PR #68.
Latest release is `3.4.18`, which is build 18 on AppVeyor. 
Build number is auto-incremented, so we'll have "gaps" (i.e. it could jump to 21 if we 20 builds that took place not on master), but at least we know a unique version of the tool.
Ideally, using something like GiVersion would improve things, as only changes to master could be modifying the patch version. We'll see. Keeping this opened for now.

**Comment by RocketPop** [comment]
FYI - if I go to the releases "tab" and click "3.4.18" the .zip binary within has version numbers throughout that say "2.4.3.0"

**Comment by SeanFeldman** [comment]
Thank you @RocketPop 
Could you raise a separate issue for that? I'll mark it as a bug and fix next week. Must be something that is not picked up during appveyor build execution.

**Comment by paolosalvatori** [comment]
Thanks @SeanFeldman to be on top of this :)

**Comment by SeanFeldman** [comment]
Closing this issue.
Bug filed under #71

**Comment by SeanFeldman** [comment]
@RocketPop fixed starting from [release 3.4.22](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/3.4.22)
