### ISSUE TITLE
Multiple Active Namespaces

### ISSUE THREAD

**Issue by niheinba** [paolosalvatori/ServiceBusExplorer#290]
Hey,

I have multiple Service Bus namespaces that I would like to look at without closing other ones down. Is that possible? Right now I have them saved properly, but everytime I go File -> Connect and select the namespace it opens that and closes the current one. Is there a toggle I am missing?

Thanks!

**Comment by SeanFeldman** [comment]
No toggle. The tool is designed for a single namespace usage. Would running two instances (or as the number of namespaces) help to workaround this issue?

**Comment by niheinba** [comment]
I was hoping to auto forward from one subscription into another. I can always play around with the SDK and do it that way instead of trying to GUI it.

Thanks for the quick response!

**Comment by niheinba** [comment]
Dang, I did not understand what I read. Thank you for your help!

**Comment by paolosalvatori** [comment]
True, there's no forwarding between namespaces... at least at this time ;)

**Comment by guibirow** [comment]
I there any technical limitation that prevents opening two namespaces at once into a single SBE instance?

**Comment by ErikMogensen** [comment]
The code is just structured that way. It would take some effort to enable multiple instances.  The workaround is, as Sean mentioned, to use multiple instances of SBE.

This request has been raised before so it is a popular request but since the workaround is pretty good I think this is a low priority issue. But feel free to create a PR for it.

**Comment by paolosalvatori** [comment]
The tool uses a treeview control to show the items contained in a Service Bus or Event Hubs namespace. When you click Ok in the connect form, the tool retrieves all the entities from the namespace and creates nodes under the treeview. Now, if you want the tool to handle multiple namespaces at the same time, the tool should be extended to manage multiple treeviews, one for each namespace. This requires a non-trivial change of the code that handles the UI.
