### ISSUE TITLE
Receive Messages in Order

### ISSUE THREAD

**Issue by cz-kmocherla** [paolosalvatori/ServiceBusExplorer#292]
Hi,
Could you please add a way to receive the messages sorted based on the timestamp so we get the latest messages first.
Currently, we get the oldest ones first and need to fetch more messages and reverse sort them to view the newer ones.

**Comment by SeanFeldman** [comment]
@cz-kmocherla there's no way to control if messages received in ascending or descending chronological order. This would need to be done once messages are received. I thought you can already sort the grid. Could you please confirm?

**Comment by cz-kmocherla** [comment]
@SeanFeldman Yes, I can sort the grid after I fetch the messages.
@paolosalvatori Yes, that is exactly what I was looking for - a LIFO ordering. The reason for this is if there are around 50000 messages in the queue, I would have to fetch all of them to view the latest 10 messages

**Comment by SeanFeldman** [comment]
@cz-kmocherla to backup @paolosalvatori here - there's a broker feature that is missing. As of today, you can't browse messages with certain status and either have to get it all or not. Here's an [example issue](https://github.com/Azure/azure-service-bus/issues/95). The broker should support browsing messages given a criteria, not this tool IMO. Cheers.

**Comment by SeanFeldman** [comment]
Looks like there's not much to be added here. Closing this issue.
