### ISSUE TITLE
Invalid body type when resubmitting messages in batch from Deadletter

### ISSUE THREAD

**Issue by jstawski** [paolosalvatori/ServiceBusExplorer#294]
When trying to resubmit 2 or more deadletter messages to the queue, the body type dropdown seems blank. When the dropdown is opened the right type seems to be selected, but when closed it shows blank. Changing the type, seems to maintain it. This is not a UI problem only as when the messages are submitted the body types can't be read by other clients. I was able to confirm this by resubmitting one by one (which are processed correctly) vs batch.

![image](https://user-images.githubusercontent.com/873800/52134415-8342bf80-2611-11e9-957f-5dfd9d4928b2.png)
![image](https://user-images.githubusercontent.com/873800/52134537-c6049780-2611-11e9-895a-578a0914d60a.png)
![image](https://user-images.githubusercontent.com/873800/52134542-c9981e80-2611-11e9-9c60-feafd3b4cf69.png)

**Comment by ErikMogensen** [comment]
Hi @jstawski, 
I created PR #296 for resolving the GUI issue. I looked at the submitting part and from what I can tell it should be the same result in batch mode as in single mode. However, I had no way of quickly determining whether it was using the intended body type. Do you have a good way of doing that?
