### ISSUE TITLE
Close of Deadletter Message edit window refreshes the current connection

### ISSUE THREAD

**Issue by rahulseth01** [paolosalvatori/ServiceBusExplorer#297]
1. Open any Dead-lettered message.
2. Click on "Close" or "X"
3. It can be noticed that Explorer will refreshes the entire connection

**Comment by SeanFeldman** [comment]
PR #298 will address this issue. Thanks @rahulseth01 for reporting the problem.

**Comment by rahulseth01** [comment]
Hi,
I see this issue resurrect in build: 4.1.112. @SeanFeldman  Can this issue be re-opened?

**Comment by SeanFeldman** [comment]
@rahulseth01 did you run into this with the latest?

**Comment by rahulseth01** [comment]
Yes, it is happening again in the latest release.

**Comment by paolosalvatori** [comment]
Can you confirm that you can see the issue in the latest release @rahulseth01? Thanks!

**Comment by rahulseth01** [comment]
Yes, it is happening in latest release.

**Comment by rahulseth01** [comment]
Hi,
Please let know any update of this bug. Can this be picked up on priority as it is delaying entire process while analyzing dead-lettered messages

**Comment by ErikMogensen** [comment]
There is an issue with some older versions of Service Bus Explorer incorrectly reporting as being the latest version. So please make a screen shot of the About box and put it in this thread to help us determine the actual version you are using.

Service Bus Explorer is 100% community driven so there are no dedicated developers.

**Comment by rahulseth01** [comment]
Thank you Eric. I do understand its a community driven and really appreciate the hard work being put by you all.
My only intention was to bring this bug up to the notice as its been quite long.
I am hereby attaching the required screenshot.

P.S: The topic refresh get triggered only when dead-letter message-box is closed (either on clicking on close button or X button) not when normal message-box is closed.

![image](https://user-images.githubusercontent.com/13518368/79258803-55116e80-7ea9-11ea-91bc-ff7ca63c1541.png)

Close of below message box triggers refresh
![image](https://user-images.githubusercontent.com/13518368/79259709-c43b9280-7eaa-11ea-9bce-8bc6c50962af.png)

**Comment by ErikMogensen** [comment]
Yes, you are using the latest release. There are some commits concerning this after the 4.1.112 release. @rahulseth01 , have you tried build the develop branch and testing that?

**Comment by rahulseth01** [comment]
Thanks Eric. Yes it works perfectly fine on develop branch.

**Comment by paolosalvatori** [comment]
Thanks @ErikMogensen! @rahulseth01 can I close the issue?

**Comment by rahulseth01** [comment]
Yes it can be closed. Btw when are you planning to cut one release from develop branch?

**Comment by ErikMogensen** [comment]
As I see it, once #410 and #411 are solved.
