### ISSUE TITLE
SBE interface is not HiDPI friendly

### ISSUE THREAD

**Issue by onovotny** [paolosalvatori/ServiceBusExplorer#30]
Does not scale well -- 
![2016-02-12_15-26-17](https://cloud.githubusercontent.com/assets/1427284/13019376/107da9b8-d19d-11e5-8060-2f5cd31e4ccb.png)

**Comment by paolosalvatori** [comment]
Thanks for the heads up! I don't have time to do any change to solve the issue. The code is on GitHub, you can try to fix the issue by yourself. :) Sorry!

**Comment by imperugo** [comment]
@onovotny you're more lucky than me :)

<img width="1424" alt="screen shot 2016-02-24 at 15 04 20" src="https://cloud.githubusercontent.com/assets/758620/13287551/e9c55b30-db07-11e5-92ed-b805c636708e.png">

**Comment by onovotny** [comment]
Has this been fixed?

**Comment by paolosalvatori** [comment]
No... sorry it has not been fixed... I don't know how to test or fix that :(
Ciao
Paolo

**Comment by onovotny** [comment]
Please don't close this then as it's still a real outstanding issue that leaves this tool unusable on many people's displays, including Surface Book and anyone with a 4k monitor.

**Comment by paolosalvatori** [comment]
Ok.. but as I said, I don't know how to solve this problem as I can't reproduce it. In addition, I don't know if I have the bandwidth to do it. In August I'll be on vacation by the way :)
Ciao
Paolo

**Comment by SeanFeldman** [comment]
@onovotny how is your monitor configured? I'm running on 4K and it's all good.

**Comment by SeanFeldman** [comment]
@onovotny @imperugo would you like to help with this?

**Comment by onovotny** [comment]
I don't have much bandwidth to help directly but I can test something when available.

**Comment by SeanFeldman** [comment]
Kicking this again - would the new feature released with [.NET FW 4.7](https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/) address this ("Take advantage of High DPI" section) @onovotny?

**Comment by onovotny** [comment]
I put some HiDPI lipstick on RSS Bandit, so I'd say anything is possible :)https://github.com/RssBandit/RssBandit

It's really just a matter of time... That said, some of the simple things, like the manifest settings, might just work with Creators Update and later?

**Comment by onovotny** [comment]
Related to that, I'd think it worth-while to put this in the Windows Store as a Desktop Bridge app.

**Comment by paolosalvatori** [comment]
@onovotny I agree with you, after Easter I can take some time to put SBE in the Windows Store as Desktop Bridge app. Regarding the migration to .NET framework 4.7, @SeanFeldman ,if not necessary to put the app in the store, I'don't wait a few months just to gethe Visual Studio 2017 more largely adopted.

**Comment by SeanFeldman** [comment]
Desktop Bridge was discussed in #49. @msimecek has shared his instructions so we should be able to apply that with AppVeyor.

**Comment by StefH** [comment]
@SeanFeldman
Upgrading to .NET Framework 4.7 and updating the app.config like [WebDAV-AudioPlayer/App.config](https://github.com/StefH/WebDAV-AudioPlayer/blob/master/src/WebDAV-AudioPlayer/App.config) dis solve DPI issues for my application.

**Comment by SeanFeldman** [comment]
Thank you @StefH.
I have no UI knowledge. @paolosalvatori is this something we should add to the config in general?
