### ISSUE TITLE
UI becomes unresponsive during deletion of DLQ

### ISSUE THREAD

**Issue by mrdrejko** [paolosalvatori/ServiceBusExplorer#300]
During deletion of DeadLetters UI freezes and becomes unusable. I couldn't use Service Bus Explorer for 1 hour during deletion of 100k messages. This is happening whenever process several thousand messages (eg. want to display 15000 messages), and time of unresponsiveness varies based on how many messages was processed.
I have found workaround (starting new instance of SBE), however don't think this is right way to do it.
Maybe, at least, to show with progress bar that process is in progress.

**Comment by ErikMogensen** [comment]
How are you deleting the messages? Are you using the Messages button and then selecting Receive and Delete or have you right clicked the queue and selected Purge Dead Letter Messages?

In a Service Bus Explorer release last year the purging of Dead Letter Messages was changed to use an algorithm for spinning up several threads when purging. It should delete 100 K messages in a lot less time than 1 hour, unless you have a really bad internet connection or hardware.

**Comment by ahofman** [comment]
Agree that Purge is better if the intent is to delete all dead lettered messages in a queue - however if @mrdrejko is deleting a subset of messages, based on a filter expression from the Deadletter tab he makes a valid point. The UI will be similarly unresponsive when resubmitting large volumes of messages. In these scenarios I think a dialog with a progress bar is a good idea.

**Comment by paolosalvatori** [comment]
@ahofman this is an excellent idea. Do you have bandwidth to implement this feature and submit a PR?

**Comment by ErikMogensen** [comment]
I also think a progress bar would be great, however it is difficult to implement properly. It would also be good to know where this is needed the most.

@mrdrejko, about the problem of the time it takes, have you tried the latest release of Service Bus Explorer? It was released a couple of weeks ago and unlike previous versions it does not show the version number in the main window title bar.
