### ISSUE TITLE
Purge operation doesn't remove Deferred messages

### ISSUE THREAD

**Issue by ahofman** [paolosalvatori/ServiceBusExplorer#302]
To reproduce:

1. Send some messages to a Service Bus queue
1. Defer them via the deferral APIs (https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-deferral)
1. Purge the queue

The deferred messages still remain in the queue.
In my tests the purge operation took a long time - > 300 seconds - even though there were < 10 deferred messages in the queue. 
![image](https://user-images.githubusercontent.com/1689712/52546713-bc4f1100-2e15-11e9-9dd1-1073f7d452d9.png)

I would expect the following

1. Purge takes a short amount of time if there are < 10 deferred messages in the queue
1. Purge can delete deferred messages

**Comment by SeanFeldman** [comment]
Purge operation is implemented as receive operation.
With ASB client, receive operation doesn't get deferred messages. It would require Peek operation to retrieve message `SequenceNumber` and receive messages by `SequenceNumber`.

Personally, I don't like purging queues the way we do right now. It really should be supported by the broker. There's an issue for that: https://github.com/Azure/azure-service-bus/issues/1

**Comment by ahofman** [comment]
Honest question - would the SBE "Purge" operation be faster and more reliable if it were implemented by deleting and re-creating the queue? That's what I do now (manually) when I find the Purge operation isn't working for me. 

cc @paolosalvatori

**Comment by SeanFeldman** [comment]
You would definitely get rid of _all_ messages, but this is such a destractive operation...

**Comment by paolosalvatori** [comment]
In my opinion, Service Bus Messaging should provide the ability to selectively purge:

- all messages including dead-lettered and deferred messages
- active messages
- dead-lettered messages
- deferred messages

from a queue or a subscription. If you agree with this idea, I will submit this feedback to the product group.

**Comment by SeanFeldman** [comment]
@paolosalvatori The request is there long time ago. Broker-side issue is at least 2 years old... https://github.com/Azure/azure-service-bus/issues/1

**Comment by paolosalvatori** [comment]
I know my friend @SeanFeldman but we have an internal feedback mechanism so I will re-iterate the need to implement this feature :)

**Comment by SeanFeldman** [comment]
I would combine the efforts.
Customer voice should be taken seriously.
Not to mention that internal things are hidden and die internally 😉

**Comment by ErikMogensen** [comment]
Until this is fixed in the service we have to workaround that shortcoming. What @ahofman describes seems to be a bug where Service Bus Explorer detects that there are messages in the queue and does its best to delete them. Instead it should detect that the messages are non deletable and give up. This won't solve the initial problem of getting rid of the deferred messages but it shouldn't take 5 minutes. 

I can fix this when we have decided how we going to migrate to the new Service Bus Client.

**Comment by SeanFeldman** [comment]
W/o derailing the conversation, are we saying "no bugs will be fixed until we decide how to move to the new ASB client"?

**Comment by ErikMogensen** [comment]
That's not what I meant. It's just a personal preference for me. Anyone else may of course fix this before that.

**Comment by paolosalvatori** [comment]
As I said, the ability to purge different kind of messages is a feature that should be provided out of the box by Service Bus, our tool can eventually compensate in some way, but for example, for deferred messages, it's not our responsibility to implement this feature.
