### ISSUE TITLE
Purging the messages in dead letter queue is not refreshing the screen once it got completed

### ISSUE THREAD

**Issue by uday060** [paolosalvatori/ServiceBusExplorer#303]
Select any queue which has dead letter messages and click on Deadletter button.
Select Receive Mode as Peek and click on Ok button
All dead letter messages are being displayed in the messages section
Click on Purge button to purge the dead letter messages in the queue
Once it got completed, still the screen is showing all the dead letter messages in messages section.

Expected Functionality : Messages section should be refreshed once purge operation got completed.

**Comment by SeanFeldman** [comment]
Purge button refers to the active messages, not dead-lettered messages.
If you want to purge dead-lettered messages, use <kbd>Purge DLQ</kbd> button.
