### ISSUE TITLE
Add TimeSpan support for the Message Custom Properties

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [paolosalvatori/ServiceBusExplorer#304]
I use custom TimeSpan property for the retry mechanism. Unfortunately this type is not supported by the MessageForm and I am unable to edit & resend this message correctly. 
<img width="339" alt="old" src="https://user-images.githubusercontent.com/5083018/52865229-6becf180-313c-11e9-9119-e2947dbd9617.PNG">

For the testing purposes, I did it on my fork and it looks like small change. Add an option to the dropbox and convert it inside MapStringTypeToCLRType.

<img width="348" alt="new" src="https://user-images.githubusercontent.com/5083018/52865476-ffbebd80-313c-11e9-9f04-31d4287c15f8.PNG">

Let me know if you see advantages in supporting this type, I'm happy to propose PR.

**Comment by SeanFeldman** [comment]
Would be good @lukasz-pyrzyk, thanks.
