### ISSUE TITLE
Clicking on messages to see the details or clicking on "Repair and resubmit" fails in 4.1.111

### ISSUE THREAD

**Issue by batizar** [paolosalvatori/ServiceBusExplorer#307]
I am not able to click on messages in Message List to see their details or "Repair and resubmit" DLQ messages in 4.1.111. It shows  `Exception: The item argument cannot be null.` in log window.

Tested with 4.0.110 and everything works as expected.

Cheers.

**Comment by SeanFeldman** [comment]
@batizar I've just tried 4.1.111 and it worked.

Click <kbd>Deadletter</kbd> then "Peek top 10" then double-click on any message brings "Repair and Resubmit Messages" window. Was able to update and resubmit a message.

**Comment by MikeWilliams-UK** [comment]
This is a symptom of #310.
I have submitted a PR with my code fixes.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/4706ba915ae70f1246772fca4702c88996c603c7
