### ISSUE TITLE
Very slow loading times for topics with a high number of subscriptions

### ISSUE THREAD

**Issue by sterobson** [paolosalvatori/ServiceBusExplorer#308]
We have a Service Bus with three topics, and each topic has approximately 1000 different subscriptions. Loading the namespace in Service Bus Explorer takes between 5 and 10 minutes with the program completely unresponsive during this time.

I've investigated the problem and it stems from the fact that for every subscription the program is doing an additional request to get the subscription's rules so that it can build the tree. In our case this leads to the following requests:

- Read list of subscriptions for **TopicA** (1 request)
- Read rules for each subscription in **TopicA** (1000 requests)
- Read list of subscriptions for **TopicB** (1 request)
- Read rules for each subscription in **TopicB** (1000 requests)
- Read list of subscriptions for **TopicC** (1 request)
- Read rules for each subscription in **TopicC** (1000 requests)

This results in 3000 additional requests. I've tinkered with the code and when I remove the rule requests the load time improves significantly, and the tree can be built in tens of seconds rather than many minutes.

Given that Service Bus supports up to 2000 subscriptions per topic I believe our use case is valid. Would it be feasible for Service Bus Explorer to implement lazy loading of the rules nodes, so that the rules request for a subscription is only sent when that particular subscription is highlighted or expanded?

**Comment by ErikMogensen** [comment]
Good suggestion, I think this is something that should be added. Please create a PR for this.

**Comment by sterobson** [comment]
@ErikMogensen - thanks, I'm on it. I've created a branch locally and implemented the changes, but I get a 403 error when I try to push the branch or create a pull request. Do I need additional permissions on the repo to do this?

**Comment by ErikMogensen** [comment]
Great! You need to fork it and then push your changes to your fork of the repository. From the fork you can create the PR using the GitHub UI.
