### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by honght0068** [paolosalvatori/ServiceBusExplorer#31]
<16:41:30> The link uri http://xxxxx-ns.servicebus.windows.net/ has been successfully retrieved.
<16:41:42> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 1 of 10.
<16:41:55> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 2 of 10.
<16:42:07> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 3 of 10.
<16:42:19> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 4 of 10.
<16:42:32> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 5 of 10.
<16:42:44> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 6 of 10.
<16:42:56> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 7 of 10.
<16:43:09> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 8 of 10.
<16:43:21> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 9 of 10.
<16:43:33> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.. Method <GetNotificationHubs>b__2a: retry 10 of 10.
<16:43:46> Exception: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxxx-ns-sb.accesscontrol.windows.net''.
<16:43:46> InnerException: The token provider was unable to provide a security token while accessing 'https://xxxxx-ns-sb.accesscontrol.windows.net/WRAPv0.9/'. Token provider returned message: 'The remote name could not be resolved: 'xxxx-ns-sb.accesscontrol.windows.net''.

**Comment by tomkerkhove** [comment]
It looks like the client can't connect to the token provider - Are you sure it's connected to the internet?
