### ISSUE TITLE
Errors when body is empty

### ISSUE THREAD

**Issue by MikeWilliams-UK** [paolosalvatori/ServiceBusExplorer#310]
If a message has no body then the message properties are not fetched.
This worked in a previous vesion.

"<16:03:29> Exception: The item argument cannot be null."
is seen in the log window if the message is double clicked on.

**Comment by MikeWilliams-UK** [comment]
I have downloaded the source debugged it and tracked down how to "fix" it for us.

File $\src\ServiceBusExplorer\Helpers\JsonSerializerHelper.cs function
Function JsonSerializerHelper.IsJson at line 114

If I replace
```csharp
throw new ArgumentException("The item argument cannot be null.");"
```
with
```csharp
return false;
```

With this change SBE functions as it previously did with messages that have no body.

**Comment by SeanFeldman** [comment]
@MikeWilliams-UK sounds like a bug. Could you raise a PR and add a test to [`JsonSerializerHelperTest`](https://github.com/paolosalvatori/ServiceBusExplorer/blob/e2c0a84334d46875d1a8828838fce258eda0c6c9/src/ServiceBusExplorer.Tests/Helpers/JsonSerializerHelperTest.cs)? Thank you.

**Comment by MikeWilliams-UK** [comment]
Just forked the repo, going to fix and submit pr, hopefully sometime today.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/4706ba915ae70f1246772fca4702c88996c603c7
