### ISSUE TITLE
Use Microsoft.Azure.Services.AppAuthentication for getting access to service bus

### ISSUE THREAD

**Issue by Zenuka** [paolosalvatori/ServiceBusExplorer#318]
It would great if we could use the current user's to connect to service bus using `Microsoft.Azure.Services.AppAuthentication` nuget so that you won't need to store a connection string or fetch it from the azure portal everytime.

**Comment by tomkerkhove** [comment]
This only works for applications running on Microsoft Azure, how would you see this working then?

Do you want to run it on a VM or? If so, not sure if this is supported.

**Comment by Zenuka** [comment]
No, I didn't mean to run it on a VM but just on my machine under my user. Using this library as a token provider instead of shared access key, like: https://azure.microsoft.com/en-us/resources/samples/app-service-msi-servicebus-dotnet/

**Comment by tomkerkhove** [comment]
Interesting. But MSI only works nicely in Azure given "Managed" service identity is managed by MSFT.

See https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#how-does-the-managed-identities-for-azure-resources-worka-namehow-does-it-worka

**Comment by Zenuka** [comment]
Yes, but I want to benefit from it when running it on my own pc under my own account. I've written Web Api's using this nuget to access other azure resources (like key vault or service bus) by using an azure managed service identity and I can run the web api's locally without any change in code. It will use the current user to get access token (if the user has access of course). 

For service bus you do need explicit rights (not implicit rights like when you are subscription owner).

**Comment by SeanFeldman** [comment]
@Zenuka would you like to help the project and send a PR?
I'm not an expert on MSI, so if you don't have the bandwidth, could you help with getting the knowledge how to achieve this on a local app? Thanks.

**Comment by paolosalvatori** [comment]
Hi @Zenuka, using Microsoft.Azure.Services.AppAuthentication to adopt the user's credentials to authenticate against an Azure Active Directory tenant and use Azure RBAC to access a Service Bus namespace looks an interesting option. You also need to make sure to add your use to the Service Bus Data Owner role specifying as scope your Service Bus namespace(s),  or the resource group / subscription that contains them. I'm closing this issue, in case please submit a PR if you haven't done it yet (I'm reviewing past issues one by one right now).

**Comment by paolosalvatori** [comment]
I'll investigate when I have some time. I used the ManagedServiceIdentityTokenProvider but that assumes that you create a system-assigned managed identity on Azure, even if when running the code locally it impersonates the developer credentials. In other words, it works if you run the app from Visual Studio, not sure how it works if you do it from the command-line.

**Comment by Zenuka** [comment]
The AppAuthentication nuget uses one of 3 options:

1. MSI endpoint (available when running in Azure)
2. An access token Visual Studio provides (I think using an environment var)
3. A token used from the Azure CLI (stored in your user folder somewhere)

So if you would be authenticated using the Azure CLI that might work.

**Comment by SeanFeldman** [comment]
I might be mistaken, but MSI can also work with environment variables.
Saying that AZ CLI sounds like the best option.
