### ISSUE TITLE
Cannot revert Configuration file option to "Application Configuration File"

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#319]
In View > Options, the option "Configuration File for Settings and Connection Strings" defaults to "Application Configuration File" (I think). At some point, I set it to "Both (User file will override)", and now I can't set it back.

I'll open View > Options, switch it to "Application Configuration File", hit Save, and hit OK. If I re-open View > Options in the same program session, it'll still be set to "Application Configuration File". But if I exit Service Bus Explorer and restart it, the log says "The files C:\Users\...\UserSettings.config and C:\ProgramData\chocolatey\...\ServiceBusExplorer.exe.Config are used for the configuration settings.", and in View > Options, it is back to "Both (user file will override)".

This is Service Bus Explorer version 4.1.113 on Windows 10. SBE is installed via chocolatey. I have uninstalled and reinstalled SBE, and it didn't make a difference.

**Comment by apjanke** [comment]
Looks related to https://github.com/paolosalvatori/ServiceBusExplorer/issues/280.

**Comment by ErikMogensen** [comment]
Good catch! It seems that Service Bus Explorer does not update the user configuration file which it would have to. Meanwhile to workaround this delete the line <add key="ConfigFile" value="UserConfig" /> from the User configuration file.

**Comment by apjanke** [comment]
The workaround worked. Thanks!
