### ISSUE TITLE
Copy namespace URL/connection string action

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#320]
In the navigation tree on the left, when you right-click a Queue or Topic, they have context menu items for copying their URLs, like "Copy Queue URL", "Copy Deadletter Queue URL", and so on. But when you click on the root namespace node, there's no options for copying URLs. I think it would be nice to have items for "Copy Namespace URL" and "Copy Connection String URI".

It would be convenient to have this, particularly for connections created using the multi-field dialogs in File > Connect, because you can't Save those, and as far as I can tell, they don't expose their connection string URIs anywhere else.

What do you think? If this is something you're okay with, I think I could code up a PR to do this.

**Comment by apjanke** [comment]
Here's a PR: #325

**Comment by SeanFeldman** [comment]
👍 

Just an FYI, you don't need to comment about a PR. GitHub automatically does it 🙂

![image](https://user-images.githubusercontent.com/1309622/54381587-c8680180-4653-11e9-8ad1-4e0d203fae9c.png)

**Comment by apjanke** [comment]
Ah. Thanks, and sorry.
