### ISSUE TITLE
Pretty-printing of XML for exported Queues, Topics, etc

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#322]
I'm trying out the Export functionality for queues, topics, etc.

The generated XML files are hard to read because the XML is all in one line with no spaces.

Would you consider a PR for adding pretty-printing (on multiple lines with indentation) for these XML files?

**Comment by SeanFeldman** [comment]
👍

**Comment by apjanke** [comment]
Great.

By the way, thank you and @paolosalvatori for making this tool! At work, we're building a new project using Azure Service Bus queues, so we need an admin tool to view our queue state and debug stuff in it. Nothing else fits the bill. (And it's surprising that the Azure Portal doesn't even have a basic queue viewing tool.) Viva la open source!

**Comment by apjanke** [comment]
That turned out to be easy: #324.

**Comment by paolosalvatori** [comment]
I was busy during the last few months, so sorry for replying so late, thanks for the great contribution @apjanke :)
