### ISSUE TITLE
Send messages from files doesn't work

### ISSUE THREAD

**Issue by iamkarlson** [paolosalvatori/ServiceBusExplorer#326]
Hi,
Do you have any guide on how to make sending messages from the exported messages work? I exported messages from the queue and now I want to send them. I have a file with the following contents:

```
{
  "body": {
    "Id": "4dac3e79-0744-e911-b8b3-000d3a21d08c",
    "Name": "Job 10",
    "Description": "Job Description",
    "Status": "Submitted",
    "JobType": "REPORT",
    "SubmittedDate": "2019-03-11T14:10:49.581",
    "StartedDate": null,
    "CompletedDate": null,
    "OutputFileName": null,
    "Remarks": null
  },
  "contentType": null,
  "correlationId": "d242b81d-94a0-44a2-ad56-e21cd7edd29c",
  "deadLetterSource": null,
  "deliveryCount": 1,
  "enqueuedSequenceNumber": 0,
  "enqueuedTimeUtc": "2019-03-11T14:10:52.845Z",
  "expiresAtUtc": "9999-12-31T23:59:59.9999999",
  "forcePersistence": false,
  "isBodyConsumed": false,
  "label": "Job Created",
  "lockedUntilUtc": null,
  "lockToken": null,
  "messageId": "aa793d8f-0406-4b0d-9a5b-0a9ffb048cbd",
  "partitionKey": null,
  "properties": {
    "EventSource": "Process",
    "EventType": "Created",
    "Entity": "ReportJob",
    "Identifier": "4dac3e79-0744-e911-b8b3-000d3a21d08c"
  },
  "replyTo": null,
  "replyToSessionId": null,
  "scheduledEnqueueTimeUtc": "0001-01-01T00:00:00",
  "sequenceNumber": 56,
  "sessionId": null,
  "size": 532,
  "state": 0,
  "timeToLive": "10675199.02:48:05.4775807",
  "to": null,
  "viaPartitionKey": null
}
```

How can I pick this structure in _Sending messages_ dialog?

**Comment by SeanFeldman** [comment]
Right click --> Send message --> <kbd>Select files</kbd>, but looks like it's brokern 🙁

**Comment by iamkarlson** [comment]
yeah, I've selected files already, but it just loads them to the window and does nothing else

**Comment by SeanFeldman** [comment]
Want to take a stab at fixing it?

**Comment by apjanke** [comment]
> yeah, I've selected files already, but it just loads them to the window and does nothing else

After that, you have to check-box the files you want to send, and then click the Start button to actually send them as messages.

But that’s not the only issue.

I think I kinda see the problem. The UI doesn’t seem to differentiate between files that each contain a message body, and a file that contains a collection of multiple messages exported by SBE. I went through the “Select files” process, and it does seem to work, for what it does. (One problem is that if you’re on the Message or Generator sub-tab and do Select files, it doesn’t switch to the Files sub-tab after loading those files into the list, so it may not be apparent that it had any effect.)

There's a radio button set for Text File / Binary File / Json Template / Xml Template. If I select Json Template (which I _think_ means “previously exported messages”?) and select a file that I had previously created using SBE’s Export Messages feature, an error appears in the log, and then it sends the entire contents of that file as a single message.

```
<20:23:04> C:\Users\NY510094\Documents\BrokeredMessage_Mrtl-Rma-Test-Vstudio-Sub-01_03-14-2019 20-17-51.json is an invalid Json template. The file will be used as text message rather than a template. 
<20:23:04> Sender[0]:   Message sent. MessageId=[47ba8b35-ef6b-46ec-b597-1946d22f0354] SessionId=[NULL] Label=[Service Bus Explorer] Size=[2104]
<20:23:04> Sender[0]:
            - Message Count=[1] Messages Sent/Sec=[26.3157894736842] Total Elapsed Time (ms)=[38]
            - Average Send Time (ms)=[38] Minimum Send Time (ms)=[38] Maximum Send Time (ms)=[38] 
```

I think this is two or three problems:

a) That “Json Template” reading code looks like it's trying to read in the file as a single message, not a collection of exported messages. From `src/ServiceBusExplorer/Controls/TestQueueControl.cs`:

```
                                            else if (radioButtonJsonTemplate.Checked)
                                            {
                                                try
                                                {
                                                    var brokeredMessageTemplate = JsonSerializerHelper.Deserialize<BrokeredMessageTemplate>(text);
                                                    template = serviceBusHelper.CreateBrokeredMessageTemplate(brokeredMessageTemplate);
                                                    messageTextList.Add(brokeredMessageTemplate.Message);
                                                }
```

b) If it fails reading the file as the selected format, it falls back to treating it as raw message content and sends it anyway, without prompting the user for confirmation. I think that’s wrong; I think it should abort the send with an error message instead. Doing the silent fallback the way it does now could cause unexpected data to be sent to (possibly production) queues, and is a potential source of error.

c) None of these file formats look like they're actually the “set of exported messages” format.

If you agree with my analysis here, I’ll give it a go. Two possible fixes:

1) The cheap-and-easy way is to just add another “Exported message set” file format, and have the current file-reading logic use that when it loads a file for sending.

2) The nicer way (IMHO) is to add another sub-tab next to the Message / Files / Generator subtabs to act as a “blotter” for deserialized messages. You’d be able to load the exported messages from a previously-saved file to this tab and it would show a list of all the individual messages, and then you’d hit Start to actually fire them all off into the queue.

**Comment by iamkarlson** [comment]
hi @apjanke 
I would personally prefer first approach. Cause I would seek for the files import in the files tab. Nonetheless, second option is also good. It clearly says what it does. It would be eaiser for everyone to see "Re-import messages" tab or whatever. 

However, I don't have a lot of experience in the UX so it's totally up to you which way to go.

**Comment by PingPongSet** [comment]
I have the same problem sending the message in JSON exported via Save Selected Message within ASBE.

**Comment by paolosalvatori** [comment]
Hi @iamkarlson, @apjanke, @PingPongSet the "send file" option only reads the content of the message body from file, it was not meant to read all the message properties from a a message exported in JSON fromat to file with the Save Selected Message. This is not a broken feature, it was never meant to this way :) If you have bandwidth, please create and submit a PR. Meanwhile, I'm closing this issue. Thanks!
