### ISSUE TITLE
Failure creating Event Hub in existing namespace: Forbidden

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#327]
I'm having trouble creating a new Event Hub in an existing Service Bus namespace using SBE.

I have an existing ASB namespace “mrtl-rma-test-01” that contains a Queue and a Topic. I've connected successfully to it using the default RootManageSharedAccessKey.

I tried to create an Event Hub by right-clicking on the Event Hubs node in the navigation tree, selecting Create Event Hub, putting “mrtl-rma-test-eventhub-01” as the Relative URI, and clicking the Create button in the lower left.

SBE froze for a bit over 30 seconds, and then displayed some error messages in the log.

```
<12:29:56> The files C:\Users\NY510094\AppData\Roaming\Service Bus Explorer\UserSettings.config and C:\Users\NY510094\local\repos\ServiceBusExplorer\src\ServiceBusExplorer\bin\Debug\ServiceBusExplorer.exe.Config are used for the configuration settings.
<12:30:00> The application is now connected to the sb://mrtl-rma-test-01.servicebus.windows.net/ service bus namespace.
<12:30:00> MessagingFactory successfully created
<12:30:02> The queue rma-pricing-requests has been successfully retrieved.
<12:30:03> The topic rma-pricing-notifications has been successfully retrieved.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:823b965b-c281-40e6-9ca4-cb8e8b221c1d, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:36:55 PM. Method <CreateEventHub>b__0: retry 1 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:4cdb9b33-5321-47a4-b8cd-8a4a5f40816e, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:36:58 PM. Method <CreateEventHub>b__0: retry 2 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:b3a2076d-5c38-4092-a66f-411e934f7b42, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:00 PM. Method <CreateEventHub>b__0: retry 3 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:34bb3a36-b1d7-4af8-8489-cb1ab0a3d5e7, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:03 PM. Method <CreateEventHub>b__0: retry 4 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:92475651-b846-490c-ac79-655dcb90cadb, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:06 PM. Method <CreateEventHub>b__0: retry 5 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:b3988ad8-5367-4761-ac74-42371aaf4bcc, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:08 PM. Method <CreateEventHub>b__0: retry 6 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:12e87477-0bbd-4760-a551-8d9013e96786, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:11 PM. Method <CreateEventHub>b__0: retry 7 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:472ea391-446c-4e83-86a1-fbaf9627cadd, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:13 PM. Method <CreateEventHub>b__0: retry 8 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:cb02c886-f73a-416b-8c89-4bd0d97b5c54, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:16 PM. Method <CreateEventHub>b__0: retry 9 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:00eeb0aa-7970-4ffe-89ad-dc8abe6d69bc, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:19 PM. Method <CreateEventHub>b__0: retry 10 of 10.
<12:37:21> Exception: The remote server returned an error: (403) Forbidden. TrackingId:aebb2b0f-f2b9-4873-ae64-98b9a6d31c28, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:mrtl-rma-test-eventhub-01, Timestamp:3/14/2019 4:37:21 PM
<12:37:21> InnerException: The remote server returned an error: (403) Forbidden.
```

Is this expected to work? When I look at Event Hubs in the Azure Portal web page, it looks like they exist in separate namespaces from the ASB Queues and Topics. For example, they're a separate "service" from the main Service Bus service. And when I create an Event Hub in the Portal, it won't allow me to reuse the same namespace that's already in use for a Queues and Topics namespace.

A couple usability issues besides the failure itself:

* The UI froze for over half a minute, with no indication that it was working on anything.
* While the exception timestamps indicate they came in over the course of 30 seconds, the log entries for them weren't written until the end of the process.
* A 403 Forbidden error isn't typically expected to go away over time, so should SBE really be doing those retries?

**Comment by apjanke** [comment]
Yeah, I think the issue is that Namespaces for Queues/Topics, Event Hubs, and Relays are different kinds of namespaces, and can only contain their appropriate type of entity.

I created a new Event Hub namespace in Azure Portal, connected to it with SBE, and created a new Event Hub there, and it worked. Then I tried to create a Queue in that namespace, and got basically the same error as before:

```

<13:01:34> The files C:\Users\NY510094\AppData\Roaming\Service Bus Explorer\UserSettings.config and C:\Users\NY510094\local\repos\ServiceBusExplorer\src\ServiceBusExplorer\bin\Debug\ServiceBusExplorer.exe.Config are used for the configuration settings.
<13:02:10> The application is now connected to the sb://mrtl-rma-eventhub-test-01.servicebus.windows.net/ service bus namespace.
<13:02:10> MessagingFactory successfully created
<13:02:53> The event hub test-hub-01 has been successfully retrieved.
<13:03:04> 2 partitions for the event hub test-hub-01 have been successfully retrieved.
<13:03:04> 1 consumer groups for the event hub test-hub-01 have been successfully retrieved.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:1194f199-badb-46f4-a288-21aa83183b99, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:13 PM. Method <CreateQueue>b__0: retry 1 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:2ddef03c-3847-49f9-be1b-ed507c07543d, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:16 PM. Method <CreateQueue>b__0: retry 2 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:168d1621-a2dd-4e03-9345-599fd16deb74, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:18 PM. Method <CreateQueue>b__0: retry 3 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:25d17f74-419e-4482-8381-7da466fc2c05, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:21 PM. Method <CreateQueue>b__0: retry 4 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:2c949c0b-1c65-4447-abcf-231b0322590b, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:24 PM. Method <CreateQueue>b__0: retry 5 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:26c14729-9bd0-45bf-a695-678d95fca85f, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:26 PM. Method <CreateQueue>b__0: retry 6 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:c866f718-fb76-4e01-9541-74f2b133fcba, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:29 PM. Method <CreateQueue>b__0: retry 7 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:67018b24-5785-4f0d-9ab1-621b2015ce4d, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:32 PM. Method <CreateQueue>b__0: retry 8 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:0cc9b025-25a5-4d3c-b3eb-3aae8a9f6d20, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:34 PM. Method <CreateQueue>b__0: retry 9 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:62c55004-8888-4b70-955a-b78988d37680, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:37 PM. Method <CreateQueue>b__0: retry 10 of 10.
<13:06:39> Exception: The remote server returned an error: (403) Forbidden. TrackingId:f6923809-c55e-46e1-8a4e-f9ac7bd62e18, SystemTracker:mrtl-rma-eventhub-test-01.servicebus.windows.net:my-stupid-test-queue, Timestamp:3/14/2019 5:06:39 PM
<13:06:39> InnerException: The remote server returned an error: (403) Forbidden.
```

Is there a way SBE could detect what kind of Namespace it's connecting to, and only enable the creation controls for the appropriate entity types for that namespace?

**Comment by ErikMogensen** [comment]
Microsoft changed the way namespaces work about two years ago. Namespaces created before that may contain all four kinds of entities, but newer namespaces are limited to one kind as you noticed,

I do not think it possible to determine if is an old or new namespace. In the new Service Bus client there is support for determining which kind of entity a namespace is using but I don't know how it reacts when querying an old, mixed namespace. Service Bus Explorer is still using the old Service Bus Client. We do want to move to new one.

> The UI froze for over half a minute, with no indication that it was working on anything.
While the exception timestamps indicate they came in over the course of 30 seconds, the log entries for them weren't written until the end of the process.

That is something that would be great if it was fixed.,, 

> A 403 Forbidden error isn't typically expected to go away over time, so should SBE really be doing those retries?

You are most likely correct. The new Service  Bus Client has more structured exceptions which makes it easier to determine the right kind of action.

**Comment by apjanke** [comment]
Okay, that makes sense.

> That is something that would be great if it was fixed.

I'll have a look at the code and see if it's something I could help with.

The new Service Bus Client – is that the Microsoft.Azure.ServiceBus client discussed in #284? Is it mature enough to start using now/soon?

> I don't know how it reacts when querying an old, mixed namespace

Looks like there's a [`NamespaceType.Mixed` enum](https://github.com/Azure/azure-service-bus-dotnet/blob/283a45e82dfd3245611d9c136dfc01cf1bac699b/src/Microsoft.Azure.ServiceBus/Management/NamespaceType.cs#L16-L20) to indicate those.

> The new Service Bus Client has more structured exceptions which makes it easier to determine the right kind of action.

Ah, yep. I see an [`IsTransient`](https://github.com/Azure/azure-service-bus-dotnet/blob/283a45e82dfd3245611d9c136dfc01cf1bac699b/src/Microsoft.Azure.ServiceBus/ServiceBusException.cs#L72-L76) indicator there.

**Comment by ErikMogensen** [comment]
Thankful for your help. 

Yes, that is the one in #284 

Great to see that there is a Mixed enum at least.

**Comment by apjanke** [comment]
I'm looking at `MainForm.cs` in the Design view in Visual Studio 2017, and I don't see a MenuStrip for Event Hubs, even though I see one for everything else in the navigation tree. Am I missing something?

![ngakceboghbodcbj](https://user-images.githubusercontent.com/2618447/54389657-ff034380-4676-11e9-8dbd-549bc4cfd28b.png)

**Comment by apjanke** [comment]
Okay. I think there's a quick partial fix for this. The retry logic in `RetryHelper` already has some logic to distinguish transient from non-transient exceptions. It checks `MessagingException`s to see if they're transient, and treats all `MessagingEntityAlreadyExistsException`s and `CommunicationException`s as non-transient.

```
                try
                {
                    action(); 
                    return;
                }
                catch (MessagingEntityAlreadyExistsException)
                {
                    throw;
                }
                catch (CommunicationException)
                {
                    throw;
                }
                catch (MessagingException ex)
                {
                    if (numRetries == 0 || (!ex.IsTransient))
                    {
                        throw;
                    }
                    writeToLog([...]);
                    Thread.Sleep(retryTimeout);
                }

```

The problem happening with this Event Hub creation is that the exception thrown by the failed creation in the wrong type of Namespace is a `Microsoft.ServiceBus.Messaging.QuotaExceededException`. And there's no specific `catch` clause for `QuotaExceededException`, so it falls down to the generic `catch (Exception ex)` clause. And the generic clause treats all unknown exceptions as transient.

```
                catch (Exception ex)
                {
                    if (numRetries == 0)
                    {
                        throw;
                    }
                    writeToLog([...]);
                    Thread.Sleep(retryTimeout);
                }
```

I'm writing a fix that will specifically catch `QuotaExceededException` and treat it as non-transient. I think that's fair, since that error is unlikely to go away unless you use a different management function to remove an existing item, or change your Pricing Tier, or something that will require action besides just waiting. (The case of other admins concurrently changing quota-affecting stuff can be ignored here, I think.)

That will cut the freeze time down from 30 seconds to just a couple seconds, which is a lot more acceptable.

I think you could go one further, though: Maybe the generic `Exception` catch clause should consider unknown exceptions to be non-transient, and not retry on them. What do you think?

**Comment by apjanke** [comment]
I did a PR #330 that partially fixes this by special-casing `QuotaExceededException` to be considered non-transient. It doesn't go all the way and change generic `Exception` to be non-transient, though. I'm being conservative.

That only partially fixes this problem, though. The UI still freezes for a few seconds with no indication of what it's doing. And Relay creation still freezes for 30 seconds. I think the next step is to put up a progress bar to let the user know some work is actually happening, and the UI didn't encounter an internal error.
