### ISSUE TITLE
Error When Create Consumer Group Listener

### ISSUE THREAD

**Issue by wingfeng** [paolosalvatori/ServiceBusExplorer#33]
I got an exception:"Index out of range exception" when I click the "Create Consumer Group Listener"Right click Menu item for the eventhub.
That exception throw out from PartitionListenerControl.cs line 627 in function calculateLastColumnWidth .the first tow time enter this funtion "dataGridView.ColumnCount" is equal to zero. 
so I chang the code like this:
 if (dataGridView.ColumnCount > 3)
                {
                    var columnWidth = width / 4;
                    dataGridView.Columns[0].Width = columnWidth;
                    dataGridView.Columns[1].Width = columnWidth;
                    dataGridView.Columns[2].Width = columnWidth;
                    dataGridView.Columns[3].Width = columnWidth + (width - (columnWidth * 4));
                }
It is work for me now！

**Comment by SeanFeldman** [comment]
@wingfeng would you like to submit that as a PR?
