### ISSUE TITLE
When resubmitting a block of messages all the properties are lost 

### ISSUE THREAD

**Issue by mrpmorris** [paolosalvatori/ServiceBusExplorer#339]
Same as issue #84 

This is now ocurring in 4.1.112

**Comment by ErikMogensen** [comment]
Moving the latest discussion from #84 to here.

mrpmorris wrote:
> @ErikMogensen
> 1: Go to Dead Letter Queue
> 2: Peek 999
> 3: Sort by date (descending)
> 4: Right-click (Repair and resubmit)
> 5: Format = string, Generate a new ID
> 6: Select the same queue and submit it
> 7: (I think the resubmit window stays open here, if I recall correctly then close it so the queues refresh)
> 
> It's possible that the contents only appear as a null string. I think I saw valid data in my logs once but the dead-lettered message appeared to be blank in the UI.

@mrpmorris , that works for me. To my surprise the DeadLetter properties were also copied which I did not think was possible.

I wonder if this could have to do with the content of the messages. Please try again just using plain strings as message content. As you probably know you can easily create a lot of messages by right-clicking a queue and select Send messages.

**Comment by paolosalvatori** [comment]
Hi @mrpmorris, I'm closing the issue, please reopen it if Erik trick does not work for you, or please submit a PR. Thanks
