### ISSUE TITLE
Add ability to set queue/subscription to ReceiveDisabled (and SendDisabled)

### ISSUE THREAD

**Issue by rob-hendrickx-c4t** [paolosalvatori/ServiceBusExplorer#340]
It would be very handy to be able to set a queue to ReceiveDisabled from the ServiceBusExplorer. If the SendDisabled state is also added, a queue can be set to any state from within the SB Explorer.

**Comment by paolosalvatori** [comment]
Hi @rob-hendrickx-c4t can you please clarify your request eventually with some pictures? Thanks

**Comment by rob-hendrickx-c4t** [comment]
> Hi @rob-hendrickx-c4t can you please clarify your request eventually with some pictures? Thanks

Sure thing. 
As you may know, an entity in ServiceBus can have different states as described here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus?view=azure-dotnet. Currently, the ServiceBusExplorer allows the user to enable/disable a queue or topic subscription. 

In our usage of Azure Service Bus, we sometimes set an entity to the status ReceiveDisabled, so we can keep posting messages on a queue/topic, but pause the receiver for a while. It would be handy to be able to do this from within the ServiceBus explorer. Therefor, I request to replace the following actions:

- Enable queue
- Disable queue
- Enable subscription
- Disable subscription

with the **Change status** action, which could open a popup with a dropdown with following values:

- Enabled
- Disabled
- ReceiveDisabled
- SendDisabled
. 
(With exception of the status that's currently set of course).

This would look somewhat like the below:
![image](https://user-images.githubusercontent.com/38980805/59446709-4f1ead00-8e02-11e9-9fc1-7b9032fac875.png)

Let me know if you have any additional questions.
