### ISSUE TITLE
UI becomes unresponsive after removing subscription rule.

### ISSUE THREAD

**Issue by ikondrasovas** [paolosalvatori/ServiceBusExplorer#341]
I am experiencing an issue where I cannot remove the default rule that is created for my subscriptions.

When I right-click the rule and then remove, the UI becomes irresponsible. No error, anything happens. After some minutes I received a socket timeout:

<14:13:45> InnerException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:38.2657106'.

Is this a supported operation in ServiceBusExplorer?

I can successfully create topics, subscription, etc.

I tried with the version in develop and also from the latest tagged release.

Thanks,

Igor

**Comment by SeanFeldman** [comment]
Removing rules is a supported operation.
The exception indicated communication issue.
Have you tried it with a different namespace or from a different network to see if there's any difference?

**Comment by paolosalvatori** [comment]
Hi @ikondrasovas I'm closing the issue, feel free to reopen it if you still face the same problem.
