### ISSUE TITLE
when resubmitting messages (bulk) from DLQ to a new queue, sequence of messages is not maintained

### ISSUE THREAD

**Issue by dsingh0007** [paolosalvatori/ServiceBusExplorer#342]
When submitting the DLQ messages to another queue, the messages are randomly pushed to the new queue. Can we please apply a ordering based on created datetime when these are submitted to the new queue. 
This is especially helpful when we have data dependent on another messages in the queue.

**Comment by SeanFeldman** [comment]
@dsingh0007 I haven't had a chance to look into the code, but sending message in order is not something that can be easily guaranteed. If a sending operation is failing, it would be retried by the client while another send operation succeeds.

Personally, I would not rely on a message order. Are you using queues with sessions in your solution?

**Comment by dsingh0007** [comment]
I am not using sessions (not sure how that will play out).

We are using it for integrating D365 F&O with a third party s/w and will have dependencies on the records.

An example would be a customer and its transactions.
If customer creation itself went into deadletters, all customer transactions will also go to deadletters.

Now when i want to resubmit the deadletters, i would like the customer creation be sent as the first message in queue.

Hope this helps.

**Comment by ErikMogensen** [comment]
Browsing the code for resubmitting messages in DeadLetterMessageHandler.cs and HandleQueueControl.cs it seems to be single threaded and keeping order. I also tested this and it the kept the same order as they were put on the queue.

1. Do you want the messages to be in another order than they are in the queue?

2. Are you getting any error messages?

3. Do you do the resubmit multiple times or just one?

**Comment by dsingh0007** [comment]
I think i messed up in my testing (although i tried it multiple times before raising it).
Sorry for the trouble.

1) Nope, order is fine, FIFO.
2) Nope, Have resubmitted the messages (selected multiple messages in deadletter queue and resubmit) 
   and checked it in the new queue. (was pretty sure it was not in order 2 days ago but i think i messed something here. seems to be working fine)
3) Yes, tried that multiple times.

**Comment by ErikMogensen** [comment]
Thanks for confirming!
