### ISSUE TITLE
Enable configuring proxy configuration from the Options dialog

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#343]
Configuring the proxy is a recurring issue and it is not easy to configure it as currently the only way to do this by changing the application configuration file, see #25 and #204.

Adding to the burden is it that the changes will be overwritten every time a new version is installed. The same thing happens if you change the app.config file as it is part of the source code and the proxy configuration changes should not be put in the repository.

Therefore it should be possible to store the proxy settings in the user configuration file.

**Comment by paolosalvatori** [comment]
@ErikMogensen are you going to submit a PR to solve this issue?

**Comment by ErikMogensen** [comment]
Yes, I intend to do that. When I start working on it I'll assign it to me. So until then it is open for anyone else to implement this.

**Comment by paolosalvatori** [comment]
Sounds good mate :)

**Comment by ErikMogensen** [comment]
Fixed in #434

**Comment by SeanFeldman** [comment]
@paolosalvatori, @ErikMogensen, this hasn't been released so I added a milestone to indicate where this change will appear.
I think we should release everything that is currently staged on the develop branch.

**Comment by ErikMogensen** [comment]
I agree. Since output from the develop branch is not backwards compatible (protocol and .NET version) I think the new release should be called 5.0.0.

**Comment by SeanFeldman** [comment]
Ah, forgot about it. Go for it 👍

**Comment by paolosalvatori** [comment]
Sorry for the delay, but I was quite busy in this period. Feel free to create a new release guys :)
