### ISSUE TITLE
Version checker

### ISSUE THREAD

**Issue by rajrao** [paolosalvatori/ServiceBusExplorer#345]
Would be nice if ASB Explorer would automatically check for latest version and tell me if a new version is available. As a later update, it would be nice if it would also auto-update. I want to try and add the versioning support and so want a simple issue to track

**Comment by rajrao** [comment]
I was hoping to use https://api.github.com/repos/paolosalvatori/ServiceBusExplorer/releases/latest to get the latest version and compare it to the apps version. But it looks like the API endpoint cannot be called without authentication. Any ideas?

**Comment by SeanFeldman** [comment]
I was able to invoke the link in incognito mode.

**Comment by rajrao** [comment]
Yeah, thats why I was hopeful. But when I tried it via httpClient it failed. Looking at fiddler, GitHub provides some cookies that I think allows it to work. Still looking.

**Comment by rajrao** [comment]
Figured it out, when calling from code, api.github.com needs one to send the "User-Agent" header. Otherwise it returns a 403: Forbidden error.

**Comment by SeanFeldman** [comment]
If not mistaken, to use any of GitHub API, user agent header must be present. Good luck 🙂

**Comment by rajrao** [comment]
Here is what I was thinking, 

1. have a user setting that allows user to set number of days to check for new version check.
2. Default it to 30 days (0 would be never check)
3. When a new version is detected - notify user via a dialog and give them a link to GitHub releases page.

In the future, make it so, it will download and update automatically.

What do you think?

**Comment by SeanFeldman** [comment]
Sounds good.

**Comment by ErikMogensen** [comment]
Very good. However I assume we will need a installation program, preferably packaged as an MSI for the automatic updating.

**Comment by SeanFeldman** [comment]
> As a later update, it would be nice if it would also auto-update. 

Separate issue.

**Comment by paolosalvatori** [comment]
Interesting idea, I'm going to merge your PR
