### ISSUE TITLE
Where in the Azure portal does one find the settings described in the new connection dialog?

### ISSUE THREAD

**Issue by StingyJack** [paolosalvatori/ServiceBusExplorer#346]
I'd really like to try this, but I cant figure out what it wants for connection info. Where would I be able to find the minimal config details needed to connect to a single service bus queue and view the contents?

**Comment by SeanFeldman** [comment]
File --> Connection

In the Service Bus Namespace dropdown, select "Enter connection string..." and paste it on the right side of the modal window.

![image](https://user-images.githubusercontent.com/1309622/57248725-5206d080-7000-11e9-9fc3-d0a74ca737c3.png)

**Comment by StingyJack** [comment]
Yes, paste _what_ though?  

I don't see connection strings on any of the service bus blades or service bus queue blades.

**Comment by SeanFeldman** [comment]
@StingyJack connection string is something you'll find in the portal or could use Azure CLI to find out.
Quick search brings this up: https://social.msdn.microsoft.com/Forums/en-US/c8edd9b5-76ea-4d93-8025-2e9d90b5ddf4/where-to-find-the-connectionstring-in-the-new-service-bus-portal?forum=servbus
