### ISSUE TITLE
Deprecation of Service Management support for Azure Service Bus, Relay and Event Hubs

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#348]
As mentioned in https://blogs.msdn.microsoft.com/servicebus/2018/11/01/deprecating-service-management-support-for-azure-service-bus-relay-and-event-hubs/ Microsoft will deprecate the support for using Service Management for Azure Service Bus, Relay and Event Hubs in October 2019. 

As far as I can tell ServiceBusExplorer is not using any Service Management APIs, but it would be better if someone else also confirmed this.

**Comment by paolosalvatori** [comment]
Yep, it doesn't. Thanks @ErikMogensen :)
