### ISSUE TITLE
Trying to connect gives error, "An item with the same key has already been added."

### ISSUE THREAD

**Issue by jaltenbernd** [paolosalvatori/ServiceBusExplorer#35]
I enter either my SAS or ACS into the Connection String, hit Connect, and always get this error. Clear the log and I still get it.

**Comment by SoumyaN** [comment]
Was this issue resolved? I see the same exception when trying to connect using SASConnectionString. I have been able to connect fine in the past. Seems like it happens randomly.

**Comment by SoumyaN** [comment]
I am running Service bus explorer on Parallels on Mac. I tried closing Service bus explorer app and reopening and trying to open a connection, but it still gives me the error "An item with the same key has already been added."

**Comment by SoumyaN** [comment]
To add, it works fine with ACSConnectionString. I face this issue only with SASConnectionString.

**Comment by ErikMogensen** [comment]
Are you sure? ACS was supposed to be turned off the 4th of February this year.

**Comment by ErikMogensen** [comment]
Closed as there hasn't been any response for more than a month.

**Comment by magosb** [comment]
I am also having this problem now. Also on parallels on mac. Does anyone know how this can be solved?

**Comment by ErikMogensen** [comment]
@magosb , please make sure you are using the latest release which was released in May, https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.1.112. Don't look at the version number. 

If you are able to reproduce the issue on the latest version please provide more information about your config file settings. Which config file are you using and what are existing entries for connections? Just send the config keys, not the value part which contains the connection string.

Please provide the log also.
