### ISSUE TITLE
Create IoT Hub Listener - Failing with Current Implementation

### ISSUE THREAD

**Issue by vpunugupati** [paolosalvatori/ServiceBusExplorer#351]
I tried to create IoT Hub Listener using Service Bus Explorer. It is not working and also confusion of extra parameter "End Point" what value need to be used. Even using Default Value populated also not working. Only way, It is working if I change the code to use 
CreateFromConnectionString(String) and provide Event Hub compatible End Point. This ignores the value of "End Point". May be , I am misunderstanding the current implementation. Some one suggest me what details need to be supplied to use SB explorer for IoT Hub.

**Comment by paolosalvatori** [comment]
Hi @vpunugupati you need to enter the connection string in the proper way. As a reference, please search for IoT Hub under https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/docs/documentation.md
