### ISSUE TITLE
Ability to specify ScheduledEnqueueTimeUtc message property when bulk re-submitting messages

### ISSUE THREAD

**Issue by ShaneCourtrille** [paolosalvatori/ServiceBusExplorer#352]
So there are a few different ways I could see this happening...

1. Being able to bulk modify Message Properties when you have 2+ selected..

2. "Repair and Resubmit Message" dialog could have a Message Properties panel with value of 'Use Existing' which could be overwritten with a new value that would be applied to all messages.

**Comment by paolosalvatori** [comment]
Hi @ShaneCourtrille in the past I had a similar idea, but then I didn't have time to implement this feature. Would you be able to submit a PR?

**Comment by ShaneCourtrille** [comment]
I may be able to find the time.  Let me take a look.  Is there a specific
way you think it should be done?  I'm thinking option 2 probably makes more
sense

**Comment by paolosalvatori** [comment]
Thanks @ShaneCourtrille I agree with you on option 2. @SeanFeldman @ErikMogensen @tomkerkhove?

**Comment by ErikMogensen** [comment]
Also agree on option 2.
