### ISSUE TITLE
My SBE appears to be confused about a Queue

### ISSUE THREAD

**Issue by eugen-nw** [paolosalvatori/ServiceBusExplorer#353]
I updated to the latest version - 4.1.113 - and I am still seeing these problems.  I checked the Queue in the Azure Portal and it lists 3 messages in the DLQ and 0 for all other counts of messages.

As for SBE:
1.  it shows 3 messages as being in the DLQ, yet peeking at the DLQ messages returns 0.
2.  peeking at regular messages returns all 3 of them.
3.  purging regular messages reports that 0 messages have been purged.
4.  purging the DQL messages takes forever - 364539 milliseconds - and does nothing: reports  that 0 messages have been purged.

![image](https://user-images.githubusercontent.com/15199814/58667463-f374ff80-82ea-11e9-8057-f1be224e9415.png)

**Comment by SeanFeldman** [comment]
Just for verification, can you delete the queue and re-create it, dead-letter a few messages and see if the behavior you see now is reproducible? Thanks.

**Comment by eugen-nw** [comment]
Hi Sean,


Thanks very much for having looked into this issue!

I can easily foresee that on a _new_ queue everything will work great.  The problem is that replacing Queues that operate in production is a rather costly endeavor, especially if we'll need to do it on some schedule.  Could you please suggest how we should go about diagnosing what may have gone wrong with this particular Queue and how to fix it?  On the Azure Portal the Queue looks good, there were neither warnings nor actionable items.


Thanks very much,  Eugen

**Comment by ErikMogensen** [comment]
Use Service Bus Explorer and change a property for the queue such as Batch operations and then update the queue. Change the property back and update again. That will recreate the backend for the end.

Is it a partitioned queue?

**Comment by eugen-nw** [comment]
Thanks very much Erik, your trick got my Queue back to its senses.

Yes it is a partitioned Queue.  Why were you asking please?

**Comment by SeanFeldman** [comment]
Partitioned queue sources messages from different servers. Non-partitioned queue doesn't. It could be the issue with the count (assumption).

Updating or re-creating an entity forces a refresh on the broker side of things.

**Comment by ErikMogensen** [comment]
@eugen-nw , the reason I asked was that I think this happens more often on partitioned queues as they utilize 16 message brokers whereas non-partitioned only use one.
