### ISSUE TITLE
Unable to forward dead letter messages to Queue

### ISSUE THREAD

**Issue by PriaReddy** [paolosalvatori/ServiceBusExplorer#356]
Hi,
We have an issue with forwarding the dead letter messages from our Topic to a Queue. It was all working well until last week and now it doesn't forward at all to the queue.
Azure Service bus  version - 4.1.112

The Queue is used only by my team and solely used for replaying DLMs

Steps to reproduce:
1. Set the subscriptions "Forward Dead Letters Message To" a specified Queue
2. Update
3. Refresh the ASB couple of times (until you see messages from topic will be decreased and added to Queue)

Expected Result: Messages should be forwarded to Queue
Actual Result: No messages are forwarded to queue and stays in subscription
Log: subscription for the topic has been successfully updated.

**Comment by ErikMogensen** [comment]
This may be a timeout issue, see #420. Does it still happen if you increase the timouts?
