### ISSUE TITLE
Save message body

### ISSUE THREAD

**Issue by evilbaschdi** [paolosalvatori/ServiceBusExplorer#358]
Is it possible to just extract and save the body of a message without all other properties of the brokered message as a binary file?

**Comment by paolosalvatori** [comment]
Well, we should implement this feature. Not sure I've enough bandwidth for this. Would you mind creating a PR for this feature?

**Comment by evilbaschdi** [comment]
In case I find some time :-D I'll maybe can have a look on it in a few weeks.

**Comment by paolosalvatori** [comment]
Thanks @evilbaschdi

**Comment by evilbaschdi** [comment]
gonna last another two weeks until I maybe find some time in my summer vacation.

**Comment by evilbaschdi** [comment]
I just forked the repo. In which branch should I work / push once I'm done?

**Comment by SeanFeldman** [comment]
You should target `develop`.

**Comment by evilbaschdi** [comment]
https://github.com/evilbaschdi/ServiceBusExplorer/tree/feature/ExtractBodyAsFile

current state in case you want to have a look into it before a pull request.
done:
- extended context menus for single and bulk message save
- added save logic to save a single message as .txt (default)
- added save logic to save bulk messages as (number of file).txt (default)

open:
- recognize file content to maybe save "word documents" as "doc/docx" or "zip" as "zip"

**Comment by SeanFeldman** [comment]
@evilbaschdi thank you for your work.
There's an ongoing parallel effort to split the code into several smaller project and I wanted to make sure that your effort is coordinated with @ErikMogensen.

**Comment by evilbaschdi** [comment]
@SeanFeldman no problem
@ErikMogensen how is it going? I just had quick a look into your "split" branch. what I did so far was to add some menu entries. In which project are they located now?

From my perspective there have not been so many changes, yet. I've add 6 new menu entries + handlers + respect them in the "hide logic" to only make them visible when it's needed.
So it is no bigger problem to move that code to the new solution structure in case it's nearly done.
On the other hand the work here might just have started It maybe makes more sense to push my work into the current "develop" branch.
What do you think might be the better solution?

**Comment by ErikMogensen** [comment]
@evilbaschdi , I just finished and requested @paolosalvatori to review the changes I have done. 

Depending upon that review this may or may not take some time. Since QueueControl is not moved and only has non-GUI changes so far in the restructuring work I suggest you push to the current develop branch.

**Comment by paolosalvatori** [comment]
@evilbaschdi, @ErikMogensen, @SeanFeldman I will look at the new code ideally by the end of this week, surely by the end of this month, so please try to ping me in one/two week!

**Comment by ErikMogensen** [comment]
@evilbaschdi , this can be closed, right?

**Comment by evilbaschdi** [comment]
since I din't even know this is still open ... yes, can be closed :-)
