### ISSUE TITLE
Plugin Engine

### ISSUE THREAD

**Issue by evilbaschdi** [paolosalvatori/ServiceBusExplorer#359]
Do you plan to provide the possibility of writing plugins?
Since we compress our messages to not border queue limits we have to decompress messages first. So it might be nice to do this by a plugin directly via context menu of a message.

**Comment by SeanFeldman** [comment]
@evilbaschdi are you compressing messages using https://github.com/SeanFeldman/ServiceBus.CompressionPlugin or custom code?

**Comment by evilbaschdi** [comment]
Currently I'm using custom code, since I did not know the solution you've provided.
But I took a look inside the code and it seems it's doing similar things with help from gzip.

Maybe I'll give it a try tomorrow and than give feedback.

**Comment by SeanFeldman** [comment]
The plan for SBE is to move it to the new .NET client, which supports plugins. SBE could support a mechanism to specify what plugins to use to take advantage of ServiceBus.CompressionPlugin, and other plugins (https://github.com/Azure/azure-service-bus-dotnet-plugins)

**Comment by evilbaschdi** [comment]
Sounds good.

**Comment by paolosalvatori** [comment]
Hi @evilbaschdi, the current version already provides the ability to extend the tool with plugins called message inspectors in external libraries deployed in the same folder as SBE. In this case, you have to define the fully qualified name of the class in the configuration file of the tool. Actually, the tool already provides a tool to zip and unzip messages, respectively, before sending and after receiving a message. For more information, serach for ZipBrokeredMessageInspector in the tool documentation at https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/docs/documentation.md.

**Comment by ErikMogensen** [comment]
Closing this since the current support for plugins seems to be enough.
