### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#36]
Functionality is added to the project, but having no tests to confirm if change is a breaking change or not is hindering potential contributors will to make contribute.

This is not a trivial task with an existing code base, but at least having a test project would help. Adding some more trivial tests (such as a test for [`ConversionHelper`](https://github.com/paolosalvatori/ServiceBusExplorer/issues/34)) could be a start.

Thoughts @paolosalvatori ?

**Comment by paolosalvatori** [comment]
Sorry for the delayed answer! Feel free to send me an email with more details.

**Comment by SeanFeldman** [comment]
done
