### ISSUE TITLE
Adding "Cancel Scheduled message" feature

### ISSUE THREAD

**Issue by aliqaryan2** [paolosalvatori/ServiceBusExplorer#360]
https://docs.microsoft.com/en-ca/dotnet/api/microsoft.azure.servicebus.queueclient.cancelscheduledmessageasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_QueueClient_CancelScheduledMessageAsync_System_Int64_

**Comment by SeanFeldman** [comment]
@aliqaryan2 given it's a brand new feature, please provide how you'd see it working / mocks. Thanks.

**Comment by aliqaryan2** [comment]
https://docs.microsoft.com/en-ca/dotnet/api/microsoft.azure.servicebus.queueclient.cancelscheduledmessageasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_QueueClient_CancelScheduledMessageAsync_System_Int64_

**Comment by harry-gordon** [comment]
Would be interested in seeing this feature too. My use case is that I sometimes want to totally clear the scheduled messages (without deleting the queue) so maybe we could add a "Purge Scheduled Messages" option in the queue right-click menu?

**Comment by SeanFeldman** [comment]
@aliqaryan2 sorry I have missed your message. I wasn't asking about the API, rather how you'd see it working (UI/UX).

**Comment by SeanFeldman** [comment]
@harry-gordon this feature would much simpler to implement if the broker would support retrieving messages by their status (see https://github.com/Azure/azure-service-bus/issues/95).

W/o this feature, it means peeking **all messages** on the queue and cancelling those messages that are scheduled (have `State` set to `Scheduled`). Possible, but would mean some effort to be invested in the feature.

**Comment by SeanFeldman** [comment]
If anyone is interested to give this a go, please wait till #381 is completed.

**Comment by miqm** [comment]
@paolosalvatori - can this feature request be opened? There's a method on SDK to cancel and SB Explorer can view scheduled messages.

**Comment by SeanFeldman** [comment]
@miqm, the feature to [peek messages by status](https://github.com/Azure/azure-service-bus/issues/95) is still opened. What API in the SDK are you referring to? A link to the documentation would be helpful.

**Comment by miqm** [comment]
@SeanFeldman I'm referring to this method of Azure.Messaging.ServiceBus SDK: https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender.cancelscheduledmessageasync?view=azure-dotnet 

I agree, that getting only the scheduled messages would be nice but right now we can find one (by looking at it properties) and SBExplorer doesn't have option to cancel it.

I was able to write a simple dotnet console app where I provided sequenceNo obtained from the portal explorer and the message disappeared from the queue.

**Comment by miqm** [comment]
Basically I know it might not be effective now, but ineffective is better than none...

**Comment by SeanFeldman** [comment]
I don't have much to say other than if you care much for this feature, you could 
1. Up-vote the feature request to [peek messages by status](https://github.com/Azure/azure-service-bus/issues/95)
2. Contribute a PR for this tool

If you're up to this, I'll be happy to assist with the PR, @miqm.
