### ISSUE TITLE
Add filter to search Queues

### ISSUE THREAD

**Issue by dtejada2** [paolosalvatori/ServiceBusExplorer#363]
Add feature to search in the list of Queues, one of the biggest reazons I use this tool is because is really hard to search on azure portal, even it doesn't work properly on Azure portal.

**Comment by paolosalvatori** [comment]
@dtejada2 the tool already supports the functionality you are asking for. Open the Connect form and proceed as follows:

1. Select only Queues from the Selected Entities multichoice dropdownlist
2. Click the dotted button under Queue Filter Expression
3. Enter the name of the queue in the Enter Queue Filter Expression form
4. Click the OK button in the Enter Queue Filter Expression form
5. Click the OK button in the Connect form

This picture shows the step sequence:
![Ashampoo_Snap_2019 07 17_11h37m40s_008_](https://user-images.githubusercontent.com/1658419/61365383-ee164900-a887-11e9-936e-d2228c048d4e.png)

This picture shows the final result:
![Ashampoo_Snap_2019 07 17_11h38m25s_009_](https://user-images.githubusercontent.com/1658419/61365433-05553680-a888-11e9-93a0-9376919f0055.png)

Hope this helps.

**Comment by ErikMogensen** [comment]
Closing this since it seems to be solved.
