### ISSUE TITLE
Consider a multi tab UI for Queues, Topics, and Subscriptions (and others, probably)

### ISSUE THREAD

**Issue by erizzo** [paolosalvatori/ServiceBusExplorer#364]
With a SB instance that has "lots" (ie, dozens or hundreds) of Topics, Subscriptions, and Queues, the limitation of only being able to "inspect" one at a time is a usability problem. I often need to work with several different topics, subscriptions, and/or queues in rapid succession, switching back-and-forth between them, etc. It's difficult to do with a large number in the tree view.
If I could open a Topic or Queue "in a new tab" like browsers and many other dev tools do, I could easily keep a "working set" of ones that I'm interested in. What I'm envisioning is that the "details" side (right side) would be tabbed, and there would be a context menu option on the nodes in the tree view such as "Open in new tab." But I'm open to any kind of tabbed UI that would support inspecting multiple nodes at once.

**Comment by paolosalvatori** [comment]
Hi @erizzo what you describe is a limit of the filter syntax supported by the [NamespaceManager.GetQueues method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.getqueues?view=azure-dotnet). Yes, I could also implement the feature by making a client-side filter, but in this case, the tool should retrieve all the queues, topics, subscriptions and then apply this filter on the client-side. 
Now, I give you a trick to only retrieve a subset of queues. You can organize your entities in hierarchical order as follows:

- create a category or subset called for example calculator (see the picture below)
- create multiple queues called calculator/A, calculator/B, calculator/B etc.
- in the connect from select only the type of the entities you want to retrieve, for example, queues
- finally, specify a filter like Startswith(Path, 'calculator') Eq true

As shown in the following picture, the tool will only retrieve the queues which path starts with calculator and they will appear all under a folder called calculator. Remember that fully qualified name of a queue is sb://<namespace>.servicebus.windows.net/<queue> but the queue name can be a relative path like sb://paolosalvatori.servicebus.windows.net/calculator/requestqueue.
Hope this helps! @SeanFeldman @ErikMogensen 

![Ashampoo_Snap_2019 08 02_10h24m34s_003_Service Bus Explorer](https://user-images.githubusercontent.com/1658419/62356179-c58d8080-b510-11e9-9f84-ecc27a0ced88.png)

**Comment by erizzo** [comment]
I think there is some confusion. I'm not asking for a filter, I'm asking for multi-tabbed UI. Filtering is also a useful feature, but orthogonal to having multiple tabs open. My request can not be satisfied by using a filter, I need to be looking at several different topics/subscriptions/queues at the same time.
Like I said, compare it to a web browser or database browsing tool - I'm not forced to look at only 1 web site or database table at a time.

**Comment by paolosalvatori** [comment]
Understood @erizzo. In this case, we have two options:
- the easiest way is to open each queue, topic, subscription in a separate MDI form.
- we can create tabs, but in this case we need to understand what is the event that triggers opening a new tab: right click and open in new tab like in a browser? This implementation requires more effort than the previous one, because years ago I had to handle the UI of tabs manually.
