### ISSUE TITLE
Having difficulties seeing the contents of messages on the queue

### ISSUE THREAD

**Issue by hirowla** [paolosalvatori/ServiceBusExplorer#365]
I view a queue, press "Messages", choose peek (top 10), then choose a LogBrokeredMessageInspector.  The program sits for a while, then produces the following errors:
"<13:35:57> Exception: The server rejected the upgrade request."
"<13:35:57> InnerException: The server rejected the upgrade request."

Doesn't matter what I do, I always get those errors.

Any ideas on how I can see the contents of the messages in the queues? I know there is definitely messages on the queue.

**Comment by gabrielgt** [comment]
You do not really need to choose LogBrokeredBessageInspector to see the messages in the queue. What kind of content do the messages have? Does it work without choosing an inspector?

**Comment by paolosalvatori** [comment]
The LogBrokeredMessageInspector can be used to log messages to a file, but it's not necessary to see messages in the UI.

**Comment by hirowla** [comment]
Sorry about the delay in replying. All I want is to be able to see the messages in the GUI - and that I cannot do. I thought using the LogBrokeredMessageInspector was the way to do this - I'm guessing this is not the way.

As I said, what do I have to do to be able to see the contents of queued messages in the GUI?

**Comment by ErikMogensen** [comment]
What happens if you don't select any message inspector? 

Is the internet communication using a proxy at the place you are testing this?

**Comment by hirowla** [comment]
If I don't select any message inspector, I don't see any contents either.

It is definitely going through a proxy (a corporate proxy/firewall). Are there any ports which may be an issue if blocked?

**Comment by ErikMogensen** [comment]
If there is no firewall opening for the SBMP port, 9354, then you should configure ServiceBusExplorer to use a proxy. That is currently done by adding a entry to its config file. This is described at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration. It will look something like:

> <system.net>  
>     <defaultProxy>  
>         <proxy  proxyaddress="http://proxy.contoso.com:8080"  
>                 bypassonlocal="true"  
>         />  
>     </defaultProxy>  
> </system.net>

You also need to set the Connectivity Mode from the View -> Options dialog:
![image](https://user-images.githubusercontent.com/9644248/64074344-2348f000-ccaa-11e9-92df-6f145b57d5e6.png)
You may have to try different values. Start by setting it to AutoDetect, then https and lastly http.

I have planned to make this simpler by enabling setting the proxy configuration from within Service Bus Explorer,

**Comment by paolosalvatori** [comment]
@hirowla @gabrielgt @ErikMogensen closing the issue
