### ISSUE TITLE
NuGet package for IBrokeredMessageGenerator and IBrokeredMessageInspector

### ISSUE THREAD

**Issue by gabrielgt** [paolosalvatori/ServiceBusExplorer#369]
Hello,

I have implemented a custom BrokeredMessageGenerator in my own project. But I have had to reference ServiceBusExplorer.exe from my project to implement IBrokeredMessageGenerator, which is quite ugly.

I would like to create a NuGet package with both interfaces and reference it from ServiceBusExplorer. This way, anyone could create custom message generators referencing that package.

What do you think guys?

Thanks for your time!

**Comment by SeanFeldman** [comment]
The package is probably be better created under the project and posted to the NUget using Paulo's credentials. Similar to what's done with Chocolatey. 

Unless that's what you meant. In that case ignore my comment.

**Comment by SeanFeldman** [comment]
Keep in mind that @ErikMogensen has started project restructuring.

**Comment by paolosalvatori** [comment]
Hi  @gabrielgt the project started as a sample and then it became a monolithic app. As @SeanFeldman said, @ErikMogensen just started to break down the application into multiple assemblies, so we'll make sure to create an assembly that contains only the IBrokeredMessageGenerator,  IBrokeredMessageInspector, IEventDataGenerator, IEventDataInspector interfaces.

**Comment by gabrielgt** [comment]
> The package is probably be better created under the project and posted to the NUget using @paolosalvatori's credentials. Similar to what's done with Chocolatey.
> 
> Unless that's what you meant. In that case ignore my comment.

That it is, @SeanFeldman. I wanted to separate the interfaces in a new assembly and create the package, so you can upload it to NuGet as part of this project.

But now that I know that @ErikMogensen is restructuring the solution, I better wait 😃

**Comment by paolosalvatori** [comment]
Yes, @ErikMogensen broke down the monolithic app into multiple assemblies, that's the next big change that we plan to do soon, probably in a few weeks
