### ISSUE TITLE
Sending multiple messages to Queue via the tool

### ISSUE THREAD

**Issue by burf2000** [paolosalvatori/ServiceBusExplorer#371]
I am trying to send a message to the queue, a single message works but if I have an array of them it only sends 1 message.  Am I missing something?

[{
 "visitProcessId": "0f7c85d7-2c4e-4d83-ae35-dc34d03fd433",
 "taskContextId": "bc67b415-95f7-4834-b662-0edac94aa7a6"
},
{
 "visitProcessId": "0f7c85d7-2c4e-4d83-ae35-dc34d03fd433",
 "taskContextId": "bc67b415-95f7-4834-b662-0edac94aa7a6"
},
{
 "visitProcessId": "0f7c85d7-2c4e-4d83-ae35-dc34d03fd433",
 "taskContextId": "bc67b415-95f7-4834-b662-0edac94aa7a6"
}
]

**Comment by SeanFeldman** [comment]
You can. 

To send multiple messages, Right-click on the entity and select "Send Messages" in the context menu.

To create multiple messages you need to specify "Message Count" under the "Sender" tab. By default, it's set to one.

To send multiple messages with the same schema but different values, take a look at `ThreasholdDeviceIdBrokeredMessageGenerator` under the "Generator" tab. Under "Generator Properties" there are properties of the message you can control. You'll notice that `EventId`, `DeviceId, and `Value` properties are randomized.

You can have a look at the [implementation](https://github.com/paolosalvatori/ServiceBusExplorer/blob/ce77ecd7e6a69750035a8bdd6e11e94e6979879b/src/ServiceBusExplorer/Helpers/ThresholdDeviceEventDataGenerator.cs#L81) of `ThresholdDeviceEventDataGenerator` to create your own generator. Once you have a custom one, you can register it using app.config file under `brokeredMessageGenerators` section, similar to the pre-packaged generators. Let me know if that answers your question.

**Comment by SeanFeldman** [comment]
Note that this is also documented in https://github.com/paolosalvatori/ServiceBusExplorer/blob/master/docs/documentation.md. Perhaps not in the best way. If you'd like to send a PR to clarify the doco, please do 🙂

**Comment by SeanFeldman** [comment]
@burf2000 I'm going to close this issue as your question seems to be answered.
