### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by rkralston** [paolosalvatori/ServiceBusExplorer#372]
I'm getting "Can't process file Forms\XXXXXXX.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web..."

Any build instructions would be appreciated.

**Comment by ErikMogensen** [comment]
I assume you downloaded the zipped source. Unless you have made changes to the code I recommend you delete everything you downloaded and download the zipped souce again.

Then you right-click it in FIle Explorer and click Unblock. When that is done you extract the files and build them using a late version of VS 2017 or VS 2019.

As an alternative to the above you connect to the source on GitHub using a git client. That way it is easier to always have the latest source code. But it is more complicated.

**Comment by rkralston** [comment]
Yes, I pulled the zip file unzipped and tried to compile in vs2019.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ErikMogensen** [comment]
But did you unblock it?

**Comment by paolosalvatori** [comment]
Any news on this issue?

**Comment by paolosalvatori** [comment]
Closing this issue as it has not been active for a month.
