### ISSUE TITLE
Change "Message Custom Properties" from ListView to  PropertyGrid

### ISSUE THREAD

**Issue by rosponda57** [paolosalvatori/ServiceBusExplorer#373]
It would be really nice if You can change the "Message Custom Properties" (in Message and DeadLetter) from  ListView controll to  PropertyGrid controll (like the "Message System Properties")

It would give possibility to select and copy values from  "Message Custom Properties" 

:)

**Comment by paolosalvatori** [comment]
Let's keep this ask open and postpone it till we have broken the monolithic project into multiple projects / assemeblies.

**Comment by VagyokC4** [comment]
+1, especially need the copy / paste functionality

**Comment by Greybird** [comment]
@ErikMogensen , I think https://github.com/paolosalvatori/ServiceBusExplorer/pull/493 fixed this ?

**Comment by ErikMogensen** [comment]
I think so too. Closing this. If it wasn't fixed it can always be reopened.
