### ISSUE TITLE
Configuration of message for consumption by MassTransit

### ISSUE THREAD

**Issue by frisky-lizard** [paolosalvatori/ServiceBusExplorer#374]
Hello,
This may not be an 'issue' with ServiceBusExplorer, but with the absence of similar experiences online and nothing much coming back from StackOverflow, I'd like to put the question here if I may.

I can successfully connect to my Service Bus using the connection string, and publish a message to a named queue. However, using a JSON message body (with the standard Message Properties of my machine and user name), with the JSON properties on the message body matching the properties of the model in my consumer, the consumer doesn't pick up the message once it has been added to the queue via SBE.

Part of me thinks that there is something I have missed off the message when pushing it up to Service Bus, but there is nothing readily apparent that suggests this.

Just wondering if anyone has encountered a similar issue when adding messages via SBE and consuming via MassTransit (v5.5.5)?

Thanks!

**Comment by SeanFeldman** [comment]
@frisky-lizard a few questions to help understand what's happening:

1. Could you add the SO link?
1. When the message is added to the queue, is it attempted for processing at all? Does it get dead-lettered by your MassTransit endpoint?

**Comment by frisky-lizard** [comment]
Hi @SeanFeldman 

Sure...
1.  The nearest link I found about a consumer not being invoked (without asking on there, as I wanted to check here first) is:
https://stackoverflow.com/questions/50047227/masstransit-consumer-not-getting-called

However, I am 100% certain the queue names I am working with are the same. Copied/pasted from Azure Portal to Visual Studio.

The message **is** processed, and Dead-Lettered, almost instantaneously, and the error I can see in ServiceBusExplorer is that the retry count maxed out (using the default value of 10).

In terms of my setup code, it is near-enough exactly as it is in that StackOverflow question. The _only_ exception is that I am not invoking the bus.Start() / Stop() methods, as I received an exception about the bus already being started (which I think is auto-started when calling the .Host() method).

**Comment by SeanFeldman** [comment]
Thank you @frisky-lizard.

The issue described in the SO question was referring to a message that was not sent using SBExplorer, but rather MassTransit itself. There's no correlation between your question here and that question as far as I can read it.

The fact that the message is dead-lettered indicates that the message _is_ received by your MassTransit endpoint and is failing either processing or deserialization/ingest of the message due to the differences between what MT is expecting to see vs what it finds (serialization, headers, etc). In both cases, I'd expect MT to log something about it. Once you can identify what is it that causes MT to dislike the messages, it would be easier to understand why is it not working with SBExplorer.

**Comment by frisky-lizard** [comment]
Hey @SeanFeldman, thanks for your response.

Yep, I appreciate there is a mildly weak correlation between my issue and that on SO.

That said, I think you might be onto something. I was digging through the stack trace on the DLQ'd message and IBrokeredMessageReceiver is at least trying to handle the message that was published, I suspect like you said, there are some missing headers somewhere or there is an issue with the JSON deserialization of the message.

Appreciate your brainstorming efforts. I'll continue on from here. Once I can resolve it, I'll pop the solution in here, so that other developers don't get caught out by the issue I'm running into :)

**Comment by SeanFeldman** [comment]
Sounds like a good plan. I will close the issue as it's not SBE bug, but having your update comment would be helpful to anyone who comes across this issue and runs into this exact problem. Thank you.
