### ISSUE TITLE
Do not allow entity-specific connection strings

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#376]
Feature request #375 has highlighted that today the tool is handling entity-specific connections string in a non-graceful way. The tool should prevent entity-specific connection strings from being used.

A suggestion made in https://github.com/paolosalvatori/ServiceBusExplorer/issues/375#issuecomment-530040760 could be an option.

**Comment by darrenshrwd** [comment]
FYI, if you released this (without doing #375 ) it would seem everyone will need a root level management connection string to use the tool at all, I know some people are using the tool with topic level management connection string and that if I take the EntityPath away from that connection string I can no longer manage the topic, before listing the topic on the left it fails with:

Failed to retrieve EventHub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. claim is empty.

Maybe it could still log that error...but still move on to attempt topics and queues?
