### ISSUE TITLE
Internal server error when connecting to namespace

### ISSUE THREAD

**Issue by 7k8m** [paolosalvatori/ServiceBusExplorer#38]
I encountered error as titled.

## Situation:
In Dialog named "Connect to a Service Bus Namespace",
I selected "Enter connection string ..." from combo box and enter connection string on text box named "Connection String". Other values are remained as default.

The Connection String I entered is one in Access Policies in Settings of namespace of Azure portal.
Policy is RootManageSharedAccessKey and Permission is Listen,Manage,Send .

Click OK button and then error happens.

## Error messages were as next: 
````
<10:53:25> The application is now connected to the sb://hodomap-ns.servicebus.windows.net/ service bus namespace.
<10:53:25> MessagingFactory successfully created
<10:53:58> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです TrackingId:8fd28c94-cc26-4c6f-91ab-65f13f485910,TimeStamp:2016/04/08 1:53:58
<10:53:58> InnerException: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです
````

Error tells Internal Server error in Japanese language.(Japanese language is not problem at all :grin: )

## Versions
I found this error happens in all of  3.0.3 and latest and 2.4.3.0.
I remember that 2.4.3.0 could connect in same way about a year before, but found could not connect now.

Is this bug or something else ...?

**Comment by SeanFeldman** [comment]
Is this happening for different namespaces as well? Other data centres?

**Comment by 7k8m** [comment]
I created different namespace on other data center (South Central US) and tried.
The result was that same error happens. 
`````````````
<16:27:25> The application is now connected to the sb://testconnect.servicebus.windows.net/ service bus namespace.
<16:27:26> MessagingFactory successfully created
<16:28:03> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです TrackingId:e2557b8f-c01d-40bf-af0b-f9512356c6bf,TimeStamp:2016/04/08 7:28:03
<16:28:04> InnerException: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです
`````````````

**Comment by paolosalvatori** [comment]
Hi Tomohito
would you mind sending me the connection string at the email address you find in the about form? The remote server returned an error: (500) is an internal server error is quite generic as exception message. Are you trying to connect behind a firewall? Did you try to connect to your SB namespace using another network? Thanks!
Ciao
Paolo

**Comment by 7k8m** [comment]
I sent you mail named "Connection String of Service Bus namespace failed to connect with".
Please see it.

I'm trying to connect from home network which need NAT(Network Address Translation) when connecting internet.

**Comment by 7k8m** [comment]
Connected from other PC on other network, encountered similar but different error as next.

``````````````````````
<21:09:53> The application is now connected to the sb://hodomap-ns.servicebus.windows.net/ service bus namespace.
<21:09:56> MessagingFactory successfully created
<21:10:22> The link uri http://hodomap-ns.servicebus.windows.net/ has been successfully retrieved.
<21:10:31> The notification hub hodomap has been succesfully retrieved.
<21:11:02> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:a2d17280-ea2b-4419-afd6-e12f5c905edb,TimeStamp:2016/04/08 12:11:02. Method <GetQueues>b__3c: retry 1 of 10.
<21:11:32> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:c63a128e-729d-42f2-9701-b2a920e3a45b,TimeStamp:2016/04/08 12:11:32. Method <GetQueues>b__3c: retry 2 of 10.
<21:12:08> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:dd191100-ccd6-46f6-8b6f-0ab7c3172340,TimeStamp:2016/04/08 12:12:08. Method <GetQueues>b__3c: retry 3 of 10.
<21:12:38> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:d5e16ba4-7c9a-495f-80bd-d58596b6e354,TimeStamp:2016/04/08 12:12:38. Method <GetQueues>b__3c: retry 4 of 10.
<21:13:09> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:15ece52b-6503-4f6e-8ad5-b008d7521719,TimeStamp:2016/04/08 12:13:09. Method <GetQueues>b__3c: retry 5 of 10.
<21:13:44> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:34425f3b-a174-4fca-b464-2da8e0665b1c,TimeStamp:2016/04/08 12:13:44. Method <GetQueues>b__3c: retry 6 of 10.
<21:14:19> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:ea34b52e-a2bc-45ac-9866-ae955e59bfe1,TimeStamp:2016/04/08 12:14:19. Method <GetQueues>b__3c: retry 7 of 10.
<21:14:49> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:6c75b6ec-abf0-4704-8d5c-895534b45933,TimeStamp:2016/04/08 12:14:49. Method <GetQueues>b__3c: retry 8 of 10.
<21:15:19> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:07c3955e-6336-4dc5-9f0c-768e33704d3c,TimeStamp:2016/04/08 12:15:19. Method <GetQueues>b__3c: retry 9 of 10.
<21:15:52> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:32670a8f-979e-4111-a715-ff4b422e07f9,TimeStamp:2016/04/08 12:15:52. Method <GetQueues>b__3c: retry 10 of 10.
<21:16:30> Exception: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです.TrackingId:e47d9692-7924-4212-a780-bf8d96a2944d,TimeStamp:2016/04/08 12:16:30
<21:16:30> InnerException: リモート サーバーがエラーを返しました: (500) 内部サーバー エラーです
``````````````````````

**Comment by infoTrainingym** [comment]
Same error here. Do you have found anything?

**Comment by paolosalvatori** [comment]
Do you mind sending me your connection string? You can find my email address in the about form. Thanks!
Paolo

**Comment by RocketPop** [comment]
I realize this is a bit of an older issue, but I am seeing this as well but no Japanese error messages :)
`<14:04:16> The application is now connected to the sb://native-1.servicebus.windows.net/ service bus namespace.
<14:04:16> MessagingFactory successfully created
<14:04:51> Exception: The remote server returned an error: (500) Internal Server Error. TrackingId:70b96afa-7102-4441-8a55-8c3934dca8fa, SystemTracker:native-1.servicebus.windows.net, Timestamp:1/12/2017 8:04:50 PM
<14:04:51> InnerException: The remote server returned an error: (500) Internal Server Error.
`

**Comment by paolosalvatori** [comment]
Hi @RocketPop could you please send me the connection string? You can find my email address in the about form, thanks!
