### ISSUE TITLE
Lock token metadata is not generated

### ISSUE THREAD

**Issue by luipir** [paolosalvatori/ServiceBusExplorer#382]
Hi

I faced a set of error in case messages are sent via ServiceBusexplorer application.
More details in the issue opened to azure python sdk 
https://github.com/Azure/azure-sdk-for-python/issues/7336

sorry if this is an old issue or is not an issue at all, I'm not a used Win user nor a ServiceBusExplorer user, just used to send some test messages.

regards

**Comment by SeanFeldman** [comment]
The issue is definitely unrelated to this tool as lock token is provided by the service at the time when a message is received.
As far as I know there are no issue with lock using .NET SDK. Therefore I'm inclined to think it's something that should be verified in Python SDK.

**Comment by luipir** [comment]
o, I accept the closing, I'll open it again if there are other evidences that is something related with the interaction with this tool.
