### ISSUE TITLE
Issue when resubmitting deadletter's in a .NET Binary format

### ISSUE THREAD

**Issue by seanmcne** [paolosalvatori/ServiceBusExplorer#386]
We are submitting messages in **.NET Binary** format to a service bus topic with an object type of ["RemoteExecutionContext",](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.remoteexecutioncontext?view=dynamics-general-ce-9) these messages are consumed by an azure function.  

Once a message fails and winds up in the deadletter queue, we're attempting to resubmit them, I can resubmit them using "Stream" as the type but then we get xml deserialization errors in our azure function. I've also attempted using ByteArray but that too submits a message that cannot be deserialized by the azure function. 

Here's an example of one of the exceptions: 
_Exception while executing function: SendTextMessage One or more errors occurred. Exception binding parameter 'context' Expecting element 'RemoteExecutionContext' from namespace 'http://schemas.microsoft.com/xrm/2011/Contracts'.. Encountered 'Element'  with name 'RemoteExecutionContex/', namespace ''.  Exception binding parameter 'deliveryCount' Binding data does not contain expected value 'deliveryCount'. Exception binding parameter 'enqueuedTimeUTC' Binding data does not contain expected value 'enqueuedTimeUTC'. Exception binding parameter 'messageId' Binding data does not contain expected value 'messageId'. ..._ 

Example view of one message we're having trouble with: 
![image](https://user-images.githubusercontent.com/2292260/67790285-8608fe80-fa43-11e9-99ba-a6d9a8072db7.png)

**Comment by paolosalvatori** [comment]
Sorry for the delayed answer, It looks like you are using WCF message type (binding). If not there's something unexpected happening. Can you please debug and find out? I'll close the issue for now, feel free to reopen it!
