### ISSUE TITLE
when I create iot hub listener, occur Exception: An error occurred during communication with 'N/A'. Check the connection information, then retry.

### ISSUE THREAD

**Issue by huhuhub** [paolosalvatori/ServiceBusExplorer#387]
specific error is following:
<20:04:18> Exception: An error occurred during communication with 'N/A'. Check the connection information, then retry.
<20:04:18> InnerException: 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

the connect string is : Endpoint=sb://XXX/;SharedAccessKeyName=XXX;SharedAccessKey=XXXXXX
the Event Hub Path is: XXX
the Consumer Group is : $Default

Can you help me solve it? Thank you

**Comment by paolosalvatori** [comment]
The tool does not support entity-level connection string, only namespace-level connection strings
