### ISSUE TITLE
"Save Selected Event" feature is not functioning 

### ISSUE THREAD

**Issue by mortezasoft** [paolosalvatori/ServiceBusExplorer#388]
I created an IoTHub listener and everything works smoothly. But when I right click on an event and choose "Save Selected Event" context menu option, literally nothing happens and the content does not go to the clipboard!

## Affected services
- IoT Hubs
- Event Hubs

**Comment by SeanFeldman** [comment]
The feature is confirmed to work with SB messages.

@paolosalvatori or @ErikMogensen, do you work with IoT Hub service to confirm it's working or not?

**Comment by ErikMogensen** [comment]
Sorry, I don't.

**Comment by mortezasoft** [comment]
@SeanFeldman I tested with EventHub too. Same issue there. 

The following error appears in the console when I select "Save Selected Event":

> Value cannot be null. Parameter name: str

Taking a quick look into the code, the issue seems to be here:

`        private string CreateFileName()
        {
            return string.Format(MessageFileFormat,
                                 CultureInfo.CurrentCulture.TextInfo.ToTitleCase(serviceBusHelper.Namespace),
                                 DateTime.Now.ToString(CultureInfo.InvariantCulture).Replace('/', '-').Replace(':', '-'));
        }`

serviceBusHelper.Namespace is null and causes the exception.

Hope I helped a bit.

**Comment by SeanFeldman** [comment]
@mortezasoft, ATM all the development is frozen until some [refactoring is completed](https://github.com/paolosalvatori/ServiceBusExplorer/pull/381). I'll defer to the repo owner, @paolosalvatori

**Comment by paolosalvatori** [comment]
Hi mortezasoft can you please send a snapshot of the issue? I think I understood the problem, but an picture could help clarify, thanks :)

**Comment by mortezasoft** [comment]
Hi. These are the steps how to reproduce the issue:

1. Create an IotHub Listener
2. Start it
3. Select a few rows from the datagrid. Then right click and select "save selected event"

Nothing happens and in logs section you will see:
**Exception: Value cannot be null.**
**Parameter name: str**

<img width="1077" alt="01" src="https://user-images.githubusercontent.com/876408/72628741-3dc8f080-394f-11ea-99b5-b771e94ca9ee.png">
<img width="969" alt="02" src="https://user-images.githubusercontent.com/876408/72628761-43263b00-394f-11ea-81ec-28fcfca367ff.png">
