### ISSUE TITLE
Search for a particular string in EventHub messages

### ISSUE THREAD

**Issue by rajjav123** [paolosalvatori/ServiceBusExplorer#389]
Hi ,

I am using the  Service bus explorer to see the messages in EventHub Kafka . I am able to see the messages in the explorer . But I dont see any way to search for a particular string in the message . Let us say, I am getting thousands of messages in the Eventhub and I want to search whether I have received a message with a particular string .I am not sure whether that option is already there .Can you please help me here

**Comment by katymariehughes** [comment]
I would also love this feature for the message queues. I have, since taking on a project, put significant fields in the message properties so we can query that way, but to be able to query the content of all the historical messages without these properties would be amazing.

**Comment by SeanFeldman** [comment]
Disclaimer: I am not trying to shoot down the idea, rather discuss the feasibility of this feature request.

Messaging services are not the same as databases. They were not designed to query data. Querying is usually done on the data that is processed and stored. Take the Azure Service Bus for example. Messages can be at most peeked and that's it. If you want to perform a search on the payload of the messages it would mean peeking all those messages (downloading them for a preview) and performing the search. While it _could_ be done, it poses some questions. For example, Would you expect to be able to search through all the messages? Even if there are thousands of those?

Perhaps the need to search stems from a business requirement that should be thought of in a different way? I don't have all the information and can't really guess, but I would love to learn about your scenarios.

**Comment by paolosalvatori** [comment]
I agree with Sean, the tool is not meant to search strings in messages. I'm not saying it's a bad idea, but this is the first time I hear this requirement. You could implement this feature and submit a PR, or you could, as a workaround, select messages from the datagridview and save them to a file and then search for a string in the file. I'm closing this issue, for now, feel free to reopen it.
