### ISSUE TITLE
UI freezes when peeking messages larger than 256K from a premium account

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#39]
Tested message size 512K

**Comment by paolosalvatori** [comment]
Was the maximum message size increased to 512 KB for premium accounts? I was searching around, but I was unable to find any info at this regard.

**Comment by SeanFeldman** [comment]
@paolosalvatori correct. I have it here: http://bit.ly/msgsize

**Comment by paolosalvatori** [comment]
Probably! I will contact him! Thanks mate!
