### ISSUE TITLE
Auth with active directory

### ISSUE THREAD

**Issue by pioardi** [paolosalvatori/ServiceBusExplorer#392]
Hi ,
I would like to know if auth with active directory is supported ( clientId/clientSecret/tenantId).

CC : @paolosalvatori 
Thanks in advance for your response.

**Comment by ErikMogensen** [comment]
Sorry, but that is currently not supported. There is a card for this functionality on the project board, https://github.com/paolosalvatori/ServiceBusExplorer/projects/1#card-9365395.

A suggestion for the UI part and/or a high level design of this feature would be great!

**Comment by pioardi** [comment]
Thanks @ErikMogensen  for the info , c# is not my best but I will try to implement this and/or will ask other developers if they want to collaborate on this.

**Comment by pioardi** [comment]
Work in progress https://github.com/pioardi/ServiceBusExplorer

**Comment by KrothuTheCoder** [comment]
I have been working on using the latest Microsoft.Azure.ServiceBus.Primitives.TokenProvider classes that allow use to use different types of authentication. This allowed us to develop on premise and run in cloud using the correct RBAC. I had a look at trying to convert Service Bus Explorer to use the classes I have created for our application but the new primitives are not compatible with the existing Service Bus Explorer namespace code.


Example:

```var aadTokenProvider = TokenProvider.CreateManagedIdentityTokenProvider()```

or even 

```var aadTokenProvider = TokenProvider.CreateAzureActiveDirectoryTokenProvider()```


Is it possible to update the code away from the ```Microsoft.ServiceBus.NamespaceManager``` class where the older TokenProviders are referenced?  That way we could create messaging clients passing in the newer TokenProviders

```
_queueClient =
    new MessageReceiver(_configuration["sb"], TopicName, aadTokenProvider,
        TransportType.AmqpWebSockets)
        {
            PrefetchCount = preFetchCount
        };
```

**Comment by ErikMogensen** [comment]
This has been started, the purging of ServiceBus messages is done by using the new ServiceBus SDK. This has not been released yet, so this part only exists in the develop branch. There will probably be a long period where ServiceBusExplorer will be using the new and the old SDKs so we have to have solutions for both.

To split up the huge codebase in smaller pieces and have it build for .NET Standard the classes using the new ServiceBus SDK have been put in a new project with its own assembly.

**Comment by paolosalvatori** [comment]
This will take time, not sure we have the bandwidth to completely re-write the tool and fully get rid of the old client library.
