### ISSUE TITLE
SAS Connection String other than RootManageSharedAccessKey

### ISSUE THREAD

**Issue by gopi158** [paolosalvatori/ServiceBusExplorer#393]
Hi,

I can only connect to Service Bus by using the Manage access key (RootManageSharedAccessKey) from ServiceBusExplorer.
Is there any other way to connect without providing Manage/Owner level access to other users (non-admin).

Thanks in advance...

**Comment by SeanFeldman** [comment]
Currently, that's the only way.
There's a request to [support AAD](https://github.com/paolosalvatori/ServiceBusExplorer/issues/392) and a card to add support for [RBAC/MSI](https://github.com/paolosalvatori/ServiceBusExplorer/projects/1#card-9365395).

**Comment by gopi158** [comment]
Thanks @SeanFeldman
