### ISSUE TITLE
Support for TransportType.AmqpwebSockets

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#396]
The recently merged PR #381 includes changes that cause ServiceBusExplorer to use the new SDKS for ServiceBus, Relay and EventHubs. Currently the only functionality that is using the new SDKs is the purging of ServiceBus messages.

However the new functionality does not have support for setting the TransportType to [AmqpWebSockets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.transporttype?view=azure-dotnet), which is required if you are connecting to ServiceBus through a proxy. 

TransportType in the new client translates to ConnectivityMode in the old client, but there is no automatic mode in the new client which would correspond to ConnectivityMode = AutoDetect. To handle that the GUI needs to be changed. Preferably it should support configuring the proxy settings too. This is brought up in issue #343.

**The workaround for this is to just Receive and Delete the messages.**

**Comment by Greybird** [comment]
Hi @ErikMogensen,

I just took a look at this issue, but I have trouble figuring out how to store this information, as currently, the TransportType is part of the connection string stored in the settings.
As both versions of the SDK are using the TransportType name for these two different concepts, I'm not sure how to handle this.

One way could be to store the data as part of the connection string, but with a specific name (`NewSdkTransportType=xxx`) in the transition period.
Another one could be to review completely the way connections are stored in the configuration file, but this will need more work.

Do you have a view/recommandation on this ?

Thanks,

Arnaud

**Comment by ErikMogensen** [comment]
Even though [TransportType](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.servicebusconnection.transporttype?view=azure-dotnet#Microsoft_Azure_ServiceBus_ServiceBusConnection_TransportType) is a property of the ServiceBusConnectionString class I think it should be treated as an application wide setting, just like the ConnectivityMode setting for the old client. We may have to change that in the future when/if running Messaging services on Azure Stack becomes more common.

In PR #433, I added a setting for turning on or off AMQP on the Connectivity tab page. 

What needs to be done is adding this setting to the Connect dialog and to the config infrastructure. Also it should be picked up when creating a new connection using the new client. The last task may be tricky to do in a good way.

**Comment by Greybird** [comment]
Thanks for your answer. Will wait for #433 to be approved to see how I could make this work.

**Comment by Greybird** [comment]
@ErikMogensen : just pushed a proposal.
This should do the trick.
