### ISSUE TITLE
The NuGet package used for NotificationHubs has been unlisted from NuGet

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#397]
Microsoft.Azure.NotificationHubs v2.16.0.234 has been unenlisted from NuGet. Unenlisting is not as bad as being deprecated, but still not a good thing. Information about unenlisting and deprecating NuGet packages may be found [here](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages).  

We should switch to an enlisted version of Microsoft.Azure.NotificationHubs.

**Comment by ErikMogensen** [comment]
Building with the current latest version, 3.2.1 caused several build errors.

**Comment by paolosalvatori** [comment]
Can we close this issue @ErikMogensen or it's still active? Di we find a resolution? Thanks

**Comment by ErikMogensen** [comment]
No solution yet unfortunately. I think the best way forward is that someone contacts the product group and asks about this.

**Comment by paolosalvatori** [comment]
Ok, send me an email so beginning of next week I'll try to find a contact in the Notification Hubs team. It's a long time I don't speak with this team. I think we'll have to replace the old nuget package with the new one and re-write this part.

**Comment by brannon** [comment]
Hi @ErikMogensen,

@paolosalvatori made me aware of this issue. I'm a good contact for Notification Hubs issues/questions.

That version you referenced above was unlisted on 3/23/2015 and replaced with the 1.0.0 version. The 2.16.x version was based on the same code, but was mistakenly listed with the wrong version number.

If you require the Namespace and Hub Management functionality, I would recommend using the 1.0.9 version of the SDK for now. That functionality was removed in the 2.x version (in favor of using the Microsoft.Azure.Management.NotificationHubs package). We received lots of feedback that customers still want the management functionality in the regular SDK and are working on re-adding it in the latest version. That won't be available until later in the year though.

Hope that helps!
Brannon

**Comment by ErikMogensen** [comment]
That is excellent information, thanks! 

We'll switch to 1.0.9 then. I assume the next version is based on .NET Standard. As we are gradually migrating to .NET Standard we'll start using the next version once it is released.

**Comment by paolosalvatori** [comment]
Thanks @brannon for the heads up, please make sure to ping me when you re-introduce the management functionality in the regular SDK :)

**Comment by ErikMogensen** [comment]
The Microsoft.Azure.NotificationHubs 4.0.0-preview2 described at https://github.com/Azure/azure-notificationhubs-dotnet/releases contains a feature called "Reintroduces NamespaceManager for hub management within a namespace". Seems like just what we need. Just wait until it has been fully released.

**Comment by paolosalvatori** [comment]
@ErikMogensen any news on this?

**Comment by ErikMogensen** [comment]
It is now released, https://github.com/Azure/azure-notificationhubs-dotnet/releases so we should upgrade to it.

**Comment by paolosalvatori** [comment]
Ok take your time :)
