### ISSUE TITLE
ServiceBusExplorer branch for Service Bus for Windows Server

### ISSUE THREAD

**Issue by NelsonReis** [paolosalvatori/ServiceBusExplorer#4]
There could be a branch for the other version of ServiceBusExplorer, the one that now supports Service Bus for Windows Server 1.1.

That way, it would be possible to fix bugs in that version and make all the source code available for folks using SBE for Windows Server.

**Comment by NelsonReis** [comment]
Any update on Service Bus Explorer for Windows Server, or last version is still 2.1.3.0?

**Comment by Kwen** [comment]
Could someone re-post the source for the Service Bus for Windows Server version of ServiceBusExplorer? The OneDrive links are dead.

Thanks!

**Comment by paolosalvatori** [comment]
Try this link https://onedrive.live.com/redir?resid=9DBA4A06B360A65!5890&authkey=!ANNpNeRFbU7TuIQ&ithint=file%2czip
