### ISSUE TITLE
The Azure notification device's "ChannelExpired" status is not correct

### ISSUE THREAD

**Issue by yuhaii** [paolosalvatori/ServiceBusExplorer#400]
Customer reported that some of their IOS device can't receive notifications. The azure notification hub product group confirmed that some devices use installation and their channel expired, so azure notification hub didn't send notification message to those devices. 

We also use the NotificationHubClient.GetInstallation(String) SDK to make double confirmation. Its returned Installation Class  contains ‘PushChannelExpired’ property and this value is also True.

But when we use the service bus explorer latest version 4.1.112 to check the "ChannelExpired"  value, it show as false.

![image](https://user-images.githubusercontent.com/39817657/71140933-a4be9100-224d-11ea-9f46-db2acaefc556.png)

Please help us fixing this issue.

**Comment by SeanFeldman** [comment]
@yuhaii I do not work with NotificationHubs. @paolosalvatori or @ErikMogensen, anything you can help with?

**Comment by ErikMogensen** [comment]
Neither do I and I don't think Paolo has worked with it recently either. @yuhaii , I suggest you try to debug it to find out the reason and report it back here.

**Comment by yuhaii** [comment]
Hello @ErikMogensen , 

Thanks for the reply.

I checked the notification hub related code in service bus explorer. The related code is in "ServiceBusExplorer-develop\src\ServiceBusExplorer\Controls\HandleNotificationHubControl.cs" file.

It will list the registrations with GetRegistrations function.

![image](https://user-images.githubusercontent.com/39817657/71318374-017aaf80-24cb-11ea-97d2-9d998b506fd4.png)

This GetRegistrations function will call GetAllRegistrationsAsync, GetRegistrationsByTagAsync or GetRegistrationsByChannelAsync method to get the registration list. Those 3 function will return a collection of RegistrationDescription class. But this RegistrationDescription class do not have the PushChannelExpired property.

![image](https://user-images.githubusercontent.com/39817657/71318430-d2b10900-24cb-11ea-9bca-8ab05340359c.png)

When click into 1 of those registration list. The registrationsDataGridView_RowEnter function will be called. 

It will just read the registration info which get by GetRegistrations function before.

![image](https://user-images.githubusercontent.com/39817657/71318445-02601100-24cc-11ea-9052-2bc0b519c6eb.png)

So, is it possible that GetRegistrations function didn't get the PushChannelExpired property value. It just show this property as a default 'False' value?


Best Regards,
Hai

**Comment by paolosalvatori** [comment]
Hi @yuhaii yes, might be. I implemented the Notification Hub support years ago and I didn't work with Notification Hubs recently, sorry about that. Since you look knowledgable, could you please solve the issue and submit a PR? Thanks!

**Comment by yuhaii** [comment]
Hello @paolosalvatori , thanks for your confirmation. I am trying to get the PushChannelExpired value with NotificationHubClient.GetInstallation(String) method and put it into collectionQueryResult collection. 

But this GetInstallation method need an installationId parameter. May I know how to get his value in GetRegistrations function?

![image](https://user-images.githubusercontent.com/39817657/72704294-4f9ad580-3b93-11ea-9466-db5f63cda365.png)

**Comment by paolosalvatori** [comment]
Hi @yuhaii can you please look at the documentation at https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management. Unfortunately I'm quite busy and I'm not familiar with the latest version of the Notification Hub client SDK. Sorry about that!
