### ISSUE TITLE
Rename the new assemblies

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#404]
I suggest the new assemblies names prefixed with Microsoft.ServiceBusExplorer.

Name and description of the new assemblies:

**Common**
Does not contain any graphic items, but classes that help creating graphics. Has references to both the old and the new SDKs. We should aim to move the interactions with Messaging services in this assembly to the other assemblies except to the ServiceBusExplorer assembly.

**NotificationHubs**
Since the new NotificationHubs SDK lacks some functionality we stick with the old SDK. 

**EventHubs**
Uses the new EventHubs SDK. 

**ServiceBus**
Uses the new ServiceBus SDK.

**Relay**
Uses the new Relay SDK.

**Utilities**
Contains helper classes used by the other assemblies. Does not contains references to any Messaging SDK.

**Comment by SeanFeldman** [comment]
👍 for renaming the assemblies in a consistent way.

👎 for using `Microsoft.ServiceBusExplorer.` as a prefix. The assemblies are **not** coming from Microsoft and we should not confuse the customers what are those.

**Comment by paolosalvatori** [comment]
I agree with Sean, this is an open-source project not officially supported by Microsoft. Indeed, we should even change the namespace of classes, but that would require a massive effort. We could use the following convention for renaming assemblies:

- ServiceBusExplorer.exe main assembly
- ServiceBusExplorer.*.dll other assemblies

**Comment by ErikMogensen** [comment]
Sounds good! The reason I suggested Microsoft.x was that the test assembly is named that way. 

I'll rename the assemblies including the test assembly accordingly.
