### ISSUE TITLE
Feature Request: Produce JSON File for testing Stream Analytics Queries

### ISSUE THREAD

**Issue by digitaldias** [paolosalvatori/ServiceBusExplorer#41]
It would be wonderful if I could use this tool to export "sample data" to which I can work with Stream Analytics in Azure. I somehow never am able to collect any kind of data in the portal itself.

**Comment by paolosalvatori** [comment]
If you create a Stream Analytics job that sends query results to an output Event Hub, you can use my tool to create an Event Hub listener, receive and track messages, then you can double click an individual message in the datagrid and save it. If instead, you want to send test data to an Event Hub used as source by a Stream Analytics job, you can right click and Event Hub in my tool and select Send Events. Then you can use one of the options (Message, Files, Generator) to send events to the Event Hub. Please refer to the documentation on the readme page to find how to use Files and Generator. HTH. Paolo

**Comment by digitaldias** [comment]
Would this work for IoT hub as well?

**Comment by paolosalvatori** [comment]
You can use my tool to receive events from an IoT Hub, but not to send them into an IoT Hub. You can see my Service Fabric + IoT Hub demo for a sample of device simulator that can be used to send telemetry data into an IoT Hub.

**Comment by digitaldias** [comment]
It is more just looking for something to sample data from an existing stream to save into a file so that I use that sample json to can construct the queries in Stream Analytics with. 

Whenever I Try to sample anything in Stream Analytics on the portal, it is a hit/miss operation if I'm going to get any sample JSON at all. 

So I'm not asking to SEND any data anywhere, it is more a way to sample a set of data from an existing stream, so that I can save it as JSON and use it in Stream Analytics query window.

**Comment by paolosalvatori** [comment]
@digitaldias I still don't understand what you are asking for. The tool already provides the ability to send select and files from the disk or to create a message generator that creates messages using some custom logic. Please, read the instructions in the readme file.
