### ISSUE TITLE
Package the proper files for the new SDKs

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#410]
The latest code in the developer branch is using the new SDKs for Service Bus, Relay and Event Hubs. These dlls and most likely some of their dependencies need to be included when releasing.

**Comment by paolosalvatori** [comment]
Sounds good, did you completely rewrote the helper classes to use the new client? In other words, can we get rid of the old client libraries or do we need both for now?

**Comment by ErikMogensen** [comment]
No, I just rewrote a small part. Since the new libraries are based on .NET Standard they may require other dlls too.

**Comment by ErikMogensen** [comment]
To find out which files are needed I intend to test SBE on the latest release of the following OSes:

- Windows 10
- Windows Server 2016
- Windows Server 2019

I know that Windows 7 and 8.1 are missing. If anyone wants to run SBE on any of those OSes, reply in this thread.

**Comment by SeanFeldman** [comment]
> Microsoft ended mainstream support for Windows 7 on January 13, 2015. Extended support ended o  January 14, 2020. 

> Windows 8.1 falls under the same lifecycle policy as Windows 8, and will reach end of Mainstream Support on January 9, 2018.

My vote would be dropping support for those OSes.

**Comment by paolosalvatori** [comment]
Agreed, let's stop supporting Windows 7 and Windows 8. If Microsoft stopped supporting these OSes, I don't see why we have to continue to support them :)

**Comment by ErikMogensen** [comment]
Closing this as it does not seem to be a problem
