### ISSUE TITLE
Document the new requirements (connection and .NET)

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#411]
The develop branch contains code that is using the new Service Bus SDK. In the default configuration it requires the ports 5671 and 5672 for outbound traffic, which will affect some users with locked down environments. 

If using a proxy you would have to somehow make it use AmqpWebSockets, see #396.

It is also dependent on .NET 4.6.2 instead of 4.6.1.

**Comment by paolosalvatori** [comment]
Can we add this to the README? Thanks!

**Comment by ErikMogensen** [comment]
That's a good idea.

**Comment by ErikMogensen** [comment]
We should also add this information to the release on the release page. I suggest the following text:

Version 5.x.x uses the new Service Bus SDK in addition to the old SDK. The new SDK uses AMQP for communicating with the Service Bus service. Unless you change the TransportType to AmqpwebSockets it will use ports 5671 and 5672. The old SDK uses ports 9350 - 9354 by default. 

The new Service Bus SDK required increasing NET Framework version 4.6.1 to 4.6.2. Lastly there are many more dlls that needs to be included since the new SDK is built on .NET Standard.

**Comment by SeanFeldman** [comment]
> Version 5.x.x uses the new Service Bus SDK in addition to the old SDK

The problem with 'new' and 'old' language is that thanks to Microsoft, this is no longer stands true. I suggest using `track 0` and `track 1` names. Possibly referring to some explanation on those found [here](https://weblogs.asp.net/sfeldman/the-future-of-asb-dotnet-sdk).

**Comment by ErikMogensen** [comment]
Good point and great article. Combining the information in the article with the names used in the [Service Bus Documention] (https://docs.microsoft.com/en-us/azure/service-bus-messaging/) I suggest the following text:

The current develop branch and the upcoming version 5.x.x uses the Track 1 (Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus (.NET Standard)) SDK in addition to the Track 0/WindowsAzure.ServiceBus/
Microsoft.ServiceBus.Messaging (.NET Framework)) SDK. The Track 1 SDK uses AMQP for communicating with the Service Bus service. Unless you change the TransportType to AmqpwebSockets it will use ports 5671 and 5672. The Track 0 SDK uses ports 9350 - 9354 by default.

By using the Track 1 SDK the NET Framework version had to be increased from 4.6.1 to 4.6.2. Lastly there are many more dlls that needs to be included since the Track 1 SDK is built on .NET Standard. 

For more information about Service Bus SDK versions look [here](https://weblogs.asp.net/sfeldman/the-future-of-asb-dotnet-sdk).

**Comment by paolosalvatori** [comment]
This year we could undertake the infamous re-write of Service Bus  Explorer to use the new .NET Core / .NET Standard libraries for Service Bus and Event Hubs, but we need to understand what it takes and make a plan.

**Comment by ErikMogensen** [comment]
This should be included in the 5.x release.

**Comment by ErikMogensen** [comment]
Updated the release note
