### ISSUE TITLE
Exception when clicking on "Submit" in "Repair and Resubmit Message" dialog

### ISSUE THREAD

**Issue by rajrao** [paolosalvatori/ServiceBusExplorer#414]
I am getting this error:
Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

I was running the 4.1.112 release (downloaded from Github releases page). I unblocked the zip file, before unzipping and running SBE.
I also tried building the latest code from develop and it has the same issue also.

**Comment by rajrao** [comment]
I have tried running fuslogvw and there are no binding failures. Fuslogvw does tell me that I am loading "Microsoft.ServiceBus" from the SBE folders and not from the GAC.
 
The error is also thrown when trying to use the Send Message option.

**Comment by rajrao** [comment]
I have found that the following code in a separate project will cause the "Could not load type" error.

```
MessageSender messageSender = null;
Console.WriteLine(messageSender.Path);

```
Use version 6.0.0 of the "Microsoft Azure Service Bus" library.

I am unsure of how to fix it though, as the exception doesnt provide much info on why it couldnt load the library.
I did find this same issue with SignalR, but the fix didnt help: https://github.com/SignalR/SignalR/issues/3548

Within SBE, the code that causes it all to break is:
ServiceBusHelper.SendMessages. Specifically its the call to 

```
var wcfUri = IsCloudNamespace ?
                         new Uri(namespaceUri, messageSender.Path) :
```
Path on MessageSender is implemented in the base class MessagingEntityClient

**Comment by rajrao** [comment]
The issue doesn't happen on another machine. So there must be an issue with some dlls on that machine.

**Comment by paolosalvatori** [comment]
Can you check if you have an old version of the Microsoft.ServiceBus in the GAC? That might be the issue :)

**Comment by rajrao** [comment]
It did turn out that I had a corrupted Microsoft.ServiceBus dll in my gac.

As it might help someone else, the fix is:
1. First try and cleanup registry by running:
`gacutil /u Microsoft.ServiceBus`
1. If that does not work, then you may have to clean your registry (proceed with caution):
    Look for "Microsoft.ServiceBus" in  
> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Assemblies\Global
    and delete just the "Microsoft.ServiceBus" entry.
1. Try uninstalling from GAC again. You might have to restart your computer to make it work.

If it still doesnt work, make sure you dont have any Microsoft.ServiceBus references in these 2 folders (do a search across sub-folders).
1. C:\Windows\assembly
1. C:\Windows\Microsoft.NET\assembly

**Comment by ErikMogensen** [comment]
@rajrao , great that you found the reason for the issue and thanks for putting the explanation here.
