### ISSUE TITLE
Document the commandline options that ServiceBusExplorer supports

### ISSUE THREAD

**Issue by rajrao** [paolosalvatori/ServiceBusExplorer#416]
It would be good for SBE to tell the user the different options it supports at the command line (/c, /n, /t, /q, /s)
This is currently available in docs/documentation.md, but would be nicer if it were available via the application directly.

**Comment by rajrao** [comment]
Complete

**Comment by rajrao** [comment]
Completed

**Comment by paolosalvatori** [comment]
Thanks @rajrao
