### ISSUE TITLE
The default values for server and receive timeout should be increased

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#420]
Increase the default values for server and receive timeout. I suggest setting them to 30 seconds each.

**Comment by SeanFeldman** [comment]
Receive timeout is set to 1 second, which is short indeed. Are 30 seconds needed though? x10 increase should suffice IMO. Server timeout set to 30 seconds sounds reasonable.

**Comment by paolosalvatori** [comment]
AFAIR, the reason why I set the default timeout to 1 sec it was because when running a test, if the default timeout is 30 sec the tool had to wait for 30 seconds before doing something that now I don't remember :)
