### ISSUE TITLE
Closing the DeadLetterQueue message diaglog causes a refresh of Queues and Topics

### ISSUE THREAD

**Issue by rajrao** [paolosalvatori/ServiceBusExplorer#423]
Everytime the Repair and Submit message dialog is closed for DeadLetter messages, it causes a refresh of Queues and Topics. (In our case, we have close to 100 topics and the refresh process takes a long time.

The refresh seems be done only for DeadLetter messages and is done by the following 2 lines:

```
MainForm.SingletonMainForm.RefreshQueues();
MainForm.SingletonMainForm.RefreshTopics();

```
See this line for an examlple [HandleSubscriptionControl](https://github.com/paolosalvatori/ServiceBusExplorer/blob/79d9b5273c50babb12f50818e1001451a7af53b9/src/ServiceBusExplorer/Controls/HandleSubscriptionControl.cs#L2459)

I was wondering, why this refresh is being done only for deadLetter messages. Can I take it out completely? Or can I do it only if there "RemoveDeadletterDataGridRows" was called?

**Comment by ErikMogensen** [comment]
Closing this since you provided a fix.
