### ISSUE TITLE
Azure Active Directory Login Support 

### ISSUE THREAD

**Issue by markdreyer** [paolosalvatori/ServiceBusExplorer#424]
Can I connect with my current windows identity or client ID and secret as in the following documentation:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/authenticate-application

The only options I see are connection strings. I would be willing to implement this feature if it's not on anyone's radar yet.

**Comment by ErikMogensen** [comment]
This is something that's already started. There is an issue for it, #392 and the associated PR is #394. It was quite close to merging but there was a major change to the whole code base in Service Bus Explorer so the PR needed to be modified.

Perhaps you can contribute to it anyway?

**Comment by markdreyer** [comment]
Thanks, Erik. I'd be happy to take a look at contributing to the existing
PR.

**Comment by paolosalvatori** [comment]
Closing the issue. Feel free to reopen it!
