### ISSUE TITLE
Issue when importing entities with filters with and without correlationid

### ISSUE THREAD

**Issue by kart33k** [paolosalvatori/ServiceBusExplorer#428]
Hi,

I am using ServiceBusExplorer-4.1.112.
When trying to import Entites with rules for Topics getting an error 
"the key is not found in the dictionary"
When went though the code found this line in "ImportExportHelper.cs"
`string Correlationid = "Correlationid";`
```
 if (filter.Name == string.Format(NodeNameFormat, Namespace, CorrelationFilterEntity))
            {
                ruleFilter = new CorrelationFilter(propertyValue[Correlationid] as string);
            }
```

Its not able to find CorrelationId with a capital "I".
It works if changed to 
`string CorrelationId = "CorrelationId";`
And this variable is only used in import helper.

This is a part of bigger issues where It is assuming that filter has correlationid.
My filter had only label so had to replace corerelationid with label, to make it work.
`ruleFilter = new CorrelationFilter(propertyValue[Label] as string);`

May be this is an enhancement.

Thanks
Karteek

**Comment by paolosalvatori** [comment]
Hi @kart33k sorry for the huge delay, could you fork the code, make a change in your branch and submit a PR? Thanks :)
