### ISSUE TITLE
Sending message from files is broken

### ISSUE THREAD

**Issue by StepeCZ** [paolosalvatori/ServiceBusExplorer#431]
I assume this feature is meant to support case when I have lets say 100 messages, each stored in text/json/xml file and need to publish them on the queue.

How it works:

1. Right-click queue I want to publish to and choose "Send Messages" option
2. I switch to Files tab and then load all files using "Select Files" button
3. I want to send them so I click "Start" button
4. First bug is - the UI complains "Message filed cannot be null" but thats relevant in case I want to send one message using the TextArea field, i.e. "Message" tab. Anyway I can workaround this by putting whatever text there and switch back to "Files"
5. On second attempt I can send the messages using "Start" but in this case it has some bug in iteration over the loaded messages. In my test case I picked 2 files, but it sends just one. When I pick 3 files, it sends just one message again. 

<15:40:43> Sender[0]:

            - Message Count=[1] Messages Sent/Sec=[21,2765957446809] Total Elapsed Time (ms)=[47]

            - Average Send Time (ms)=[47] Minimum Send Time (ms)=[47] Maximum Send Time (ms)=[47] 

Affected version: 4.1.112

**Comment by SeanFeldman** [comment]
I didn't have much time to investigate this, but there is a whole slew of issues with this functionality that result in this bug.

1. The message body is saved as `message` but when deserialized is expected to be `content`
1. User properties are not saved correctly.
1. Exceptions during deserialization of the read files are swallowed and not presented.
1. When deserialization exception is taking the place, the message sent is one of the messages serialized JSON, which a random thing rather than an intent.

cc @paolosalvatori

**Comment by sdg002** [comment]
Firstly, I love your tool. 

I wanted to simulate a concurrency scenario with one of our Azure worker function. I prepped the message payload files and with great eagerness proceeded to use the **File** tab.

But,  the tool would not allow me to send anything unless I filled in some text in the **Message Text** tab is filled in.

I am confused. If I select multiple files then why do I need to explicitly specify the `Message text` ?

**Comment by ErikMogensen** [comment]
That looks like a bug.

**Comment by paolosalvatori** [comment]
I will look into it when I have time, maybe next Friday

**Comment by ErikMogensen** [comment]
#514 should fix the issue with Message text being required that is brought up by @StepeCZ  and @sdg002. The GUI change in #514 should clarify the second issue that @StepeCZ mentioned. @SeanFeldman, do you want to create a separate issue(s) for the issues you found? Then we could close this issue. I believe that their is already an issue for the message properties problem.

**Comment by SeanFeldman** [comment]
@ErikMogensen, let's close and I'll raise when run into it again. Rather do that and not keep a backlog of issues if they are not important to whoever raised those. In this case, me 😀

**Comment by ErikMogensen** [comment]
Sounds good. I also suspect if/when we switch to using the latest Service Bus SDK there will be other encoding/serialization issues.
