### ISSUE TITLE
Sending a message gives error

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [paolosalvatori/ServiceBusExplorer#438]
Hello,

First of all great tool! 

However a strange started to occur today. I got these errors when I am trying to send a message:
<02:42:15> Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

I have download it from the github site, the ServiceBus.dll is in the folder. I am running it on my local dev machine on latest windows 10.

Do you know what could be the issue? I have tried to write to several queues but get the same issue.
Best
Souciance

**Comment by SeanFeldman** [comment]
Did you get from https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.1.112 ?

**Comment by SoucianceEqdamRashti** [comment]
Yes I did get it from your GitHub link. The release. And that version.

**Comment by SoucianceEqdamRashti** [comment]
I tried it now from another computer and from there it works. The only difference I can tell is that on the one that works, it doesn't have the latest windows 10 updates. But anyway it is a local problem I guess. So I will close this.

**Comment by paolosalvatori** [comment]
Thanks @SoucianceEqdamRashti for the feedback and thanks @SeanFeldman for helping here :)
