### ISSUE TITLE
ServiceBusExplorer.Setup project is not supported by VS2015 updated 2

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#44]
Couldn't load the project in VS2015 update 2.
```
ServiceBusExplorer.Setup\ServiceBusExplorer.Setup.vdproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=647009&projecttype=54435603-DBB4-11D2-8724-00A0C9A8B90C
```

**Comment by paolosalvatori** [comment]
Did you solve the problem?

**Comment by SeanFeldman** [comment]
@paolosalvatori no. I have VS2015 only on my machine.

**Comment by Rzpeg** [comment]
The installer projects are deprecated in vs2015, you need a separate extension: https://visualstudiogallery.msdn.microsoft.com/f1cc3f3e-c300-40a7-8797-c509fb8933b9
@paolosalvatori moving installers to WiX might be an option http://wixtoolset.org/

**Comment by SeanFeldman** [comment]
Another option as I've outlined [here](https://github.com/paolosalvatori/ServiceBusExplorer/issues/26#issuecomment-171735148) would be Squirrel.Windows

**Comment by paolosalvatori** [comment]
Hi Sean
I've no time to make any change... how do you suggest to proceed? Can you do it please? Thanks!
Paolo

**Comment by Rzpeg** [comment]
@SeanFeldman try installing the extention I provided

**Comment by paolosalvatori** [comment]
Will do this week when I have some spare time. Unfortunately, I'm on customer site :|

**Comment by SeanFeldman** [comment]
@paolosalvatori not this week. If we decide to go with Squirrel, I'll set some time aside to do it.
