### ISSUE TITLE
Unable to export messages from the Event Hub Listener

### ISSUE THREAD

**Issue by seanmcne** [paolosalvatori/ServiceBusExplorer#441]
I'm unable to export from the eventhub listener - this is a default/vanilla eventhub - not sure what str is null, partition key maybe?  

I'm assuming it's a bug expecting data where data isn't otherwise required? 

![image](https://user-images.githubusercontent.com/2292260/79007476-dcb15300-7b20-11ea-9a53-b8ba3eabbfb3.png)

![image](https://user-images.githubusercontent.com/2292260/79007497-e63abb00-7b20-11ea-98a9-4ae647e6c4ba.png)

![image](https://user-images.githubusercontent.com/2292260/79007454-d1f6be00-7b20-11ea-8496-1028beea030a.png)

**Comment by seanmcne** [comment]
Appears to be duplicate / same issue as #388

**Comment by ErikMogensen** [comment]
I am unable to reproduce this. You are probably right about the partition key being null. Are you able to reproduce this using the Send Events functionality that you can start from the Event Hub node within Service Bus Explorer? With and Without a partition key?

![image](https://user-images.githubusercontent.com/9644248/79138640-23b77680-7db5-11ea-9f1e-d75be9db31c7.png)

**Comment by paolosalvatori** [comment]
@seanmcne can you please see if you experience the same problem when events contain a partition key? If the answer is no, probably the root cause is partitionKey == null.
