### ISSUE TITLE
Allow peeking scheduled messages on topics

### ISSUE THREAD

**Issue by sdg002** [paolosalvatori/ServiceBusExplorer#443]
These are scheduled messages that have been sent to a Topic . They have not been received by any subscription.

The tool nicely shows the count. It would be good to have a feature that allows us to peek into their contents.

Thank you for the wonderful tool

![image](https://user-images.githubusercontent.com/20245330/80018648-39701e80-84ce-11ea-8086-21747a958809.png)

**Comment by SeanFeldman** [comment]
AFAIK, it's not possible. A topic behind the scenes is a queue, but there's no API to query it (peek messages). So while you can read a topic metadata and see that there's a scheduled in the future event/message, you cannot query those. I would suggest making a feature request from the broker team https://github.com/Azure/azure-service-bus/issues.

**Comment by sdg002** [comment]
@SeanFeldman  
I struggled for a while and then found this .NET Framework NUGET package  `Microsoft.ServiceBus` which allowed me to "peek" into the content of scheduled messages from a Topic

```
        [TestMethod]
        public void Read_ScheduledMessagesFromTopic_Which_Have_NotYet_Reached_Any_Subscription()
        {
            try
            {
                string cnstring = "Endpoint=sb://********Ufg=";
                MessagingFactory factory = MessagingFactory.CreateFromConnectionString(cnstring);
                TopicClient myTopicClient = factory.CreateTopicClient("NAME OF TOPIC");
                int index = -1;
                while (true)
                {
                    index++;
                    var message = myTopicClient.Peek();
                    if (message == null) break;

                    var props = message.Properties;
                    object objIsStream;
                    props.TryGetValue("isStream", out objIsStream);

                    //string contents = message.GetBody<string>(); //Produced Null!
                    //var bytes = message.GetBody<Object>();//Produced Null!
                    var stm = message.GetBody<System.IO.Stream>();
                    string contents = null;
                    using (StreamReader sr = new StreamReader(stm))
                    {
                        contents = sr.ReadToEnd();
                    }
                    string fileName = System.IO.Path.Combine("out", $"Message-{index}.txt");
                    System.IO.File.WriteAllText(fileName, contents);

                }

            }
            catch (Exception ex)
            {
                Trace.WriteLine(ex.ToString());
            }
        }


```

**Comment by SeanFeldman** [comment]
Thank you @sdg002. This is the old library that this project is using. So technically it should be possible then. Though I am surprised it is... a topic logically should not be the same as a queue. The implementation details of the broker seem to be leaking out. I'll play around with it and follow up. Thank you again.

**Comment by SeanFeldman** [comment]
You're right. It's possible to peek and cancel scheduled messages published to a topic.
I really questioning this feature request as it breaks the paradigm of what topic is and relies on the internal implementation of topics that could be changed (unlikely, but could). Though it's my opinion.

@paolosalvatori, @ErikMogensen, what do you think about this feature request?

**Comment by ErikMogensen** [comment]
I think we should have this as a feature, but in the GUI it should say Unsupported since, as you wrote, it may stop working anytime.

Does it work with queues too?

**Comment by SeanFeldman** [comment]
Has always worked with queues. A non-scheduled message that would be forwarded to a subscription would never be available on the topic. A scheduled message cannot be retried from a topic, results in an error. But peeking works. And peek operation is the same as receive operation, minus the settlement. I've yet to confirm if this is a bug, but the point is not wherever it worked with queues or not, but the fact that the internal implementation of topics is leaking out. Which is wrong 🙂

After thinking a bit more about it, I'm leaning towards getting an answer wherever it is an unintended side effect and will be patched on the broker or something that will remain as-is. In case the latter is the decision, to add this as a feature. Not prior to that.

**Comment by paolosalvatori** [comment]
What about sending this issue to Clemens Vasters, so he can decide if this the expected or an unwanted behavior?

**Comment by SeanFeldman** [comment]
I am not sure why to ping Clemens. That's why I've raised a [broker issue](https://github.com/Azure/azure-service-bus/issues/352). This way the team is notified, it's public, and when they respond (publicly) we'll know wherever it is an unintended behaviour and will be addressed or expected and will remain as-is.

**Comment by paolosalvatori** [comment]
@SeanFeldman sounds good, I've seen that Ashish has replied to you, so we are in good shape.
