### ISSUE TITLE
PeekBatch Support

### ISSUE THREAD

**Issue by manish-jain-1** [paolosalvatori/ServiceBusExplorer#450]
I am new to this tool. I want to check all messages without receive&delete for testing purposes. Is it possible with this tool? I was able to peek the last message but not all. I believe there is an [API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.peekbatchasync?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueClient_PeekBatchAsync_System_Int64_System_Int32_) to do it. Is it supported? Thank you!

**Comment by SeanFeldman** [comment]
Yes, you can **peek** any number of messages.
Please see the https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/docs/documentation.md, specifically the sections called "Peek and Receive Active Messages: "
