### ISSUE TITLE
Endswith in topic filter does not work

### ISSUE THREAD

**Issue by dustyghost** [paolosalvatori/ServiceBusExplorer#452]
You can filter on a topic that starts with a string, but would like to filter on topics that end with a string
![image](https://user-images.githubusercontent.com/10135321/82039700-4cc17480-969d-11ea-8685-e89b0c351ada.png)

>  <11:15:29> Exception: One or more errors occurred.
> <11:15:29> InnerException: The remote server returned an error: (400) Bad Request. SubCode=40000. Invalid Filter. The specified property 'endswith' does not exist or is not allowed.
> 
>            Parameter name: propertyName. TrackingId:01e7e5f3-aa91-4515-9a0c-6739ff25e295_G14, SystemTracker:pip17objectmessaging.servicebus.windows.net:$Resources/Topics, Timestamp:2020-05-15T10:15:28

**Comment by ErikMogensen** [comment]
SBE uses the GetTopicsAsync method for this, https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.gettopicsasync?view=azure-dotnet#Microsoft_ServiceBus_NamespaceManager_GetTopicsAsync_System_String_.

The only function it supports is StartsWith.

**Comment by dustyghost** [comment]
Thank you.
