### ISSUE TITLE
Will the real 4.1.112 please stand up?

### ISSUE THREAD

**Issue by craig-wagner** [paolosalvatori/ServiceBusExplorer#453]
I have a copy of Service Bus Explorer on my machine that indicates in the title bar is is 4.1.112. The About window looks like this.

![image](https://user-images.githubusercontent.com/729617/82707430-e30f1080-9c30-11ea-80e3-e36f6ea824de.png)

I downloaded the 4.1.112 from the Releases section of this repository. Its About window looks like this.

![image](https://user-images.githubusercontent.com/729617/82707479-fe7a1b80-9c30-11ea-8403-397cee3d2b56.png)

Does anyone know which is actually the latest version?

**Comment by SeanFeldman** [comment]
> I have a copy of Service Bus Explorer on my machine

As a compiled version or as code and you compile it?
The 2nd screenshot looks as what you get when you download the latest from the latest release page.
https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest

**Comment by ErikMogensen** [comment]
To add to Sean's answer, there were a couple of releases where the tool would make a call to a GitHub API to get the version number from the latest release and then display that. The first screenshot must be from one of those releases.

If you build it from the current develop branch to get the latest bits it will say that the version number is 1.0.0.

**Comment by paolosalvatori** [comment]
Hi @craig-wagner let us know if Erik and Sean' replies were exhaustive and if we can proceed and close the issue :)

**Comment by craig-wagner** [comment]
> > I have a copy of Service Bus Explorer on my machine
> 
> As a compiled version or as code and you compile it?

It's been there for quite some time so I don't remember for sure. I think at some point I downloaded source and built it, but I no longer have that source.

> The 2nd screenshot looks as what you get when you download the latest from the latest release page.
> https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest

It is. Sorry, tried to make that clear in the line before the screenshot.

**Comment by craig-wagner** [comment]
Okay, I think I've got it.

The executable version I've had for a while now (first About window) is mostly likely calling itself 4.1.112 because it's just asking GitHub what the latest release is.

Downloading the zip of the 4.1.112 from the releases page *is* the actual latest version.

Downloading source and building the "develop" branch tells me it's 1.0.0, which I'm assuming will change to 4.x or 5.x when it goes to master.
