### ISSUE TITLE
.NET Core Support?

### ISSUE THREAD

**Issue by AlexeyRaga** [paolosalvatori/ServiceBusExplorer#458]
Building it with .NET Core would be neat as it would enable multiple platforms and not only Windows ;)

**Comment by SeanFeldman** [comment]
This tool is using Windows Forms for UI. AFAIK, Windows Forms technology is only supported on Windows.
Please see #286

**Comment by SeanFeldman** [comment]
While not .NET Core, a somewhat related issue is https://github.com/paolosalvatori/ServiceBusExplorer/issues/527
