### ISSUE TITLE
Feature Request: Add Queue Listener for specific Message Session

### ISSUE THREAD

**Issue by jcoeltjen** [paolosalvatori/ServiceBusExplorer#464]
Is it possible to add a queue listener for a specific message session?
Or more specific: Is it currently possible to register a message handler for specific sessions or as a fallback register a session handler together with respective handlers?

We use session enabled queues for handling semi synchronous request/response calls for some legacy applications and have currently some problems in production and would like to peek some messages that belong to only one of the running message sessions.

My workaround for that right now is to use a custom C# project for that but it would be really nice to have this functionality inside the Service Bus Explorer.
If I am not alone with this feature request I would try to take the time to prepare a PR for this as a base for further discussion.

**Comment by paolosalvatori** [comment]
Do you have the bandwidth to implement this feature and submit a PR? Thanks!

**Comment by jcoeltjen** [comment]
> Do you have the bandwidth to implement this feature and submit a PR? Thanks!

I will give this a go!

**Comment by jcoeltjen** [comment]
I tried a minimalistic approach on implementing this feature and opened a PR for this (#470).
As I am a little bit rusty in writing code for WinForms please **don't** be gentle in your review.

**Comment by paolosalvatori** [comment]
Take your time @jcoeltjen no rush, and thanks for the contribution :)

**Comment by ErikMogensen** [comment]
Fixed in #470
