### ISSUE TITLE
Cannot view session state in service bus explorer

### ISSUE THREAD

**Issue by chaoqian** [paolosalvatori/ServiceBusExplorer#467]
cannot view session state in explorer:
![image](https://user-images.githubusercontent.com/3410645/92511365-0a7af080-f1c2-11ea-8343-ff51f6505589.png)

**Comment by ErikMogensen** [comment]
Does this work sometimes?

**Comment by SeanFeldman** [comment]
The code is set up to reflect the session state. @chaoqian, could you confirm the following:
1. Your sessions have a state.
2. How do you persist/write your state? (ideally sharing the code snippet).

**Comment by paolosalvatori** [comment]
Hi @chaoqian, can we close this issue? @SeanFeldman @ErikMogensen let's close this issue unless we get more context from @chaoqian. Thanks!

**Comment by kaluznyt** [comment]
Not sure if this is the issue, but I just got here to notify on some issue on the same "Session State" view. Basically, I noticed, that when I remove something from session state (set to null) - it still get displayed in that pane. So in case I have for example 2 sessions with null state, in the pane some last state is still displayed, even when I click on both.

**Comment by kaluznyt** [comment]
there seems to be a bug, when sessions are removed, the pane displays the state from last viewed: 

![image](https://user-images.githubusercontent.com/572605/96714345-4ea50780-13a2-11eb-8c56-fb68d1f10700.png)

**Comment by SeanFeldman** [comment]
@kaluznyt, yes. See https://github.com/paolosalvatori/ServiceBusExplorer/issues/467#event-3742972484

**Comment by paolosalvatori** [comment]
@kaluznyt @SeanFeldman @ErikMogensen any news on this issue or can we proceed and close the issue?

**Comment by kaluznyt** [comment]
@paolosalvatori for me it can be closed, hovever I didn't open it, I just reported some similiar behavior which I consider incorrect (session state displayed in pane, when it's null'ed out on session using SetState(null)), but it's not same behavior as originally reported in this thread
