### ISSUE TITLE
Releasing version 5

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#477]
This issue is for discussing details around the first v5.0 release instead of in the PR #474.

Should it be called 5.0.0 or 5.0.113? Personally I like 5.0.113 better, but not a big deal.

**Comment by ErikMogensen** [comment]
I have now tagged the items that I consider being a part of this release.

**Comment by SeanFeldman** [comment]
> Should it be called 5.0.0 or 5.0.113? Personally I like 5.0.113 better, but not big deal.

If we want to follow the [SemVer](https://semver.org/) model with x.y.z, the z part is a patch release for bug fixes. We're making a breaking change by removing some old functionality and changing the client we're going with. In the past, @paolosalvatori used to link the major version to the ASB SDK client. I'm not sure we'd want to continue that tradition. Everyone understands SemVer and it would be easier to decide on the version because there's a clear set of rules to follow. My recommendation would be to follow SemVer and start with a 0.

**Comment by paolosalvatori** [comment]
@SeanFeldman @ErikMogensen I'd follow the tradition, and if the client library changed the major version, we should change the major version of SBE. Thoughts?

**Comment by SeanFeldman** [comment]
This is not needed IMO. When a _breaking_ change is introduced or something that would force environment modification, a major makes sense. Like a newer .NET Framework, which could be a blocker if not installed on a machine. Otherwise minor and patch changes suffice.

**Comment by paolosalvatori** [comment]
@SeanFeldman I know it's not necessary, but since we did a lot of changes since the last release we could take the chance to increase the number of the major version, right?

**Comment by SeanFeldman** [comment]
@paolosalvatori I think we're talking about the same thing. This outgoing release will be 5.0.0.

**Comment by SeanFeldman** [comment]
@paolosalvatori, @ErikMogensen, have you had a chance to review closed issues/PRs to assigned the `5.0.0` milestone and label things accordingly? Once you 👍, I'll get the release out.

**Comment by ErikMogensen** [comment]
I have gone through the PRs and assigned the milestone label on the relevant ones and then labeled them. I approve going ahead.

**Comment by paolosalvatori** [comment]
I review PR closed by the bot, and I decided to make a list of issues I want to take a chance to review and possibly solve. Here is the list:

- https://github.com/paolosalvatori/ServiceBusExplorer/issues/431
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/383
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/388
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/432
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/373
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/340
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/349
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/294
- https://github.com/paolosalvatori/ServiceBusExplorer/issues/214

**Comment by SeanFeldman** [comment]
I'm assuming these will be done in the 5.x timeframe, not blocking 5.0 release, correct?

**Comment by paolosalvatori** [comment]
Correct, go ahead with the release, fixing the above issues will be a best-effort activity if and when I\we'll have some spare time

**Comment by SeanFeldman** [comment]
@paolosalvatori or @ErikMogensen, happy holidays! Here's a [small gift](https://github.com/paolosalvatori/ServiceBusExplorer/pull/486) you'd need to approve.

**Comment by ErikMogensen** [comment]
Thank you Sean! This is quite a big release! Lots of features and fixes created by 20 contributors.

I approved it but didn't merge it as I am not sure which merge method you'd prefer. Is it "Rebase and merge" you want for this?

Happy holidays!

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/ea8b9397d610b07c4764d65022a651c6054aad7e
[Announced](https://twitter.com/sfeldman/status/1342932925214466048?s=20)

**Comment by paolosalvatori** [comment]
Thanks @SeanFeldman and @ErikMogensen, I just disconnected for the Christmas holidays :)
