### ISSUE TITLE
DateTime chooser for StartDate in EventHub listener doesn't display am/pm for time component

### ISSUE THREAD

**Issue by steavy29** [paolosalvatori/ServiceBusExplorer#478]
Repro steps:
1. Actions -> Create Event Hub listener
2. In opened window, in section Options there is "StartDate" datetime picker.

A.R.
"StartDate" picker allows user to choose date via calendar control and edit time component. Time is in 12h day format but am/pm part is not visible so it's not possible to understand what time you select.
![image](https://user-images.githubusercontent.com/9865713/98805536-64956d80-2420-11eb-8f14-44014d41f559.png)

E.R.
Either user 24h time format or display am/pm component.

Not sure if this affects the time picker, but maybe will also help: 
- my PC uses 24h format for displaying time
- Date, time & regional formatting settings in Windows are set to:
    - Regional format: Ukrainian

**Comment by paolosalvatori** [comment]
This change makes sense, I will schedule a change next week. Sorry for the delayed answer, but I'm quite busy in this period.

**Comment by steavy29** [comment]
Hi.

Is there any understanding when this can be scheduled for implementation?
I could try to help with this and make a PR if that's an accepted practice.
Appreciate any info on this. Selecting time range there now is giving a headache every time.

Thanks

**Comment by paolosalvatori** [comment]
Hi @steavy29 I'll look into it this week unless you already submitted a PR.

**Comment by ErikMogensen** [comment]
@steavy29 , I think this is fixed by #493 so I am closing this now. Let us know if this isn't fixed.
