### ISSUE TITLE
Contributor level access can connect through explorer to service bus

### ISSUE THREAD

**Issue by harishlyadav** [paolosalvatori/ServiceBusExplorer#479]
I am trying to connect as contributer level access to service bus, but getting timeout exception.
Do i need to change anything here in appsetting ?

&lt;add key="subscriptionId" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" /&gt;
&lt;add key="certificateThumbprint" value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" /&gt;

See the attached image.

![access sb](https://user-images.githubusercontent.com/31185629/99584572-6c877b80-29e5-11eb-9910-c772ce538794.PNG)

**Comment by ErikMogensen** [comment]
By contributor access, do you mean you have Contributor access on the Service Bus namespace? Currently there is not support for authentication through Azure AD, but hopefully we can add that in the future.

Right now there is only support for connecting using SAS keys.

**Comment by ErikMogensen** [comment]
Closing due to no response.
