### ISSUE TITLE
2.1.3.0 - "Exception: Index was out of range" when selecting a subscription for a topic

### ISSUE THREAD

**Issue by vascofernandes** [paolosalvatori/ServiceBusExplorer#48]
When selecting a subscription for a topic I get the following exception:

Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

![capture](https://cloud.githubusercontent.com/assets/10337953/16763228/505f6e2a-4828-11e6-8668-c9c3aa87166a.PNG)

Regards

**Comment by SeanFeldman** [comment]
@vascofernandes any chance you could provide steps to build a topic that would reproduce this issue? 
Also, what build of the sbexplorer are you using?

**Comment by SeanFeldman** [comment]
Version 2.1.3.0 from the screenshot

**Comment by SeanFeldman** [comment]
@vascofernandes given that the latest is 3.0.4, could you test with the latest and co firm of the issue is still happening? Thanks.

**Comment by vascofernandes** [comment]
The topics and subscriptions are added with C# using 
Assembly Microsoft.ServiceBus, Version=2.1.0.0,
ServiceBus.v1_1.1.0.6\lib\net40-full\Microsoft.ServiceBus.dll

However, with 2.1.3.0, even if I delete all Entities, manually create a new topic (named Test), and try to manually add a subscription (by clicking Create Subscription), if fail with the same exception.

I did try the latest, 3.0.4.
It connects successfully but is does not show a list of topic/queues. There is no sub-tree to expand.

**Comment by SeanFeldman** [comment]
Are you connecting to Windows Server SB?

**Comment by vascofernandes** [comment]
I installed SB on my windows 8.1 machine and did "Create a New Farm". 
No problems there. All running fine.

Get-SBFarmStatus shows that everything is running fine.

**Comment by vascofernandes** [comment]
I will try build locally 2.1.3.0 and debug it.

**Comment by SeanFeldman** [comment]
SB library for WSSB is much older than for Azure SB. Can't tell you what's the issue here. 
You could pull the codes down and debug it. Suspect something in the client library has changed, while WSSB has not been updated.
@paolosalvatori any ideas?

**Comment by vascofernandes** [comment]
The OneDrive link for 2.1.3.0 is dead.

**Comment by paolosalvatori** [comment]
Try this link for the source code of 2.1.3: https://1drv.ms/u/s!AmUKNmugpNsJrgKSItfhDqF4sx2z
Ciao
Paolo

**Comment by jo-me** [comment]
I have the same issue in version 3.1.4
I can connect to a ServiceBus / Eventhub using a connection strng, but I cannot start a listener.

**Comment by paolosalvatori** [comment]
Hi
Please try the last version of the tool. 
Ciao
Paolo

**Comment by r3dlin3** [comment]
Hi,

I have the exact same issue on the current latest version (3.4.24) while trying to create a listener on a Azure Service Bus.
I'm using the binaries from the zip file of the release.
Is there a workaround? Something I need to install first?

**Comment by paolosalvatori** [comment]
Could you please send me the connection string and tell me on which entity you are trying to create the listener? You find mu email address in the about form. This week I'm pretty busy. Expect a delayed answer.

**Comment by r3dlin3** [comment]
I have tested on a VM under Windows 2012 R2 and it's working...
My workstation is under Windows 10 1607 but in french whereas my VM is in english...
Weird...

**Comment by vip32** [comment]
this is also happening in 3.4.24 for me

![image](https://cloud.githubusercontent.com/assets/164303/23549328/002f8f24-000c-11e7-8754-ed4db8c8db59.png)

connected with a azure connection string. this happens when trying to view the subscriptions.

**Comment by vip32** [comment]
maybe it makes sense to re-open this issue

**Comment by paolosalvatori** [comment]
I close the issue, because I can't repro it. When clicking a subscription I don't get any error.

**Comment by WarrenKin** [comment]
I am also seeing this issue, I can run on a Win 7 Pro machine with no issues, but on my Win 7 Enterprise laptop I see this "Index was out of range" exception.  It occurs with both my production and test Service Bus connection string.  Has someone got to the bottom of this one?  

![sbexplorerexception](https://cloud.githubusercontent.com/assets/28863283/26310293/37ae6b8e-3ef8-11e7-9c16-5a4d59fefc96.JPG)

**Comment by paolosalvatori** [comment]
Hi @WarrenKin I've no way to repro this problem. If you have Visual Studio installed on that machine, it would be great if you could debug through the application and tell me exactly which method call fails. Sorry about that.

**Comment by WarrenKin** [comment]
Hi Paolo,

The CalculateLastColumnWidth is the method that crashes, it seems the object passed into the method is null:

[cid:image001.jpg@01D2D30A.EC8A0E50]

This is the statement where it finally complains:

[cid:image002.jpg@01D2D30A.EC8A0E50]

Please let me know what else you require….

Warren

**Comment by paolosalvatori** [comment]
Hi @WarrenKin I don't see the images :(

**Comment by WarrenKin** [comment]
Paolo, I've edited my previous comment and attached the VS clip.

**Comment by paolosalvatori** [comment]
Hi @WarrenKin in which version of the tool do you see the problem? The latest or 2.1.3? And in which class? Thanks! HandleQueueControl or HandleSubscriptionControl? Thanks!

**Comment by WarrenKin** [comment]
The class is HandleSubscriptionControl and the version I am using is 3.0.4.

**Comment by paolosalvatori** [comment]
Can you please check the latest version? Thanks!

**Comment by WarrenKin** [comment]
Do you mean this:

![sbexplorerversion](https://cloud.githubusercontent.com/assets/28863283/26314138/e83ab21c-3f04-11e7-89bf-2bb8d2ba8ad6.JPG)

**Comment by paolosalvatori** [comment]
I don't recognize that view. I mean the latest version of the code or the latest release you can download from GitHub .

**Comment by WarrenKin** [comment]
I see what you mean now, I have downloaded the latest code from GitHub and the issue is now fixed, thank you so much.  I thought I had the latest version 3.0.4, I'll have to check where I found this download because I am sure it said it was the latest and it was only about 1 month ago, and I see you're now at 4.0.89. Thanks again - it's a brilliant tool.

**Comment by paolosalvatori** [comment]
Thanks @WarrenKin :)
