### ISSUE TITLE
api-version exception when trying to connect to latest on-prem version "Service Bus 1.1 with TLS 1.2"

### ISSUE THREAD

**Issue by NiklasEMS** [paolosalvatori/ServiceBusExplorer#480]
api-version exception when trying to connect with SB Explorer to latest on-prem version "Service Bus 1.1 with TLS 1.2"

Perhaps this exception can be caught and adjusted to correct api-version? Or omitted from the uri? The error states that it can be removed or use supported ones. Or this is always hard-coded in Microsoft.ServiceBus.dll dependency? 

Perhaps possible to set api-version in connection details to be used for this connection? 

These are the supported ones reported back: 2012-03,2012-08,2013-04,2013-07

<16:00:20> InnerException: The remote server returned an error: (400) Bad Request. The api-version in the query string is not supported. Either remove it from the Uri or use one of '2012-03,2012-08,2013-04,2013-07'..TrackingId:26a3a3cb-782b-4b76-ae6b-c6e86eb02871_GNEBT201601,TimeStamp:11/20/2020 4:00:20 PM

Send and Receive operations works fine with 2016-07 api-version later DLL. I have used DLL from windowsazure.servicebus.4.1.3.nupkg (3.0.50870.7) without problems. Perhaps only management adds the api-version to the uri? 

Repro:
Install SB 1.1 with TLS 1.2 (latest on-prem Service Bus)
:: Download WebPI : https://www.microsoft.com/web/downloads/platform.aspx
:: Online installation:
WebpiCmd.exe /Install /Products:ServiceBus_1_1_TLS_1_2 /AcceptEula

Run Service Bus setup wizard to create default Service Bus installation (ServiceBusDefaultNamespace)

Get SAS KeyName + Key for Endpoint, e g 
Get-SBAuthorizationRule -NamespaceName ServiceBusDefaultNamespace

Try to connect with latest SB Explorer. Earlier 2.1 version works fine.

**Comment by paolosalvatori** [comment]
As stated on the README page, the Service Bus Explorer 2.1.0 can be used with the Service Bus for Windows Server 1.1. The Service Bus Explorer 2.1.0 uses a version of the Microsoft.ServiceBus.dll client library which is compatible with the Service Bus for Windows Server 1.1 RTM version. You can download the source code of the Service Bus Explorer 2.1.0 [here](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/2.1.0).

**Comment by NiklasEMS** [comment]
Thanks. I did also some decompiling of multiple Microsoft.ServiceBus.dll clients where I found this hard-coded api-version limitation in there. I will use old 2.1.0.

**Comment by paolosalvatori** [comment]
Thanks @NiklasEMS

**Comment by aaravpandya** [comment]
@paolosalvatori Hi, we are facing the same issue but with a twist. We can connect to service with TLS 1.0, and 1.1 enabled. But unable to do so with only 1.2 enabled. Any ideas?

**Comment by aaravpandya** [comment]
Hi, solved this issue by simply bumping the .NET version to '4.7.2'.
