### ISSUE TITLE
支持问题

### ISSUE THREAD

**Issue by l623164469** [paolosalvatori/ServiceBusExplorer#483]
can this version support macos？

**Comment by paolosalvatori** [comment]
Do you mean macros? For doing what? Can you please be crisper about your request?

**Comment by l623164469** [comment]
I want a MAC os client,can this use in Mac os? This is a windows client




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paolosalvatori/ServiceBusExplorer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:34
收件人:&nbsp;"paolosalvatori/ServiceBusExplorer"<ServiceBusExplorer@noreply.github.com&gt;;
抄送:&nbsp;"莂理莪、謝"<623164469@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [paolosalvatori/ServiceBusExplorer] 支持问题 (#483)





 
Do you mean macros? For doing what? Can you please be crisper about your request?

**Comment by paolosalvatori** [comment]
No, I’m sorry, this tool only runs on Windows.
