### ISSUE TITLE
ReSharper displays errors when opening the solution in Visual Studio

### ISSUE THREAD

**Issue by gabrielweyer** [paolosalvatori/ServiceBusExplorer#487]
- Visual Studio Community 2019 (16.8.3)
- ReSharper 2020.3.1 Build 203.0.20201223.80701

The repository contains a ReSharper setting file (`src\ServiceBusExplorer.sln.DotSettings`). When opening the solution in Visual Studio with ReSharper installed and Solution Wide Analysis enabled, 173 errors are displayed:

![image](https://user-images.githubusercontent.com/2101647/103326131-07727b80-4aa3-11eb-8158-e80d52e236bf.png)

These errors do not prevent Visual Studio from compiling or launching Service Bus Explorer. Through `src\ServiceBusExplorer.sln.DotSettings` some code inspections have been configured to have a level of _Error_. This is distracting for developers using ReSharper as it appears that the solution have errors. Reducing the severity of these code inspections to _Warning_ would remove the errors.

**Comment by paolosalvatori** [comment]
Interesting observation @gabrielgt , let me see if we can remove it.
