### ISSUE TITLE
Premium ServiceBus - Create Queue/Topic with max Queue Size - 80GB

### ISSUE THREAD

**Issue by abhikt48** [paolosalvatori/ServiceBusExplorer#499]
Premium ServiceBus provide facility to create Queue/Topic with max **80GB** Queue Size. 
But ServiceBus explorer provides facility to create queue upto **5GB** only. 

Can you please provide facility to create Queue/Topic with max capacity. 

Note - This is not a priority requirement, but good to have this feature, so we don't need to create Queue from Azure Portal with max size.

![image](https://user-images.githubusercontent.com/22897837/103646967-6f690c00-4f52-11eb-8401-b4f752e028e4.png)

**Comment by SeanFeldman** [comment]
This is possible with the track 1/2 SDKs (Microsoft.Azure.ServiceBus and Azure.Messaging.ServiceBus).

- SDK track 1: using `ManagementClient` you can get the namespace info with `.GetNamespaceInfoAsync()`. It returns `NamespaceInfo` with `MessagingSku` property.
- SDK track 2: using `ServiceBusAdministrationClient` you can get the namespace info using with `GetNamespacePropertiesAsync()`. It returns `NamespaceProperties` with `MessagingSku` property

**Comment by paolosalvatori** [comment]
@SeanFeldman do you want to make the change?

**Comment by SeanFeldman** [comment]
@paolosalvatori sure. It's going to be a bit hacky as the main project is still on SDK track 0 (`WindowsAzure.ServiceBus`).
