### ISSUE TITLE
Textboxes need to be filled out when creating a new queue

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#501]
Previously you only needed to enter the Relative URI to create a queue. Now you have to put a number in almost every textbox.

I believe this is caused by #493. Is this something you want to look into, @Greybird ?

**Comment by Greybird** [comment]
Sure of course! I'll fix this!

**Comment by Greybird** [comment]
Here it it, sorry again!

**Comment by ErikMogensen** [comment]
That was quick, thanks!
