### ISSUE TITLE
GitVersionTask is deprecated

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#502]
The NuGet package GitVersionTask is reported as deprecated by Visual Studio even though the latest version is installed. I assume there is a replacement package. 

I don't want to start the discussion about GitVersion or not again, but just mention that as far as I am concerned I still think we are better off without it.

**Comment by SeanFeldman** [comment]
I don't have any objections to taking it out. As long as we automated the release pipeline.
With the changes over the years, AppVeyor and GitVersionTask could be replaced with GitHub Actions and simpler approaches/libraries. Just to be very clear, I'm having very little spare time these days to drive changes.

**Comment by ErikMogensen** [comment]
Cool, perhaps we should have an issue for migrating to GitHub Actions.

**Comment by paolosalvatori** [comment]
GitHub Actions is cool, I used it in June/July. We can definitely look at it. I'm not an AppVeyor expert though.
