### ISSUE TITLE
Refactor ServiceBusHelper2 to reduce number of service invocations

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#506]
Follow-up to #504 

Currently, it generates a large and unnecessary number of calls due to its call on demand implementation.

**Comment by ErikMogensen** [comment]
It would be great it this is not implemented using static fields since in the future SBE may support working with multiple namespaces concurrently.

**Comment by paolosalvatori** [comment]
In the very very very future 😄

**Comment by SeanFeldman** [comment]
damn bot 😂

**Comment by ErikMogensen** [comment]
@SeanFeldman, you can use the Pinned label to avoid the bot, but that is cheating...
