### ISSUE TITLE
Question on SB Explorer's Security Certification

### ISSUE THREAD

**Issue by TheAzureGuy** [paolosalvatori/ServiceBusExplorer#507]
Hello!

Has there any work been done to assess potential vulnerabilities in SB Explorer and establish its risk profile? 
With so many customers using it, how do those customer certify the use of this tool in their non-prod and prod environments?
When will SB Explorer support reading ASB connection strings from a secure storage like KeyVault instead of having to hard-code them in the application's .config file?

Thank you in advance for your responses.

**Comment by SeanFeldman** [comment]
@TheAzureGuy good question. I have no idea about risk profiling. @paolosalvatori, did you do any of that at any point in time?

> When will SB Explorer support reading ASB connection strings from a secure storage like KeyVault instead of having to hard-code them in the application's .config file?

Do you mind to raise a feature request? Raising multiple questions/feature requests in a single issue has been proven not to be very effective. Thank you.

**Comment by paolosalvatori** [comment]
Hi @TheAzureGuy your name and that CAT picture remember me someone who worked for many years in my team and I met several times in Seattle and once in Milan in April 2013, right? 😄 Now that the migration from the old to the new SDK is complete, we can think to add Azure Activity Directory (AAD) authentication to the tool. This should also allow integrating SBE with a secret store like Key Vault via Azure RBAC, assuming that the current user is authenticated and proper policies have been created on Key Vault to let him\her list and get connection strings from the selected Key Vault resource. This implementation is doable, but it takes time, and @SeanFeldman, @ErikMogensen, and the other contributors are doing their best to evolve the tool in their spare time. SBE is an OOS tool used by hundreds of customers use SBE every day, but it's not an official Microsoft tool so as such it doesn't need to go through a security threat analysis. If you are very welcome my friend if you want to contribute to the integration of SBE with Key Vault as described above. 😃

**Comment by TheAzureGuy** [comment]
@paolosalvatori yes, my friend, I'm the same person who still keeps a special place in his heart for you and our AzCAT team. 

It is very exiting to see how Service Bus Explorer, one of your work-life "babies", has become such a popular tool. However, it would have been even better if the tool was able to demonstrate some form of enterprise readiness by supporting AAD auth and KeyVault storage at a minimum.

**Comment by paolosalvatori** [comment]
@TheAzureGuy I agree with you, before it was not possible because the old client SDK did not support AAD integration, but now that we dismissed the old SDK it's perfectly doable. Would you have time to help me with this effort? I'm very busy in this period so I may not have much spare time for this 😢

**Comment by ErikMogensen** [comment]
I'd like to see something where you can choose to use the existing way of getting connection strings from config files or login and then stay logged in even if you change namespace. While logged in, you should be able to get connection strings from Key Vault or [access Azure Messaging services directly using AAD](https://docs.microsoft.com/en-us/azure/service-bus-messaging/authenticate-application).

**Comment by TheAzureGuy** [comment]
@ErikMogensen that's exactly what I was looking for! I open SBE and it prompts me to log in to my Azure subscription. It then uses my auth token to get a secret from Key Vault the name of which I provide via .config file. The value of the KV key is a JSON with the schema that SBE is able to read (just literally a collection of ASB connection strings expressed via name/value pairs similar to what we currently have to maintain in the .config file. The rest is just as easy as 1+1. Display the collection of connection strings and allow me to choose one which I want to connect to. Super easy. Very secure.

**Comment by paolosalvatori** [comment]
This is on my todo-list, but I just changed team and I'm very busy. Long-term I'm planning to implement AAD authentication and integrated RBAC and the ability to read connection strings from Key Vault.
