### ISSUE TITLE
Regression: cannot resubmit a message

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#510]
When attempting to resubmit a message an exception is thrown:

> Exception: The message body cannot be read multiple times. To reuse it store the value after reading.

**Comment by paolosalvatori** [comment]
I suppose this is due to the way the message is cloned, right? And I suppose this is due to the old code that we recently re-introduced in SBE...

**Comment by ErikMogensen** [comment]
I was unable to reproduce this using the latest develop branch. Was it one message or was it the batch resubmit?

**Comment by SeanFeldman** [comment]
Single message

**Comment by ErikMogensen** [comment]
I have tried that both from deadletter and normal queue. Also tried peek and received. Please state repro steps including message content.

**Comment by RascoApps** [comment]
I'm experiencing this issue as well. after editing, the original message is still sent.

**Comment by ErikMogensen** [comment]
@RascoApps, this issue occurs in the latest released build. Is that what you are using? The issue you are describing has been fixed in the current develop branch with PR #496.

@SeanFeldman, which build are you using when this occurs?

**Comment by SeanFeldman** [comment]
> @SeanFeldman, which build are you using when this occurs?

I believe it was the latest, 5.0.1. Not 100% sure. I'll raise a separate issue when/if it happens.

**Comment by lkurzyniec** [comment]
My steps to reproduce:
1. Enter either queue or topic subscription
2. Click Deadletter and Peek some messages
3. Click Repair And Resubmit Selected Message (single message)
4. Click Submit 
5. Choose Send To queue/topic
6. Click Ok - works fine, message send successfully
7. Again - in Repair and Resubmit Message window - Click Submit
8. Again - Choose Send To queue/topic
9. Again - Click Ok  - Exception: The message body cannot be read multiple times. To reuse it store the value after reading.

```
<10:17:43> [1] messages were sent to [my-local-sb] in [130] milliseconds.
<10:18:40> Exception: The message body cannot be read multiple times. To reuse it store the value after reading.
```

Version: 5.0.1

**Comment by paolosalvatori** [comment]
@lkurzyniec do you experience the issue with the latest version and/or release?

**Comment by lkurzyniec** [comment]
@paolosalvatori yes, all the time.
![](https://imgur.com/PJwfhXg)

**Comment by paolosalvatori** [comment]
@SeanFeldman @ErikMogensen are you planning to fix this issue? Otherwise, I'll have to reserve some time in the coming weeks to fix this issue.

**Comment by ErikMogensen** [comment]
This issue should be fixed by PR #496. @lkurzyniec, is it possible for you to verify that by building and testing the develop branch?

Since this is a critical functionality and another bug #492, also solved by #496 is worse I think we should aim for making a new release.

**Comment by paolosalvatori** [comment]
@ErikMogensen @SeanFeldman is #496 solves this issue + #492, let's ship a new release 😄

**Comment by ErikMogensen** [comment]
@SeanFeldman , I'd would appreciate it if you created the release.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/f87537a5ded12501a9e33fc3edd2a29487246425

**Comment by paolosalvatori** [comment]
Thanks @SeanFeldman @ErikMogensen 😄

**Comment by lkurzyniec** [comment]
@ErikMogensen downloaded the newest version (5.0.2) with chocolatey and confirmed that the fix made the job, well done, thank you!

**Comment by ErikMogensen** [comment]
Thanks @lkurzyniec! I was a bit surprised that you were able to download it from Chocolatey since there were an issue with an icon url in the latest packages but I see now that you may download packages even though they are not approved. That icon url should be correct in the next release, 5.0.3.
