### ISSUE TITLE
Ability to remove a Message Property in MessageForm

### ISSUE THREAD

**Issue by sillo01** [paolosalvatori/ServiceBusExplorer#518]
I am able to add message properties in the Send Message. Once a property is added I can not find a way to remove it.
![Screenshot 2021-02-05 162412](https://user-images.githubusercontent.com/10253834/107095638-c7ec2d00-67ce-11eb-909e-41021fdb61c9.png)

**Comment by SeanFeldman** [comment]
It's not very intuitive but if you select a row and press <kbd>Delete</kbd> that will do it.

**Comment by sillo01** [comment]
Thanks, it never came to my mind using the keyboard.
