### ISSUE TITLE
Multi select & delete

### ISSUE THREAD

**Issue by ekevoo** [paolosalvatori/ServiceBusExplorer#52]
Should allow multi-select of queues, topics, subscriptions, for deletion.

**Comment by SeanFeldman** [comment]
Multi-select would be tricky, considering that control used to handle the tree is a `TreeView` and that one doesn't have a good multi-select support.

**Comment by paolosalvatori** [comment]
Agreed. And I don't think you want to take the risk of deleting multiple queues in a production environment.

**Comment by ekevoo** [comment]
What if that's exactly what I want to do? What if I have a stuck topic because it reached the 2000 subscriptions limit and I need to un-stuck some hundred devices NOW?

I'm not asking for an easy, "fat-fingerable" way to multi-delete. I don't mind if it's buried 5 menus deep. I just want ONE way to multi-delete.

**Comment by SeanFeldman** [comment]
@ekevoo there are two questions here:
1. Warning users about multiple entities removal (UI concern)
2. Technical ability to track multi-selected items when using `TreeView` control

Assuming first question is addressed with super-duper clear warning, the second question remains unanswered. I have very limited experience with WinForms and can't spend time on researching the options. Would it be something you could help with?

**Comment by paolosalvatori** [comment]
@ekevoo if you such a have a large amount of entities in a production environment, I highly suggest you to create PowerShell scripts rather than using my tools to update or delete a large number of topics, queues or subscriptions.

**Comment by ekevoo** [comment]
If production use is not recommended, then why the worry about production
misuse?

I already created a small winforms app to fix my problem. Powershell is no
good because I needed a basic UI to check status and pick the right topic.

**Comment by paolosalvatori** [comment]
I will eventually enable multi-entity selection on the treeview. Time permitting :)

**Comment by SeanFeldman** [comment]
@ekevoo what about nested path option? ("path/to/your/queue")
If you have queues arranged in the following way
![image](https://cloud.githubusercontent.com/assets/1309622/25537067/4769ff86-2bfa-11e7-9f82-47efb077d8a4.png)
You could delete X and remove everything beneath it (Y and Z).

Does that work for you?

**Comment by SeanFeldman** [comment]
@ekevoo would you be interested in sending a PR to help with this feature request?

**Comment by ekevoo** [comment]
Unfortunately I'm no longer working with Azure or Visual Studio anymore.

On Jan 29, 2018 18:37, "Sean Feldman" <notifications@github.com> wrote:

@ekevoo <https://github.com/ekevoo> would you be interested in sending a PR
to help with this feature request?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/paolosalvatori/ServiceBusExplorer/issues/52#issuecomment-361395101>,
or mute the thread
