### ISSUE TITLE
on which branch initial code example reside that shown at youtube

### ISSUE THREAD

**Issue by tutul2010** [paolosalvatori/ServiceBusExplorer#521]
Hi,
I am new to pub-sub and SB message broker model and try to understand it properly.
I watched this you tube vid(https://www.youtube.com/watch?v=gQ5P8WVpj30&ab_channel=NickChapsas) and trying a initial kick start for me .I understood that Showed code  example is very helpful  for me.
It will a great help for me if any body tell me that where the  initial code example resides which shown at you tube vid.

Many thanks,

**Comment by tutul2010** [comment]
Thank you @ErikMogensen.

**Comment by ErikMogensen** [comment]
Good luck with your learning @tutul2010!
