### ISSUE TITLE
How does ServiceBusExplorer decide the message Status

### ISSUE THREAD

**Issue by rad-app** [paolosalvatori/ServiceBusExplorer#522]
How does ServiceBusExplorer decides the message Status

**Comment by SeanFeldman** [comment]
Message status is a system property on each message. SBE reflects that value.

**Comment by rad-app** [comment]
Message Status Property is not exposed through Azure SDK. Is SBE using Azure SDK internally or something else?
Can you please help me with the exact code where SBE derives the Message Status Property? Here I want to know if message is submitted from some other client to service bus queue without setting the status then how SBE derives the message status?

**Comment by ErikMogensen** [comment]
Message status is not exposed by the Azure Service Bus service when you are communicating with it using AMQP. However, it is exposed when you are using the SBMP protocol. The [oldest Service Bus SDK](https://www.nuget.org/packages/WindowsAzure.ServiceBus/) is able to communicate with the Service Bus service using SBMP so it is exposed it that library.

There is a request for adding support for message status when using AMQP at https://github.com/Azure/azure-service-bus/issues/95
