### ISSUE TITLE
Switch main window text/name/header to current connection ASB namespace.

### ISSUE THREAD

**Issue by groozin** [paolosalvatori/ServiceBusExplorer#523]
At the moment of the issue when I have multiple SBE windows opened at the same time and connected to 3 (basically more than 1) ASB instances, I can't really tell the difference between them by looking at the windows. Either during task switching (like Alt-Tab shortcut on Windows) or using gestures on Touchpad or when hovering over the SBE icons in the taskbar. 

See below for screenshots.
![image](https://user-images.githubusercontent.com/3785575/111395410-1984b300-86bd-11eb-94d1-a68a3c601d1f.png)
![image](https://user-images.githubusercontent.com/3785575/111395434-22758480-86bd-11eb-8068-80f9ba381195.png)

Can we switch the main title/text of the window to ASB namespace when the connection is loaded/made?

**Comment by ErikMogensen** [comment]
Great idea!
