### ISSUE TITLE
time format should include ss.ffffffff

### ISSUE THREAD

**Issue by qsdfplkj** [paolosalvatori/ServiceBusExplorer#530]
when looking at the scheduleEnqueuetime and equeue time's both are in minutes.... would be nice to see a more precise time that includes seconds and milliseconds.

**Comment by SeanFeldman** [comment]
Out of curiosity, what's the use case for such precision that I have a feeling cannot be guaranteed by the broker.

**Comment by qsdfplkj** [comment]
I don't understand what you are referring to about precision of the broker. Displaying the seconds would already be very helpful for me. The milliseconds/microseconds I guess can live without.
The reason I would like to include seconds is that I've some messages in the DLQ and I'm trying to correlated messages in the logfile or app-insight and this might help pinpoint the cause. Especially with lock tokens expiring after seconds not minutes and I use the scheduled enqueue time to handle deferred messages where the schedule enqueue time is exponential in seconds.

**Comment by paolosalvatori** [comment]
@qsdfplkj when I implemented this feature I had in mind scenarios where message consumption is scheduled after minutes, not seconds. We could simply replace the actual textbox with a smaller textbox + dropdownlist where you can select the unit of time:
- seconds
- minutes
- hours
The solution should be relatively simple to implement. @qsdfplkj let us know if you can implement this feature and submit a PR, thanks.

**Comment by qsdfplkj** [comment]
https://github.com/paolosalvatori/ServiceBusExplorer/pull/535

**Comment by ErikMogensen** [comment]
@qsdfplkj, please post one or more screenshots of the GUI changes.
