### ISSUE TITLE
export messages to file

### ISSUE THREAD

**Issue by bschelst** [paolosalvatori/ServiceBusExplorer#534]
hi,
Maybe I'm just being blind, but is there a way to export all queues messages to a file?
I can view the data, but don't see option to export them?

**Comment by ErikMogensen** [comment]
It is a bit hidden. Select multiple messages and then right click.
![image](https://user-images.githubusercontent.com/9644248/114319248-01b01b80-9b11-11eb-8085-0ffe1e468adf.png)

**Comment by ErikMogensen** [comment]
I hope that answered your question. Reply here if it didn't.
