### ISSUE TITLE
Faulty values displayed for a message `ExpiresAtUtc` and `TimeToLive`

### ISSUE THREAD

**Issue by ben-002** [paolosalvatori/ServiceBusExplorer#539]
## Service Bus Explorer Version
`5.02` or `4.1.112`  - same behavior

## Expected
After sending a message to a topic with a TTL different than default value, if I peek that message, for its `ExpiresAtUtc` and `TimeToLive` correct values should be displayed. Of course corelated with the TTL.

## Actual
After sending a message to a topic with a TTL different than default value, if I peek that message, for its `ExpiresAtUtc` and `TimeToLive` maximum values are displayed. Same thing if the TTL is set at the subscription level or at both levels. However, when I move the message to deadletter(using the Service Bus Explorer tool for testing a subscription), the correct value is displayed. The value is still correct if I once again move the message but this time from deadletter to the active messages. The core behavior of TTL is correct though, messages are auto-deleted after the specified time has passed. It's only **a display issue**. Really confusing one because it's not mirroring the reality.

![image](https://user-images.githubusercontent.com/69915112/117456403-cf97ab00-af50-11eb-91fb-76cb7472822e.png)

![image](https://user-images.githubusercontent.com/69915112/117455977-5e57f800-af50-11eb-8ef4-62cfb6628b80.png)

**Comment by ErikMogensen** [comment]
Hi @ben-002, I just tried this with the current develop branch, which should have the same behavior regarding this as the versions you tested it on. I put 600 seconds (=10 minutes) as TTL and put it on a queue with a 1 minute Default Time to Live. After 2 minutes I started a receive which caused the messages to be moved to the DLQ. 

Then I used sent a message to the queue again and it added 10 minutes to the current time for the TTL , which makes sense to me. 

Please provide more details of how to reproduce this issue and what is not working as expected.

**Comment by ben-002** [comment]
When a message arrives **for the first time** into a subscription, its `ExpiresAtUtc` and `TimeToLive` are displayed incorrectly(e.g 12/31/9999 for `ExpiresAtUtc`). The displayed values are not the real ones, as the message will expire after the specified TTL will pass. However, as I mentioned, and you have already seen, `ExpiresAtUtc` and `TimeToLive` will be correctly displayed if the message will is moved to deadletter. So, the problem is not in deadletter on in moving the message back on the queue - that was just an example where things work as expected. The displayed value when a message arrives for the first time looks faulty in my case.

**Comment by ben-002** [comment]
To reproduce just send a message to a subscription with a TTL and check its `ExpiresAtUtc` and `TimeToLive`. Nothing else.

**Comment by ErikMogensen** [comment]
I tested to send two messages with 90 seconds TTL to a topic with three subscriptions. The ExpiresAtUTC and TimeToLive look correct on all of the messages in all of the subscriptions.

We recently updated the depending NuGet packages, perhaps that fixed this. I am not sure if that was part of the 5.0.2 release. Please download and build the latest from the develop branch if that is possible for you.

**Comment by ben-002** [comment]
From the latest develop branch

https://user-images.githubusercontent.com/69915112/117717999-32ed3b80-b1e4-11eb-85b7-6afbbf6accf2.mp4

**Comment by paolosalvatori** [comment]
@ben-002 any news on this issue?

**Comment by ben-002** [comment]
Hello @paolosalvatori.  I haven't had the chance to look into what @ErikMogensen suggested, yet. So, no updates from my side at this moment.

**Comment by ben-002** [comment]
Ok, first thing first, I've created a new Console Application using the same package ServiceBusExplorer has - **WindowsAzure.ServiceBus**. This is the result(also visible in what @ErikMogensen already posted). 

![image](https://user-images.githubusercontent.com/69915112/118488041-01b0c600-b724-11eb-9fb1-71385a680b33.png)

Right after the message is received, the value is wrong.

Second thing, I've created a new Console Application using the latest package -  **Azure.Messaging.ServiceBus**.

![image](https://user-images.githubusercontent.com/69915112/118487542-7df6d980-b723-11eb-8bff-add580fca4e9.png)

As you can see, the malfunction is present in both packages. I will write here once I create issues on their dedicated repos.

**Comment by ben-002** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/21127

**Comment by ErikMogensen** [comment]
@ben-002, I see that you got an answer that this is a service side issue. I suggest you create an issue for that in https://github.com/Azure/azure-service-bus/issues/.

**Comment by ben-002** [comment]
Well I'm a bit confused right now. They say in their response that this behavior it's expected. I posted a new comment asking for more details. I also opened an issue on the service: https://github.com/Azure/azure-service-bus/issues/432

**Comment by ben-002** [comment]
@ErikMogensen @paolosalvatori This is by design. The explanation is posted here:https://github.com/Azure/azure-sdk-for-net/issues/21127
I will close the issue now.
