### ISSUE TITLE
"field must be a number" when creating queue/topic entity

### ISSUE THREAD

**Issue by kaluznyt** [paolosalvatori/ServiceBusExplorer#548]
Hello, 

I noticed in the newer versions when creating a messaging entity like queue or topic, and not filling in all of the fields it cannot create due to validation "The X value of the X field must be a number". It seems it was a good approach to default to 0 when a value is not provided. But perhaps there is some thought behind adding this validation ? It's not an issue, but just a small inconvenience :)

Tomasz

**Comment by ErikMogensen** [comment]
Hi,

I just tested to create a queue and a topic and both worked as long as I put anything in the Relative URI textbox. For a short while this didn't work but I don't think that was released. 

Have you tried the latest version? There were some versions released where it shows the latest released version in the About box even though the actual version is not that version.

**Comment by kaluznyt** [comment]
I just downloaded latest version, yet this is occurring:
![image](https://user-images.githubusercontent.com/572605/118867619-90b80c80-b8e3-11eb-8870-0f85b7120fa1.png)
![image](https://user-images.githubusercontent.com/572605/118867643-97468400-b8e3-11eb-8e8a-b85de653f42a.png)
![image](https://user-images.githubusercontent.com/572605/118867663-9ca3ce80-b8e3-11eb-867d-33b42c6acc00.png)

**Comment by kaluznyt** [comment]
other issue I think worked earlier is when I have a queue with "session" enabled, I'm not able to view the messages due to:
<20:49:47> The queue abc has been successfully created.
<20:49:55> Exception: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:d18faf83-a76e-45fa-b305-fd2b61e0be1a_G1_B0, SystemTracker:abcdefg123:Queue:abc, Timestamp:2021-05-19T18:49:54
<20:49:55> InnerException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:d18faf83-a76e-45fa-b305-fd2b61e0be1a_G1_B0, SystemTracker:abcdefg123:Queue:abc, Timestamp:2021-05-19T18:49:54
but that's another thing, perhaps I could create another case

**Comment by kaluznyt** [comment]
Ok, just took a look at the code in TimeSpanControl and it seems that it's by design that all of the particular fields are being validated, so perhaps need to just live with it and always put zeroes in the empty fields :)

**Comment by ErikMogensen** [comment]
Hmm, strange. Are you able to create a queue just by filling in the _Relative URI_ field and then clicking _Create_? 

Please create another issue for the session problem.

**Comment by kaluznyt** [comment]
yeah, if there is just Relative URI then it creates it with all defaults, but if just any number is put in any of fields like I would like 1 minute lock timeout, then it fails the validation, since other "empty" fields need to be filled with zeroes

**Comment by ErikMogensen** [comment]
I see. 

@Greybird, it would be great if you looked into how this could be fixed.

**Comment by Greybird** [comment]
@ErikMogensen sure, will take à look !
