### ISSUE TITLE
Bug when getting messages from session-enabled queue

### ISSUE THREAD

**Issue by kaluznyt** [paolosalvatori/ServiceBusExplorer#549]
Hello, 

There seem to be some bug introduced in the newest version, I compared dev with master branches, and dev is working fine, and master have the issue (as well as 5.0.3 release). 

Issue is, when there is a session-enabled queue it is not able to get the messages and getting an error:
<22:03:54> Exception: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:1c3b5adc-53de-44b0-88d0-4233e3b9ee11_G9_B27, SystemTracker:tkaluzny1234:Queue:abc, Timestamp:2021-05-19T20:03:53
<22:03:54> InnerException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:1c3b5adc-53de-44b0-88d0-4233e3b9ee11_G9_B27, SystemTracker:tkaluzny1234:Queue:abc, Timestamp:2021-05-19T20:03:53

It's most probably some issue around the queueclient/message receiver handling in ReceiveModeForm GetMessages method, now it seems it relies only on fromSessoin variable, which is always null, and has been in the previous versions, but there was another flag earlier which indicated if a queue is "session enabled". That flag seems to be missing now hence it most probably created a queue client for session enabled queues.

**Comment by SeanFeldman** [comment]
Duplicate of https://github.com/paolosalvatori/ServiceBusExplorer/issues/545?

**Comment by kaluznyt** [comment]
yeah, true :) closing
