### ISSUE TITLE
Tab order in 'Enter Topic Filter Expression' is out of order

### ISSUE THREAD

**Issue by 2ndcahl** [paolosalvatori/ServiceBusExplorer#551]
5.0.3.
Right-click "Topics" and select "Filter Topics"
Press Tab on the keyboard several times and you will see that it is not in order.
Expected it to change to the different fields/button, starting from the top and working it's way down.

**Comment by ErikMogensen** [comment]
Yes, you are right. There are a lot of places where this is not set. I'll work on this.
