### ISSUE TITLE
Purge messages in queue not working in 5.0.3

### ISSUE THREAD

**Issue by SeanoNET** [paolosalvatori/ServiceBusExplorer#554]
Hi,

The purge button on the `HandleQueueControl` is no longer removing active messages from the queue and is instead removing dead-letter messages in Service Bus Explorer version 5.0.3.

To repro:

1. Double click queue that has at least one active message and hit the 'Purge' button.
2. Click 'OK' when the message dialog appears.
2. Active message(s) are not deleted, instead messages in the dead-letter queue are deleted.

Status message also displays
```<17:13:49> [0] messages have been purged from the dead-letter queue of the [test] queue in [0] seconds.```

**Comment by SeanFeldman** [comment]
Fixed in https://github.com/paolosalvatori/ServiceBusExplorer/commit/1259cc8035e1e3b953c3c6f7de983d7086a8ad30
