### ISSUE TITLE
ServiceBusExplorer not opening anymore on Windows 10 with latest update

### ISSUE THREAD

**Issue by asadsahi** [paolosalvatori/ServiceBusExplorer#557]
There was a windows 10 update yesterday, since then ServiceBusExplorer is not opening anymore (Doesn't give any error either). This is my current windows 10 version:
![image](https://user-images.githubusercontent.com/3470892/120445929-02329900-c381-11eb-93c4-3984d7c59d01.png)

I suspect this is because SB explorer's publisher is unknown, but not sure as it doesn't give any indication. Checking through windows compatibility tool, it says this isn't compatible.

Stuck with this now, so any clue/workaround is appreciated until we have a working fix for it.

**Comment by ErikMogensen** [comment]
@asadsahi, what do get get if you enter `ver `in a command prompt? I get `Microsoft Windows [Version 10.0.19042.928]` and it starts on my computer.

**Comment by asadsahi** [comment]
@ErikMogensen this is my version:
```
Microsoft Windows [Version 10.0.19042.1023]
```

**Comment by ErikMogensen** [comment]
I tried on another computer and that one had [Version 10.0.19043.985] and it worked. Then I saw that there was some optional update in the Windows update dialog which I installed. After that it now has [Version 10.0.**19043**.1023] . ServiceBusExplorer 5.0.3 still works. 

Strange that you are running a different build (19042), but with the same Revision (1023).

Some questions:

1. Have you checked the event log for error messages? 
2. Is the computer connected to a AD with policies that may block ServiceBusExplorer? 
3. Are other programs working? 
4. If you build a desktop exe wtih VS, are you able to run it? 
5. Have you unblocked all files in the directory?
6. What happens if you try to debug it?

**Comment by asadsahi** [comment]
Thanks @ErikMogensen 

Have you checked the event log for error messages?
_This was the first thing I checked and nothing in event logs._

Is the computer connected to a AD with policies that may block ServiceBusExplorer?
No. I am logged in on my own computer with admin rights with no AD.

Are other programs working?
Yes. All other programs are working fine, only SBE.

If you build a desktop exe wtih VS, are you able to run it?
Yes. Yesterday I managed to run the debug version of SBE through building in VS. However, there was an Object reference null error at `ServiceBusHelper` line 600, which upon initialising let me run it.

`        public Dictionary<string, ServiceBusNamespace> ServiceBusNamespaces { get; set; } = new Dictionary<string, ServiceBusNamespace>();`


Have you unblocked all files in the directory?
I can't see any option to unblock. However all files aren't read only or hidden if that is the option you meant.

What happens if you try to debug it?
It runs with debug under VS as explained above after resolving Object reference error.

It could possibly be specific to my machine but can't explain why none of the versions work, but debug one works. Tried the release version from develop branch and that works too.

**Comment by ErikMogensen** [comment]
I suspect that this is due to the contents of the user profile servicebusexplorer configj file. It is located at  %APPDATA%\Service Bus Explorer, for instance  C:\Users\erik\AppData\Roaming\Service Bus Explorer.

If there is a file called UserSettings.config there, rename it and try again.

**Comment by asadsahi** [comment]
That is correct @ErikMogensen 

It is working now. This isn't anything to do with windows update, but with any misconfigured connection string being saved in that file. e.g SBE doesn't like connection string with `EntityType` in it, even it gives the error, it still saves for some reason, hence stops opening as the logic to load connection string seems to be in startup somewhere.

Deleting the config file as mentioned from above location would fix this as well.

Thanks, closing the issue.

**Comment by ErikMogensen** [comment]
@asadsahi, glad that you found it. This is a bug and should be fixed. How did the connection string look like? You can xxx the actual entity names.

**Comment by asadsahi** [comment]
@ErikMogensen I am trying to replicate the error with different combinations of connection strings, but can't see this happening anymore. Will keep an eye out and if this occurs again, will try and find out specific connection string which caused this issue.

**Comment by ErikMogensen** [comment]
Can you do a restore from recycle bin?

**Comment by asadsahi** [comment]
Sorry @ErikMogensen I modified the original config file, didn't delete it.
