### ISSUE TITLE
Is this a MS official tool?

### ISSUE THREAD

**Issue by OneMoreSecond** [paolosalvatori/ServiceBusExplorer#558]
I'm not very clear after reading README

**Comment by ErikMogensen** [comment]
No, it is not supported by Microsoft. We should probably update the usage agreement. @paolosalvatori, who works at Microsoft, initially created the tool as a Microsoft sample so I guess the license agreement is left from that time.

**Comment by paolosalvatori** [comment]
The tool is provided under Apache license: you can find the license in the main folder: https://github.com/paolosalvatori/ServiceBusExplorer/blob/develop/LICENSE.txt 😃
