### ISSUE TITLE
Click on "Purge" tries to purge Dead letter queue

### ISSUE THREAD

**Issue by kaluznyt** [paolosalvatori/ServiceBusExplorer#559]
Hi, 

Noticed when I click on Purge on a queue, it displays log 
<09:38:14> [0] messages have been purged from the dead-letter queue of the [queue] queue in [0] seconds.

same as when clicked on Purge DLQ, 

I guess this is some kind of bug ? (Messages are not purged)

**Comment by bhugot** [comment]
Same here

**Comment by kaluznyt** [comment]
Just to add, this is observed in v5.0.3
Workaround - use v5.0.2

**Comment by ErikMogensen** [comment]
Yes, that is not good. This is a duplicate of #554. It is fixed in the develop branch and we are working on releasing 5.0.4 where the fix for this is included.
