### ISSUE TITLE
peeking the dead letter queues only peeks up to 250 messages

### ISSUE THREAD

**Issue by joellyons** [paolosalvatori/ServiceBusExplorer#56]
Find a queue or subscription that has lots of messages in the deadletter queue.  Try to peek more than 250 and notice you can only ever get 250 messages back.  Receiving more than 250 messages seems to work fine.

**Comment by joellyons** [comment]
I submitted a pull request with a possible fix for queues and subscriptions.

**Comment by SeanFeldman** [comment]
@paolosalvatori good to close?

**Comment by paolosalvatori** [comment]
Sorry guys, I'm quite busy in this period. Did you fix the problem via a pull request? Thanks!

**Comment by joellyons** [comment]
I pulled the latest @SeanFeldman after you merged my pull request and have been using the Explorer ever since and it seems to be working fine at least in my environment.

**Comment by SeanFeldman** [comment]
👍
