### ISSUE TITLE
Cannot save entity specific connection string

### ISSUE THREAD

**Issue by avdv** [paolosalvatori/ServiceBusExplorer#560]
My connection string includes an `EntityPath=...` stanza at the end.

Trying to save this string in the connection dialog displays an error message:
![image](https://user-images.githubusercontent.com/3471749/121493446-240eca00-c9d8-11eb-95b4-4b5a30e21ba3.png)

Removing the Entity Path setting and hitting "Save" stores the configuration.

But I cannot connect without the entity path being present, so every time I need to use `File -> Connect..`, enter the entity path and hit OK instead of just using the saved connection from `File -> Saved Connection` (ie. <kbd>Ctrl+1</kbd>).

**Comment by avdv** [comment]
Wouldn't this just need the same change is in https://github.com/paolosalvatori/ServiceBusExplorer/pull/422 ? 

Ie. just remove this check: https://github.com/paolosalvatori/ServiceBusExplorer/blob/af1aabc961d1ec2308a11950e544a9d2fcccc938/src/ServiceBusExplorer/Forms/ConnectForm.cs#L625-L635
:question:

**Comment by ErikMogensen** [comment]
@avdv, can you try it? If it works, please create a PR for it.
