### ISSUE TITLE
Unable to submit message, GAC

### ISSUE THREAD

**Issue by ryanbowden** [paolosalvatori/ServiceBusExplorer#561]
`<09:41:09> Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
`

Seems I have come across this issue again #525 , #438, #414

Fixed it on my last machine but now happening a new machine I recently got. But really struggling to fix it this time. Can't remember what I did, think I added the package to GAC in the end. 

Think bigger this is there a code change that can be made to this software so it stops trying to use the GAC and use the packages it has download?

**Comment by ErikMogensen** [comment]
This seems to be a common issue. I checked two NuGet package versions for [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus/) (which contains the Microsoft.ServiceBus.dll assembly), v4.1.1 and the latest, v6.1.1 and both have the same strong name, `Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`.

To the best of my knowledge there is no way of preventing the Assembly loader from loading the assembly in the GAC (Global Assembly Cache) if the strong name reference in the calling assembly matches the one in the GAC. The official information about how the Assembly loader locates an assembly is available [here](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies).

My recommendation is to use gacutil to either remove the Microsoft.Service assembly from the GAC or replace it. 

Assuming that you have gacutil.exe in your path then one way of removing it is to:

1. Start a command prompt in administrative mode.
2. Enter `gacutil /u Microsoft.ServiceBus`

If you want to replace the Microsoft.Service assembly instead you can do like this:

1. Start a command prompt in administrative mode.
2. Navigate to the ServiceBusExplorer directory.
3. Enter `gacutil /if Microsoft.ServiceBus.dll`

There is more information about assemblies in the GAC [here](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/working-with-assemblies-and-the-gac).

**Comment by codes4pizza** [comment]
I also had this issue back in March. I found that an old install of KingswaySoft SSIS Productivity Pack had added the Microsoft.ServiceBus.dll assembly to the GAC. After uninstalling that product i was able to submit messages.

Using gacutil to remove was not an option because the installer had placed some kind of lock/reference on the file.

**Comment by ryanbowden** [comment]
@ErikMogensen I went with you second option and overwrote the old one. Thank you.
