### ISSUE TITLE
Resubmit Messages in Batch Mode

### ISSUE THREAD

**Issue by markbartolo** [paolosalvatori/ServiceBusExplorer#564]
Hi,

Is there a limitations to the number of messages that you can resubmit form the Deadletter queue at once in batch mode?

![image](https://user-images.githubusercontent.com/15801722/121876966-630b8b00-cd0a-11eb-83fd-b316060a57ed.png)

Thanks.

**Comment by ErikMogensen** [comment]
There is no limit. It used to be a limitation depending upon the size of the messages and which Service bus SKU was receiving the messages. This was changed three years ago and now the messages are sent one by one instead, which removes the limit so you can send as many as you want.

**Comment by markbartolo** [comment]
Thank you @ErikMogensen
