### ISSUE TITLE
MessageID in body of message does not match MessageId of the Message System Properties right pane

### ISSUE THREAD

**Issue by ngreyes** [paolosalvatori/ServiceBusExplorer#565]
MessageId in body of a dead letter message does not match MessageId of the Message System Properties right pane.

I'm no expert on this and realize that developers may customize the properties, but it will be nice to know if the message id in both sides should match.   Additionally the session Id does not appear on the right pane.

Any comment is appreciated.  Using Service Bus Explorer ver. 5.0.3.

**Comment by ErikMogensen** [comment]
What do you mean by the message id in the body? Is that something the sending application put there? A screenshot may help.

**Comment by paolosalvatori** [comment]
Do you mean that the MessageId that you set explicitly with the UI of the tool does not correspond to the messageId you see when peeking or reading the message?

**Comment by ngreyes** [comment]
The message send from one micro service to another in our case is a Json string which contains a message ID, session ID and others.   I though that that those IDs corresponded to the IDs on the side panel, but I gather by you questions that that's not the case.  The side panel I guess has the real IDs for the message sent and not the customized content.  I'm going to close this.
