### ISSUE TITLE
Consuming messages in event hubs with schema registry

### ISSUE THREAD

**Issue by TrujilloGarcia** [paolosalvatori/ServiceBusExplorer#568]
Currently from what I have seen the application does not support the use of the schema registry. Is there a simple way to solve this or some other alternative?
In the same way, would it be possible for this functionality to be implemented in future versions or would it be difficult?

**Comment by ErikMogensen** [comment]
I see in the article [Azure Schema Registry in Event Hubs (Preview)](https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview) that this functionality is still in preview. @paolosalvatori, @SeanFeldman, do we have any policy regarding using features that are in preview? In my opinion we could allow it if it is in code that is only executed when the user has chosen to and it is clearly stated in the GUI that this feature is in preview.

It seems like there is some work needed to get this working. Assuming that this will GA your best bet for getting this functionality is to create a PR for this yourself. However, this seems like a quite useful feature that may be used for Service Bus too so perhaps someone else will implement support for it.

**Comment by SeanFeldman** [comment]
I've had a mixed experience with Previews. For example, Service Bus large messages Preview is rolling out for over 6 months now. And I don't think the public preview is out yet (not sure). Blob Index Tag took almost a year and some things were working, some not, availability depended on region, etc. So I'm not a good advisor here. For me it would depend on:
1. How "stable" the preview is?
1. What are the moving parts?
1. What's a tentative date to have the preview wrapped.

A long-standing PR to add the functionality is fine but would need to be constantly be rebased on top of ever-changing `develop` to avoid stailness.
