### ISSUE TITLE
Subscription filtering not working

### ISSUE THREAD

**Issue by mack0196** [paolosalvatori/ServiceBusExplorer#571]
I've tried using name, subscription, path, subscriptionName with like '%...%' but I get a fail like this.
What is the correct way to set a subscription filter in Service Bus Explorer? 

<11:30:24> Exception: The remote server returned an error: (400) Bad Request. Invalid Filter. The specified property 'subscriptionName' does not exist or is not allowed.

           Parameter name: propertyName TrackingId:16ff4ca9-cfb3-4e62-ae06-38be5276d9a0_B17, SystemTracker:NoSystemTracker, Timestamp:2021-06-29T16:30:23

**Comment by ErikMogensen** [comment]
You can set the filter either SQL style or Correlation style. These styles are the standard ones and are described [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/topic-filters). Very similar functionality is available in the Azure Portal.

Here is an example of a filter:
![image](https://user-images.githubusercontent.com/9644248/124376206-1c280a00-dca6-11eb-826e-b71bfbbf4c6e.png)

Which tier is your service bus namespace in? You need the Standard or Premium tier to use topics.

Do you get the error when adding the filter? 

Do you get the same error when adding the filter using the Azure Portal?

**Comment by mack0196** [comment]
Using 'Name LIKE 'something%' on the topic to filter subscriptions gives me this error
![image](https://user-images.githubusercontent.com/6463105/141826027-4eb823ed-d5cf-4b5e-be9f-aa4a96867e77.png)
