### ISSUE TITLE
Getting the list of queues times out

### ISSUE THREAD

**Issue by sksk571** [paolosalvatori/ServiceBusExplorer#574]
We have about 7000 queues in a single namespace (these are development queues created for local testing and QA). Attempt to view them in ServiceBusExplorer finishes with the timeout error:
```
Failed to retrieve Service Bus queues. Exception: System.TimeoutException: The operation has timed out.

              at ServiceBusExplorer.ServiceBusHelper.GetQueues(String filter, Int32 timeoutInSeconds) in C:\projects\servicebusexplorer\src\Common\Helpers\ServiceBusHelper.cs:line 1589

              at ServiceBusExplorer.Forms.MainForm.<ShowEntities>d__318.MoveNext() in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4354
```

**Comment by ErikMogensen** [comment]
That's a lot of queues! What's your Server timeout? Increase it until it works.
![image](https://user-images.githubusercontent.com/9644248/124503741-77511e00-ddc6-11eb-9764-0b686cb224e1.png)

In case you don't know about it, you can filter queues based on their name. PR #468 added the ability to put different colors on them depending upon name and whether they are leaf queues or not.

**Comment by SeanFeldman** [comment]
Are 7000 queues the result of all lower environment/devs sharing the same namespace or there's a legitimate need in that number of queues?

**Comment by sksk571** [comment]
Increasing timeout to 300 seconds fixed the issue, thanks.

@SeanFeldman this namespace is shared between dev/QA environments, therefore it contains so many queues.

**Comment by SeanFeldman** [comment]
That's what I suspected. Standard tier namespaces are intended specifically for that and do not cost anything additional. The practice of sharing a single namespace among developers and testers is unnecessary in most scenarios. You might want to look into provisioning a namespace per developer/QA environment. This will lead to less complexity, reduced number of entities, remove dependencies and improve your experience working with ASB.

**Comment by luanraithz** [comment]
I had the same issue, my scenario was an e2e test that didn't clean up the queues and I couldn't even use the explorer to delete them (timeout when listing the queues).
Everytime the application started, about 20 queues were created and after about a month we reached the limit of 10k :P

**Comment by ErikMogensen** [comment]
@luanraithz, what is your timeout setting?

**Comment by luanraithz** [comment]
I was able to list the queues increasing the timeout to 300, as suggested in the issue previously.

During the process of cleaning up the queues the program stopped working multiple times, but it worked.

**Comment by ErikMogensen** [comment]
Good.

> During the process of cleaning up the queues the program stopped working multiple times, but it worked.

Did it freeze and then worked after a while or did it crash?

**Comment by luanraithz** [comment]
It froze but worked. Never crashed.
