### ISSUE TITLE
Could not load file or assembly "System.Runtime.CompilerService.Unsafe, version=4.0.4.1 ..."

### ISSUE THREAD

**Issue by darkurse** [paolosalvatori/ServiceBusExplorer#576]
**Version affected :** 
5.0.4

Using the "ServiceBusExplorer-5.0.4.zip" zip file.

**repro steps :**
Click the topic name in the tree view generates this message in the logs below.

![image](https://user-images.githubusercontent.com/1208226/124902828-9b3d7b00-dfe3-11eb-8781-6be63171eaeb.png)

**NB:** I have to add the "purge messages" action doesn't seem to work either but this could be due to the above error. 
       Version 5.0.3 couldn't purge messages which is the reason why I downloaded the latest version.

**Comment by ErikMogensen** [comment]
v5.0.4 contains `System.Runtime.CompilerService.Unsafe, Version=4.0.5.0` so there must be something redirecting it to an older version. Have you kept your servicebusexplorer.exe.config file between upgrades? If so, please use the servicebusexplorer.exe.config  from 5.0.4 and copy just the settings you need from the old config file, which is usually only the connection strings to the new config file.

I recommend to use the _User Configuration file_ setting to avoid trouble when upgrading.
![image](https://user-images.githubusercontent.com/9644248/125158960-9956f180-e174-11eb-88d9-7c0315524255.png)

**Comment by darkurse** [comment]
Spot on ! Thank you very much.

**Comment by ErikMogensen** [comment]
Great! We have to fix the update procedure somehow.
