### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by iM4rv** [paolosalvatori/ServiceBusExplorer#58]
http://1drv.ms/1nEl7ps

**Comment by paolosalvatori** [comment]
Strange it works for me. I will ask someone else to check it. Thanks!

**Comment by tomkerkhove** [comment]
Doesn't work on my machine as well but you should be able to download one of the releases over here.
That works for me..

**Comment by paolosalvatori** [comment]
Try this link: https://1drv.ms/u/s!AmUKNmugpNsJrgLTaTXkRW1O07iE

**Comment by SeanFeldman** [comment]
@paolosalvatori I really think rather than having a zip on OneDrive this should be a branh (support branch).

**Comment by iM4rv** [comment]
Thanks! Works now.

**Comment by paolosalvatori** [comment]
@seanfeldman I agree with you, but I don't have time for doing it :) Can you help me with that? Thanks :)

**Comment by SeanFeldman** [comment]
@paolosalvatori since I'm not a collaborator on the repo level, external PR can only target an existing branch. Two options

1. Create a `support-2.1` branch
1. Make me a collaborator 😛

**Comment by paolosalvatori** [comment]
Hi @SeanFeldman I think that both options are viable :) What about creating a separate project to avoid mixing up the two tools that have a different code base? Thoughts?
Ciao
Paolo

**Comment by SeanFeldman** [comment]
Sure, though it would be strange to have same tool 2 different repos :)

**Comment by SeanFeldman** [comment]
I'll create an orphaned branch `support-2.1` and commit the code from the zip on that one once have admin right to the repo (discussed with @paolosalvatori).
That way we'll have the repo with both code bases (same application) and can have a release linked as well. No more onedrive/dropbox/googledrive links :)
