### ISSUE TITLE
When receiving messages that contain a null messageproperty the system shows a NullReferenceException in the logfile

### ISSUE THREAD

**Issue by wvdd007** [paolosalvatori/ServiceBusExplorer#581]
We are using NServicebus to publish our messages.  This means that all metadata of the messages is more or less handled automatically.  This works fine except for one property "NServiceBus.ExceptionInfo.HelpLink", which happens to be null.  This breaks the code that retrieves the property type.  This can be easily solved by changing 
`public override Type PropertyType => _dictionary[_key].GetType();`
to
`public override Type PropertyType => _dictionary[_key]?.GetType();`

I would do this myself but I don't seem to be able to create a pull request.

**Comment by SeanFeldman** [comment]
@wvdd007 to create a PR you need to fork the repository first.
