### ISSUE TITLE
Microsoft Defender SmartScreen prevents the exe file from executing.

### ISSUE THREAD

**Issue by divekarvinit** [paolosalvatori/ServiceBusExplorer#585]
Here is the image of the error which is displayed when `ServiceBusExplorer.exe` is executed. The same error occurs when it is Run As Administrator.

Error: Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

Service Bus Explorer Version: **5.0.4, 4.1.112**
Operating System: Windows 10 Enterprise
System Type: 64-bit operating system, x64-based processor
OS Build: 19042.1110

![image](https://user-images.githubusercontent.com/18706548/128097610-7c09221d-bee2-487c-b91b-690304484198.png)

**Comment by ErikMogensen** [comment]
Have you unblocked it? See https://github.com/paolosalvatori/ServiceBusExplorer/issues/372#issuecomment-531106179 for how to do it. Since you have unzipped it, you can try to just unblock servicebusexplorer.exe.

**Comment by divekarvinit** [comment]
Sweet! Thanks, @ErikMogensen . That works!
