### ISSUE TITLE
Exported brokered message cannot be imported properly to be sent to a queue

### ISSUE THREAD

**Issue by benclerix-cegeka** [paolosalvatori/ServiceBusExplorer#586]
**Service Bus Explorer version: 5.0.4**

I saved a brokered message in json format (e.g. from a topic). The contents look like this (some properties redacted):

```
{
  "body": {
    *someJsonBody*
  },
  "contentType": "application/json",
  "correlationId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
  "deadLetterSource": null,
  "deliveryCount": 1,
  "enqueuedSequenceNumber": 117004163,
  "enqueuedTimeUtc": "2021-08-13T07:49:14.7043957Z",
  "expiresAtUtc": "9999-12-31T23:59:59.9999999",
  "forcePersistence": false,
  "isBodyConsumed": false,
  "label": null,
  "lockedUntilUtc": null,
  "lockToken": null,
  "messageId": "ed03a9f0-3829-43f9-9a66-c8cb218dfedf",
  "partitionKey": null,
  "properties": {
    "NServiceBus.Transport.Encoding": "application/octect-stream",
    "NServiceBus.MessageId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
    "NServiceBus.MessageIntent": "Publish",
    "NServiceBus.ConversationId": "9585c069-a6af-465a-9a4e-ad830080e1c9",
    "NServiceBus.CorrelationId": "286382a8-2103-4d13-8f1f-ad830080e1c9",
    "NServiceBus.OriginatingMachine": "default000001",
    "NServiceBus.OriginatingEndpoint": "Nservicebus.SomeEndpoint",
    "$.diagnostics.originating.hostid": "9a5fd04bc8db78ec116cde0e70855410",
    "NServiceBus.ContentType": "application/json",
    "NServiceBus.EnclosedMessageTypes": "SomeFQDN, SomeAssembly, Version=1.21.812.13, Culture=neutral, PublicKeyToken=null",
    "NServiceBus.Version": "7.2.3",
    "NServiceBus.TimeSent": "2021-08-13 07:49:14:694480 Z"
  },
  "replyTo": null,
  "replyToSessionId": null,
  "scheduledEnqueueTimeUtc": "0001-01-01T00:00:00",
  "sequenceNumber": 1,
  "sessionId": null,
  "size": 1060,
  "state": 0,
  "timeToLive": "10675199.02:48:05.4775807",
  "to": null,
  "viaPartitionKey": null
}
```

I expected to be able to send this message to a queue:
- Right click on queue: "Send messages"
- Click open and select the brokered message json file
- I generate a new "messageId" and "NServiceBus.MessageId" property.
- I leave the message format to "Text" and click "Start"

This gives me the following result:
![2021-08-13 11_16_13-Window](https://user-images.githubusercontent.com/34366781/129336816-c34eeb09-19cc-4709-9170-253a06af9ad6.png)

The message is successfully sent to the queue
When I look up the new generated message by messageId I see that when a handler picks up the message it is unable to extract logical messages from incoming physical message. In my case this in an NServicebus message, which would use the "NServiceBus.EnclosedMessageTypes" property for this.
When inspecting the message I see that the complete contents of the brokered message in JSON format are in the message body which seems strange to me.

My expectations are that:
- When opening the message I should only see the message body in the "message text" field
- Properties in the "properties" object should be displayed in the "Message Properties" list on the right
- All other properties on the top level should be used behind the scenes

Are my assumptions correct or am I doing something wrong?

I contacted Yves Goeleven about this, who contacted @SeanFeldman about this.
If you need more information to reproduce the issue or if I made a mistake, please let me know.

Also I noticed when I left a message property empty, like this:
![2021-08-13 10_49_18-Window](https://user-images.githubusercontent.com/34366781/129336837-3db6aef2-5375-43f0-a5b8-b915b77be738.png)

I'm getting the following error:
```
<10:47:30> The following validations failed:
 -  property conversion error: Object reference not set to an instance of an object.
<10:47:30> Exception: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.. Method <SendMessages>b__1: retry 1 of 10.
<10:47:30> Exception type was: System.ArgumentNullException.
.....
<10:47:31> Exception: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.. Method <SendMessages>b__1: retry 10 of 10.
<10:47:31> Exception type was: System.ArgumentNullException.
<10:47:31> Sender[0]:
            - Exception occurred: Value cannot be null.
           Parameter name: The BrokeredMessage parameter cannot be null.
            - Message Count=[0] Messages Sent/Sec=[0,0] Total Elapsed Time (ms)=[0]
            - Average Send Time (ms)=[0] Minimum Send Time (ms)=[0] Maximum Send Time (ms)=[0] 
```
Not related to the main issue, but maybe it helps someone in the future.

**Comment by SeanFeldman** [comment]
Thank you for reporting this bug, @benclerix-cegeka. It’s a bug. I’ll take a look at it.

**Comment by SeanFeldman** [comment]
No, no news. Billable time comes first 🤷‍♂️

**Comment by benclerix-cegeka** [comment]
@SeanFeldman sorry for the ping, but the stale bot is working too hard ;)

**Comment by SeanFeldman** [comment]
Yeah, Stalebot is good at its work. I'll look at it, and if it's quick, I will fix it.
No promises, though. My bills need to be paid first 😉

**Comment by SeanFeldman** [comment]
@benclerix-cegeka, I've started a PR (#617). Hopefully, it will not have horrible side effects when completed.
