### ISSUE TITLE
not clear how to start SBE after choco install

### ISSUE THREAD

**Issue by owingruters** [paolosalvatori/ServiceBusExplorer#587]
after choco install it is not clear how to start the application. Its not found in windows search, not as shortcut and not on the desktop. Is also not found in the 32 or 64 bit program files directories, not on the explorer search. Eventually I found it using windosws search, only when typing in fully "servicebusexplorer"
can you update the documentation to clarify how to open after installing?

**Comment by BrettBailey** [comment]
Also took a while to find.

If it helps others for me it was at:

C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe

**Comment by broomfn** [comment]
It's not just me then!

**Comment by halfer53** [comment]
Agree, it took me a while to find the path

**Comment by BrettBailey** [comment]
I had to install choco so that I could install SBE.  Would prefer to just download the binaries.

**Comment by ErikMogensen** [comment]
@BrettBailey, the published zip file contains the binaries.
