### ISSUE TITLE
"Hi mate, how are you?" cannot be changed and persisted

### ISSUE THREAD

**Issue by dracan** [paolosalvatori/ServiceBusExplorer#588]
First of all - thank you for this _amazing_ tool! It's so super-useful.

My comment is a very trivial one, but I thought I'd raise it anyway. It's just about the "Hi mate, how are you?" text that's there by default when trying to send a new message. Azure Service Bus Explorer looks a very well done, professional-quality tool. And this might just be me, but that message just looks silly. When using it in a screen-share - I always feel I have to explain to other people in the call that it's not my message - it's for some reason the default message. It feels like an odd thing to have in an other-wise, very well polished application. It just feels totally out of place.

**Comment by SeanFeldman** [comment]
You can change the default text in the settings to something "All Your Base Are Belong to Us" to make it look more professional.

**Comment by dracan** [comment]
Ah, I didn't realise it was a setting. However, it doesn't seem to work. Whatever I change it to - it doesn't persist. If I close the dialogbox and reopen it, it's back to "Hi mate, how are you?".

**Comment by SeanFeldman** [comment]
> If I close the dialogbox and reopen it, it's back to "Hi mate, how are you?".

Looks like it's greeting you each time, which is expected behaviour 😀

Likely a bug. Want to have a look into it if you have a spare cycle?

**Comment by dracan** [comment]
I've had a quick look - but don't know the codebase well enough to work out the issue without spending more time on it than I have sadly. Obviously - this is very low priority anyway. I just thought I'd mention the default text - as I'm not the only one I've seen use this tool who's raised eyebrows at the choice of default message 😉 

Re. the saving bug - it seems to save it as expected _until_ I open the "Send Message" dialogbox. That then resets the setting back to the default.

**Comment by ErikMogensen** [comment]
@dracan, what do you think is a good message text?

**Comment by dracan** [comment]
@ErikMogensen I don't think it needs any default text. The most natural from at least the way I use it would be... when the SendMessage dialogbox opens, if the message text area is empty, and has focus ready to paste or type straight away into it.

**Comment by ticosido** [comment]
I don't think this is fixed.  If you change the default text to some other value (e.g. "Hello"), it is persisted.  However, if you delete the value entirely, it reverts to the "Hi mate" text.

I'm not particularly au fait with the code, but looking here:

https://github.com/paolosalvatori/ServiceBusExplorer/blob/862a5e9e1950972a86bc5c6c82c739689a5d6ec9/src/Common/Helpers/MessageAndPropertiesHelper.cs#L153

The method it uses checks for the setting being NULL or empty, and if it is, uses the default ("Hi mate") value.

I'd like to be able to have a blank initial value.

**Comment by SeanFeldman** [comment]
@ticosido could you PR that since you've already have the context? Thank you.
