### ISSUE TITLE
Issue sending messages bigger than 1MB

### ISSUE THREAD

**Issue by Uleertel** [paolosalvatori/ServiceBusExplorer#592]
Hi,
First thanks for this amazing tool and all your work.

I'm using a new Premium Service Bus Namespace and created a topic with a maximum message size of 102400KB that is in public preview since a few weeks.
I would like to send test messages to this topic with a text content bigger than the previous limitation of 1MB, using Service Bus Explorer.

## Actual Behavior
1. I tried with the default connection parameters, "send messages" menu on the topic, pasting my text in message text and "start"=> I have a maximum message size Exception.
2. I read this article (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messagingl) and see that we should use the AMQP protocol. So I create a new connection selection "AMQP" as Transport type. => Message sent. **BUT**  when I go to the subscription and get the messages it's empty and the size property is 0.
3. I tried with the "new client" checkbox in the connection window with same result.

## Expected Behavior
1. Is there a way with the current release of service bus explorer to send and receive messages bigger than 1MB?

Thanks

**Comment by SeanFeldman** [comment]
The current ASB SDK used (track 1) doesn't support large messages API. Therefore, it will require the latest ASB SDK (track 2) to send messages larger than 1MB.

**Comment by Uleertel** [comment]
Thank you for your quick answer, is there any plans to move to this track 2 sdk?
And sorry it's a bit out of topic but do you know if the current version of azure function trigger will work with this kind of message?

**Comment by ErikMogensen** [comment]
Actually it is using track 0 (I think @SeanFeldman came up with the idea to call it track 0) for this part of the code. We want to migrate it to track 2 but that depends upon voluntary effort without support from Microsoft. Perhaps @Uleertel, perhaps you want to create a PR for changing this? There is a class with the name ServiceBusExplorer2 that you should use.

@SeanFeldman, have you checked with Microsoft if they are going to make track 0 support large messages? I heard that it was to possible to receive large messages when transportmode=amqp. I tried sending but the messages end up without body.

**Comment by Uleertel** [comment]
@ErikMogensen you may have to look twice about the empty messages. After some tests it appears that messages with size=0 in Service bus explorer are in fact larger than 1MB. When I read the queue from my azure function I receive the full content.
