### ISSUE TITLE
Feature Request: Add menu entry to duplicate subscriptions 

### ISSUE THREAD

**Issue by jcoeltjen** [paolosalvatori/ServiceBusExplorer#593]
## Background
From time to time I run into issues for some specific event consumers in our Service Bus backed microservice landscape.
It would be really helpful during debugging to be able to see what messages exactly are sent out to the application.
Just creating a new subscription on the topic is the current workaround but unfortunately this newly created subscription will receive all messages sent to the topic.

We heavily use the SQL filters to control what messages are sent out to what consumer. 
Because of that what I need for debugging is not a catch-all subscription but instead a subscription that is configured exactly the same as another one (besides its name of course).

## Proposal
It would be nice to have an additional option in the context menu for a subscription that allows to "duplicate" the subscription.
The button would just open the regular window for creating a new subscription (from the context menu of a topic) but would fill all the parameters with the configuration of the subscription to duplicate.

The second part of the scope would be to also include / copy the subscription rules from source to target too.

If you are open for such a feature I would try to implement this during some downtime or as a small weekend hackathon.

**Comment by SeanFeldman** [comment]
@jcoeltjen sounds like an interesting feature. Right-click on a subscription --> "Duplicate", provide a new name. The same could be applied to the queues. Or even topics.

Go ahead, raise a PR. When you do, have some screenshots to show what it looks like in the end. And thank you!

**Comment by jcoeltjen** [comment]
Closing this issue as the related PR has been merged.
