### ISSUE TITLE
Build alternative UI on MAUI

### ISSUE THREAD

**Issue by miqm** [paolosalvatori/ServiceBusExplorer#601]
I'd like to propose building alternative UI on .NET MAUI to bring the Explorer to macOS and Linux platforms.

There were some discussions and proposals already in #286 and task would require bumping to .NET 6 but it might be worth the effort. The portal version is very limited in capabilities and the existing alternative https://github.com/telstrapurple/PurpleExplorer is quite primitive.

I know it's a lot of work but since it's opensource perhaps someone is there that will do it?

**Comment by ErikMogensen** [comment]
@miqm, that's sounds good. I have no experience of MAUI though. Moving up to .NET 6 is a major effort though but you are most welcome to help out.
