### ISSUE TITLE
sending messages from file

### ISSUE THREAD

**Issue by rubenVerschueren** [paolosalvatori/ServiceBusExplorer#608]
during a migration test we ended up with many (a few thousand) DLQ messages on a subscription listener of service bus topic A.
there are several listeners X,Y,Z on this topic both the X and Y have the same rule.

I have 2 issues actually. the first is I can export the DLQ messages and use that file to resend them, but the file will contain the message body, properties and metadata. When using the file this is all sent as the body, which is not what I want. How can I make sure that message sent from a file use the body and properties correctly and ignore everything else? There doesn't seem to be a setting to control this either in export or the resending from a file.

the second issue I have is since topic listener X did handle the messages correctly, can I resend the message just for listener Y?
my idea to this would be to first change the rule on listener Y to for instance "[existing rule]  OR retry = 1" and then setting the retry property when I'm resending the message, but this doesn't seem like a good solution. Especially if we want to start resending messages on an acceptance or production environment.

**Comment by SeanFeldman** [comment]
Problem #2 is a topology problem. You can’t target a specific subscription w/o doing some modifications to the message headers or the subscription rules. That’s why I like forwarding topology, where a subscription is forwarding messages to a queue that is used to receive.

**Comment by ErikMogensen** [comment]
@rubenVerschueren, regarding the first problem, is it the same as #586?

**Comment by rubenVerschueren** [comment]
@ErikMogensen yes I believe so. If there is no solution possible for my second issue, this bug can be closed and I'll track the other one.
