### ISSUE TITLE
Listener Complete & Delete wrongly the Messages

### ISSUE THREAD

**Issue by AngelRodriguez8008** [paolosalvatori/ServiceBusExplorer#612]
I am using follow configuration in a Listener
![image](https://user-images.githubusercontent.com/27274469/149377552-fdc6121e-6a5c-4325-bfa0-26a3fbf55639.png)

I realize after many tries that Explorer is Receiving & Deleting the Message,  that  cause a lot of Data LOST. 

Please let me know if this is a Bug or the "normal" behavior. 

Please clarify this as soon as possible.

**Comment by ErikMogensen** [comment]
In my opinion this is the expected behavior using PeekLock, but it should be clear that the messages will be deleted. 

One thing that could be done to lessen the risk of this happening and similar dangers is to have a 'Safe' or 'Operations' mode where some menu alternatives would be greyed out.

**Comment by AngelRodriguez8008** [comment]
@ErikMogensen this is not the "expected behavior using Peek", Peek & Abandon left the Messages intact in the Queue. What for the Listener (Performance Counter) should be the default configuration.
![image](https://user-images.githubusercontent.com/27274469/170487238-1de9584d-9838-4bd8-9987-15ec1e62278c.png)
