### ISSUE TITLE
Large message support

### ISSUE THREAD

**Issue by jscheeres** [paolosalvatori/ServiceBusExplorer#614]
Right now large messages are not supported. 

The example below is a message of 3MB. This size is not correct, the message text is nog vissible.

![image](https://user-images.githubusercontent.com/10026982/151520155-9c160d22-5723-4de6-8fc0-e90b358e2350.png)

**Comment by SeanFeldman** [comment]
See #592

**Comment by jscheeres** [comment]
See @SeanFeldman comments
