### ISSUE TITLE
CPU utilization going very high

### ISSUE THREAD

**Issue by jamyryals** [paolosalvatori/ServiceBusExplorer#62]
When you right click on a Subscription and "Create Subscription Listener" the Listener window opens and functions correctly. The problem occurs when you close that window, the CPU begins to spike until you restart the app. 

I found the AsyncTrackMessage method of the ListenerControl class has an inescapable loop that appears to be preventing these resources from being cleaned up successfully. I have created a pull request that allows this loop to break when the control is disposing. It seems to have resolved the issue for me. 

[https://github.com/paolosalvatori/ServiceBusExplorer/pull/61](url)

**Comment by paolosalvatori** [comment]
Thanks! I merged your fix!
