### ISSUE TITLE
Use user config by default

### ISSUE THREAD

**Issue by cmeeren** [paolosalvatori/ServiceBusExplorer#621]
After installing Service Bus Explorer from Chocolatey, saving connection strings fails because the app does not have write access. I have to go to View -> Options and select "User Configuration File" at the top in order to be able to save connection strings. (Alternatively I can run Service Bus Explorer as an administrator, but that's not good.)

**Comment by cmeeren** [comment]
Bump

**Comment by cmeeren** [comment]
Bump to avoid automatic closing

**Comment by tonesoutherland** [comment]
I second this request. I didn't know how to do this as I couldn't easily find anything in the documentation, and no notifications indicated the write access issue. An easy fix would be to update the documentation... near the top as I would suspect this is one of the first things most users of the application will be looking to do.
