### ISSUE TITLE
CR & LF (\r\n) characters added in Resubmitted Dead-lettered Message

### ISSUE THREAD

**Issue by chandraatgithub** [paolosalvatori/ServiceBusExplorer#626]
CR - Carriage Return(\r) and LF - Line feed(\n) characters gets added automatically, when resubmitted the dead-lettered message. Using Service Bus Explorer, Version 5.0.4 we tried to resubmit a message  from topic subscription dead-letter back into the same azure service topic. Message payload carry CSV data in body.

Findings...
Resubmitted message size automatically increased (slightly). 
While receiver decode the message, \r\n found at the end of each row.

Example feed
Fresh payload CSV format in message body (i have added **\r\n** to show the exact issue):
SKUs **\r\n**
100-01 **\r\n**
100-02 **\r\n**
100-03 **\r\n**

Resubmitted message turned as below:
SKUs **\r\n\r\n**
100-01 **\r\n\r\n**
100-02 **\r\n\r\n**
100-03 **\r\n\r\n**

**Comment by SeanFeldman** [comment]
5.0.5 is out. Could you validate using the latest version? Thanks.
