### ISSUE TITLE
Removing/deleting a DLQ message is not possible due to lock duration

### ISSUE THREAD

**Issue by cdrrr** [paolosalvatori/ServiceBusExplorer#632]
When I'm trying to repair a message from a topic and flag "Remove message from DLQ", I get the below error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/49124845/162155923-893e7704-499a-4605-b85b-e3c1b0238cd4.png)

Also, manual removing the message (right click -> delete message) doesn't work.

The version of SB explorer I'm using is 5.0.4.

Has anyone encountered this issue before? Any suggestions? Thanks

**Comment by ErikMogensen** [comment]
The reason you are getting that error message is that there is no good way of deleting a message other than the top message. Therefore Service Bus Explorer uses a workaround explained at #192. 

You can temporarily increase the Lock duration for the queue up to 5 minutes. That may be enough time for Service Bus Explorer to read all the messages that are above the message you want to delete. If it is not enough you can try again and hope for faster processing or delete one or more of the messages that are before the message you want to delete.

**Comment by cdrrr** [comment]
@ErikMogensen - I understand your opinion on that however, for other topics it works just fine. I am thinking that it might be something related to the service bus itself? Or maybe the SDK?

**Comment by SeanFeldman** [comment]
@cdrrr I would try to delete messages with the latest SDK. If the behaviour continues, you might have an outlier and would need to either delete the parent queue or open a support case with Microsoft.

**Comment by ErikMogensen** [comment]
@cdrrr, it is a question of time. The Lock duration for the topic is 30 seconds and during that time Service Bus Explorer has to read all messages that are before the message you wanted to delete. How long that takes depends upon the size of the messages, the number of messages, the health and available capacity of the Service Bus service and the latency to the service bus topic. It may depend on other factors too, but those are the ones I can think of. 

As I previously wrote, temporarily increase the Lock duration to 5 minutes and see if that works.
