### ISSUE TITLE
Resubmit Selected Messages In Batch Mode issue

### ISSUE THREAD

**Issue by BruAlcaraz** [paolosalvatori/ServiceBusExplorer#633]
Hi, I am facing an issue sometimes when I use the Batch Mode to resubmit multiple messages. 
Sometimes the messages resubmitted have a string added to it '@strin3http://schemas.microsoft.com/2003/10/Serialization/�'
It has happened sometimes not every time. Can anyone help me with that?

![image](https://user-images.githubusercontent.com/20819845/162193849-a487555d-95db-4335-b581-4f0fcf803392.png)

Current Version that I am using is 5.0.7 but it happened on other versions as well

**Comment by ErikMogensen** [comment]
Strange. 

1. It may be the way the messages are displayed. I think the tool guesses how the message should be displayed. Please check a message that looks **good** in Service Bus Explorer in another tool, such as the Azure Portal Service Bus Explorer, if those characters exist in that message. 

2. If those characters are not there in question 1 I wonder if you are sure they are added by Service Bus Explorer?

3. Does this happen if you resubmit messages one by one?

**Comment by SeanFeldman** [comment]
@BruAlcaraz, the sender of the message is using a really old SDK and likely sending the payload which gets serialized with old ASB's internal serializer rather than a stream of bytes. What's the SDK used to generate the message and the specific code that sends it?

**Comment by BruAlcaraz** [comment]
Hi @ErikMogensen 
1) in the Original message the characters are not there.
2) they only get there after I resend via batch but strangely enough the issue does not happen always.
3) no it never happens when resending one by one. But once the issue happens in that batch that I need to resend one by one and make sure to delete the added characters.

**Comment by BruAlcaraz** [comment]
> @BruAlcaraz, the sender of the message is using a really old SDK and likely sending the payload which gets serialized with old ASB's internal serializer rather than a stream of bytes. What's the SDK used to generate the message and the specific code that sends it?

I'll double check it in the morning and get back to you. But as I mentioned to Erik the characters only shows when the messages are resent in a batch never happened on any originally sent messages.

**Comment by SeanFeldman** [comment]
> the characters only shows when the messages are resent in a batch never happened on any originally sent messages.

That's good, let's narrow the scope to that code then, to see how the message batch is resubmitted. Thanks.

**Comment by OwainRichardson** [comment]
Has there been any updates or finds on this thread. It's an issues I'm seeing also when re-submitting in batch.

**Comment by FredrikDahlberg** [comment]
I think the problem is in https://github.com/paolosalvatori/ServiceBusExplorer/blob/main/src/ServiceBusExplorer/Forms/MessageForm.cs#L418 The body is read as a Stream and that won't work if body type is String.

`message.Clone(message.GetBody<Stream>(), messagesSplitContainer.Visible);` 

Maybe it is enough to check if `bodyType == BodyType.String` and if true do `message.GetBody<string>()` instead. Just make sure it does not break anything else.

**Comment by DerekSMorin** [comment]
I'm seeing this as well.

**Comment by Anshuljkt** [comment]
I solved this issue based on @FredrikDahlberg's suggestion and opened a pull request. Hope this helps! https://github.com/paolosalvatori/ServiceBusExplorer/pull/764
