### ISSUE TITLE
Save connection button missing

### ISSUE THREAD

**Issue by Gerboa** [paolosalvatori/ServiceBusExplorer#634]
A previous version I was using allowed me to save connection details but this appears to no longer be available in the Connection dialog although the (disabled) "Saved connections" menu is still there.

**Comment by ErikMogensen** [comment]
I think you haven't changed the default selection in the dropdown.
![image](https://user-images.githubusercontent.com/9644248/162273218-83c41766-d5a2-4139-9582-c7cda267f1fb.png)
You need to select the item below it, _Enter connection string..._. Then you should see the _Save_ button. Once you have saved a connection the _Saved connections_ menu item will be enabled.

**Comment by ErikMogensen** [comment]
Assuming the explanation solved the issue.
