### ISSUE TITLE
Purging session queues is extremely slow

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#635]
Session queues take a lot longer to purge than a normal queue.

**Comment by IanKemp** [comment]
When a collaborator opens an issue and the bot closes it as WONTFIX...

**Comment by SeanFeldman** [comment]
The Stale bot is misconfigured. It should respect the `enhancement` label. The repo's owner will adjust it to fix the bot's behaviour.
