### ISSUE TITLE
Window not configured correctly to work with fancy zones

### ISSUE THREAD

**Issue by TheAtomAnt** [paolosalvatori/ServiceBusExplorer#637]
I often have to open three or more instances of service bus explorer to view various queues in different environments. I like to dock them. I use a tool called FancyZones from the Windows Power Toys offering to do this. However, Service Bus Explorer doesn't work correctly with this tool. I created an issue [https://github.com/microsoft/PowerToys/issues/17354] and they came back with the following:

Checked ServiceBusExplorer, and the window doesn't have WS_VISIBLE style, that's why it's ignored by FancyZones.

I am unsure what this means or how to correct it, or if it's truly an issue with Service Bus Explorer. Can a dev please take a look and correct if possible or report that it's a none issue if it's not?

**Comment by SeanFeldman** [comment]
@TheAtomAnt, this is a FOSS project. There are no "assigned" or "allocated" developers to look at the issues. A few of us volunteer here and there, and some contribute to the areas where they'd like to see some improvement. If you'd like to see this addressed sooner, I suggest rolling the sleeves and giving it a try or convincing someone from your organization to help.
