### ISSUE TITLE
Save Selected message => Body is now escaped Json String (Was not the case in 5.0.4)

### ISSUE THREAD

**Issue by StevenLangeraert** [paolosalvatori/ServiceBusExplorer#640]
When I now save selected messages the boy property contains and escaped version of the message

[
  {
    "body": "{\"event\":{\"id\":\"f9dd07f5-ea02-4c79-b825-cb635a5a63d0\",\"operation\":\"publish\",\"

Prior (until version 5.0.4 it was) it looked like

[
  {
    "body": {
      "event": {
        "id": "1bb5d923-772b-472b-b855-a910e8fa0060",

I wrote some tests that can deserialize the saved files into objects of type MessageBusItem<T>, Which was a one-step deserialization, now I need two. The body was also more readable and editable (for testing purposes). Can this be configured? Downgrading to 5.0.4 for now.

Kind Regards,
Steven

**Comment by SeanFeldman** [comment]
The behaviour up to 5.0.7 was a [bug](https://github.com/paolosalvatori/ServiceBusExplorer/issues/586). I suppose in your case it worked out fine. But if it was working as intended, you’d have to have two steps, wouldn’t you?

An alternative would be adding an option to extract JSON in the format you need as a non-default option. Would you be able to send a PR?

**Comment by StevenLangeraert** [comment]
Actually now (5.0.7) it works indeed with a two-step deserialization. The main issue I have is the readability of the body element, which makes it now much harder to read/ edit the json files in a text editor. I have no experience with desktop application development. I'll see if I can figure something out.

Thanks for your reply
