### ISSUE TITLE
Filtering messages in subscriptions is not working

### ISSUE THREAD

**Issue by aboelmor** [paolosalvatori/ServiceBusExplorer#645]
![0_messages_retrieved](https://user-images.githubusercontent.com/19220278/166420609-35f5f79b-bf94-41bb-a639-a8bb3baf47c9.PNG)
When trying to filter messages based on specific message data, the filter returns 0 records. 
`<10:49:58> The filter expression [JobId = 'TESTSAN12'] from 1/1/0001 12:00:00 AM to 12/31/9999 11:59:59 PM has been successfully applied. [0] messages retrieved.
`
I have tried the system filtering e.g., sys.Label = "JobUpdated", and it worked normally

My messages payloads are in Json format. Please advise

**Comment by SeanFeldman** [comment]
Filtering is performed on the headers, not the payload. Payload might be anything you want so it's almost impossible to get it right.
