### ISSUE TITLE
Updating from 5.0.5 to 5.0.7 lose saved connection strings

### ISSUE THREAD

**Issue by yarus** [paolosalvatori/ServiceBusExplorer#649]
After updating to 5.0.7 I found that all my saved connection strings get lost :(.
This is very inconvenient since I had a dozen saved connections and now I have to spent a lot of time figuring them out again.

**Comment by miaooss** [comment]
Make sure you dont override the `ServiceBusExplorer.exe.config`

**Comment by ErikMogensen** [comment]
@yarus, one way to avoid that is to make the connection strings be stored in the user config file. That way they won't be touched during upgrade.
