### ISSUE TITLE
I cannot create any topic Version 5.0.7

### ISSUE THREAD

**Issue by miaooss** [paolosalvatori/ServiceBusExplorer#651]
Version 5.0.7

I'm not able to create any topic, this is the exception I have

<15:11:59> Exception: The type initializer for 'Azure.Core.ClientOptions' threw an exception.
<15:11:59> InnerException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by SeanFeldman** [comment]
I wonder if it's environment-specific. Could you try a different computer or a VM?

**Comment by crozzer** [comment]
> Version 5.0.7
> 
> I'm not able to create any topic, this is the exception I have
> 
> <15:11:59> Exception: The type initializer for 'Azure.Core.ClientOptions' threw an exception. <15:11:59> InnerException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I also get this when trying to open the details of a queue (or do anything with a queue frankly).

**Comment by cieciurm** [comment]
Hi,

I'm also experiencing errors when clicking on any queue in 5.0.7.

`<11:04:01> Exception: The type initializer for 'Azure.Core.ClientOptions' threw an exception.`
`<11:04:01> InnerException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

System information:

|OS Name|Version|
|-|-|
|Microsoft Windows 10 Enterprise|10.0.19044 Build 19044|

**Comment by ErikMogensen** [comment]
This may be caused by upgrading but not updating the assembly references in the config file. What happens if you try this with the latest release (right now 5.0.12) in another directory?

**Comment by crozzer** [comment]
> This may be caused by upgrading but not updating the assembly references in the config file. What happens if you try this with the latest release (right now 5.0.12) in another directory?

Upgraded to the latest version (5.0.14) and copied my saved connections into the generated config and now all works as expected.

**Comment by cieciurm** [comment]
Hi, 
I checked on 5.0.15 and accessing a queue works just fine.
Thanks!
