### ISSUE TITLE
Feature suggestion: Repair and Resubmit to different queue/topic

### ISSUE THREAD

**Issue by danielwagn3r** [paolosalvatori/ServiceBusExplorer#664]
For scenarios with forward dead-lettered messages to different queue/topic it would be cool to be able to specify the target queue/topic when using repair and resubmit messages feature. E.g. resubmitting messages to the originating queue/topic.

**Comment by SeanFeldman** [comment]
> E.g. resubmitting messages to the originating queue/topic.

In general, messages failing processing are retired were the failure has occurred, not where the messages have originated. What would be a practical use case for this feature request?

**Comment by SeanFeldman** [comment]
BTW, this is already possible. By default, SBE will select the entity where the message was DLQ-ed, but the destination can be changed.
Closing as addressed.
