### ISSUE TITLE
ClickOnce

### ISSUE THREAD

**Issue by vonlar** [paolosalvatori/ServiceBusExplorer#67]
What do you think about moving this towards a click once deployment model?  Is it even worth it as I believe the Service Bus team is likely trying to include these types of features in the portal.

**Comment by SeanFeldman** [comment]
@vonlar I'd rather see bits released via GitHub releases.
This is WIP for issue #2

**Comment by paolosalvatori** [comment]
Hi guys, I can't spend time on this, it would be great if you could help me, thanks :)

**Comment by SeanFeldman** [comment]
ClickOnce or Desktop Bridge (Project Centennial)?
Looks like #49 superseeds this.
@vonlar if you agree, please let know and we'll close this in favor of #49. Thanks.

**Comment by vonlar** [comment]
@SeanFeldman So let's chat about this a bit more.
ClickOnce is preferable over an installer, but since we can't save the connection without editing the config file, ClickOnce isn't a good solution (the config file will likely get put in an arbitrary hard to find place).

I can implement #49, but I would want to use VSTS.  I'm already working on the CI process anyway.  It will also solve #2.  However I would likely use semver, but we can tag a valid release now and semver would take over from there.  You wouldn't touch the versioning inside the app.config.

**Comment by SeanFeldman** [comment]
@vonlar #49 is being worked on already (@msimecek could you please confirm?) and it would be great to get your help with it. @paolosalvatori is also working on it according to his [comment](https://github.com/paolosalvatori/ServiceBusExplorer/issues/49#issuecomment-267542785).

What I question is the need in VSTS. We already chose [AppVeyor for CI/CD](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer). It's fully capable of everything what we wanted to have with much less ceremony. Including solution for #2\*. And a the great part about it - it's all [in the repo](https://github.com/paolosalvatori/ServiceBusExplorer/blob/master/appveyor.yml) and can be modified as we need to. 

Just an FYI, AppVeyor is used by many OSS projects, including MSFT ones. [Check it out,](https://www.appveyor.com/docs/) you might like it 😃 

\* versioning was discussed in the past #29. I'll reopen the issue to have that conversation again.

**Comment by vonlar** [comment]
@SeanFeldman I'm familiar with AppVeyor, I just stick with VSTS since it's free and I'm not well versed in AppVeyor.  It's good since it's free for OSS projects.  I wouldn't be of much help with the CI CD process then.

As far as ClickOnce goes, I'd still prefer it over an installer any day it would also get rid of that darn installer project as well.  But then a prerequisite is being able to save the connection strings.  Really up to you guys since you're heading the charge.  I'm more than happy to help with anything, unfortunately time is just limited as I am sure is the same with everyone :)

**Comment by SeanFeldman** [comment]
@vonlar never say never (in regards to helping with AppVeyor).

Now back to the original issue - ClickOnce. I'm not an expert on this subject. Based on my quick read, it seems like [Desktop Bridge](https://developer.microsoft.com/en-us/windows/bridges/desktop) (Project Centennial) is the promoted way of deploying desktop applications that are not originally created as UWP. This means SBE would be available in the Windows Store. That to me is a significant step. Correct me if I'm mistaken, but with ClickOnce it's not an option.

Saying that, personally I don't need neither Windows Store version nor ClickOnce version. I need a standalone portable version.  How about this: we move forward with APPX (#49) first and evaluate this issue after? I see no problem with having multiple packaging options with CD using AppVeyor.

**Comment by vonlar** [comment]
@SeanFeldman Agreed.  After seeing a broadcast today to the MVPs about Bridge, it's not ready yet (imo).  I wholeheartedly concur with you about the staged deployment approach.

The only thing I will mention is that I can have a CI / CD process for automated builds and releases completed in about 20 minutes with VSTS ;).

I'll add one other comment to one of the other posts concerning the installer and WiX.

Please note these are just comments and I'll defer to you.

**Comment by SeanFeldman** [comment]
> I'll add one other comment to one of the other posts concerning the installer and WiX.

👍 

Closing for now. We'll review this once APPX is completed.

**Comment by msimecek** [comment]
Regarding the Desktop Bridge - it's available for submissions, only the developer needs their account provisioned with specific capabilities.

Technically, I got the process of generating APPX ready in VSTS. I'm not familiar with AppVeyor, but I guess it should work there as well, because it's just calling an EXE file with appropriate manifest. So as long as the build machine runs Windows, it should be fine.

**Comment by vonlar** [comment]
This will have the same problems as a ClickOnce deployment if we don't allow for saving of the connection string. Do we have an issue open on that one yet?

**Comment by SeanFeldman** [comment]
@msimecek AppVeyor is Windows Server based. I can help with integration if needed. Open a PR marked as [WIP]?

**Comment by SeanFeldman** [comment]
@vonlar a single connection string can be read from an [environment variable](https://github.com/paolosalvatori/ServiceBusExplorer/pull/18).

**Comment by paolosalvatori** [comment]
I guys, I'm reading the thread just now ad I disconnected during vacation. I'm not an ALM expert, but let me know how I can help you. In my opinion, you may explore all the possible ways and eventually extend the documentation on GitHub or blog about your solution. I don't see any problems to bring forward multiple approaches as soon as someone takes the ownership and responsibility to maintain it. 
Connection strings and any other settings can be stored in environment variables ad Sean said. This requires some coding, but it's doable
