### ISSUE TITLE
SBE does not launch

### ISSUE THREAD

**Issue by andrestalavera** [paolosalvatori/ServiceBusExplorer#681]
Hi,
When I try to open `ServiceBusExplorer.exe` (5.0.10) on my Windows 11, I have this message:

![image](https://user-images.githubusercontent.com/4092891/190368895-1c52f717-477e-4305-b84f-676ff6a8e62e.png)

And when I click on `Yes`, I have this page
![image](https://user-images.githubusercontent.com/4092891/190368843-36c61579-71c9-4d3b-8389-e11734166fa1.png)

**Comment by ErikMogensen** [comment]
There is a bug in 5.0.10, please try 5.0.12.
