### ISSUE TITLE
On click a Queue bug

### ISSUE THREAD

**Issue by JRRN** [paolosalvatori/ServiceBusExplorer#685]
Version Bus Explorer 5.0.14
Servicebus Client 3.0.53723

<19:48:49> Exception: No se puede cargar el archivo o ensamblado 'System.Runtime.CompilerServices.Unsafe, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)
<19:48:49> InnerException: No se puede cargar el archivo o ensamblado 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)

**Comment by SeanFeldman** [comment]
Localized exceptions are not helping much 🙂

> Unable to load file or assembly

How are you running the tool?

**Comment by JRRN** [comment]
Download from release version from GitHub and exec from windows 10.


El 22 sept 2022, a las 15:55, Sean Feldman ***@***.***> escribió:

﻿

Localized exceptions are not helping much 🙂

Unable to load file or assembly

How are you running the tool?

**Comment by SeanFeldman** [comment]
> Download from release version from GitHub and exec from windows 10.

Downloaded to the local drive? To the network share? Tried to run it using the command line? Clicked on the executable?

I've followed your repro steps and had no problem past the Smart Screen warning
<img src="https://user-images.githubusercontent.com/1309622/191822235-4b9a2787-853c-421a-a587-5e540169470f.png" width=300/>

![image](https://user-images.githubusercontent.com/1309622/191822410-307d767b-eb12-490f-9f39-bc8e0058cc3b.png)

1. Try another machine/environment
2. Provide details steps of what you've already tried

A side note - this is a **FOSS** project. While we strive to help others, you should do the same while describing your problem.

**Comment by JRRN** [comment]
ServiceBusExplorer.exe.config Wrong file
