### ISSUE TITLE
replay dead letter messages from topic subscriber into itself

### ISSUE THREAD

**Issue by camous** [paolosalvatori/ServiceBusExplorer#69]
Hello, is it possible possible to receive and resend messages from a subscriber's dead letter into the subscriber itself ? I would like to prevent sending a message for all subscribers when only a subset of them failed. (risk of state changes conflict)

**Comment by SeanFeldman** [comment]
@camous you could resubmit the message using `Repair & Resubmit` functionality. First receive your messages from DLQ, then use repair and resubmit. Is that what you need?

**Comment by camous** [comment]
Repair & submit functionality resend the message for all subscribers rather one specific subscriber. I don't even know if it's possible with the Service Bus API in C#. Or maybe have to play with an extra message filters/rules for forcing the message to go only in one subscriber ...

**Comment by SeanFeldman** [comment]
Sending a message from a subscriber to itself is not possible AFAIK. Only to a queue or a topic.

Extra filtering is viable a possible approach.

Assuming you'd have a topic called `topic` and let's say a subscription `sub1` you want to reprocess your messages for, you could set up forwarding rule fro `sub1`'s DLQ. Then any DLQed message forwarded would have a header `DeadLetterSource`. For this sample, the value would be `topic/Subscriptions/sub1`. Your filter would be able to identify messages using this info. 

Warning - you could run into an infinite loop with this approach if you don't prevent infinite forwarding.

**Comment by camous** [comment]
Yes, we are currently implementing a 'forcedestination' filter configured for each subscriber
`(Exists([forcedestination]) AND [forcedestination] = 'XXXXXX-dev')`

moreover, on our C# subscriber listener, the abandon() method automatically add this 'forcedestination' property.

**Comment by paolosalvatori** [comment]
Hi @camous, as Sean said, there's no mechanism to directly send a message to specific subscription of a given topic, so using an extra rule \ filter expression in the subscription and one or more extra properties in the message that you intend to resend that make the expression to evaluate to true, seems to be the only way to solve your problem.

**Comment by camous** [comment]
thanks for the confirmation :) as said on my previous comment, we addressed the problem with extra properties & filters and works perfectly so far.

**Comment by paolosalvatori** [comment]
Excellent, thanks for the confirmation :)
