### ISSUE TITLE
Use Service Bus Explorer for sending RabbitMQ messages without accessing the Cloud?

### ISSUE THREAD

**Issue by scampsd** [paolosalvatori/ServiceBusExplorer#692]
Good morning,
I would like to use the Service Bus Explorer, for sending RabbitMQ messages in my local environment.

Is this possible, which means:
- Is there an extension for working with RabbitMQ?
- Is it possible to work with Service Bus Explorer without needing to access the Cloud?

Thanks in advance

**Comment by SeanFeldman** [comment]
The tool is not designed to support RabbitMQ.

**Comment by scampsd** [comment]
@SeanFeldman: Thanks for the quick reply. Are you aware of any extensions which support RabbitMQ?

**Comment by SeanFeldman** [comment]
Not for this tool, no. You could try [Cogin](https://www.cogin.com/QueueExplorer/rabbitmq/)

**Comment by scampsd** [comment]
Oops, that contains a "Buy" button and the trial period is just for two weeks. No free tool?

**Comment by SeanFeldman** [comment]
And how do you think free is exactly free? Someone always pays for it. Either by donating time or money.

**Comment by scampsd** [comment]
You're absolutely right. Sorry for my last remark and have a nice day.
