### ISSUE TITLE
Reproducing the issue #590

### ISSUE THREAD

**Issue by yomotoya** [paolosalvatori/ServiceBusExplorer#695]
We can reproduce the issue https://github.com/paolosalvatori/ServiceBusExplorer/issues/590 on v5.0.14. Will the issue be fixed on v5.1.0? If so, when is 5.1.0 going to be released? I found a Pull Request https://github.com/paolosalvatori/ServiceBusExplorer/pull/591. I’d appreciate any information on current status and plan to fix of the issue. Thank you.

**Comment by ErikMogensen** [comment]
Reopened #590 instead.
