### ISSUE TITLE
Feature Request - request confirmation when deleting Notification Hubs/Service Buses etc

### ISSUE THREAD

**Issue by BigBadJock** [paolosalvatori/ServiceBusExplorer#699]
Would it be possible to have request confirmation when deleting Notification Hubs, or Queues, Topics, Service Buses etc? 

A simple "Are you sure? Okay/Cancel" would be great.

**Comment by ErikMogensen** [comment]
You can do this by checking the following check box in the Options dialog window.
![image](https://user-images.githubusercontent.com/9644248/199833133-763e5dd6-1d27-4d9a-bfa1-a13038c3ed04.png)

**Comment by BigBadJock** [comment]
Thanks

**Comment by yggdrasil-tynor** [comment]
We have not for the 3rd time (by a mistake) deleted a queue that was in production. Would it make sense to introduce a field that you need to type in the queue / topic name, when deleting it?
