### ISSUE TITLE
BulkPurge NullReferenceException When Topic Has No Subscriptions

### ISSUE THREAD

**Issue by avalanchis** [paolosalvatori/ServiceBusExplorer#702]
### Summary:

Selecting any of the options under Topics -> Purge will cause a Null Reference Exception if a Topic exists with no Subscriptions.

### Expected behavior:

1. Select **Topics** -> **Purge** -> **Messages**, **Dead-letter Queue Messages**, or **All Messages** 
2. The appropriate purge function is performed on all topics.

### Actual behavior:

1. Select **Topics** -> **Purge** -> **Messages**, **Dead-letter Queue Messages**, or **All Messages**
2. The following message appears in the Log window:

     `<09:52:57> Exception: Object reference not set to an instance of an object.`

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/bc288d24ca69f1a78a3739fae837967d11380ff7
