### ISSUE TITLE
All connection settings lost when updating via Chocolatey

### ISSUE THREAD

**Issue by dirkrheeder** [paolosalvatori/ServiceBusExplorer#705]
All connection settings are lost after running an update via Chocolatey. Have to recreate them all

**Comment by ErikMogensen** [comment]
One way to avoid this from happening is to set it to use the "User configuration file". Then the connection strings are stored in your user profile.
<img width="214" alt="image" src="https://user-images.githubusercontent.com/9644248/214025343-6ff7c49e-46be-4e41-9b7f-4a083c2ffe91.png">

**Comment by dirkrheeder** [comment]
Thank you
