### ISSUE TITLE
How can we delete a single message from the topic (we work with SAS token)

### ISSUE THREAD

**Issue by dbzowkakpmguk** [paolosalvatori/ServiceBusExplorer#711]

**Comment by Narayan-Mitra** [comment]
Hi,
We are unable to delete a specific message from service bus topic using tool -ServiceBusExplorer-5.0.15

we need help to delete certain message from below topic.
![image](https://user-images.githubusercontent.com/113661915/214835496-028abc79-67a7-494f-bd9b-ad3d15a890e8.png)

For example what will be the steps to delete 2nd message from above topic. 
Please suggest if there is any way for the same.

**Comment by SeanFeldman** [comment]
Have you tried receiving by the message's sequence number?

**Comment by Narayan-Mitra** [comment]
Hi, when we receive message with 'Receive and Delete' mode, From sequence number option is disable.
![image](https://user-images.githubusercontent.com/113661915/217272267-c787fa8a-5932-4e6b-8693-8aa5d1db4cc9.png)

**Comment by ErikMogensen** [comment]
It is not possible to remove any message except the first using the tool. It is possible to do that on dead letter queues though. 

The reason for this is that the only solution I could come up with for doing this requires that the tool makes a peek lock on every message that is in front of the message you want removed and then abandons those locks. That causes the Delivery count to increase by one on every message that is in front of message that is going to be removed. That in turn may cause the message to be moved to the dead letter queue, which is probably not intended. 

Perhaps it would be all right to implement it for normal with a nagging message describing the consequences... However, I currently don't have time to do that so you will have to create the PR for this yourself.
