### ISSUE TITLE
Exception when creating new topic.

### ISSUE THREAD

**Issue by RHIssa** [paolosalvatori/ServiceBusExplorer#713]
I'm seeing the following exception logged when attempting to create a new topic:

`Exception: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Using version 5.0.15. The exception does not occur in version 4.1.112.

**Comment by ErikMogensen** [comment]
Did you use the same servicebusexplorer.exe.config file for both versions?

**Comment by RHIssa** [comment]
Ah, yes, I did - I was wanting to bring in my saved connection strings from the previous version, and copied the old version's config file to the new version.
I've restored the new version's config and instead copy-pasted only the <serviceBusNamespaces> element to the new config. Now it all works as expected.
Thanks for bringing that up, @ErikMogensen !
