### ISSUE TITLE
When testing in-built Send Event and Create Partition/Consumer Group Listener, message is sent and received yet the message does not appear

### ISSUE THREAD

**Issue by henryz0113** [paolosalvatori/ServiceBusExplorer#720]
Hi Guys,
Appreciate the work you guys put into the explorer. 
It really does make life easy.
However, I found an issue while testing the in-bult send and listen function to view the message.

**[Summary]**
I tried sending, receiving and reading messages through the built-in function as I wanted to see if the messages are going through fine. The message is sent and received fine but, the issue with reading the messages that was sent.
![SendEvent](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/a91dfd13-7931-425d-ab35-f98106831303)
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/5d8f9abf-7104-413a-8074-e447653ea91e)

The functions used within the explorer are `Send Event` / `Create Partition Listener`
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/d730e577-53fe-438f-8b61-6e3bd06ac86e)
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/84ba7464-88b1-4294-8e33-b0f4ffb8791f)

**[Issue]**
The issue appears from `5.0.7`, the version I had, and also updated to newest `5.0.15`, and the issue is still appearing as well.

When sending the message I can see an Exception returning from the activity log.

`Exception : This object is read-only and cannot be modified. `
This message also appears on the `properties` of `Event System Properties` when viewed from the Listener popup console. 

![error](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/0bee294f-604a-4024-a559-dfc56fd2d375)

Also you can `Event Custom Properties` is blank, where it should have the `machine name` and the `user name`.

**[TroubleShooting / Validating]**
I have validated that with version `5.0.3`, we are able to send and receive the test message and be able to read the test message sent. 
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/134192d3-2ddf-4c49-8ed7-be834d4b77e9)

From this image, you can see that the `properties` is blank without the exception.
As well as, the `Event Custom Properties` has `machine name` and `user name` filled up. 

Could you please fix this issue?
Thank you in advance.

**Comment by ErikMogensen** [comment]
That's not good....

I compared the code in 5.0.3 with 5.0.7 and I see that WindowsAzure.ServiceBus was upgraded from 6.0.3 to 6.2.0. Are you able to build the solution? In that case, please downgrade the latest source code to use WindowsAzure.ServiceBus 6.0.3 and test if you can reproduce the issue.

**Comment by henryz0113** [comment]
Hi @ErikMogensen I don't know is the right way to do it but I've overwritten the Microsoft.ServiceBus.dll from 5.0.3 to the 5.0.15 
And I am able to see the messages on the 5.01.15. 

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/3b81794b-dfb2-4be0-8723-0a65f0b4b10d)

However, I am not to sure what are the impacts of changing this. 
Would this be the correct way to do so?

Thanks

**Comment by ErikMogensen** [comment]
Good that you found the issue. There may be other bugs or missing features in the older version. You can look at the Release notes for the later releases, for instance [Release note for WindowsAzure.ServiceBus 6.2.0](https://www.nuget.org/packages/WindowsAzure.ServiceBus/6.2.0). I suggest you keep using that version.

The best thing would be if you created a case with Microsoft and asked them to fix the bug. However, I believe they will be reluctant to fix it and instead suggest a switch to the other SDK for Event hubs. But It is not possible to switch ServiceBusExplorer to that SDK since it is lacking support for managing Event hubs using connection strings.

**Comment by henryz0113** [comment]
Thanks @ErikMogensen. I'll check with Microsoft on this.

**Comment by DelS-AGL** [comment]
I have had a similar problem reading Event messages with V-5.0.15 (and every version after V-5.0.4).
On advice from @ErikMogensen, I replaced Microsoft.ServiceBus.dll with the version used in V-5.0.4 which has resolved my problem. Thanks.

**Comment by SeanFeldman** [comment]
I've looked into what's happening, and it appears to be a breaking change with [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus). SBE relies on the **public API** to clone an `EventData` using [`EventData.Clone()`,](https://github.com/paolosalvatori/ServiceBusExplorer/blob/ad382ccb52d238f85b7159682f3c387e109a44ed/src/ServiceBusExplorer/Controls/PartitionListenerControl.cs#L647C18-L647C18) but the underlying implementation has been changed, and now the exception is thrown.

<details><summary>System.NotSupportedException: This object is read-only and cannot be modified.</summary>
<code>
   at Microsoft.ServiceBus.Common.ReadOnlyDictionary45`2.System.Collections.Generic.IDictionary<TKey,TValue>.set_Item(TKey key, TValue value) in Microsoft.ServiceBus.Common\ReadOnlyDictionary45.cs:line 308
   at Microsoft.ServiceBus.Messaging.EventData.UpdateUserPropertiesForReceive() in Microsoft.ServiceBus.Messaging\EventData.cs:line 303
   at Microsoft.ServiceBus.Messaging.EventData.Clone() in Microsoft.ServiceBus.Messaging\EventData.cs:line 246
   at ServiceBusExplorer.Controls.PartitionListenerControl.eventDataDataGridView_RowEnter(Object sender, DataGridViewCellEventArgs e) in C:\github\SeanFeldman\ServiceBusExplorer\src\ServiceBusExplorer\Controls\PartitionListenerControl.cs:line 647
</code>
</details>

**Comment by SeanFeldman** [comment]
This is also the case for the `Properties` property of `EventData`.

**Comment by SeanFeldman** [comment]
Some more analysis of the code path for EventHubs shows that the approach taken for both `BrokeredMessage` and `EventData` was storing the original messages in the grid, and whenever a specific one would be selected, it would be cloned for manipulations such as stream and properties reading to populate the selected message UI controls. With the Clone method broken, the implementation doesn't hold and would require reading messages once only, storing some abstraction that would allow "cloning"/working with the event body.

For `Properties`, I'm not sure what the solution is since SDK is throwing, and we have no access to those.

**Comment by SeanFeldman** [comment]
@henryz0113, a [potential workaround](https://github.com/paolosalvatori/ServiceBusExplorer/pull/740) w/o downgrading the SDK is coming.

**Comment by henryz0113** [comment]
Hey @SeanFeldman thank you for the update! 💯

**Comment by SeanFeldman** [comment]
@henryz0113, you can check out the branch and give it a try. I'm not a frequent EH user to validate SBE change. If you could do that and post your findings, it would help. Thank you.

**Comment by henryz0113** [comment]
Hey @SeanFeldman awesome job!!
Looking great!

We can pick up every information! 
@ErikMogensen can you please double check and merge it as well?

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/66353492/698e6584-5839-4535-a77a-be9df38e66ac)
