### ISSUE TITLE
Build server status for a PR

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#73]
AppVeyor can update [status of a PR](https://www.appveyor.com/docs/notifications/#github-pull-request)

> GitHub Pull Request notifications is a perfect way to notify all developers working on a pull request. AppVeyor can post a new comment with build results to a pull request being built. GitHub will send email notifications to all subscribed developers

**Comment by SeanFeldman** [comment]
[`AppVeyour.yml` updated](https://github.com/paolosalvatori/ServiceBusExplorer/commit/c95df491ce4eeb3d0c06810993e9b98271195c04) to enable PR notification. @paolosalvatori will verify it's working.

**Comment by SeanFeldman** [comment]
@paolosalvatori ping

**Comment by paolosalvatori** [comment]
Hi @seanfeldman what should I do exactly? I don't see any button to approve the change :)

**Comment by SeanFeldman** [comment]
Works. Tested with the failing PR #75 
![image](https://cloud.githubusercontent.com/assets/1309622/22499463/29c466b4-e81c-11e6-84be-06b1f4b3b082.png)

**Comment by paolosalvatori** [comment]
Thanks @seanfeldman
