### ISSUE TITLE
Explain filter Expressions please

### ISSUE THREAD

**Issue by Dennizzzzz** [paolosalvatori/ServiceBusExplorer#734]
Can you add a wiki please to explain how the filter expression work?

I've got couple of thousand messages, and want to find those with a label containing the word 'send'.
Expression: sys.Label contains 'send' does not work.

i've got one message with label 'archive 123', filter 'sys.Label='archive 123' does not work. 
Also tried without the 'sys.'. Does not work. 

Where is the help for the filtering?

**Comment by SeanFeldman** [comment]
To second what Eric said, there are plenty of resources. This project is focusing on the tooling
