### ISSUE TITLE
Event Hubs - Events Custom Properties on Listener screen don't render - started occurring since after Release 5.0.4

### ISSUE THREAD

**Issue by minascasiou** [paolosalvatori/ServiceBusExplorer#738]
When 
- connecting to Azure Event Hubs 

Then
on the **Listener** screen, Events tab
- Events Custom Properties on don't render 

This started occurring since after Release 5.0.4

**Comment by SeanFeldman** [comment]
@minascasiou, a [potential workaround](https://github.com/paolosalvatori/ServiceBusExplorer/pull/740) w/o downgrading the SDK is coming.

**Comment by ErikMogensen** [comment]
@minascasiou, please try the brand new 5.0.18 release.

**Comment by minascasiou** [comment]
Awesome, thank you Erik!
Works like a charm!
