### ISSUE TITLE
Save connection strings

### ISSUE THREAD

**Issue by rosslyn-amanbaloch** [paolosalvatori/ServiceBusExplorer#74]
I want the ability to save my connection strings so I don't have to re-enter them anytime I want to see a different service bus

**Comment by tomkerkhove** [comment]
You can add them to the config file in the `appSettings`-section.

But I agree having it in the UI would be a nice-to-have.

**Comment by SeanFeldman** [comment]
Would any of you want to send a PR to help with this? 😃

**Comment by paolosalvatori** [comment]
Hi guys, we may add a save button to the connect dialog that provides the ability to save a connection string with a name inside the config file. I'm very busy this week. Would this work out for you?

**Comment by rosslyn-amanbaloch** [comment]
Guys, I had a look into implementing this, however, I couldn't find any approach to saving the hash table back.
Do I need to write a custom section handler? or is there a better approach?

**Comment by SeanFeldman** [comment]
@rosslyn-amanbaloch link?

**Comment by rosslyn-amanbaloch** [comment]
https://www.codeproject.com/Articles/32490/Custom-Configuration-Sections-for-Lazy-Coders

**Comment by SeanFeldman** [comment]
Saving has to happen pro-actively. So you either have to expose a UI element to trigger it or do it automatically. Are you saving to a registry, location indicated by a registry, or something else?

**Comment by rosslyn-amanbaloch** [comment]
I was planning to Add a save button on the form and saving back to the config file on clicking it.

**Comment by SeanFeldman** [comment]
Note that .config could be replaced if someone would overwrite files with a newer version.

**Comment by rosslyn-amanbaloch** [comment]
Do you mean we can use a different approach for storing connection strings?

**Comment by SeanFeldman** [comment]
@rosslyn-amanbaloch correct. One of the ideas was to store a location in registry that would point to the configuration.

**Comment by paolosalvatori** [comment]
I added the ability to enter and save a connection string in the configuration file directly from the Connect form. Just select Enter a connection string... in the Connect form, paste a connection string in the Connection String textbox and press the Save button to specify a key for the namespace and save it both to the ServiceBusExplorer.exe.config and App.config (if it exists).

**Comment by SeanFeldman** [comment]
@paolosalvatori would be nice if we'd reference issue from a PR or have a closing comment with the commit SHA1 that resolved the issue 😃

**Comment by SeanFeldman** [comment]
closed via 79525c67592d9bc96f33591b5aa89e62f54fe6e6
