### ISSUE TITLE
Include scheduled messages in counter

### ISSUE THREAD

**Issue by Kakaranish** [paolosalvatori/ServiceBusExplorer#753]
Hi, I think it would be great to have scheduled messages included in total messages on queue. For now scheduled messages are not visible on queue summary:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/31103437/0c4de2ab-cda5-4ea9-80fa-2763db2b1c40)
This sometimes causes that I think there are messages on queue when in reality there are. It would be great for me to not go through all queues to check if any messages are scheduled :)

**Comment by Greybird** [comment]
hi @Kakaranish,

You can already configure the values shown on queue summary through the options
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8553578/cefc4e07-6356-4f14-a1a3-fca1808ff304)
Is this what you need ?

**Comment by Kakaranish** [comment]
Awesome. That's exactly what I was looking for. Thank you. Closing.
