### ISSUE TITLE
how to add new tab in PartitionListenerControl

### ISSUE THREAD

**Issue by YFJiang** [paolosalvatori/ServiceBusExplorer#755]
Can i use  add a new tab in PartitionListenerControl using design view

**Comment by ErikMogensen** [comment]
Yes, I do not see any problem with that. 

Out of curiosity, what is the purpose for that tab?

**Comment by YFJiang** [comment]
If i want to add a button, can i drag a button and put it in the page?



---- Replied Message ----
| From | Erik ***@***.***> |
| Date | 12/06/2023 04:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [paolosalvatori/ServiceBusExplorer] how to add new tab in PartitionListenerControl (Issue #755) |

Yes, I do not see any problem with that.

Out of curiosity, what is the purpose for that tab?

**Comment by ErikMogensen** [comment]
Yes

**Comment by YFJiang** [comment]
I add some buttons there.and events tab looks like this



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Erik ***@***.***> |
| Date | 12/09/2023 23:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [paolosalvatori/ServiceBusExplorer] how to add new tab in PartitionListenerControl (Issue #755) |

Yes
