### ISSUE TITLE
ServiceBusExplorer is not showing the topics

### ISSUE THREAD

**Issue by viveknuna** [paolosalvatori/ServiceBusExplorer#766]
I am using the 5.0.18 version. I am connecting to a service bus by using its connection string. It's not showing the topics now. It was working fine before but suddenly stopped showing the topics now. It's working fine for the other service bus.

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/3524495/72fbc260-e02c-4b65-bb02-8b779d04f2f3)

**Comment by SeanFeldman** [comment]
> It's working fine for the other service bus.

Is it working correctly for another ASB namespace?

**Comment by SeanFeldman** [comment]
Closing as it's not something with SBE.
The question is also posted on [SO](https://stackoverflow.com/q/77811551/59563).
