### ISSUE TITLE
Allow purge of all items in a queue or subscription

### ISSUE THREAD

**Issue by bunceg** [paolosalvatori/ServiceBusExplorer#77]
Sometimes in testing (or prod) we get a rogue process that sends lots of messages to a queue, or fails lots of messages and puts these to the deadletter queue.

It would be helpful to be able to purge all of these, without having to Receive them all first

**Comment by paolosalvatori** [comment]
Why don't you select the queue, click Deadletter button, then in the dialog select Receive and Delete under Receive mode and All under Message Count?

**Comment by bunceg** [comment]
Because, unless I'm mistaken, this downloads all the messages to the UI which is a problem when I have > 1000 messages. The UI locks up for a few minutes whilst it gets everything. For 100K (a really bad rogue process!!) this is unusable.

**Comment by SeanFeldman** [comment]
@bunceg native client doesn't support purging. Until that functionality exists, the only option is to drain your messages the way @paolosalvatori suggested.

I'm closing this issue as there's nothing we can do at this point.
Would suggest we get back to it once the new ASB client has the ability to purge. [Cast your vote](https://github.com/Azure/azure-service-bus-dotnet/issues/46) here if you'd like MSFT to implement purge functionality.

**Comment by bunceg** [comment]
okay... could this be handled by #60 then... one suggestion by paolo near the end was to receive/delete without loading the messages into the dataview. At the moment, using the latest from master, my UI is locking up with even a smaller size of queued items, so an alternative "do not load" may be easier..

An alternative discussed here [http://stackoverflow.com/questions/9920323/clearing-azure-service-bus-queue-in-one-go](url) would be to do this behind the scenes within the tool, and then replace it when a better version comes out?
