### ISSUE TITLE
Accidental queue deletion validation

### ISSUE THREAD

**Issue by Didjacome** [paolosalvatori/ServiceBusExplorer#773]
Hello everyone, 👋
================================

I hope this message finds you well and in good spirits. I'm reaching out because I've encountered a bit of a puzzle and could really use your insights or advice.

### Context

My goal was simple:
- clear out some old messages that were lingering in the queue longer than they should have.

### Scenario 

So, here's what happened:

I initiated the "Receive Dead-Letter Queue Messages" process at 13:05 using the ServiceBusExplorer application. However, the app crashed without generating any logs, yet it seemed to continue processing the action. I let it run for an hour. Upon returning at 14:00 to check the status, I discovered that the queue had been deleted.

I checked the Azure portal to determine what might have happened, consulting the active log, but found no record of any activity.

Since diagnostic settings for operational logs are enabled on the service bus, I was able to identify a log in Azure Log Analytics indicating that the queue was deleted at 13:32.

#### tools used:

- Operating System: Windows (Windows Server 2019 DataCenter)

- Service Bus Explorer Version: 5.0.18

- Service Bus Client Version: 3.0.52723

### Questions for Verification:

1. Could using the "Receive Dead-Letter Queue Messages" feature in Service Bus Explorer inadvertently delete the queue?

2. Where does Service Bus Explorer store logs of previous actions?

This version adds a touch of humor and a more conversational tone to make the request more engaging and friendly.

**Comment by Didjacome** [comment]
I've noticed that, in this scenario, the other two individuals possess administrative "Contributor" access across the entire service bus.

However, I've been unable to locate any record of the queue's deletion in the Azure portal, specifically within the active logs section.

I proceeded to recreate the queue, and interestingly, upon its recreation, the record of this action became visible in the portal's active logs.

**Comment by SeanFeldman** [comment]
Yeah, something is off. I don't know how that would be even possible with a message receiving.

**Comment by Didjacome** [comment]
Thank you for your feedback. I have a few questions that I hope you can help me with:

- Could the ServiceBusExplorer application have somehow performed the delete queue action? Is there a way to get this log from the ServiceBusExplorer application?

- Alternatively, could ServiceBusExplorer have activated the "Enable Auto-Delete on Idle Queue" option, which caused the queue to be deleted during a period of inactivity?

**Comment by SeanFeldman** [comment]
Both operations are explicit UI operations that would require a human. So the short answer is no.

I'm also extrapolating years of use of this tool and I don't recall anyone running into this issue.

Could you also check what the accidental deletion setting is set to for you?
Options --> General

It's should turned on by default.

But in general, receive operations are not destructive towards entities.

**Comment by Didjacome** [comment]
I understand. Therefore, we can conclude that the "ServiceBusExplorer" application did not delete the queue as previously mentioned.

This is quite peculiar because we have not activated the "Auto-Delete on Idle Queue" feature. Following your request, I checked the properties of the queue and noticed that the "Auto-Delete on Idle" property is represented by a sequence of numbers, for example, "P15268199DP2J48M8.4096807S."

**Comment by Didjacome** [comment]
@SeanFeldman and @ErikMogensen Thank you all immensely for your help and support. Confirming with the community that the "Receive Dead-Letter Queue Messages" option in Service Bus Explorer indeed does not delete the queue without manual intervention has been incredibly helpful. I have already opened a ticket with Microsoft to inquire if they can offer further information about the incident or undertake a more thorough investigation into the Azure backend.
