### ISSUE TITLE
How does the SBE retrieve the number of messages/dlq messages on a SB topic

### ISSUE THREAD

**Issue by RichardOberdieck** [paolosalvatori/ServiceBusExplorer#774]
I have an issue where the SB monitoring on Azure and other places sometimes does not provide the accurate number of messages sitting on a SB topic. Specifically, if the number of messages is low (but not 0), Azure will sometimes say that there are no messages. However, the ServiceBusExplorer has so far always been accurate, so my assumption is that it uses a different way to query the status of the SB.

Could you please point me to the code where this query is done? Then I can see whether I can use the same one for my project. Thanks :)

**Comment by SeanFeldman** [comment]
Azure monitor is using metrics that might be behind by a couple of minutes where SBE is using the SDK (legacy) to query that information in real-time.

**Comment by ErikMogensen** [comment]
It retrieves the message count in multiple places, one place is the method GetMessageCount in the QueueServiceBusPurger class. That uses the SDK track 2, which is the latest and recommended SDK. 

There are also other places where the messages count is retrieved but some of them use the SDK track 0, which should be avoided.

**Comment by RichardOberdieck** [comment]
Awesome, thanks @SeanFeldman and @ErikMogensen !
