### ISSUE TITLE
Save Sender settings as well

### ISSUE THREAD

**Issue by JuganD** [paolosalvatori/ServiceBusExplorer#786]
Hey, me and my colleagues are using SB explorer quite often and we've noticed that the settings in **Sender** tab, when sending a service bus message to specific queue, are not saved like the message content.

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/40771401/1469e1a1-5fba-4456-8336-2d0c5752df91)

The **Label**, in particular, is what our app uses to navigate through the message types.
On each start of the explorer, it falls back to 'Service Bus Explorer'.

It would be very handy if those settings are also persisted between restarts.

**Comment by SeanFeldman** [comment]
Regression related to #783 or a new issue, @ErikMogensen?

**Comment by ErikMogensen** [comment]
> Regression related to #783 or a new issue, @ErikMogensen?

I believe it's an old issue. 

@JuganD, which SBE version are you using?

Also, what is your setting for 
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/4c495724-fc8d-404a-a83c-f9e219a9928e)
?

If it is set to "Application configuration file", please set it to "User configuration file" and test if it makes a difference.

**Comment by JuganD** [comment]
These are my settings, they were set to User Configuration File:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/40771401/8ba64ace-2756-49da-822d-721a9f99cac8)

Currently using version 6.0.0, but we've noticed this on the last version we used as well - 5.0.17

**Comment by ErikMogensen** [comment]
I was able to reproduce it. However, you can change the label by setting it in the `View | Options` dialog box. 

I don't know if it is a good thing if you changed the stored label when sending a message, but it should be consistent with the message content of course.

**Comment by JuganD** [comment]
Can confirm that the options do save it, even when the app is reopened.
This really helps, thanks!
