### ISSUE TITLE
Exception with Azure.Core (for release 6.0.0)

### ISSUE THREAD

**Issue by jassent** [paolosalvatori/ServiceBusExplorer#787]
Upgraded to the current version (6.0.0).

Added a connection string successfully.

Cannot view any queues or topics due to a "Could not load file or assembly 'Azure.Core" exception.

A screenshot is included. Ignore the "specified argument was out of the range of valid values ... parameter name active does not exist" as that was from me trying a different configuration option to see if it would allow me to connect. 

Downgrading to 5.0.18 allows a successful connection with no error. 

<img width="1299" alt="2024-06-29_11-31-52" src="https://github.com/paolosalvatori/ServiceBusExplorer/assets/22982404/3cc47932-04e7-40b5-abef-efa3e501dc6f">

```
<11:27:24> The file C:\Users\xxxx\AppData\Roaming\Service Bus Explorer\UserSettings.config is used for the configuration settings.
<11:27:29> The application is now connected to the sb://xxxxx.servicebus.windows.net/ service bus namespace.
<11:27:29> MessagingFactory successfully created.
<11:27:31> Exception: Could not load file or assembly 'Azure.Core, Version=1.33.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by ErikMogensen** [comment]
Did you keep the servicebusexplorer.exe.config from the previous release?

**Comment by jassent** [comment]
I am not sure how to best answer that. I ran the update using scoop: "scoop
update ServiceBusExplorer". When I opened Service Bus Explorer it was
version 6.0.0 and all prior saved connections were lost - so I re-added.
When I uninstalled version 6 and re-installed version 5.0.18 using scoop,
the same connection string worked with no error.

**Comment by ErikMogensen** [comment]
Ok, it seems that you are using the assembly configuration part for v6.0.0, but to make sure:

Please install v6.0.0 and look in servicebusexplorer.exe.config for Azure.Core. It should look like this.      

```xml
<dependentAssembly>
        <assemblyIdentity name="Azure.Core" publicKeyToken="92742159e12e44c8" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.38.0.0" newVersion="1.38.0.0" /
</dependentAssembly>
```

**Comment by jassent** [comment]
> Ok, it seems that you are using the assembly configuration part for v6.0.0, but to make sure:
> 
> Please install v6.0.0 and look in servicebusexplorer.exe.config for Azure.Core. It should look like this.
> 
> ```
> <dependentAssembly>
>         <assemblyIdentity name="Azure.Core" publicKeyToken="92742159e12e44c8" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-1.38.0.0" newVersion="1.38.0.0" /
> </dependentAssembly>
> ```

Thank you! This led me to the solution. I uninstalled 5.0.18 and installed 6.0.0. When I opened the servicebusexplorer.exe.config there was no reference for Azure.Core. When I checked the directory that config file was almost a year old. To resolve, I renamed the servicebusexplorer.exe.config to servicebusexplorer.exe.config.old and then renamed servicebusexplorer.exe.config.original to servicebusexplorer.exe.config. 

A screenshot is below. It shows uninstalling, installing, and the old file name. 

Feel free to close the issue. Thank you for the suggestion and helping me to resolve. 

<img width="1906" alt="2024-06-30_07-22-47" src="https://github.com/paolosalvatori/ServiceBusExplorer/assets/22982404/42d9a048-7e3f-4e46-9b96-5c928ae010f5">

**Comment by ErikMogensen** [comment]
Good, that you got it resolved. 

So, Scoop doesn't replace the servicebusexplorer.exe.config file?

In that case it is going to create problems.

**Comment by jassent** [comment]
> So, Scoop doesn't replace the servicebusexplorer.exe.config file?

Correct, it seems to be re-deploying the prior version previously installed on the computer and renaming the correct one in the 6.0.0 nupkg file to "servicebusexplorer.exe.config.original".
