### ISSUE TITLE
Batch resubmit of messages of deadletter messages does not ask for Message Inspector

### ISSUE THREAD

**Issue by bunceg** [paolosalvatori/ServiceBusExplorer#79]
If you need to resubmit a number of messages from the deadletter queue the current process appears to be impractical for large numbers of messages that take advantage of zipping content before publishing to the queue. Because our messages are zipped, we use the Zip message inspector to be able to convert these before viewing in Service Bus Explorer.

If we then want to re-submit a single message, we can perform "repair and resubmit", then 

- remove the "DeadLetterReason" custom properties (that read "MaxDeliveryCountExceeded an "Message could not be consumed after XX delivery attempts"
- Change the message inspector to the Zip 
- submit to the correct queue/topic

For '000's of messages this is impractical. When we try the "batch resubmit", all messages fail with Zip interpretation problems. This appears to be related to the fact that we cannot choose the message inspector during batch resubmit, as it's the same error we get for a single message resubmit where we do not choose the message inspector then either.

As a side issue (though this is from a long time ago so may no longer be accurate) I also recall that we need to the the DeadLetterReason properties too otherwise Service Bus will instantly reject the message. I don't think ServiceBusExplorer does this?

**Comment by paolosalvatori** [comment]
Can you please try to get the latest version and see if the issue has been fixed? Basically now when you select multiple messages to resend, the tool shows a dialog where you can select a message inspector to apply to all resubmitted messages. In addition, the code eliminates the DeadLetterReason and DeadLetterErrorDescription properties.

**Comment by bunceg** [comment]
Hi Paolo,

Just tried on the latest and the dialog now shows and appears to resubmit correctly. Thanks!

**Comment by paolosalvatori** [comment]
Excellent. Thanks For the confirmation!

**Comment by MikeWilliams-UK** [comment]
Hi Paulo,

> In addition, the code eliminates the DeadLetterReason and DeadLetterErrorDescription properties.

Looks like this is where the clearing of all properties bug has crept in.
