### ISSUE TITLE
ability to delete a single message on topic / queue

### ISSUE THREAD

**Issue by maitrefou974** [paolosalvatori/ServiceBusExplorer#798]
Hi,
somebody already talked about this but nothing changed since...
https://github.com/paolosalvatori/ServiceBusExplorer/issues/228

It is possible to delete a single message in DLQ, why do not add this feature in Messages view ?
Right-click on line, delete message... and the software will "peek and delete" only 1 line starting from this sequence number...

**Comment by SeanFeldman** [comment]
It was closed due to inactivity.
No need to open a new issue if one already exists.
You can add your comment to the original issue.

**Comment by SeanFeldman** [comment]
Duplicate

**Comment by ErikMogensen** [comment]
See the discussion at #771
