### ISSUE TITLE
transfer one on multiple message from Messages to Dead-letter

### ISSUE THREAD

**Issue by maitrefou974** [paolosalvatori/ServiceBusExplorer#799]
Hi,
I don't know if the feature exists... So I ask the question :
Is it possible to move some messages from a topic / queue to its dead-letter queue ?

In code would be like if we consumed the messages in a loop and returned a DeadLetterMessage action for each selected message.

Thank you!

**Comment by SeanFeldman** [comment]
> Is it possible to move some messages from a topic / queue to its dead-letter queue ?

No. Messages are moved to the DLQ by the broker (service side), not manually.

**Comment by SeanFeldman** [comment]
You can receive a message and dead-letter it, but have to receive it first. See documentation for this option [here](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.deadlettermessageasync?view=azure-dotnet#azure-messaging-servicebus-servicebusreceiver-deadlettermessageasync(azure-messaging-servicebus-servicebusreceivedmessage-system-collections-generic-idictionary((system-string-system-object))-system-string-system-string-system-threading-cancellationtoken)).

**Comment by maitrefou974** [comment]
I know how to do it in code, I wanted to know if there is a user button on service bus explorer to do it.

**Comment by SeanFeldman** [comment]
Recieved and delete a single message from DLQ is the only thing I can think of that comes the closest to this.
