### ISSUE TITLE
DeleteRelayAsync() throw exception "The remote server returned an error: (405) Method Not Allowed"

### ISSUE THREAD

**Issue by sharmavishalvk** [paolosalvatori/ServiceBusExplorer#80]
Hello, Thanks for the good app, I really liked it. 
I'm looking forwrd to utilise DeleteRelayAsync() however it always throw exception as "The remote server returned an error: (405) Method Not Allowed" as type Microsoft.ServiceBus.Messaging.MessagingExceptionDetail.
Am I missing something here... fix for it?
Thanks! Vishal

**Comment by paolosalvatori** [comment]
I don't understand. Are you getting this issue when using my tool or when invoking DeleteRelayAsync from your app? :)
