### ISSUE TITLE
Keep the subscriptions nodes showing and expanded when a topic is refreshed

### ISSUE THREAD

**Issue by Tony20221** [paolosalvatori/ServiceBusExplorer#802]
I have the subscription nodes expanded and showing for a topic. When I refresh a topic, the subscription nodes collapse and I have to expand them to notice the refresh. The nodes show stay expanded.

**Comment by NaorisKong** [comment]
Try to develop this feature, implement this on topic subscriptions mode only?
If someone can give some guidance that will be nice. As different mode have different Treeview structure and have different refresh function.
