### ISSUE TITLE
How to connect to Azure IoT Hub message feedback event hub stream from ServiceBusExplorer

### ISSUE THREAD

**Issue by tedvanderveen** [paolosalvatori/ServiceBusExplorer#81]
Azure IoT Hub provides Event Hub compatible endpoint for various purpuses. One of which is endpoint for feedabck/delivery result of Cloud-to-Device messages information on messages/servicebound/feedback
How can I connect to this endpoint with ServiceBusExplorer?

**Comment by paolosalvatori** [comment]
Service Bus Explorer uses an EventHubClient to read messages from the messages/events endpoint. But according to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging, you can read messages from a cloud-to-device endpoint using the same approach. I should extend the tool to integrate the IoT Hub SDK. I'm quite busy in this period, but I could implement this feature in the future.
