### ISSUE TITLE
Connectivity with Service Bus for Windows 1.1 under "workgroup"

### ISSUE THREAD

**Issue by firasr** [paolosalvatori/ServiceBusExplorer#83]
Am using Service Bus Explorer (2.1) to connect to Service Bus for Windows 1.1 installed on a separate server. The connect seems to occur successfully but it doesn’t list any items under Queues/Topic tree. I keep getting the following error:

** The application is now connected to the sb://esbtestserver:9355/test1 service bus namespace.
** MessagingFactory successfully created
** Exception: The token provider was unable to provide a security token while accessing ‘https://esbtestserver:9355/test1/$STS/Windows/’. Token provider returned message: ”.. Method b__3c: retry 1 of 10.
** InnerException: The token provider was unable to provide a security token while accessing ‘https://esbtestserver:9355/test1 /$STS/Windows/’. Token provider returned message: ”.

I also keep getting similar error when trying to create a new queue.

Both my PC and the server is not part of domain. They are under workgroup.

However, things work just fine using a .NET test application I wrote which uses ServiceBus.v1_1 package (it includes Microsoft ServiceBus assembly version 2.1.60426.1) with the same connection string I use in the tool (which contains WindowsUsername=sbuser ;WindowsDomain=[NotUsed];WindowsPassword=123123).

What could be the issue?

**Comment by paolosalvatori** [comment]
It should work. try the following:
WindowsUsername=<local-user-name-on-the-SB-machine>;WindowsDomain=<SB-machine-name>;WindowsPassword=<local-user-password>

**Comment by paolosalvatori** [comment]
When connecting to a Service Bus for Windows Server located in another workgroup, make sure you creating a user X with the same username and password on both the client machine and the workgroup machines hosting Service Bus. Add the user to ManageUsers  for the namespace using the https://msdn.microsoft.com/en-us/library/azure/jj248750(v=azure.10).aspx Set-SBNamespace PowerShell cmdlet. Finally, run your client application under the user X to connected to the Service Bus namespace. This should work thanks to a Windows Passthrough Authentication. For more information, see https://msdn.microsoft.com/en-us/library/cc237015.aspx.
