### ISSUE TITLE
Created date of the subscription also changing when updating the rule.

### ISSUE THREAD

**Issue by RamsankarRajendran** [paolosalvatori/ServiceBusExplorer#85]
Whenever changing the subscriptions rule or user description of the particular subscription, the creation date the subscription also getting changed. I am getting the created and last updated date of the subscription in java programmatically using azure java sdk. Both the created and updated date are same. 
The scope is created date of the subscriptions should remains same and the last modified date(updated date) of the subscription will get updated date on doing any changes in subscription.

**Comment by SeanFeldman** [comment]
@RamsankarRajendran when you modify a subscription description using Java SDK, do you get the expected outcome (i.e. creation and last updated dates are not the same)?

**Comment by paolosalvatori** [comment]
Hi @RamsankarRajendran this question is not really about the tool, this is more a question for the product group: @clemensv or @djrosanova

**Comment by SeanFeldman** [comment]
@RamsankarRajendran you can raise it here: https://github.com/Azure/azure-service-bus/issues
