### ISSUE TITLE
Ability to view message content in explorer

### ISSUE THREAD

**Issue by napalm684** [paolosalvatori/ServiceBusExplorer#86]
This is more of a question/feature request if it is not there.  Is there a way for me to view the message content without pasting the data in hex format and converting to ASCII with something like http://www.rapidtables.com/convert/number/hex-to-ascii.htm ?  I am sorry if this is covered elsewhere but I couldn't find it.  Thanks in advance love the tool.

**Comment by SeanFeldman** [comment]
When you send your brokered messages using ASB, what type do use for the body/payload?

**Comment by paolosalvatori** [comment]
I could invest some time in the visualization of the message. At the moment the tool recognize and properly indent TEXT, XML and JSON messages, while it represents in binary format any non recognized format. You can create a message inspector for the tool to parse the content of incoming messages, configure the message inspector in the configuration file and select it from the dropdown list when you receive messages.

**Comment by SeanFeldman** [comment]
Message inspector sounds like a good idea. @napalm684 would you like to do that?

**Comment by napalm684** [comment]
@SeanFeldman So I am looking at the package we use to send a BrokeredMessage and it appears we are using the overload that simply takes the message object.  Per the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage) this uses a binary XmlDictionaryWriter (Microsoft.ServiceBus.Messaging.DataContractBinarySerializer)?  Is that why I am getting the format in Hex within the tool I assume?  I would love to assist with creating a message inspector.  Upon a cursory review, I assume you are referring to an implementation of ```IBrokeredMessageInspector```?  Not sure what kind of timeline I could deliver it in but have been looking for a project to contribute too ;-)

**Comment by napalm684** [comment]
@paolosalvatori can you confirm the interface above is the implementation needed for this viewer functionality?

**Comment by napalm684** [comment]
Is there a trick to get the broker message inspectors to show up in the drop down?

**Comment by SeanFeldman** [comment]
Double check if there's a need to drop a line in the configuration file.

**Comment by napalm684** [comment]
I did drop a line in the configuration file @SeanFeldman but not even the pre-configured ones (from master already) load when I click the messages button on a subscription.

**Comment by SeanFeldman** [comment]
Not sure. @paolosalvatori can you help out?

**Comment by paolosalvatori** [comment]
Hi @napalm684 @seanfeldman, I realizes that there's some regression bug preventing message interceptors to be loaded correctly in the tool. I'll work to fix that when I'll have time and follow up here.

**Comment by paolosalvatori** [comment]
I found the bug and I will check in the fix this Monday. I recently changed the namespace of classes in the tool, so the FQDN of message inspectors in the configuration fillet is now incorrect. That'said why the tool dies not load them at start :)

**Comment by SeanFeldman** [comment]
@napalm684 this should be fixed now. Please re-open in case it's not working. Thanks.

**Comment by napalm684** [comment]
Wasn't the issue to create a new message inspector this just blocked that work?

**Comment by paolosalvatori** [comment]
Hi @napalm684 what is the problem? The ability to create a message inspector has been fixed. Regarding the visualization of the message, if the payload contains some special characters, the tool visualize the content in binary format.

**Comment by napalm684** [comment]
No I meant the issue was opened as a feature request.  We found the blocker (that is now fixed as a result).  Up to you on if you want to manage the feature request or just handle a PR when/if it comes.

**Comment by napalm684** [comment]
@paolosalvatori Does this help?  This is what I am shooting for in my [commit](https://github.com/napalm684/ServiceBusExplorer/commit/8b12810368b038e06dd8c566ccaa7d33eba07404).  The hex display is of limited value to me when displaying a message.  While not perfect, this is better than me pasting the hex content into the tool I mentioned previously.

**Comment by paolosalvatori** [comment]
I fixed the problem. I also added a new setting in the Options form called Use ASCII. Please download the latest version, give it a try and let me know. I didn't try if messages get visualized as expected when Use ASCII is set to true.

**Comment by napalm684** [comment]
@paolosalvatori works well enough for me.  Thank you for doing it I would have gladly done a more robust pull request :-) .  Honestly I didn't even know about the options form as I hadn't used it till now.  Thanks again!
