### ISSUE TITLE
Versioning alternative

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#88]
Currently, we build a versioned of SBE when compiling on the buildserver (appveyor).
Locally, version is always set to `1.0.0.0`. 

Originally, [GitVersion](https://www.nuget.org/packages/GitVersionTask/) was thought of an option (#29). Perhaps that's something to re-evaluate.

**Comment by SeanFeldman** [comment]
@paolosalvatori do we need to update AppVeyor to reflect changes made in #94?

**Comment by SeanFeldman** [comment]
Looks like there's a disconnect between GitVersion and AppVeyor
![image](https://cloud.githubusercontent.com/assets/1309622/25235778/6ae0c542-25a3-11e7-935b-b83c861c5278.png)

**Comment by SeanFeldman** [comment]
PR #94 was only accounting for the local development and compilation to get the version, rather than both local and buildserver (AppVeyor). When AppVeyor is creating a release build, it uses the version on the build server. This is needed for the future installer and consistency. I'll look into connecting AppVeyor and GitTask info next week. 
Moving forward, with consideration for #49, version should be consistent when building on the build server. Local version should be based on whatever branch you're on _and_ in release mode imo.

**Comment by paolosalvatori** [comment]
Agreed. Thanks @SeanFeldman

**Comment by SeanFeldman** [comment]
Closed via 53ebed7681f291194b35a33857b98e021220f920

**Comment by SeanFeldman** [comment]
@paolosalvatori quick update on what I've done.

After playing with AppVeyor and GitVersion this is what I've set in place.
- Changes done on a branch once committed into master will auto increment the patch version. 
- We can control versions by applying tags (setting "new base").
- /releases will contain pushed released versions in that follow the Major.Minor.Patch format
  - Release description will also contain contain AppVeyor build number
![image](https://cloud.githubusercontent.com/assets/1309622/25648838/4c27b874-2f8d-11e7-9fab-b97bb31a7bf8.png)
- SBE executable will be always versioned as the release (major.minor.patch) and about box will also provide the branch and the commit SHA used to building the version).
![image](https://cloud.githubusercontent.com/assets/1309622/25648874/a0e41b0a-2f8d-11e7-903b-182eb7bfa658.png)
- Locally built version will **always** be 1.0.0(.0) and should remain like that to distinguish a partisan build vs an official one (will be needed for #49)
- **Changes should be developed on a branch, and a branch is merged to the `master` using ["Create a merge commit" option](https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github) for GitVersion to manage versions properly** (violators will be prosecuted 😈).
