### ISSUE TITLE
Index was out of range

### ISSUE THREAD

**Issue by dberryalliance** [paolosalvatori/ServiceBusExplorer#89]
I have an Azure Service Bus namespace that I'm able to use 4.0.57, from the released zip file, and an older 3 version to explore.  However, when I click on any Topic Subscription, I receive the following items in the log:

```
<13:28:08> Exception: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

I cannot perform any operations on the subscription, e.g. Receive Messages or Dead Letter Queue items.  Or view any of the subscription configuration details.  My colleague, who is using the very same builds on her machine, does not have these issues.

I'm uncertain what environmental differences might lead to this behavior.

**Comment by paolosalvatori** [comment]
Mmm... this is quite strange. Maybe it could be due to the entity named and regional settings on your machine?

**Comment by timj92** [comment]
I've had this same issue. Deleting the entire directory and re-building it didn't help. A direct copy of the built application to another machine **did** work. 

For me, the only solution was to use another machine. I believe I remember tracing this error back to something to do with window width, but I wasn't able to solve it.

**Comment by goanpao** [comment]
I was facing the same issue. From my analysis in HandleSubscriptioControl.cs the following method is having an issue. 
_private void CalculateLastColumnWidth(object sender)_ 
The columns.count for object sender is 0 hence the code breaks at this statement
                    var width = dataGridView.Width -
                                dataGridView.RowHeadersWidth -
                                dataGridView.Columns[1].Width -
                                dataGridView.Columns[2].Width;

A simple check of if (dataGridView.Columns.Count < 5) { return;}
resolved the issue for me although I am not sure that is the right approach.

**Comment by paolosalvatori** [comment]
Thanks for the heads up. This should be fixed now. I added this line of code:

if (dataGridView.Columns.Count == 0) {return;}
