### ISSUE TITLE
Can't access messages in TransferDeadLetter

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#90]
Aside from the queue and it's DLQ (`queue/$DeadLetterQueue`), there's also a transfer deadletter queue (`queue/$Transfer/$DeadLetterQueue`) that can store messages. 

It's impossible to access it using the tool.

**Comment by paolosalvatori** [comment]
Hi @seanfeldman, good suggestion :) I'll implement this feature when I'll have time.

**Comment by SeanFeldman** [comment]
@paolosalvatori perhaps should be labeled with `help wanted` and delegated?
Sometimes this repo remind me of this [old episode](https://www.youtube.com/watch?v=qWet8T__mGk) (see translation in comments) 😃

**Comment by snekbaev** [comment]
@SeanFeldman at least it is not like the same scene but in the [first part ](https://www.youtube.com/watch?v=973swwNZx90) of that movie :))))

**Comment by SeanFeldman** [comment]
That @snekbaev is yet to be determined...

**Comment by paolosalvatori** [comment]
@SeanFeldman @snekbaev nice video :) I should have more bandwidth after Easter, so I will introduce the ability to see messages from the transfer dead letter queue.

**Comment by SeanFeldman** [comment]
@paolosalvatori I was actually thinking of doing that if you don't mind. Saying that, if you have certain preferences on where and how we should expose is - I won't mind suggestions for the UI 😉

**Comment by paolosalvatori** [comment]
@SeanFeldman is pretty simple, you just have to create a new tab in the queue and subscription handler controls and reuse the same controls from yhe dead ketter medxages tab. You also need to add a new button, called Transfer and make sure is visualiced only when you have selected an existing entity, and not when creating a new one. Then you have to create menu items in the drop down menu in the main form for queue and subscription entities. I can make it after Easter, I'mean on vacation thesempio two days, while nextra week I'mean on customer site.

**Comment by SeanFeldman** [comment]
Looks like you're picking up the local dialect quite fast @paolosalvatori 😜

**Comment by paolosalvatori** [comment]
Do you mean my English? No, it's just Italian English dialect :)

**Comment by SeanFeldman** [comment]
यह अंग्रेजी नहीं था 😃
