### ISSUE TITLE
purge function requires confirmation

### ISSUE THREAD

**Issue by camous** [paolosalvatori/ServiceBusExplorer#91]
version : 4.0.57

purge function took place (mentally, habit) of receive deadletter queue message and should ask for confirmation as it could lead to data loss and incorrect usage. (hints, already did :))

personally I would even **only** keep the option in "Action" menu rather quick access
![image](https://cloud.githubusercontent.com/assets/8566299/24710993/00fdff3a-1a1f-11e7-9a2d-250261e89365.png)

**Comment by paolosalvatori** [comment]
Thanks for the suggestion @camous :)

**Comment by camous** [comment]
tested & worked great 👍
