### ISSUE TITLE
Setup project will migrate to VS2017 community

### ISSUE THREAD

**Issue by dogleft** [paolosalvatori/ServiceBusExplorer#95]
Hi, when opening ServiceBusExplorer.sln in VS2017 community, I see an error dialog on the migration. 
All project but the setup project migrated. Error message:  The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660147&projecttype=54435603-DBB4-11D2-8724-00A0C9A8B90C

Attaching upgrade log

[UpgradeLog.zip](https://github.com/paolosalvatori/ServiceBusExplorer/files/931166/UpgradeLog.zip)

**Comment by paolosalvatori** [comment]
Thanks @dogleft for the heads up. We didn't migrate the project to VS2017 yet. @SeanFeldman let's take this offline.

**Comment by SeanFeldman** [comment]
@dogleft we've got an issue #49 that is addressing the installer problem.

Moving forward, the plan is to switch to the [Desktop Bridge](https://developer.microsoft.com/en-us/windows/bridges/desktop) to provide an installer + updates.
