### ISSUE TITLE
 SBE Does not purge messages from Topic’s session enabled Subscription

### ISSUE THREAD

**Issue by eperov** [paolosalvatori/ServiceBusExplorer#96]
Hi,
I am getting an Exception when purge messages from Topic’s session enabled Subscription:

<15:23:33> Exception: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:56c88faf-fe99-45b3-867a-3e60086730cc_G14_B10, SystemTracker:xyzsb:topic:edtop~31|edtsub1, Timestamp:4/19/2017 10:23:33 PM

Reading messages is ok.

Thanks

**Comment by eperov** [comment]
Purging from session enabled queue raises the same error.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/paolosalvatori/ServiceBusExplorer/commit/8f9d3d0cbf694d60be8df387686e6c3619d8d1cc
