### ISSUE TITLE
Premium tier queue sizes

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#97]
Premium tier queue size can go up to 80GB
![image](https://cloud.githubusercontent.com/assets/1309622/25317716/3f5a7982-283b-11e7-89ec-c346235c6895.png)

Currently, UI only shows up to 5GB.
![image](https://cloud.githubusercontent.com/assets/1309622/25317731/72374164-283b-11e7-9040-8f9c32426ca0.png)

Possible sizes are: 1, 2, 3, 4, 5, 10, 20, 40, 80

**Comment by paolosalvatori** [comment]
@SeanFeldman good point, let's fix that!

**Comment by paolosalvatori** [comment]
It would be better to show different values for standard and premium messaging, but it's impossible to understand if a namespace is standard or premium without looking at the ARM resource properties, which would require authentication against an AAD.

**Comment by SeanFeldman** [comment]
All we can do at this point (seems like) is to adjust the slider to show the size to reflect the actual size since values are coming properly via `QueueDescription`.

**Comment by paolosalvatori** [comment]
Ok, let's do it.

**Comment by SeanFeldman** [comment]
For now, will just override the size in UI based on the value from `QueueDescription` we get back.

**Comment by SeanFeldman** [comment]
Closed via #122

**Comment by SeanFeldman** [comment]
Raised an issue with the old client: https://github.com/Azure/azure-service-bus/issues/82

**Comment by paolosalvatori** [comment]
Great catch @SeanFeldman. This issue is connected to the problem we discussed yesterday about the inability to determine with a call to the NamespaceManager the type and sku of a Service Bus namespace.
