### ISSUE TITLE
Ability to identify tier type / namespace type

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#99]
Currently, SBE doesn't have an idea what tier or namespace type is used.
Related issue #97

**Comment by SeanFeldman** [comment]
We could get the ability to determine what tier NS belongs to when a new "lightweight" management library is available. Tracking issue: https://github.com/azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419

**Comment by paolosalvatori** [comment]
@SeanFeldman could you please investigate this option whenever you have some spare time? Thanks :)

**Comment by ErikMogensen** [comment]
Fixes by #504
